.github/workflows/releaser.yml
.goreleaser.yaml

Merge this once we go public 👍 
This enables opening a PR to winget-pkgs and removes the private setting for SLSA.
@dussab @lukehinds:
Note that the winget-pkgs integration is about goreleaser generating all of the files and opening a PR against their repository. 
We would then need to go and click on the PR checkboxes each time we release (unless we buy the paid version of goreleaser). 
Also on the first time we publish, we have to go through their CLA confirmation.

Release minder to microsoft/winget-pkgs and remove private setting for SLSA

---

docs/docs/how-to/create_profile.md

Since we still need to work on filtering our profile status per repo,
the best thing we have for now is to print a JSON output and filter it
through JQ. Let's show that in our docs.

Show the JSON output of profile_status list in docs

---

docs/docs/getting_started/login.md

My assumption is that when people are getting started they will use the hosted instance more often, therefore those instructions should appear first.

Update login instructions in docs

---

internal/providers/github/github_rest.go
internal/providers/github/github_test.go

e.g. to get the minder helm chart, we need the API to call:
```
https://api.github.com/orgs/stacklok/packages/container/package/minder%2Fhelm%2Fminder
```
but we've been seeing a bunch of:
```
GET
https://api.github.com/orgs/stacklok/packages/container/minder/helm/minder:
404 Not Found
```
in the logs.

PathEscape artifact name to process artifacts with slash in the name

---

docs/docs/run_minder_server/installing_minder.md

Addressing comments from https://github.com/stacklok/minder/pull/1567

Update Minder Helm Installation

---

.mk/build.mk
.mk/db.mk
.mk/develop.mk
.mk/gen.mk
.mk/helm.mk
.mk/identity.mk
.mk/test.mk
Makefile

Changes: 
* Organises our make targets into groups of makefiles
* Adds a `stop-docker` command
* Sanitises the output for some of the targets to something less verbose

Organise make targets into separate makefiles

---

README.md

There is a broken link on the read me. This PR is fixing it :)

docs: fixes broken link to CLI docs on the readme

---

README.md

This PR adds a link to the API from the readme

Docs: adds a link to the API to the readme

---

internal/engine/actions/remediate/gh_branch_protect/gh_branch_protect_test.go

This ensures we're not overwriting `EXPECT` calls in between the parallel
tests and thus ensuring we don't have race conditions.

Instantiate mock client for each test in branch protection remediations test

---

internal/db/profiles_test.go
internal/db/repositories_test.go

We used to silently delete the repository if it happened that we chose
the same "repo id" when creating a random repository. This is not correct
and lead to hard-to-find and flaky tests.
Now, we instead check if the repo id exists and if it does, we generate a new ID
before creating the repo.

Fix flaky database tests

---

internal/controlplane/handlers.go
internal/controlplane/handlers_test.go
internal/controlplane/server_test.go

The intention is to link minder's health with the database and keep the
db connection open for longer.

Hook up minder healthcheck to database health

---

.mk/develop.mk

Now you can use an environment variable to tell our `run-docker` target
to skip the teardown phase. It may be done as follows:
```bash
export RUN_DOCKER_NO_TEARDOWN=true
```
This will result in subsequent calls to `make teardown` to skip the
`docker-compose down` call at the beginning of the run.
this is handy for cases where you're doing rapid development and want
to keep the database changes.

Enable skipping teardown when using the `run-docker` Makefile target

---

cmd/cli/app/repo/repo_delete.go

Follow the same pattern as other deletion commands like `minder profile delete` and `minder rule_type delete`
Fix #1562

Make repo deletion message consistent with similar commands

---

cmd/cli/app/auth/auth_login.go
cmd/cli/app/auth/html/login_success.html

Use embedded HTML page, instead of writing HTML in a string.

Improve login success page

---

cmd/cli/app/version/version.go
internal/constants/version.go
internal/util/cli/useragent/useragent.go
internal/util/helpers.go

This replicates the user agent format that browsers use in order to
get more relevant debugging information without revealing any PII.

Add enhanced user agent informtion to CLI

---

deployment/helm/templates/deployment.yaml
docker-compose.yaml

Disable file system caching of tuf metadata for minder.
In sigstore/sigstore there's a [SIGSTORE_NO_CACHE](https://github.com/sigstore/sigstore/blob/ee007c4780d59fec556ddf09607cfefcd63923e1/pkg/tuf/client.go#L57) env var that apparently should allow cosign to work without storing anything on disk which would allows us to keep having a readonly file system for minder.
Related to: https://github.com/stacklok/minder/pull/1606 and https://github.com/stacklok/minder/issues/1589

Set SIGSTORE_NO_CACHE=true in minder

---

cmd/server/app/migrate.go
cmd/server/app/migrate_up.go
cmd/server/app/migrate_version.go

When testing more complex database migrations, it's useful to do
migration one step up or down. This patch adds a new parameter to
migrate up and down that allows to specify the number of steps,
defaulting to migrating the whole way up or down.
Also adds a new migrate subcommand version that prints the current
database version.

Add switch to migrate up/down to do one step migration, add migrate version

---

docs/docs/getting_started/register_repos.md

👋 As I was following the [Getting Started guide](https://docs.stacklok.com/minder/getting_started/) I got stuck on the [Register a repo step](https://docs.stacklok.com/minder/getting_started/register_repos) since even though I did auth, I missed enrolling.
For those of us who suck at reading docs, I am adding a Prerequisites section to the register a repo page, following the example of the other steps.

docs: adds prerequisites to the register a repo getting started page

---

CONTRIBUTING.md

I was kinda lost today while trying to build the documentation to preview my changes.
This PR is adding a link to the docs readme from the contribution guidelines. It's also fixing the markdown title hierarchy and completing the ToC.

Adds a link to docs readme to contribution guidelines

---

internal/container/container.go

Container registries don't handle uppercases for the owner (or namespace).
We need to do some parsing to allow for these. Else, repositories
in my personall account (JAORMX) won't work.

Convert owner name to lowercase when building container image reference

---

config/config.yaml.example

The following PR adds a comment with how to update the config.yaml in case you want to run minder outside of the docker-compose stack. Helpful for debugging.

Add issuer_url for running minder outside of docker-compose

---

database/migrations/000007_status_delete_procedure.down.sql
database/migrations/000007_status_delete_procedure.up.sql
internal/db/profiles_test.go

In case an entity was deleted (typically a PR but a repo delete is also
a valid use-case), we would not update the profile status until the next
profile run.
For that, we need to add a new database trigger in a migration.
Sort-of-related is a bug in the original procedure that we had where if
all the current rules were skipped and we added a failure the overall
status would still be a failure. I added a new version of the old
procedure to cover that plus some tests.
Fixes: #1610

Add a stored procedure to handle entity deletions

---

internal/engine/ingester/diff/parse.go
internal/engine/ingester/diff/parse_test.go

Normalize python package names before sending to OSV

---

database/migrations/000008_remove_null_prs.down.sql
database/migrations/000008_remove_null_prs.up.sql
internal/engine/eval_status.go

For some reason (probably refactoring and merging too many patches at
the same time?) we no longer linked PRs with evaluation results. This
meant that once a PR was merged, the evaluation result was still
included.- Also link PR IDs with evaluation status
To get rid of the dangling references, we delete them in a migration. This is OK, because there are only two events that we listen on:
- PR is opened - in this case we upsert a PR entry
- PR is closed - in this case we delete a PR entry and ignore ErrNoRows
Fixes: #1608

Link PRs with rule_evaluation_status properly

---

internal/engine/executor.go

We didn't really log the error it seems, it was visible in the status
and in the database, but having it in logs is useful, too.
If the error we pass is `nil`, the log message would be `Info` instead.

Log the full remediation and alert error

---

internal/engine/actions/remediate/gh_branch_protect/gh_branch_protect.go
internal/engine/actions/remediate/gh_branch_protect/gh_branch_protect_test.go

The GH API returns both `Protection.RequiredStatusChecks.Contexts` which
is deprecated and `Protection.RequiredStatusChecks.Checks` which is
supposed to be used now on GET, but the PUT update needs to only set one
or the other.
Let's filter out the deprecated field so that setting branch protection
rules when commit statuses are in place works fine.
Fixes: #1596

Handle PR statuses when setting branch protection rules

---

cmd/cli/app/auth/auth_login.go
cmd/cli/app/auth/auth_whoami.go
cmd/cli/app/auth/common.go

Similar to PR https://github.com/stacklok/minder/pull/1648 this prints the projects into
multiple rows, now for the `auth login` subcommand. This created a function that is
re-used.

Print multiple projects in `auth login` subcommand

---

internal/engine/executor.go

Commit 0ef19262ce6fd6f6ff3cbe068fe8189a91f7b7ca added logging for
remediation and alert levels, but it turns out that we would even log
skipped remediations and alerts as errors which made the logs very
spammy.
Let's fix all but fatal errors.

Don't log skipping rules as errors

---

.gitignore

This allows us to create a symlink instead of relying on explicitly cloning the repo.

Remove trailing slash from rules-and-profiles entry in gitignore

---

pkg/api/protobuf/go/minder/v1/validators.go

I don't know why I commented that out, but this re-introduces that check.
Closes: https://github.com/stacklok/minder/issues/1659

Re-introduce entity validation for rule types

---

.mk/build.mk
cmd/dev/app/root.go

`mindev` is a small command line utility to help us add minder development
utilities. e.g. debugging tools for rule types and profiles.

Rename `medev` to `mindev`

---

.trivyignore

This allows us to have a passing CI with proper documentation of the accepted risk.

Add trivyignore file with risk acceptance

---

.github/workflows/test.yml
deployment/helm/templates/deployment.yaml
deployment/helm/templates/job.yaml
deployment/helm/values.yaml
deployment/helm_tests/basic.yaml
deployment/helm_tests/basic.yaml-out
deployment/helm_tests/helm_test.go
deployment/helm_tests/sidecar.yaml
deployment/helm_tests/sidecar.yaml-out
go.mod
internal/config/db.go

Since many people probably care about their helm versions, I didn't make it part of the bootstrap command, and instead rely on helm already being installed for this test.
I started with trying to use https://github.com/mittwald/go-helm-client/, but it turns out that has a bunch of out-of-date dependencies, and all the APIs changed because that's how k8s API dependencies work.

Add support for sidecars to migrate and minder, add tests for same

---

internal/engine/eval/vulncheck/pkgdb.go
internal/engine/eval/vulncheck/pkgdb_test.go
internal/engine/eval/vulncheck/review_test.go
internal/engine/ingester/diff/parse.go
internal/engine/ingester/diff/parse_test.go

- Start by finding any version changes
- Then find the package name whose version was changed
Fix #1631

Update package-lock.json parsing strategy

---

README.md
cmd/cli/app/profile/profile_create.go
cmd/cli/app/profile/profile_get.go
cmd/cli/app/profile/profile_list.go
cmd/cli/app/profile/profile_update.go
cmd/cli/app/profile/table_render.go
cmd/cli/app/provider/provider_enroll.go
cmd/cli/app/quickstart/embed/profile.yaml
cmd/cli/app/quickstart/embed/secret_scanning.yaml
cmd/cli/app/quickstart/quickstart.go
cmd/cli/app/repo/repo_register.go
cmd/cli/main.go
internal/util/statuses.go

The following PR implements a quickstart command which is intended to provide a happy path to getting started with minder and be executed after a user has authenticated and enrolled their provider.
Covers the following functionality:
* Prompts the user to enroll their repository provider
* Prompts the user to register one or more repositories with Minder
* Prompts the user to create a `secret_scanning` rule type
* Prompts the user to create a profile called `quickstart-profile` with the `secret_scanning` rule type set to `enabled` for their registered repositories.
Screenshots: 
* Step 0 - Welcome
* Step 1 - Provider enrollment
* Step 2 - Repository registration
* Step 3 - Prompt for confirming the creation of secret scanning rule type
* Step 4 - Prompt for confirming the creation of a …

Implement a quickstart command for minder

---

.gitignore

This was previously used by our helm generation but fell out of use.
We shouldn't be ignoring this file anymore as it's no longer generated.

Remove `combined.yml` from gitignore

---

cmd/cli/app/quickstart/quickstart.go

A few things to polish for the quickstart command.

Update quickstart command message layout

---

internal/engine/actions/alert/security_advisory/security_advisory.go
internal/engine/actions/remediate/gh_branch_protect/gh_branch_protect.go
internal/engine/actions/remediate/pull_request/pull_request.go
internal/engine/actions/remediate/rest/rest.go
internal/engine/eval/trusty/actions.go
internal/engine/eval/vulncheck/review.go
internal/engine/ingester/rest/rest.go
internal/util/rest.go

This should make errors more pronounced when someone has a bug in their rule and the remediation or evaluation template doesn't expand fully
Fixes: #1242

Use missingkey=error for text/template

---

docs/docs/getting_started/enroll_provider.md
docs/docs/getting_started/first_profile.md
docs/docs/getting_started/login.md
docs/docs/getting_started/quickstart.md
docs/docs/getting_started/register_repos.md

The following PR updates the docs with the quickstart command and also splits the existing login section to login and enrolling a provider.
Fixes: https://github.com/stacklok/minder/issues/1706

Update the docs with the quickstart command

---

cmd/server/app/serve.go
internal/config/events.go
internal/controlplane/handlers_user_test.go
internal/controlplane/server_test.go
internal/eea/eea_test.go
internal/engine/executor_test.go
internal/events/eventer.go
internal/events/eventer_test.go

This removes the boilerplate on other parts of the code and instead moves
the responsibility to eventer.

Do database queue connection initialization on eventer

---

internal/db/repositories_test.go

This aims to avoid issues such as:
```
repositories_test.go:166:
Error Trace:	/home/runner/work/minder/minder/internal/db/repositories_test.go:72
/home/runner/work/minder/minder/internal/db/repositories_test.go:166
Error:      	Received unexpected error:
pq: duplicate key value violates unique constraint "unique_repo_id"
Test:       	TestListRepositoriesByProjectID
```

Increase entropy of repo ID generation for tests

---

internal/engine/ingester/artifact/artifact.go
internal/engine/ingester/artifact/artifact_test.go
internal/engine/ingester/artifact/config.go
internal/engine/ingester/artifact/tag_match.go

This changes the ingester to also allow a `tag_regex` field as part of its
configuration. The idea is that folks would be able to write a profile with
a configuration that matches all release-related tags for their containers.
Such a configuration would look as follows:
```yaml
artifact:
- type: artifact_signature
params:
tag_regex: "v*"
def:
is_signed: true
is_verified: true
is_bundle_verified: true
```

Allow regex matching of artifacts with artifact ingester

---

internal/engine/errors/errors.go

At the moment we store any evaluation error as `string(err)` which is
great for its simplicity and allows us to unwrap the error and test it
with `errors.Is` or `errors.As`, but the string representation also
includes the string representation of the error itself.
In order to both support unwrapping but also be able to extract only the
raw message from the evaluator, let's add a `EvaluationError` structure
that implements the error interface so it can be tested for with `As`,
unwraps into base which is `ErrEvaluationFailed` through the usual
`NewErrEvaluationFailed`.
The user-visible result is that the errors are no longer stored with the
`evaluation failure` prefix, but raw, which will be useful for storing
JSON in the result.

Return only the raw evaluation error message without prefix

---

go.mod
go.sum
internal/engine/eval/rego/lib.go
internal/engine/eval/rego/lib_test.go

Adds a new function called `ListGithubActions` to the rego library along
with tests. The function calls the frizbee function and formats the
output as a Rego set to allow for easy comparisons later.
Also adds frizbee as a dependency for minder.

Use frizbee to add a new function ListGithubActions to the rego library

---

cmd/cli/app/auth/auth_revoke_provider.go
cmd/cli/app/provider/provider_enroll.go
cmd/cli/app/rule_type/rule_type_delete.go

Adds an optional `--yes/-y` flag for bypassing the yes/no prompt.
There are four commands that have this prompt currently, 
1. `minder auth revoke_provider`
2. `minder auth delete`
3. `minder rule_type delete`
4. `minder provider enroll`
I have added to all the above except `minder auth delete` as I feel this one should always ask for a confirmation. Let me know if we should add to this one too.
_Updated(by @rdimitrov):_
Fixes #1519

Add a yes flag to skip prompts for CLI commands

---

README.md

This is just a tiny change to make the quickstart guide more precise.

Tiny change to the quickstart guide

---

internal/engine/interfaces/interface.go
internal/engine/rule_types.go

This PR is continuation of https://github.com/stacklok/minder/pull/1727
We need to be able to pass ingestion results to Actions to be able to
remediate what had been ingested.

Extend the EvalParams interface to store ingestion result

---

internal/engine/actions/remediate/pull_request/pull_request.go
internal/engine/actions/remediate/pull_request/pull_request_test.go
internal/engine/ingester/git/git.go
internal/engine/interfaces/interface.go

This would allow us to modularize better the actual action that's done
(currently creating a file in git) and then keep on adding more actions like calling frizbee to change actions' tag to a SHA.
Fixes: #1729

Make the pull-request remediator use git-go instead of plan GH API calls

---

database/mock/store.go
database/query/profiles.sql
internal/controlplane/metrics.go
internal/db/profiles.sql.go
internal/db/querier.go

The quickstart profile are a bit of a special case, with a special name
(that's not enforced, but I don't think the number of false positives
would be very high). We don't have another way to see if a profile was
created by the quickstart tool and while we could add one, it's not
worth the effort.
This PR adds a gauge that counts the profiles with the quickstart name
so that we can get metrics on their usage.

Add a gauge to count the quickstart profiles

---

internal/util/rand/random.go

Fixes #1352.
There are several potential locations to fix this, but I think this proposed change helps to remedy other tests that rely on random values.
I tested on the main branch to reproduce the flakiness as follows:
```console
for i in {1..10} ; do go test -count 1 ./internal/db/... ; done
```
I consistently get an error similar to the following (but mostly not at the first run):
```console
2023-11-30 23:28:49.938 WIB [11553] ERROR:  duplicate key value violates unique constraint "projects_name_idx"
2023-11-30 23:28:49.938 WIB [11553] DETAIL:  Key (name)=(dZGJGaiAlN) already exists.
```
Hence resulting `STATEMENT:  -- name: CreateOrganization :one` and `STATEMENT:  -- name: CreateProject :one` to fail, similar to https://github.com/stacklok/minder/issues/1352.
```console
2023-11-30 …
```

Make sure each call to NewRand is initialized with a unique seed

---

cmd/dev/app/root.go
cmd/dev/app/rule_type/rttst.go
cmd/dev/app/rule_type/ruletype.go

This adds an explicit parent command for `mindev` for rule types. This will
make it easier to add more sub-commands there.

Modify `mindev` to have `ruletype` subcommand

---

cmd/dev/app/rule_type/lint.go
cmd/dev/app/rule_type/ruletype.go
go.mod
go.sum

This is a helper command to lint minder rule type definitions. The main
value it currently brings is being able to also lint rego rules.

Introduce `mindev ruletype lint` command

---

config/config.yaml.example
deployment/helm_tests/basic.yaml-out
deployment/helm_tests/sidecar.yaml-out

We accidentally persisted the documentation reference for events
in Spanish instead of English in the configuration example. This
changes that.

Switch events configuration reference to English

---

README.md

The `make run-docker` step of the README has a dependency on [`ko`](https://ko.build/install/). Add that in the README itself.
(Note that `make` is also implicitly depended on in the "Build it from source" section of the README, but not listed in the prerequisites, nor is it installed by default on most base systems. Its omission makes a certain amount of sense to me, but I thought that I would call that out explicitly while I'm proposing changes to this section.)

README: add `ko` as a dependency for minder-server

---

cmd/cli/app/ruletype/common.go
cmd/cli/app/ruletype/rule_type.go
cmd/cli/app/ruletype/rule_type_apply.go
cmd/cli/app/ruletype/rule_type_create.go
cmd/cli/app/ruletype/rule_type_delete.go
cmd/cli/app/ruletype/rule_type_get.go
cmd/cli/app/ruletype/rule_type_list.go
cmd/cli/app/ruletype/rule_type_update.go
cmd/cli/app/ruletype/table_render.go
cmd/cli/main.go

This even renamed the package. Cause, why not!?
Closes: #1755

Rename Rule Type sub-commands to `ruletype`

---

cmd/cli/app/profile/common.go
cmd/cli/app/profile/profile_apply.go

This adds the `minder profile apply` sub-command. It also adds
some handy utility functions to simplify writing other profile
sub-commands such as `profile create`.
Closes: #1756

Add subcommand to apply profiles

---

internal/auth/jwtauth.go
internal/controlplane/handlers_profile.go

Use method that checks admin role, since that's the only role currently used.

Simplify authorization and cleanup unused methods

---

.github/workflows/test.yml
.mk/test.mk

By default, gotestfmt will output all tests and their logs. In case you want to see which test is failing it gets a bit difficult to navigate through all of them, so this simplifies that.
I've used the `-all` option out of the following.
- successful-tests: Hide successful tests.
- successful-downloads: Hide successful dependency downloads.
- successful-packages: Hide packages with only successful tests.
- empty-packages: Hide packages that have no tests.
- all: Hide all non-error items.

Run tests in a silent mode (error only output)

---

internal/eea/eea.go

Followup to https://github.com/stacklok/minder/pull/1834; we made some progress, but then got stuck on a `pull_requests` that had been removed.

Avoid attempting to lock other deleted resources

---

.mk/identity.mk
docs/docs/developer_guide/get-hacking.md

I was looking to check our logging quickly, and didn't want to fish out / set up an OAuth app, so I added a username/password option for development.

Add username/password login, and better document setting up login in get-hacking

---

cmd/cli/app/artifact/artifact_get.go
cmd/cli/app/artifact/artifact_list.go
cmd/cli/app/auth/auth.go
cmd/cli/app/auth/auth_delete.go
cmd/cli/app/auth/auth_login.go
cmd/cli/app/auth/auth_whoami.go
cmd/cli/app/profile/profile_apply.go
cmd/cli/app/profile/profile_create.go
cmd/cli/app/profile/profile_delete.go
cmd/cli/app/profile/profile_get.go
cmd/cli/app/profile/profile_list.go
cmd/cli/app/profile/profile_update.go
cmd/cli/app/profile_status/profile_status_get.go
cmd/cli/app/profile_status/profile_status_list.go
cmd/cli/app/provider/provider_enroll.go
cmd/cli/app/quickstart/quickstart.go
cmd/cli/app/repo/repo_delete.go
cmd/cli/app/repo/repo_get.go
cmd/cli/app/repo/repo_list.go
cmd/cli/app/repo/repo_register.go
cmd/cli/app/ruletype/rule_type_apply.go
cmd/cli/app/ruletype/rule_type_create.go
cmd/cli/app/ruletype/rule_type_delete.go
cmd/cli/app/ruletype/rule_type_get.go
cmd/cli/app/ruletype/rule_type_list.go
cmd/cli/app/ruletype/rule_type_update.go
internal/util/cli/cli.go
internal/util/helpers.go

This wrapper makes it easier for us to build sub-commands, since it
wraps the `RunE` function and avoids the boilerplate we used to have.
Closes #1746

Add CLI wrapper that passes in a default context and GRPC client

---

deployment/helm/README.md
deployment/helm/values.yaml
deployment/helm_tests/basic.yaml
deployment/helm_tests/basic.yaml-out
deployment/helm_tests/sidecar.yaml-out
internal/engine/eval/trusty/trusty_rest_handler.go

It turns out we were encoding some internal pre-launch configuration details in the public helm chart.  This switches the defaults so they should work outside Stacklok's EKS cluster.

Point Trusty helm chart default to public instance

---

cmd/cli/app/artifact/artifact_list.go
cmd/cli/app/profile/profile_list.go
cmd/cli/app/repo/repo_delete.go
cmd/cli/app/repo/repo_get.go
cmd/cli/app/repo/repo_list.go
cmd/cli/app/repo/repo_register.go
cmd/cli/app/ruletype/ruletype_delete.go
cmd/cli/app/ruletype/ruletype_list.go
internal/controlplane/common.go
internal/controlplane/handlers_artifacts.go
internal/controlplane/handlers_oauth.go
internal/controlplane/handlers_oauth_test.go
internal/controlplane/handlers_repositories.go

Fix #1752
Fix #1745
Also, make GitHub the default provider in the CLI, since that's the only option we allow to get past the CLI (this was initially suggested in #1745, which I had mistakenly assumed would be fixed by the server change)

Get default provider from those enrolled in project

---

internal/providers/github/github_rest.go

The Do method in our github_rest wrapper behaved a bit differently from
the go-github method it was wrapping - instead of always returning the
result so that the caller might check it, it would always return nil on
error.
This made checking for specific error codes (like 404) awkward
especially if we pass this interface to a library as you'd have to cast
the error to go-github's error codes and then grab the reply from there
anyway.
Passing the body always would enable us to use this interface (or a
variant of it) in frizbee instead of directly passing in the go-github
instance.

Always return response from github_rest's Do()

---

cmd/cli/app/artifact/artifact_get.go
cmd/cli/app/artifact/artifact_list.go
cmd/cli/app/auth/auth_delete.go
cmd/cli/app/auth/auth_login.go
cmd/cli/app/auth/auth_logout.go
cmd/cli/app/auth/auth_whoami.go
cmd/cli/app/docs/docs.go
cmd/cli/app/profile/profile_apply.go
cmd/cli/app/profile/profile_delete.go
cmd/cli/app/profile/profile_get.go
cmd/cli/app/profile/profile_list.go
cmd/cli/app/profile/status/profile_status_get.go
cmd/cli/app/profile/status/profile_status_list.go
cmd/cli/app/provider/provider_enroll.go
cmd/cli/app/quickstart/quickstart.go
cmd/cli/app/repo/repo_delete.go
cmd/cli/app/repo/repo_get.go
cmd/cli/app/repo/repo_list.go
cmd/cli/app/repo/repo_register.go
cmd/cli/app/root.go
cmd/cli/app/ruletype/ruletype_create.go
cmd/cli/app/ruletype/ruletype_delete.go
cmd/cli/app/ruletype/ruletype_get.go
cmd/cli/app/ruletype/ruletype_list.go
internal/util/cli/cli.go

Explicit is better than implicit.
We already handled the output rendering in the cobra CLI root, which does
the explicit `Execute` function. This was already even done with the
`ExitNicelyOnError` construct. So, instead of handling the logic in several
places, this moves returns the error everywhere.
The caveat is that we would miss the caller's context. That is, we would miss
a message of what was going on when the error happened. To address this,
I introduced a function called `MessageAndError` which allows us
to print a message to the right stream in cobra and then return the error.
Closes: https://github.com/stacklok/minder/issues/1747

Don't `ExitNicelyOnError` on the sub-commands

---

.github/workflows/generation.yml

This should have caught the error I made in #1831 declaring the removal of the `Context` message safe.  Let's rely on the automation, instead.

Re-enable proto compatibility checks

---

go.mod
go.sum
internal/config/db.go

This is not strictly required and is no longer being used.

Remove cloud provider provided database password

---

internal/util/cli/style.go

This was bothering me when runing `minder auth login` and other commands in a default 80x24 MacOS terminal window.
Before:
(note that the output is cropped top & bottom -- more than 24 lines of output, since all the fancy banner lines wrap)
After:

Use terminal width for Minder output

---

internal/crypto/crypto.go
internal/crypto/crypto_test.go

Fixes #1902 
Noticed by CodeQL. I don't believe this was reachable, but this is belt & suspenders protection.

Avoid over-large allocation in EncryptBytes

---

.github/workflows/codeql.yml

This allows it to run reliably, since it uses the OS's golang version
by defalut which is too old.

Setup go in CodeQL action

---

cmd/cli/app/quickstart/quickstart.go
internal/util/cli/cli.go

I was using the quickstart command to record a demo and was frequently
hitting deadline exceeded if I wasn't quick enough.
Let's add a context around each step so that the user actually has time
to read the text we present.

Create context between steps in quickstart

---

internal/engine/actions/remediate/pull_request/pull_request.go
internal/engine/actions/remediate/pull_request/pull_request_test.go
internal/engine/actions/remediate/pull_request/types_actions_replace_tags.go
internal/engine/actions/remediate/pull_request/types_registry.go

In the PR remediation that replaces tags for checksums, we need a way to
pass in an exclusion list from the user input in the profile.
This implements that by parsing an `exclude` key from the `def` section
of the rule.

Parse GitHub Action exclusion from rule def

---

docs/docs/ref/proto.md
pkg/api/openapi/minder/v1/minder.swagger.json
pkg/api/protobuf/go/minder/v1/minder.pb.go
proto/minder/v1/minder.proto

The dev docs were leaking into the OpenAPI that's generated from minder.
This fixes that to generate more relevant docs.

Set documentation for context appropriately

---

cmd/cli/app/ruletype/common.go
cmd/cli/app/ruletype/ruletype_apply.go
cmd/cli/app/ruletype/ruletype_create.go

This creates a new context with timeout for each file that's being processed,
thus avoiding the timeout that happens when using a single context for
all files.

Reset timeout for each file processed by `ruletype` `create`/`apply`

---

internal/reconcilers/artifacts.go
internal/reconcilers/run_profile.go

These were still validating integers while they're not UUIDs. This also
moved one event reference to be `project` instead of `group`.

Remove invalid validation for projects in reconcilers

---

internal/engine/actions/remediate/pull_request/pull_request.go
internal/engine/actions/remediate/pull_request/pull_request_test.go

The PR remediation was checking if a PR with the same contents already
exist as a fast and cheap check to avoid triggering the remediation
again. But in case the profile changes or the contents change for
another reason, we want to push to the existing branch to update it, but
don't try to open a PR again as that would fail with 422.
To do that, this patch adds a check if a PR is already open from the
branch we just pushed to and if it is, just returns before opening the
PR again.

Don't attempt to reopen a PR after updating a branch if it already exists

---

.github/CODEOWNERS

This adds the maintenance team as CODEOWNERS

Add CODEOWNERS to minder

---

pkg/api/protobuf/go/minder/v1/validators.go

We added profile type and validation recently which is great, but since
those fields are not set by older clients who didn't have those fields
in their protobuf definitions, those fields would come to the server as
empty and the validation would have failed.
This would impact e.g. an older client running quickstart against a new
server.
We should remove this workaround after a couple of releases when we can
be reasonably sure everyone has migrated to a new client.

Default to v1 and profile if profile type or version are not set to fix old clients

---

tools/go.mod

Separating out this change from #1790

Allow tools to depend on targets in the rest of the minder repo

---

docs/docs/developer_guide/get-hacking.md

The proper service name in 'docker-compose' is 'migrate'.
Ref: https://minder-docs.stacklok.dev/developer_guide/get-hacking#run-the-application

Fix "Get Hacking" page service name

---

deployment/helm/Chart.lock
internal/controlplane/handlers_authz.go

See https://github.com/stacklok/minder/discussions/1957 -- requests though the GRPC gateway don't seem to have proper auth (returning `codes.Unauthenticated`, but we're not providing anything more useful in terms of error message to distinguish different cases.
I'd really love it if I'd written tests for `UnaryAuthorizationInterceptor` earlier, but I compounded the technical debt here to get the quick fix in.

Pass through error messages from AuthFromMD for debugging

---

docs/docs/understand/alerts.md
internal/util/cli/table/simple/simple.go

Details:
1. Changes the width for the key value columns to 50
2. Noticed the alert documentation had a code snippet that was not rendering properly
3. Noticed the ID headers were inconsistent

Fix alert docs and update key value column width

---

README.md

Fixes this - 
in favour of this

Fix styling for discord badge in Readme

---

internal/engine/actions/remediate/pull_request/pull_request.go

Turns out that the `Head` parameter of the `PullRequestListOptions`
structure doesn't just take the branch name but `owner:branch`.
The tricky thing is that if you just use the branch name, then the list
operation would just return all the currently open PRs. I think this might be
a bug in the GH API, but what do I know. 
This bug would manifest as minder pushing some code into a branch, but then
not opening a PR if any other PR was opened against an enrolled repository.
I didn't notice this in my initial testing beacuse I would either have 0
PRs or just 1 with the tag-to-sha patch.
To try this, you can use a curl request against one of my test repos:
```
curl -L -v \
-H "Accept: application/vnd.github+json" \
-H "Authorization: Bearer $TOKEN" \
-H "X-GitHub-Api-Version: 2022-11-28" \ …
```

Fix pull_request remediation from branch

---

cmd/dev/app/root.go

The dev tool does not use a configuration file. Let's remove the parsing from there.

Remove config parsing from `mindev`

---

.github/workflows/build.yml
.github/workflows/chart-publish.yml
.github/workflows/codeql.yml
.github/workflows/compose-migrate.yml
.github/workflows/deploy-doc.yml
.github/workflows/generation.yml
.github/workflows/golangci-lint.yml
.github/workflows/image-build.yml
.github/workflows/license-check.yml
.github/workflows/migrate-touch.yml
.github/workflows/releaser.yml
.github/workflows/security.yml
.github/workflows/stalebot.yml
.github/workflows/test-deploy-doc.yml
.github/workflows/test.yml
.github/workflows/update-docs-cli.yml
.github/workflows/update-docs-dbschema.yml
.github/workflows/update-docs-helm.yml

This is a Minder automated pull request.
This pull request replaces references to actions by tag to references to actions by SHA.
Verifies that any actions use pinned tags
Pinning an action to a full length commit SHA is currently the only way to use
an action as an immutable release. Pinning to a particular SHA helps mitigate
the risk of a bad actor adding a backdoor to the action's repository, as they
would need to generate a SHA-1 collision for a valid Git object payload.
When selecting a SHA, you should verify it is from the action's repository
and not a repository fork.
For more information, see
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

Replace unpinned actions with pinned action

---

internal/engine/ingester/git/git.go
internal/engine/ingester/git/git_test.go
internal/providers/git/git.go
pkg/providers/v1/errors.go

This changes the logic for the git ingester to output an evaluation
failure if the branch didn't exist.
Closes: #1804

Surface git clone errors as failures if the branch doesn't exist

---

.github/workflows/deploy-doc.yml

The minder docs are mean to be bleeding edge. This changes the deploy
trigger to build on merges to `main` instead of on every release.

Deploy docs on merges to `main`

---

cmd/cli/app/artifact/artifact_get.go
cmd/cli/app/artifact/artifact_list.go
cmd/cli/app/auth/common.go
cmd/cli/app/profile/table_render.go
cmd/cli/app/repo/repo_list.go
cmd/cli/app/repo/repo_register.go
cmd/cli/app/ruletype/common.go
cmd/cli/app/ruletype/ruletype_get.go
cmd/cli/app/ruletype/ruletype_list.go
internal/util/cli/table/simple/simple.go
internal/util/cli/table/table.go

After talking with Ozz we decided to revert the commit for now because making the other method use the same layout ended up being unnecessarily more code than we save here. Once we revisit our choice of table framework the whole interface will probably be removed too so we can fix this then.
This reverts commit ec8dff906ee59bd1ee5d63341bbf4c98e4a4e5db. 
Closes https://github.com/stacklok/minder/pull/2009

Revert "Use variadic parameters for the table interface (#2008)"

---

cmd/cli/app/root.go

The message that the config file is not present and that default are
about to be used should not be printed on stdout as it breaks json
output - you can't then just pipe the rest of the command to jq.
I would honestly prefer to remove the message altogether as asking users
to redirect stderr to /dev/null seems like a nuisance, but let's start
with not printing the message to stdout.

Don't print informational message on stdout

---

internal/util/cli/cli.go

We used to just print the stringified error code, e.g. Invalid Argument, but not the actual reason.
Fixes: #2012

Print Details, not Description when a rpc error is caught

---

cmd/cli/app/root.go

The newline was missing which was messing with the output.

Add newline to `No config file present, using default values.`

---

cmd/dev/app/rule_type/rttst.go

This overwrites the remediation and alert to be `off` since we don't want to
execute actions when testing. This is not _yet_ supported and causes a segfault.
So, let's turn it off for now. If the need comes to test the actions themselves
with `mindev` we can work on turning it on later. But, for now, no segfault
is better.
Closes: https://github.com/stacklok/minder/issues/1858

Don't execute actions when running `mindev ruletype test`

---

cmd/cli/app/profile/list.go

Instead of having several tables as so:
```
$ minder profile list
No config file present, using default values.
+--------------------------------------+----------------------------------------------------+----------+-------+-----------+
|                  ID                  |                        NAME                        | PROVIDER | ALERT | REMEDIATE |
+--------------------------------------+----------------------------------------------------+----------+-------+-----------+
| 6fec2b7b-6489-487c-8fe3-f611efdf5d53 | demo-profile                                       | github   | on    | on        |
+--------------------------------------+----------------------------------------------------+----------+-------+-----------+
+--------------------------------------+----------------------- …
```

Print profiles in one table instead of several

---

cmd/cli/app/ruletype/common.go
cmd/cli/app/ruletype/ruletype_apply.go
cmd/cli/app/ruletype/ruletype_create.go
cmd/cli/app/ruletype/ruletype_get.go
cmd/cli/app/ruletype/ruletype_list.go
internal/util/cli/table/layouts/layouts.go
internal/util/cli/table/simple/simple.go

This shows more details for the rule type in a vertical table.
e.g.
```bash
$ minder ruletype get -i 7f1bbee6-a27a-4318-95f5-7408f2fcb106
No config file present, using default values.
+-------------+-----------------------------------------------------------+
|  RULE TYPE  |                                                           |
+-------------+-----------------------------------------------------------+
| ID          | 7f1bbee6-a27a-4318-95f5-7408f2fcb106                      |
+-------------+-----------------------------------------------------------+
| Name        | dependabot_configured                                     |
+-------------+-----------------------------------------------------------+
| Provider    | github                                                    | …
```

Show rule type details vertically in get call

---

internal/controlplane/handlers_githubwebhooks_test.go
internal/engine/executor_test.go
internal/util/testqueue/passthroughqueue.go

The idea is that the eventer should be ready to issue events before we
try to parse and process an event.
This also adds another log line to know if the test is blocked because of the
last `Wait` call.
Moreso, this adds logging to the mock event handler plugin.
Finally, this makes sure handler registration happens before the eventer runs, so we don't loose events.
Closes https://github.com/stacklok/minder/issues/1710

entity event handler test fixes

---

internal/events/eventer.go
internal/events/eventer_test.go

Fix #1839
Opted for a histogram instead of gauge, because the library doesn't have a synchronous gauge.

Add metric for message processing latency

---

.github/workflows/lint.yml
.github/workflows/main.yml
.github/workflows/pr.yml
.github/workflows/tags.yml

This re-uses the `golangci-lint.yml` file and renames it `lint.yml`.
Now it runs lint AND go mod tidy verification, it'll probably hold more lint
commands in the future.
Closes: https://github.com/stacklok/minder/issues/1795

Add CI job that makes sure that `go mod tidy` is run

---

cmd/server/app/root.go
docker-compose.yaml
internal/config/identity.go

Add flag for identity server base URL

---

internal/events/eventer.go

We have two places where middlewares are added, one of them being a duplicate. This commit fixes that.

Refactor eventer middleware

---

docs/docs/getting_started/quickstart.md

--profile is now --name
I was attempting the quickstart guide and came across this one small issue.

Fix: Docs - Update quickstart.md

---

internal/events/eventer.go

Closes: https://github.com/stacklok/minder/issues/1922
This PR adds functionality for emitting metrics when a message is added to the dead-letter queue. This is done by adding a "tracking" middleware that checks for the "posion" metadata added by the Watermill library.
Also, this change fixes the "recordMetrics" function which wasn't emitting any histogram-related metrics - we should be operating on `msg`, rather than on the result of `h()`.

Add DLQ metrics

---

internal/events/eventer.go

This PR is a follow-up on the following suggestion: https://github.com/stacklok/minder/pull/2052#discussion_r1440992647
Also, we can now see the metrics being exported as expected in Grafana (in Staging) (+ the "poison" attribute):
`minder_messages_processing_delay_milliseconds_count{app="minder",instance="10.0.2.229:9090",job="kubernetes-pods",namespace="mediator",node="ip-10-0-2-241.ec2.internal",otel_scope_name="eventer",pod="minder-7fc6d89469-qfhxr",pod_template_hash="7fc6d89469",poison="false"}`

Refactor DLQ eventer observability func

---

internal/config/client/config_test.go

This fixes the command line arguments test for the client cli. It also adds
a test that's skipped but reflect the issue we have in #2067.

Add dedicated test for to reproduce #2067 and another one to test cli

---

cmd/cli/app/root.go
internal/constants/prod.go
internal/constants/staging.go

Staging can sometimes be unstable and there's need to warn users about this

Warn users when the target environment for the CLI is staging

---

cmd/cli/app/repo/repo_register.go
cmd/cli/app/repo/repo_register_test.go
internal/util/cli/cli.go

Fixes #1826 
---
Major Changes:
-  `repo register --name` now skips registered repos, printing to the console that repo is already registered
- Added UT for  `getUnregisteredInputRepos` (new function)

`repo register --name` should skip already registered repositories

---

cmd/cli/app/root.go
cmd/server/app/root.go
internal/config/client/config_test.go
internal/config/utils.go
internal/config/utils_test.go

Fixes #2067
---
For rationale see https://github.com/stacklok/minder/issues/2067#issuecomment-1877102081
Major Changes:
- Check config file contents before adding it to the viper store
- UT for `GetKeysWithNullValueFromYAML`

Handle null values in config file to prevent incorrect data retrieval from viper store

---

cmd/cli/app/root.go

This ensures that -ojson output is valid JSON

Pipe a CLI warning to stderr

---

docs/docs/ref/proto.md
pkg/api/openapi/minder/v1/minder.swagger.json
pkg/api/protobuf/go/minder/v1/minder.pb.go
pkg/api/protobuf/go/minder/v1/minder.pb.gw.go
proto/minder/v1/minder.proto

The Context currently contains the provider and the project. A user is not tied to either of those, so we don't need to include the context in user related operations like fetching and deleting.

Remove context from user CRUD requests

---

docker-compose.yaml

This adds a simple OpenFGA deployment to the docker-compose in order for us
to test and work with this.
It uses an in-memory datastore and no authentication, so this is not suitable
for production.

Add OpenFGA deployment to docker-compose

---

internal/controlplane/handlers_oauth.go
internal/controlplane/handlers_profile.go
internal/controlplane/handlers_repositories.go

The body of `providerError` is:
```golang
func providerError(err error) error {
if errors.Is(err, sql.ErrNoRows) {
return util.UserVisibleError(codes.NotFound, "provider not found")
}
return fmt.Errorf("provider error: %w", err)
}
```
So all these cases were doubling-up `"provider error: provider error: "`

Remove double-wrapping of "provider error"

---

cmd/cli/app/profile/apply.go
cmd/cli/app/profile/common.go
cmd/cli/app/profile/create.go
cmd/cli/app/quickstart/quickstart.go
cmd/cli/app/ruletype/common.go
cmd/cli/app/ruletype/ruletype_apply.go
cmd/cli/app/ruletype/ruletype_create.go
docs/docs/ref/proto.md
internal/controlplane/handlers_profile.go
internal/controlplane/handlers_ruletype.go
internal/engine/executor.go
internal/engine/profile.go
internal/engine/profile_test.go
internal/engine/rule_types.go
pkg/api/openapi/minder/v1/minder.swagger.json
pkg/api/protobuf/go/minder/v1/minder.pb.go
pkg/api/protobuf/go/minder/v1/profile.go
pkg/api/protobuf/go/minder/v1/rule_types.go
proto/minder/v1/minder.proto

- Remove the top level context from protos that already have a nested context (ruletype, profile)
- Add function to fetch nested context
- Allow CLI command flags to override YAML context
Note: this does not change the DB implementation, where ruletypes, profiles and repos are still tied to a provider and project.
Fix #2103

Remove duplicate top level context

---

internal/engine/actions/actions.go
internal/engine/errors/errors.go
internal/engine/executor.go
internal/engine/executor_test.go
internal/engine/interfaces/interface.go
internal/engine/rule_types.go
internal/logger/telemetry_store.go
internal/logger/telemetry_store_test.go

Extends the telemetry store so that all the rules being evaluated are stored in the telemetry store for sending later.
Fixes: #1881

Rule evaluator business telemetry

---

internal/controlplane/handlers_profile.go
internal/controlplane/handlers_ruletype.go
internal/engine/context.go
internal/engine/executor.go
internal/reconcilers/run_profile.go

- Directly access project ID field for consistency
- Remove unused field project name and provider ID
- Remove check for project existence in entity validator, because it's checked later, and the check here is inconsistent because the execution only reaches here when the user doesn't supply a value

Cleanup entity context

---

internal/engine/eval/vulncheck/pkgdb.go

Small PR to expose the suggested patch version in the `patchLocatorFormatter` interface.
Currently, this interface only allows for checking whether a patch version has been found, and does not allow the suggested version to be easily retrieved.
Will be useful for providing richer minder summaries on PRs.

Allow retrieval of suggested patch version in `patchLocatorFormatter` interface

---

internal/controlplane/handlers_ruletype.go

Use the DB saved result for the response instead of reusing the request body.

Derive ruletype response from DB entry

---

internal/verifier/sigstore/container/container.go
internal/verifier/sigstore/sigstore.go

The following PR has the following changes:
* Recreates https://github.com/stacklok/minder/pull/2120 switching Minder to using offline sigstore verification. For those that are interested there's a nice and detailed explanation of how this works at https://github.com/stacklok/minder/pull/2120#issuecomment-1892619405 
* Sets the TimestampVerificationData to nil. The reason is it was wrongfully used, but also its value is obtained from the `SignedEntryTimestamp` assuming `verifyWithObserverTimestamps()` is set (we do set it).
Thanks to @haydentherapper for raising this! 🍻

Switch to offline Sigstore verification and set TimestampVerificationData to nil

---

internal/controlplane/common.go
internal/controlplane/handlers_artifacts.go
internal/controlplane/handlers_authz.go
internal/controlplane/handlers_authz_test.go
internal/controlplane/handlers_oauth.go
internal/controlplane/handlers_oauth_test.go
internal/controlplane/handlers_profile.go
internal/controlplane/handlers_repositories.go
internal/controlplane/handlers_ruletype.go
internal/controlplane/server.go
internal/engine/context.go

- For all requests where the authorization depends on the project, populate the project in the context
- Always fetch the project from the context when making authorization decisions
Fix https://github.com/stacklok/minder/issues/2078

Add middleware that populates project in context

---

internal/controlplane/handlers_authz.go
internal/controlplane/handlers_authz_test.go
internal/controlplane/handlers_profile.go
internal/controlplane/handlers_ruletype.go
internal/engine/context.go

In https://github.com/stacklok/minder/pull/2139#discussion_r1455758961, I noted that we were using the result from `EntityFromContext` without checking to see if it was `nil`.  @eleftherias suggested that we might as well return a concrete struct rather than littering our code with obnoxious checks.  In doing so, I found a case where we `panic` if `Project` is set and `Provider` is not, so I fixed it and added tests until fear turned to boredom.
I also removed `GetProvider` and `GetProject` methods (and switched to direct struct references), since they didn't seem to add any value.  (If they were defaulting values even if `EntityContext` were `nil`, I'd have kept them, but it seemed superfluous in this case.)

Remove EntityContext pointers and replace with struct references

---

go.mod
go.sum

Release notes https://github.com/open-telemetry/opentelemetry-go/releases/tag/v1.22.0

Bump go.opentelemetry.io/otel/exporters/prometheus from 0.44.0 to 0.45.0

---

internal/controlplane/handlers_artifacts.go
internal/controlplane/handlers_authz.go
internal/controlplane/handlers_oauth.go
internal/controlplane/handlers_profile.go
internal/controlplane/handlers_repositories.go
internal/controlplane/handlers_ruletype.go
internal/controlplane/handlers_user.go
internal/engine/executor_test.go
internal/logger/telemetry_store.go
internal/logger/telemetry_store_test.go
internal/logger/telemetry_store_watermill.go
internal/logger/telemetry_store_watermill_test.go

The following PR adds telemetry data for authenticated RPC calls for each Minder service.
**Context related:**
* `login_sha` - SHA256 hash of the user's identity from Keycloak (sub field from the token)
* `provider` name and `project` UUID (project name was removed in https://github.com/stacklok/minder/pull/2124) 
**Resource related:**
* `repository` and `artifact` ID 
* Both IDs and Names of `profiles` and `rule types` in requests and in evaluation results
**Improvements:** (not part of this PR)
* I saw @eleftherias's comment at https://github.com/stacklok/minder/pull/2130#issuecomment-1894104431 and that would be nice once we have it, because then we should be able to move most of the telemetry code from this PR out of the handlers and replace it with one in the middleware. …

Add BusinessTelemetry to authenticated RPC calls

---

cmd/server/app/migrate_up.go
config/server-config.yaml.example
deployment/helm/Chart.lock
deployment/helm_tests/basic.yaml-out
deployment/helm_tests/sidecar.yaml-out
go.mod
go.sum
internal/authz/authz.go
internal/config/server/authz.go
internal/config/server/config.go

This ensures that we create an authz store as part of the migration command.
To enable this, an Authz configuration section was created.
The next step is to actually populate the model.

Create initial configuration for authz and create store as part of migration

---

internal/config/server/authz.go

We should default to an empty string since we initially generate and
then list the store ID's when building the authz client. Passing a
default store ID is not the right thing to do. We should instead just
pass a store ID from the configuration once we have already bootstrapped
the app.

Don't default to `minder` as default store ID is authz configuration

---

internal/engine/actions/remediate/pull_request/pull_request.go
internal/engine/ingester/git/git_test.go

Fixes #2159 
--- 
- The initial approach was to copy the billy filesystem, but `go-git` internally restores the filesystem while checking out to different branches.
- The ingested data would be technically modified after being cached, but the state of the originally fetched branch would be preserved.

Checkout back to the original branch to reset the filesystem preventing ingest cache from corrupting

---

cmd/server/app/migrate_up.go
internal/authz/authz.go
internal/config/server/authz.go

This adds the model writing to the migration script. It'll auto-detect
the store ID unless it's explicitly provided.
Note that I had to remove the token path file validation since it was running and failing.
Closes https://github.com/stacklok/minder/issues/1854

Initialize model on migration

---

internal/engine/eval/rego/lib.go
internal/engine/eval/rego/lib_test.go

This adds a new rego function called `file.http_type` which, as the name
suggests, reads the HTTP type for a given file.
The intention is to be able to write policies that verify that files
must (or most not) be of a given type.

Add rego function to detect file types

---

internal/authz/authz.go
internal/authz/interface.go

This fills up the implementation for the Write and Delete tuples for the
OpenFGA Authz client in such a way that it's easy to hook up in the
minder server.

Implement Write and Delete tuple functions for OpenFGA Authz Client

---

cmd/dev/app/container/cmd_verify.go
cmd/dev/app/container/container.go
cmd/dev/app/root.go

This is useful when hacking on artifact attestation support so that the
developer doesn't have to run the full minder machinery.
Example usage:
```
mindev container verify --owner=jakubtestorg --name=bad-go --digest=sha256:d7c4ea4a259b5886c42b66182ab7632b8bc3e3751af8393372d2806e6abdc83
```

Add a mindev command to verify containers

---

internal/logger/telemetry_store.go
internal/logger/telemetry_store_test.go
internal/logger/telemetry_store_watermill_test.go

"telemetry: 1" 
This discrepancy is likely due to how the log data is being serialised or interpreted between Fluent Bit and the Output targets. This "might" be the reason we are not seeing logs exported to S3 since we have a 
`$telemetry ^(true)$` condition.

Update: telemetry field to be string

---

docs/docs/how-to/using-minder-with-ghas.md

Adding a new page to the "Using Minder" section of Minder docs to explain how to use Minder with GitHub Advanced Security.

Create new docs entry under "Using Minder" for using Minder with GHAS

---

internal/engine/eval/rego/lib.go

I'm not sure why we made it to return `true` only for non-directory
files. But I think it makes sense to have it be `true` for directories
as well.

rego: Return `true` for `file.exists` for directories too

---

cmd/server/app/serve.go
database/mock/store.go
database/query/projects.sql
internal/controlplane/default_project.go
internal/controlplane/handlers_user.go
internal/controlplane/handlers_user_test.go
internal/controlplane/identity_events.go
internal/controlplane/identity_events_test.go
internal/controlplane/server.go
internal/db/projects.sql.go
internal/db/querier.go

This hooks up the initial creation of tuples for authorization in the
server.
Tuples define the relationships between users and projects in minder via
a role.
The intent is for these to happen first, and roll them back if database
operations fail.
Closes: https://github.com/stacklok/minder/issues/1851
Closes: #1850

Hook up authz tuple writing to Minder server

---

cmd/server/app/serve.go
internal/authz/authz.go

This sets up OpenFGA as the authzClient implementation. This will
effectively start populating tuples in OpenFGA from created minder
projects and registered users.
This, however, does not actually do authorization just yet. We haven't
hooked up the needed middleware.

Set up OpenFGA as authz client implementation for minder server

---

cmd/server/app/migrate_up.go
internal/authz/authz.go

This adds a final step to the minder migration script to go throught the
existing users and attempt to migrate them into OpenFGA.
Closes: https://github.com/stacklok/minder/issues/1849

Add migration step for minder users to FGA tuples

---

cmd/dev/app/container/cmd_verify.go
go.mod
internal/controlplane/handlers_githubwebhooks.go
internal/reconcilers/artifacts.go
internal/verifier/sigstore/container/container.go
internal/verifier/sigstore/sigstore.go
internal/verifier/verifier.go

In addition to fetching provenance attestations from an OCI image, let's also
support the GitHub attestation endpoint as a fallback (a fallback since it's
not GA yet).
The attestation reply is unmarshalled into a protobuf representation and
passed to sigstore-go.
Fixes: https://github.com/stacklok/epics/issues/174

Support GitHub attestation endpoint

---

docker-compose.yaml
internal/engine/eval/trusty/config.go
internal/engine/eval/trusty/trusty.go
internal/engine/eval/trusty/trusty_rest_handler.go

This uses the `description` scores in trusty to be able to evluate
scores using the trusty evaluator. This allows for having more detailed
policies such as the following:
```yaml
version: v1
type: profile
name: acme-github-profile
context:
provider: github
alert: "on"
remediate: "off"
pull_request:
- type: pr_trusty_check
def:
action: summary
ecosystem_config:
- name: npm
score: 8
evaluate_score: provenance
- name: pypi
score: 8
evaluate_score: provenance
```
That is, we're able to just care about provenance and not just the
trusty summary.

Add ability to evaluate scores based on detailed scores for trusty

---

internal/authz/authz.go

This detect if the error for deleting an object is caused by the tuple
not existing, and if so, it discards the error since that's what we
wanted. Thus making calls to the tuple deletion idempotent.

Make authz tuple deletion idempotent

---

internal/util/helpers.go

These functions don't appear to be used or tested. Let's remove them
rather than leave them to rot.

Remove unused code

---

cmd/dev/app/container/cmd_verify.go
internal/controlplane/handlers_githubwebhooks.go
internal/engine/ingester/artifact/config.go
internal/reconcilers/artifacts.go
internal/verifier/verifier.go

The following PR allows for configuring a custom sigstore root. Currently defaults to the PGI.
Motivated by https://github.com/stacklok/epics/issues/182

Allow to configure a custom sigstore tuf root

---

cmd/server/app/migrate_up.go
cmd/server/app/serve.go
internal/authz/authz.go
internal/authz/interface.go
internal/authz/mock/noop_authz.go
internal/authz/mock/simple_authz.go

This removes the OpenFGA-specific logic from the migration script and
relies instead on a more general interface. This also makes the authz
constructor to return that interface to make this happen. The functions
that no longer need exporting are now private, and unused functions are
removed.

Solidify authz Client interface

---

.github/workflows/compose-migrate.yml
docker-compose.yaml

- Fixing CI failure:
`
Error: error while creating authz client: Key: 'AuthzConfig.ApiUrl' Error:Field validation for 'ApiUrl' failed on the 'required' tag
Message: Error executing root command
Details: error while creating authz client: Key: 'AuthzConfig.ApiUrl' Error:Field validation for 'ApiUrl' failed on the 'required' tag
`
- Modified logic of checking container state

Update compose-migrate action to run openfga container alongside

---

docs/docs/ref/proto.md
pkg/api/openapi/minder/v1/minder.swagger.json
pkg/api/protobuf/go/minder/v1/minder.pb.go
pkg/api/protobuf/go/minder/v1/minder.pb.gw.go
pkg/api/protobuf/go/minder/v1/minder_grpc.pb.go
proto/minder/v1/minder.proto

This adds the protobuf API definition for our permissions API; that is,
the API that allows us to assign permissions to subjects.
Note that roles are not something we allow users to extend; their names
are identifiers that we define as relationships in OpenFGA.

Define Permissions API

---

internal/authz/authz.go
internal/authz/interface.go
internal/authz/mock/noop_authz.go
internal/authz/mock/simple_authz.go
internal/controlplane/handlers_user_test.go
internal/controlplane/identity_events.go
internal/controlplane/identity_events_test.go

This removes the minder check for projects while deleting a user to
instead fully rely on OpenFGA's relationships to make the deletion.

Fully rely on OpenFGA to delete user permissions

---

cmd/cli/app/auth/common.go

This prints the user subject on user creation, login and when doing
`whoami`. This will be helpful for setting up roles once the permissions
API is ready.

Print user subject on `auth` subcommands

---

internal/authz/authz.go
internal/authz/authz_test.go
internal/authz/interface.go

This adds a unit test to validate that any role we add to the `AllRoles`
list is indeed a valid relation in the FGA model.

Ensure roles in authz `AllRoles` are defined in FGA model

---

internal/controlplane/handlers_authz.go
internal/controlplane/handlers_token.go

The token interceptor seemed like a better place for adding the user subject to the business telemetry.

Move user id telemetry to token interceptor

---

cmd/cli/app/project/role/role_grant_list.go

I had left there the error that comes out of `role grant` which is not
what we want to show to users for this scenario.

Fix CLI error output for `role grant list`

---

.github/workflows/compose-migrate.yml
cmd/server/app/migrate_up.go

Instead of checking for the expected tables which might come and go,
make sure that the version corresponds to the highest version in the
database migration files.

Change the database migration CI workflow to check for the expected DB version instead

---

docker-compose.yaml

The following updates the tmpfs path in our docker compose file.
You can find more details in the issue below but essentially the caching started failing with permission denied errors after a change that has no obvious connection. 
We've noticed this with @teodor-yanev and he checked that the issue is not present in our staging/prod envs. 
I'll be happy if someone explains how one relates to the other 🤯 
Fixes: https://github.com/stacklok/minder/issues/2260

Update the tmpfs path for sigstore caching in docker compose

---

cmd/server/app/serve.go
internal/engine/executor.go

From: https://discord.com/channels/1184987096302239844/1185287949240242258/1202878694201237515
The wait group counter was being incremented and decremented, but the server wasn't waiting for all entity event executions to finish. This change ensures that the server waits for all entity events to be executed before exiting.

Add wait to ensure all entity events are executed

---

cmd/cli/app/profile/table_render.go
database/migrations/000017_rule_evaluations_rule_name_backfilling.down.sql
database/migrations/000017_rule_evaluations_rule_name_backfilling.up.sql
database/query/profile_status.sql
internal/controlplane/handlers_profile.go
internal/db/models.go
internal/db/profile_status.sql.go
internal/engine/actions/alert/security_advisory/security_advisory.go
internal/engine/eval_status.go
internal/engine/executor_test.go

Fixes #1609
---
Changes and implications:
- `entity_profiles.contextual_rules` are modified to have rule name key with `rule_type` or `rule_type-rand_uuid` in case of collisions
- Existing null `rule_evaluations.rule_name` columns are filled by referring to `name` key in `entity_profiles.contextual_rules`
- Handlers and Sql queries are updated to reflect not null constraint on `rule_evaluations.rule_name` column
- `migration_profile_backfill_log` table is created to support migrating down
- The rules are reconciled by the subsequent `InternalProfileInitEventTopic`, and `ExecuteEntityEventTopic` events. Profiles/Repositories not receiving these types of events **won't be reconciled** to update them to the latest state.
- Reconciliation can potentially open new PRs/Security Advisories, …

Fix Rule Evaluation Logic for Handling Multiple Rules of the Same Type - Part 2 (Data Backfilling)

---

docs/docs/developer_guide/get-hacking.md

When running minder outside of docker-compose, openfga also needs to be started explicitly.
Document this fact in the README.
Note: In future, it may make sense to solve this problem by using `profiles` in the docker-compose
file. For example, all the dependencies needed for running minder outside of docker could be
added to `dependencies` profile, so that they can be started with:
`docker-compose up --profile dependencies`
(Perhaps with a Makefile wrapper, e.g. `make docker-dependencies-run`)

Add "openfga" to list of services to start

---

go.mod
go.sum
internal/engine/eval/vulncheck/pkgdb.go
internal/engine/ingestcache/ingestcache.go
internal/providers/telemetry/telemetry.go

We were using an old release of `xsync` from 2022 which hasn't been
receiving updates through dependabot because of the `v3` module bump.

Migrate to github.com/puzpuzpuz/xsync/v3

---

internal/verifier/sigstore/sigstore.go
internal/verifier/sigstore/tufroots/tuf-repo.github.com/root.json

This patch embeds a root.json to be able to bootstrap the TUF root for
github's private sigstore instance as well as sets the appropriate
verifier options based on what fields are populated in the certificates
produced by GH's Fulcio instance.

Support GH's private sigstore instance

---

internal/controlplane/handlers_githubwebhooks.go
internal/engine/ingester/artifact/artifact.go
internal/verifier/sigstore/container/container.go

The following PR updates:
* We now collect and try to create a bundle for all simple signing layers present in the artifact's manifest. This is the use case when we search for signatures in the OCI registry.
* We no longer filter webhook events for `.sig` versions
* Renamed the `workflow_name` parameter we expose to the rule type to something more generic like a `signer_identity` and it nows include the value of the SAN parameter (for example this now allows for users to set the email of the identity that  is expected to sign the artifact through Fulcio)
Fixes: #2298

Verify all simple signing layers, do not filter events for .sig, enable OIDC identities

---

internal/controlplane/handlers_user.go

This changes the user deletion logic to first delete a user and the
relevant project information in minder and only after that doing the
deletion in keycloak. This would address issues where the deletion gets
interrupted thus leaving a user's project in minder whereas keycloak
would provision an entirely new user.

Fix user deletion logic (first minder then keycloak)

---

cmd/cli/app/auth/auth_whoami.go
cmd/cli/app/auth/common.go

This will be useful in scripts to read the project ID associated with
the username, e.g.:
```
minder auth whoami -ojson | jq '.projects[] | select(.name == "jhrozek") | .projectId'
```

Add json/yaml output to whoami

---

cmd/cli/app/profile/status/status_list.go
cmd/cli/app/profile/table_render.go
cmd/cli/app/ruletype/common.go
go.mod
go.sum
internal/util/cli/cli.go
internal/util/cli/table/simple/simple.go

* Removes the use of emojis in profile and remediation statuses - they were nice, but they always messed up the table rendering 
* Moved the Guidance column from the detailed `profile status list` table and put it in the `ruletype get` output
* Added a Skipped text for remediations that skipped, prior to that it was empty looking and it looked like there could have been an error
* Added a function that concatenates and wraps a string. Used that in the `ruletype create/apply` output so it renders on a smaller footprint. 
* Shortened some of the headers too because of that.

Update CLI table outputs for ruletype and profile

---

docs/docs/getting_started/first_profile.md
docs/docs/how-to/manage_profiles.md

Updated the example profile and removed the emojis from the example output for `profile status`.

Update docs for getting started and how to

---

docs/docs/ref/proto.md
internal/engine/eval/trusty/actions.go
internal/engine/eval/trusty/trusty_rest_handler.go
internal/engine/eval/vulncheck/review.go
internal/engine/ingester/diff/parse.go
internal/engine/ingester/diff/parse_test.go
pkg/api/openapi/minder/v1/minder.swagger.json
pkg/api/protobuf/go/minder/v1/minder.pb.go
pkg/api/protobuf/go/minder/v1/minder.pb.gw.go
proto/minder/v1/minder.proto

* Updates the go parser extracting the new packages from the `go.mod` diff
* Updates the go parser unit tests, it seemed previously they were addressing `go.sum` patch diffs
* Fixes the Trusty hyperlink for the alternative packages and now shows `No alternative found` when there's no package alternative found.
* Renames the `Ecosystem` column to `Pkg` so there's no horizontal scrolling because of this
* Fixes a bug in Minder which was not rendering to the user low-score packages that had no alternatives. 
Fixes: #2314 
**Before:**
**After:**

Fix a few Trusty issues that enable support for Go in Minder

---

.github/workflows/test.yml

We've selected https://coveralls.io/ for tracking code coverage for Minder. Set up coverage as another action with limited permissions.

Enable Coveralls for coverage reporting

---

.github/workflows/test.yml

Reverts stacklok/minder#2342
The YAML here is not valid (wrong indentation), and this causes all testing to break.

Revert "Enable Coveralls for coverage reporting"

---

.github/workflows/test.yml
README.md

We can also use the direct URL (https://coveralls.io/github/stacklok/minder), but it won't show up on the Coveralls webpage unless you have repo admin, so the badge is a handy way to get to coverage.

Add coveralls badge, reduce debugging spew

---

internal/util/statuses_test.go

This adds test coverage for the aforementioned package.

Add test coverage for `internal/util/statuses`

---

internal/util/rest.go
internal/util/rest_test.go

This adds tests for the functions in the aforementioned package.

Add test coverage for `internal/util/rest`

---

internal/auth/jwauth_test.go
internal/db/repositories_test.go
internal/util/rand/random.go
internal/util/rand/random_test.go

This cleans up the aforementioned package, thus minimizing it and
removing a bunch of dead code. some code that was only used in one
package's tests was moved to the relevant test file.

Remove unused functions from `internal/util/rand`

---

.github/workflows/lint.yml

Instead of having to manually maintain the golangci-lint version in our
job, let's instead default to the latest one. This will get us the
latest and greatest CI checks provided by the tool and reduce the
maintenance burden of manual upgrades to this file. Unfortunately, this
is something that dependabot does not support updating.

Use latest golangci-lint in CI

---

.mk/test.mk

1. Explicitly include code under /cmd and /internal, even if it is not
being tested
2. Exclude auto-generated DB code under /internal/db
3. Exclude anything which contains `/mock/` in the package - assumption
is that these are mocks for tests

tweak test coverage behaviour 

---

.github/workflows/lint.yml

This allows the action to add relevant comments to the code when
linting. These permissions were taken from the action's doc.

Allow golangci-lint to comment on PRs

---

.github/workflows/main.yml

Elevate the permissions on the linting job to allow for golangci-lint to comment and set statuses
Fixes: https://github.com/stacklok/minder/actions/runs/7962377835

Elevate the permissions on the linting job in main.yml

---

internal/controlplane/handlers_authz.go
internal/controlplane/handlers_authz_test.go

Fixes #2376
When the context of a request is missing, return a user-visible "InvalidArgument" response. Previously, this returned a regular Go error which caused the GRPC server to return a 500 response to the client.

When the `context` of a request is nil, return InvalidArgument/400

---

.github/workflows/pr.yml
.github/workflows/tags.yml

Missed fixing this for the other workflows running the linter job.

Fix linting permissions for pr.yml and tags.yml workflows

---

internal/eea/eea.go
internal/eea/eea_test.go

This just adds more coverage. Note that this also removed an invalid branch that used to check for `sql.ErrNoRows` upon a `ListFlushCache` call, that branch is never reached as the list would just return an empty array.

Add more coverage to `internal/eea` package

---

cmd/dev/app/container/cmd_verify.go
cmd/server/app/serve.go
internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_repositories.go
internal/controlplane/server.go
internal/engine/actions/alert/security_advisory/security_advisory.go
internal/engine/actions/remediate/gh_branch_protect/gh_branch_protect.go
internal/engine/actions/remediate/pull_request/pull_request.go
internal/engine/actions/remediate/rest/rest.go
internal/engine/eval/homoglyphs/application/invisible_characters_eval.go
internal/engine/eval/homoglyphs/application/mixed_scripts_eval.go
internal/engine/eval/trusty/trusty.go
internal/engine/eval/vulncheck/vulncheck.go
internal/engine/executor.go
internal/engine/ingester/artifact/artifact.go
internal/engine/ingester/diff/diff.go
internal/engine/ingester/rest/rest.go
internal/providers/github/github.go
internal/providers/github/github_rest.go
internal/providers/github/github_test.go
internal/providers/providers.go
internal/providers/ratecache/store.go
internal/providers/ratecache/store_test.go
internal/reconcilers/artifacts.go
internal/reconcilers/reconcilers.go

Issue #2261 
* We employ an optimistic concurrency control model to minimize goroutine blocking and reduce rate limit errors, thus preventing integration bans
* Each server replica maintains its own set of rate-limited clients, eliminating the need for synchronization across replicas. If a rate limit error occurs, the client self-blocks and is added to a cache for future requests
* Requests that return rate limit errors are retried following a backoff period
Note:
The current watermill pub-sub implementation being used, i.e. SQL and go channels, are both a single channel with head-of-line blocking, which means that blocking in middleware/handler blocks all processing. So, currently, if a token is blocked, the entire processing will be blocked.
This will change when we shift to other …

Handle rate limiting errors for GitHub API

---

cmd/server/app/serve.go
internal/providers/ratecache/store.go
internal/providers/ratecache/store_test.go

Issue #2261 (From https://github.com/stacklok/minder/pull/2271#discussion_r1495557451)
* Using Wait() in server.go introduced the bug where if the context is not cancelled, the server will continue to wait even if other go routines finished
* Replaces Wait() with non blocking Close() operation
* All this is done to free the resources associated with ticker

Fix infinite wait for ratecache using non blocking Close() func

---

docs/README.md

OpenFGA seems to be using 3000 in our default docker setup which makes
the default `yarn serve` invocation throw an error. Let's change the
example `yarn` invocation to use a different port.

Change the yarn serve port for docs to 3001

---

proto/buf.yaml

See #2395 for details -- we needed to restore a removed proto field.

Mischief managed, return buf breaking checks to normal.

---

internal/engine/eval/vulncheck/pkgdb.go
internal/engine/eval/vulncheck/review.go

Fixes a few issues that affected the OSV support in Minder:
* Previously we were parsing the go.sum file which it does make sense, but we have no control over. Once we switched to parsing the go.mod file this broke the patching action Minder does (different format)
* Finding the line where the vulnerable package resides was prone to errors (line should be split to exactly 3 pieces)
* Counting the indentation was wrong and rendered poorly the suggested commit

Fix OSV support for Go to properly identify go.mod packages

---

internal/engine/ingester/diff/parse.go
internal/engine/ingester/diff/parse_test.go

Currently we are querying with Trusty all newly introduced dependencies, including the transitive ones which are not something we can update.
The following PR updates the diff ingester to skip ingesting Go dependencies that are indirect as they are transitive to the the main dependencies and are not actionable.
Before:
After:

Do not ingest indirect go dependencies

---

internal/controlplane/handlers_githubwebhooks.go

Reported on slack:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x48 pc=0x103b59350]
goroutine 1 [running]:
github.com/stacklok/minder/cmd/cli/app/repo.printRepoRegistrationStatus({0x14000128858, 0x1, 0x0?})
github.com/stacklok/minder/cmd/cli/app/repo/repo_register.go:245 +0xd0
github.com/stacklok/minder/cmd/cli/app/repo.RegisterCmd({0x104122e10, 0x14000536070}, 0x104b17f20, 0x1400063a408)
github.com/stacklok/minder/cmd/cli/app/repo/repo_register.go:93 +0x678
github.com/stacklok/minder/cmd/cli/app/repo.init.GRPCClientWrapRunE.func5(0x104b17f20, {0x103b61543?, 0x4?, 0x103b61547?})
github.com/stacklok/minder/internal/util/cli/cli.go:126 +0x138
github.com/spf13/cobra.(*Command).execute(0x104b17f20, …
```

Fix client crash with fix for GHSA-q6h8-4j2v-pjg4

---

internal/controlplane/handlers_authz.go

I've broken my staging account in a bunch of ways, but one of them is that I don't seem to be able to get project auto-detection to work (`authzClient.ProjectsForUser`).  We don't log the error from this call, so all I see is `cannot find projects for user` in the logs.  Let's include the detailed error message in the logs, in case it explains what's going on.
N/A

Improve logging when ProjectsForUser returns an error

---

internal/controlplane/handlers_repositories_test.go

Add test coverage for #2432, which was rushed in to fix GHSA-q6h8-4j2v-pjg4 -caused client crash
I ran `go test ./...`

Add test coverage for #2432

---

database/migrations/000020_webhook_id_resize.down.sql
database/migrations/000020_webhook_id_resize.up.sql
internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_repositories.go
internal/db/models.go
internal/db/repositories.sql.go
internal/db/repositories_test.go

Fixes #2443 (other fixes needed)
Related to the repo ID change made by Evan recently: use 64-bit ints for webhook IDs. This involves increasing the size of integer we use in the DB schema, and making changes to the business logic where we set the IDs.

migrate webhook IDs to 64-bit integers

---

go.mod
go.sum
internal/config/server/config.go
internal/config/server/server.go
internal/controlplane/server.go

This configures CORS middleware for minder's HTTP server which currently
is merely a gateway that converts from JSON to the GRPC implementation.
This also adds the means to configure CORS's allowed origins.

Allow for configuring CORS in minder's HTTP server

---

cmd/cli/app/auth/auth_login.go
cmd/cli/app/auth/common.go
cmd/cli/app/auth/offline.go
cmd/cli/app/auth/offline_get.go
cmd/cli/app/auth/offline_revoke.go
cmd/cli/app/auth/offline_use.go
internal/util/helpers.go

This adds new sub-commands to `minder auth` which enable the usage and installation
of offline tokens. These tokens enable you to create long-lived credentials which are handy
for CI and automation cases.
Co-Authored-By: Eleftheria Stein-Kousathana <eleftheria@stacklok.com>

Support for offline tokens

---

database/mock/store.go
database/query/provider_access_tokens.sql
internal/controlplane/handlers_oauth.go
internal/db/provider_access_tokens.sql.go
internal/db/provider_access_tokens_test.go
internal/db/querier.go

For OAuth flow provider enrollments we used to delete and recreate the
provider access token in order to be able to list the new token based on
CreatedAt. For the case where we pass a PAT, we would just error out
in case the token was already created.
Let's just upsert in both cases and instead of CreatedAt let's look at
UpdatedAt.
This will be useful for tests.
Fixes: #2411
Manual testing with both PAT enrollment and OAuth flow.
- [N/A] Updated any affected documentation.
- [N/A] Checked that related changes are merged.

Upsert provider access tokens instead of Create and Delete

---

cmd/dev/app/rule_type/lint.go

In order to allow us to use `mindev` in CI, this adds the ability for the
`ruletype lint` subcommand to walk through a directory and read multiple files.
This then aggregates the errors and prints them out.
To begin somewhere, it also adds the ability to skip rego validations which are quite verbose. We
can fix those little by little and enable them in CI later. They are enabled by default in
the sub-command.

Allow rule type linting to skip rego and read many rule types

---

internal/controlplane/handlers_repositories_test.go
internal/engine/actions/remediate/pull_request/pull_request.go
internal/engine/actions/remediate/pull_request/pull_request_test.go
internal/engine/eval/vulncheck/review.go
internal/engine/eval/vulncheck/review_test.go
internal/providers/github/github_rest.go
internal/providers/github/mock/github.go
pkg/providers/v1/providers.go

Ref https://github.com/stacklok/epics/issues/154
Make the GitHub provider interface more generic, in preparation for the GitHub app implementation.
Some methods were specific to the OAuth app implementation, for example getting the authenticated user.

Make GitHub provider interface more generic

---

internal/controlplane/handlers_repositories_test.go
internal/engine/eval/trusty/actions.go
internal/engine/eval/vulncheck/actions.go
internal/engine/eval/vulncheck/report.go
internal/engine/eval/vulncheck/review.go
internal/engine/eval/vulncheck/review_test.go
internal/providers/github/github_rest.go
internal/providers/github/github_test.go
internal/providers/github/mock/github.go
pkg/providers/v1/providers.go

Closes https://github.com/stacklok/minder/issues/1862
---
This PR allows for a single status comment to be repeatedly created and updated, illustrating an overview state of the minder evaluation. This summary comment is made **in conjunction with the minder review comment**.
- New interface for comments that includes formatting, more info, and emojis :octocat: 
- Creates or updates a single summary comment atop a PR that is edited whenever a new evaluation is run
- Finds correct prior minder review from GitHub API and (when applicable) dismisses it and creates a new review
- Include separate `internal/engine/eval/vulncheck/report.go` that handles review and status comment templating
- Checks if review or comment is from user `stacklokbot` -- preventing a user from abusing magic comment …

Create single status comment and correctly dismiss reviews

---

database/migrations/000025_provider_auth.down.sql
database/migrations/000025_provider_auth.up.sql
internal/db/models.go
internal/db/providers.sql.go
internal/providers/github/github.go

This adds an authorization_flow enum to the minder database. This is then used by providers.
GitHub will use two, which are enforced via a migration script. Any new projects
will get these two authorization flows set up.
Fixes #2517

Add provider authorization flow types to database

---

database/mock/store.go
database/query/session_store.sql
internal/controlplane/handlers_oauth.go
internal/controlplane/handlers_oauth_test.go
internal/db/querier.go
internal/db/session_store.sql.go

I noticed that the `port` field from `GetProjectIDPortBySessionState` isn't used anywhere in the response.  Removing it in preparation for some other refactoring.
Note: I did _not_ remove the column from the database _yet_, as I expect to have more substantial migrations in the future that I'll roll it into.  I could add a "currently unused" comment, but I think that would break our "no changes to existing migrations" check.

Remove unused 'port' from session state queries

---

docker-compose.yaml

Currently the OpenFGA playground is run by default in a local run (via `make run-docker`). The default port for OpenFGA playground is 3000, which also happens to be the default port for Next.js (used by a great many sites).
Avoid contention for this port by moving OpenFGA playground to 8085. You can now access it as http://localhost:8085/playground

OpenFGA: change playground port to 8085

---

internal/engine/profile.go

The get command was only returning remediate status, not alert.
Fixes: https://github.com/stacklok/epics/issues/237
```
curl -H "Authorization: Bearer $MINDER_BEARER_TOKEN" 'http://localhost:8080/api/v1/profile/67c550c7-74cd-4bd6-a6f4-78ffc65d6af9?context.provider=github&context.project=a34dc21e-0164-4508-ada1-32419bc72d65&id=67c550c7-74cd-4bd6-a6f4-78ffc65d6af9'
```

Return alert status in profile get

---

cmd/dev/app/container/cmd_verify.go
internal/engine/ingester/artifact/artifact.go
internal/verifier/sigstore/container/container.go

The access token set in `containerAuth` always comes from the GitHub client. Instead of passing in both the token and the client, only pass in the client and then fetch the access token from the client.

Reuse token from GitHub client in container verifier

---

internal/verifier/sigstore/container/container.go

Instead of creating a custom GitHub authenticator, use the built-in Basic auth Authenticator.
The difference is in the returned error, where the custom authenticator returned `ErrAuthNotProvided` if the owner or token was empty. 

Use basic auth for container verifier

---

cmd/cli/app/artifact/artifact.go
cmd/cli/app/profile/profile.go
cmd/cli/app/project/role/role.go
cmd/cli/app/provider/provider.go
cmd/cli/app/quickstart/quickstart.go
cmd/cli/app/repo/repo.go
cmd/cli/app/ruletype/ruletype.go
internal/util/cli/project.go

This allows for setting the project ID to work on via an environment variable.
One would set the `MINDER_PROJECT` environment variable as follows:
```
export MINDER_PROJECT=$(minder project list -o json | jq -r '.projects | map(select(.name == "foo"))[0].projectId')
```
Where `foo` is the project ID.
Then, one could simply do `minder repo list` or any other project-scoped operation
without needing to pass in the `-j` or `--project` flag.
This could be enhanced further by having a dedicated CLI command to get the ID, but let's enhance that
in further PRs.

Allow setting project ID via environment variable

---

cmd/server/app/migrate_up.go
database/mock/store.go
database/query/providers.sql
internal/controlplane/handlers_profile_test.go
internal/controlplane/handlers_ruletype_test.go
internal/db/providers.sql.go
internal/db/providers_test.go
internal/db/querier.go
internal/eea/eea_test.go
internal/projects/create.go

A recent PR added the "authorization flows" concept to the database ( https://github.com/stacklok/minder/pull/2570 ). It even added a migration
to ensure existing entries had an appropriate default. However, it did not change the default
provider created in each project to actually contain the aforementioned default flows.
This PR fixes that.

Ensure we actually set the default auth flows for the github provider

---

internal/providers/github/github.go

Wrapping a `StaticTokenSource` in a `ReuseTokenSource` behaves the same as simply using a `StaticTokenSource`.
The `ReuseTokenSource` will reuse a token until it's invalid and then fetch a new one from the provided source.
Since `StaticTokenSource` always returns the same token, the result was that `ReuseTokenSource` was behaving as a `StaticTokenSource`.

Use static token source for GitHub provider

---

cmd/dev/app/root.go
cmd/dev/app/testserver/testserver.go
cmd/server/app/serve.go
internal/auth/noop/jwtauth.go
internal/controlplane/server.go
internal/db/embedded/testdb.go
internal/events/eventer.go
internal/service/service.go

This adds the ability for `mindev` to spawn an all-in-one minder test server.
This server has noop authn/z and uses an embedded postgres database to operate.
This is meant for integration testing and is not for production, hence why it was
added in mindev.
Note that user provisioning needs to be done with:
```
grpcurl -plaintext -H "Authorization: Bearer foo" localhost:8090 minder.v1.UserService/CreateUser
```

Add test server `mindev` command

---

cmd/cli/app/provider/provider_enroll.go

While testing #2566, I noticed that we always reported successful enrollment, even when the enrollment timed out or failed.  Also, the code seemed overly complicated (4 goroutines and a WaitGroup).
Refactored to use 2 goroutines and a channel, and cleaned up error reporting.
Switched from both a timeout _and_ a call limit to only a timeout.
(Sorry, the bug fixes and refactoring sort of go hand-in-hand)
Manual testing alongside #2566

Clean up provider enroll, provide error message on failure

---

cmd/cli/app/provider/provider_enroll.go
internal/controlplane/handlers_oauth.go
internal/controlplane/handlers_oauth_test.go
pkg/api/protobuf/go/minder/v1/providers.go

This modifies the provider enrollment to actually verify that the provider supports the given auth flows before attempting them.
This is enforced both in the CLI and the server.
Closes: https://github.com/stacklok/minder/issues/2518

Actually check for auth flows in provider enrollment

---

buf.gen.yaml
pkg/api/openapi/minder/v1/minder.swagger.json

Every http method in swagger.json includes:
```
"default": {
"description": "An unexpected error response.",
"schema": {
"$ref": "#/definitions/googlerpcStatus"
}
```
this grpc response breaks autocomplete and TS understandings of the things.
Fixes: #2619

Suppress the default googlerpc.Status reply from swagger.json

---

internal/controlplane/handlers_ruletype.go
internal/ruletypes/service.go
internal/ruletypes/service_test.go

https://github.com/stacklok/minder/pull/2622 changed the project from coming from the context
to coming from the provider. This broke heirarchical rule type creation.
This PR fixes that.

Use project ID from entity context for ruletypes

---

cmd/dev/app/container/cmd_verify.go
cmd/dev/app/rule_type/rttst.go
internal/controlplane/handlers_oauth.go
internal/controlplane/handlers_repositories_test.go
internal/engine/actions/remediate/gh_branch_protect/gh_branch_protect_test.go
internal/engine/actions/remediate/pull_request/pull_request.go
internal/engine/actions/remediate/pull_request/pull_request_test.go
internal/engine/actions/remediate/remediate_test.go
internal/engine/actions/remediate/rest/rest_test.go
internal/engine/ingester/artifact/artifact_test.go
internal/engine/ingester/git/git_test.go
internal/engine/ingester/ingester_test.go
internal/engine/ingester/rest/rest_test.go
internal/providers/credentials/empty_credential.go
internal/providers/credentials/empty_credential_test.go
internal/providers/credentials/github_token_credential.go
internal/providers/credentials/github_token_credential_test.go
internal/providers/git/git.go
internal/providers/github/github.go
internal/providers/github/github_rest.go
internal/providers/github/github_test.go
internal/providers/github/mock/github.go
internal/providers/http/http.go
internal/providers/providers.go
internal/verifier/sigstore/container/container.go
pkg/providers/v1/credentials.go
pkg/providers/v1/providers.go

Remove the token from the Provider interface, since not all providers will have a token.
Introduce `Credential` interface that represents a credential used when interacting with a provider.
There is a `EmptyCredential` implementation that allows  performing Git operations, like `clone`, and making REST calls without using authentication.
The other implementation is the `GitHubTokenCredential` which is a token credential used when interacting with the GitHub provider.
Fixes #2519
This PR will have conflicts with https://github.com/stacklok/minder/pull/2566.

Introduce provider Credential interface

---

internal/providers/github/github_rest.go

When listing packages by repository, we were relying on the repository owner being the same user that generated the token being used.
Currently the token user and repo owner will always be the same, but to be safer we should use the explicit owner parameter that this function is called with.
note: I validated that we store always store the repo owner, both when the owner is a user and when the owner is an organization.

Explicitly specify owner when listing packages

---

deployment/helm/templates/ingress.yaml

Apparently I missed adding the `EvalResultsService` to our helm chart

Add EvalResultsService to ingress.yaml

---

internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_repositories.go
internal/controlplane/handlers_repositories_test.go
internal/controlplane/server.go
internal/repositories/github/mock/service.go
internal/repositories/github/service.go
internal/repositories/github/service_test.go

The implementation didn't pass a provider name + ID and this broke staging

Revert "Move repository create to RepositoryService (#2632)"

---

internal/controlplane/handlers_profile.go

Because we internally construct a go map when retrieving the list of
profiles and then iterate over it, the result of ListProfiles is not
ordered. But this is putting a strain on the UI that would have to order
the results or else every refresh might produce a different looking set
of results.
Fixes: #2658
Running minder profile list in a loop.

Sort the list of profiles before returning to clients

---

internal/util/helpers.go

This allows for using the `MINDER_AUTH_TOKEN` environment variable to
set the minder token used for authentication; thus bypassing reading the
credentials.json file and attempting to refresh.
This is mostly meant for usage in testing enviornments where keycloak might be disabled.

Allow using an environment variable to override the token from the CLI

---

database/migrations/000031_case_insensitive_names.down.sql
database/migrations/000031_case_insensitive_names.up.sql
database/query/artifacts.sql
database/query/profile_status.sql
database/query/profiles.sql
database/query/projects.sql
database/query/providers.sql
database/query/rule_types.sql
internal/db/artifacts.sql.go
internal/db/profile_status.sql.go
internal/db/profiles.sql.go
internal/db/projects.sql.go
internal/db/providers.sql.go
internal/db/rule_types.sql.go

Fixes #2682
Per discussion elsewhere today, it was noticed that most of our names are stored as TEXT with exact-match UNIQUE indexes.  It's potentially confusing to be able to have both `Important-rule` and `important-rule` in the same project, so we should switch the indexes to case-insensitive on the `name`.
`go test ./...` plus manual testing attempting to register a rule named `codeql_enabled` and `CodeQL_Enabled`.

Minder resource names should be case-insensitive

---

internal/controlplane/handlers_repositories_test.go
internal/engine/actions/remediate/pull_request/pull_request.go
internal/engine/actions/remediate/pull_request/pull_request_test.go
internal/providers/github/github_rest.go
internal/providers/github/mock/github.go
pkg/providers/v1/providers.go

A follow-up to an earlier commit, renames the confusing GetUsername
github interface method to GetName to convey better that it's just the
name. Since the name can be empty and we'd still like to use "something"
for the PRs as an identifier, we use the login as a fallback
just manually

Rename GetUsername to GetName, use GetLogin as fallback when opening a PR

---

internal/controlplane/handlers_projects.go
internal/projects/create.go
internal/projects/meta.go

This adds a `public` metadata key in the project's metadata. This will hold whatever is fine
to display for the project in an API/UI. The first two instances added there are the description
(previously unused) and the "display name".
The display name is always displayed and defaulted to the project's name. It is also defaulted
in all new projects.
It should show up as follows:
```
$ minder project list -o json
{
"projects": [
{
"projectId": "73460926-70c3-4d7d-bf34-1c224a1ec4d4",
"name": "jaormx",
"createdAt": "2024-03-18T16:18:19.521054Z",
"updatedAt": "2024-03-18T16:18:19.521054Z",
"displayName": "jaormx"
}
]
}
```
Adding the ability to update a project will come in a subsequent PR.
***Mark the type of change …

Add "public" metadata section in project's metadata and use it for display name

---

database/query/profiles.sql
database/query/rule_types.sql
internal/controlplane/handlers_profile.go
internal/controlplane/handlers_profile_test.go
internal/controlplane/handlers_ruletype.go
internal/db/profiles.sql.go
internal/db/rule_types.sql.go
internal/marketplace/namespaces/validation.go
internal/profiles/service.go
internal/ruletypes/service.go
internal/ruletypes/service_test.go
pkg/api/protobuf/go/minder/v1/validators.go

Relates to https://github.com/stacklok/minder/issues/2543
These methods ensure that it's not possible to create/update/delete
bundle/namespaced profiles or rule types through the API.
Dedicated methods are supplied for creating these entities with a
subscription ID. These methods will be called by the bundle
management code which will be implemented in a follow up PR.
Patch and delete methods which have not yet been migrated to the
respective service interfaces have been modified to prevent modification
of bundle rule types/profiles.
Rules
---
1. Rules and profiles belonging to bundles must have namespaced names.
2. A namespaced name consists of two DNS-like IDs separated by a slash
3. Rules and profiles which were created from a bundle have a foreign key reference back to the …

Prevent modification/deletion of rules belonging to a subscription

---

database/query/profile_status.sql
internal/controlplane/handlers_evalstatus.go
internal/db/profile_status.sql.go

- **Extend ListRuleEvaluationsByProfileId to include severity**
- **Add the ruletype severity when returning the list of evaluations**
Add the ruletype severity when returning the list of evaluations
Instead of empty severity, let's return the one from the ruletype
Fixes: #2709
```
curl  -H "Authorization: Bearer $MINDER_BEARER_TOKEN" 'http://localhost:8080/api/v1/results?context.project=8f701090-efb9-477e-983a-39a34cb73b42&context.provider=github' | jq
```

Add the ruletype severity when returning the list of evaluations

---

internal/engine/profile.go

The `GET` operation was left out from showing the display name for profiles. This fixes that.

Also show display name in `GetProfile` API

---

internal/controlplane/handlers_githubwebhooks_test.go
internal/controlplane/handlers_oauth_test.go
internal/controlplane/handlers_profile_test.go
internal/controlplane/server.go
internal/controlplane/server_test.go
internal/eea/eea.go
internal/engine/entities/entity_event.go
internal/engine/executor.go
internal/events/common/driver.go
internal/events/constants.go
internal/events/eventer.go
internal/events/eventer_test.go
internal/events/gochannel/gochannel.go
internal/events/interfaces.go
internal/events/metrics.go
internal/events/sql/postgres.go
internal/profiles/service.go
internal/reconcilers/reconcilers.go
internal/repositories/github/service.go

This makes use of the eventer interfaces in order to make the implementation
more portable. Individual components no longer hold an `Eventer` pointer, and
instead they just use the relevant interface contains the functions they need
to use.
Turns out that most of minder just uses publishers, and we set up the consumers
in a central place. This will be handy to simplify our tests.
The driver implementations of the eventer were also moved to their own packages.

Separate the eventer into interfaces

---

internal/controlplane/handlers_evalstatus.go

This change modifies the evaluation status response to return the repository UUID instead of the slug. It also populates the entity info map with the repository details.
/cc @jhrozek 

Eval Status: Return repository UUID, populate entity info

---

internal/controlplane/handlers_user_test.go
internal/controlplane/identity_events.go
internal/controlplane/identity_events_test.go

The transaction is not being executed for some reason, this
only executes the rollback if there's an error and logs a rollback
error too.

Only run transaction rollback for deleting user when there's an error

---

internal/controlplane/handlers_projects.go
internal/controlplane/handlers_projects_test.go

This detects the `ErrNoRows` error when getting project information
in the ListProjects call to detect if a project was deleted while the RPC
was being executed. Thus, no longer erroring out.
Fixes #2751
Added a unit test

Detect project deletion while `ListProjects` gathers projects

---

cmd/server/app/webhook.go
cmd/server/app/webhook_update.go
docs/docs/run_minder_server/run_the_server.md
internal/controlplane/handlers_repositories_test.go
internal/providers/github/common.go
internal/providers/github/mock/github.go
internal/repositories/github/webhooks/manager.go
pkg/providers/v1/providers.go

Adds a minder-server subcommand that allows you to change minder webhook secrets
in github as a way of rotating the secret
Fixes: #2722
```
minder-server webhook update -p github
```

Add a CLI for rotating webhook secrets

---

config/server-config.yaml.example
docs/docs/run_minder_server/run_the_server.md
internal/config/server/webhook.go
internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go

In order to provide for a clean webhook secret migration, we need to
provide a window of using the old secret. For this, we add an array of
PreivousWebhookSecrets to the WebhookConfig structure. If validating the
payload with the WebhookConfig.WebhookSecret fails, we fall back to
validating using the previous secrets.
Because validating the request reads the request body, we need to read
the body first and save in a byte slice in case we do have the fallbacks
configured.
Related: #2722
Tested by setting the correct shared secrets in the previousWebhookSecrets
array and junk in WebhookConfig.WebhookSecret as well as the usual case
of WebhookConfig.WebhookSecret containing the correct secret.

Provide an array of fallback secrets to allow secret migration

---

internal/controlplane/handlers_profile_test.go
internal/engine/profile.go
internal/profiles/validator.go
internal/profiles/validator_test.go

This adds proper validation so that rule type entity declarations match
what the profile declares. This avoids errors where the user may accidentally set
the wrong entity for a rule in a profile.
Fixes #https://github.com/stacklok/minder/issues/2757

Add validation for rule type entities

---

internal/controlplane/handlers_oauth.go
internal/controlplane/handlers_repositories.go
internal/controlplane/handlers_repositories_test.go
internal/providers/github/app/app.go
internal/providers/github/common.go
internal/providers/github/mock/github.go
internal/providers/github/oauth/oauth.go
pkg/providers/v1/providers.go

- **Drop is_org and owner parameters from repo listing methods of RepoLister and GitHub interfaces**
- **Move the owner attribute to the delegates**
- **Remove ListUserRepositories and ListOrganizationRepsitories in favour of ListAllRepositories**
Fixes #2756
Tested by calling `repo register` for both an enrolled org an a user account.

Remove isOrg from function calls to GitHub Provider

---

internal/controlplane/handlers_repositories.go
internal/providers/providers.go

This fixes a recently introduced bug, where we weren't showing the user a descriptive error message when they tried to register repos before enrolling a provider.
With this fix, the user now sees the message: `cannot get credential for provider: did you run `minder provider enroll`?` if they run `minder repo register` without having an enrolled provider.

Show user facing error when credential is invalid

---

cmd/cli/app/provider/provider_enroll.go
database/migrations/000037_session_state_foreign_key.down.sql
database/migrations/000037_session_state_foreign_key.up.sql
internal/controlplane/handlers_oauth.go
internal/controlplane/handlers_oauth_test.go
internal/controlplane/server.go
internal/controlplane/server_test.go
internal/providers/provider_definitions.go
internal/providers/service.go

This is a subset of https://github.com/stacklok/minder/pull/2750, which does not actually remove the built-in provider.
This creates a provider on successful enrolment, if the provider does not already exist.
It also allows makes enrolment less GitHub specific.
Ref #2520

Refactor enrolment to be more flexible with provider class

---

internal/controlplane/handlers_repositories.go
internal/controlplane/handlers_repositories_test.go
internal/providers/github/app/app.go
internal/providers/github/common.go
internal/providers/github/common/common.go
internal/providers/github/mock/github.go
internal/providers/github/oauth/oauth.go
pkg/providers/v1/providers.go

Instead of returning a github-specific struct, it now returns minder's
`Repository` protobuf, which is a more portable format for us.
The intention is that other repository providers will be able to leverage this
and hook more easily to minder.
Related-to: https://github.com/stacklok/minder/issues/2769

Make `repo-lister` interface more general

---

internal/engine/actions/actions.go

When working on the OCI registry, I noticed we were issues a funky error message
when the alerter cannot be instantiated. This fixes that.

Fix error message when instantiating alerter

---

database/query/providers.sql
internal/db/providers.sql.go

The query was outputting the providers in the wrong order. This fixes that.
Fixes https://github.com/stacklok/minder/issues/2790

Fix pagination in provider list

---

internal/controlplane/handlers_profile_test.go
internal/controlplane/server.go
internal/marketplaces/service.go
internal/marketplaces/subscriptions/mock/subscription.go
internal/marketplaces/subscriptions/service.go
internal/profiles/mock/service.go
internal/profiles/service.go
internal/profiles/validator.go
internal/profiles/validator_test.go
internal/ruletypes/mock/service.go
internal/ruletypes/service.go

Relates to #2541
1) Use `db.Querier` instead of `db.ExtendQuerier` - we do not need the
extra methods of ExtendQuerier
2) Modify Validator to accept a qtx. This is needed for the project
creation flow where the rules used by the profile get created in the
same transaction that the profile gets created in.

Tx changes for marketplace

---

cmd/cli/app/auth/auth_login.go
cmd/cli/app/auth/common.go
cmd/cli/app/auth/offline_get.go

For the hipster case of someone running the minder CLI on a toolbox, it is
often the case that the container cannot open a browser. Let's add a hidden flag
to allow for such hipster cases.

Allow for skipping opening the browser on login

---

database/migrations/000038_coalesce_nil_labels.down.sql
database/migrations/000038_coalesce_nil_labels.up.sql
database/query/profiles.sql
internal/db/profiles.sql.go

I was stupid and thought that setting the default on the column in
migration would ensure that we default to '{}' as well as the
grpc-generated getter returning an empty slice by default. Turns out
that one defaults to returning nil.
To fix that, we explicitly rewrite nil labels to an empty array.

Explicitly coalesce labels on create and update to {}

---

cmd/cli/app/root.go
cmd/dev/app/container/cmd_verify.go
cmd/dev/app/rule_type/rttst.go
cmd/server/app/webhook_update.go
internal/config/server/config.go
internal/config/server/github_app.go

This ensures that the github app private key can be read from the secret store.
Previously, if a configuration was a pointer type, then we would not bind its fields to environment variables.

Allow reading pointer config values from env

---

database/mock/store.go
database/query/profiles.sql
internal/controlplane/handlers_evalstatus.go
internal/controlplane/handlers_profile.go
internal/db/profiles.sql.go
internal/db/profiles_test.go
internal/db/querier.go
internal/db/store.go
internal/engine/executor.go
internal/engine/executor_test.go
internal/engine/profile.go

In order to support listing by labels, let's extend the
`ListProfilesByProjectID` SQL statement with two optional parameters -
`include_labels` and `exclude_labels`. These default to `[]` which is
also the first branch in the SQL statement which would list all profiles
with no labels.
Please refer to the unit tests for more use-cases.
Related: #2759
1. results API - list all the profiles regardless of labels
```shell
curl  -H "Authorization: Bearer $MINDER_BEARER_TOKEN" 'http://localhost:8080/api/v1/results?context.project=2e7e96d2-6cf0-4af0-8f02-c84df2c2dddf&context.provider==github&label_filter=%2A' | jq -r '.entities[].profiles[].profileStatus.profileName'
```
returns all the profiles
2. results API - list the profiles without labels …

Add label support for ListProfilesByProjectID

---

cmd/cli/app/auth/auth_login.go
cmd/cli/app/auth/common.go
cmd/cli/app/auth/offline_get.go
cmd/cli/app/provider/provider_enroll.go

Turns out the viper keys were conflicting and I was not fetching what I
thought I was. This resulted in `skip-browser` always being false.
By using a unique flag name, I'm now able to pass `--skip-browser` to either `offline get`
or `login`.
This also removes the `hidden` flag from this parameter, as it's handy enough to expose it.

Expose and actually fix skip browser

---

internal/controlplane/common.go

This is to clarify the expectations on this function.

Add comment on inferProvider call

---

internal/config/server/config.go
internal/config/server/config_test.go
internal/config/utils.go

Revert PRs that default the config value.
This is to continue to get the default port for the SQL connection for the events.

Revert default config

---

deployment/helm/README.md.gotmpl

Update helm README with instructions on github app secrets.

Add helm documentation about GitHub App secrets

---

cmd/dev/app/bundles/build.go
cmd/dev/app/bundles/bundle.go
cmd/dev/app/root.go
pkg/mindpak/build/packer.go
pkg/mindpak/build/packer_test.go

Relates to #2544
Provide a command for building a bundle from a specific directory.
Made a few small changes to mindpak as part of this PR, including writing the archive to a .tar.gz instead of a .tar
Example usage:
```
mindev bundle build stacklok/healthcheck@1.0.0 ~/data/healthcheck healthcheck-bundle.tar.gz
```

Add bundle build command to mindev

---

deployment/helm/README.md
deployment/helm/templates/deployment.yaml
deployment/helm/values.yaml

this allows us to run custom init containers in minder, which is handy
in conjunction with `extraVolumes` and `extraVolumeMounts`.

Add `initContainers` option to the deployment settings in Helm

---

internal/engine/actions/actions.go

This fixes another issue caught by the smoke tests - that if we update the action setting, i.e. alert or remediation afterwards in a profile this does not cause alerts or remediations to happen.
This was not easily happening so far with alerts because they were enabled by default.
Locally

Do not skip action processing decision if evaluation did not changed

---

internal/engine/actions/remediate/gh_branch_protect/gh_branch_protect.go
internal/engine/actions/remediate/rest/rest.go

Another fix caused by the change of how we decide which actions should run and which not. This affectsr ruletypes that don't remediate through pull requests.

Remediation types other than pull_request don't have a turn-off behaviour, so skip instead

---

cmd/server/app/serve.go
internal/config/server/identity.go
internal/controlplane/handlers_user.go
internal/controlplane/identity_events.go
internal/util/helpers.go

I was getting ready to add some additional user lookups, and I noticed that the current interactions with keycloak were repeated in at least two places.  I unified the existing setup behind interfaces in the configuration, though I expect at some point I'll come back to #2391 and extract things to a proper interface for IDP lookups.

Clean up calls to Keycloak behind config

---

internal/controlplane/common.go
internal/controlplane/handlers_profile.go
internal/controlplane/handlers_profile_test.go
internal/controlplane/handlers_repositories.go
internal/controlplane/handlers_repositories_test.go
internal/controlplane/server.go
internal/providers/store.go

This provides an interface for retrieving Providers out of the database, and encapsulates the logic for doing so. This makes it easier to stub out the provider retrieval logic for testing, and decouples the controlplane from the details of finding the right provider for a request.
There are other places in the codebase where this should be used, but that is an exercise for a future PR.
***Outline how the changes were tested, including steps to reproduce and any relevant configurations. …

Create ProviderStore interface, migrate controlplane to use it

---

database/mock/store.go
database/query/provider_github_app_installations.sql
database/query/providers.sql
internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/server.go
internal/db/provider_github_app_installations.sql.go
internal/db/providers.sql.go
internal/db/providers_test.go
internal/db/querier.go
internal/providers/installations.go
internal/providers/installations_test.go
internal/providers/mock/service.go
internal/providers/service.go
internal/service/service.go

Adds a new HTTP handler for handling the github app. The handler fires an event
to a newly added provider installation handler which in turns talks to the
provider service that handles the deletion.
There's some additional refactoring as well as questions about provider and installation
relationships that I'll point out inline in the PR.
Fixes: #2727
I tested two scenarios:
1) "claimed" installation that I created with `minder provider enroll --provider=github-app --owner=jakubtestorg`
and then deleted from the org page. This hits the codepath that deletes both the installation and the provider.
2) "unclaimed" installation that I created by navigating to `https://github.com/apps/jakub-s-local-minder-test/installations/new` where …

Handle GitHub App installation deleted event

---

database/migrations/000044_github_installation_cascade_delete.down.sql
database/migrations/000044_github_installation_cascade_delete.up.sql

In a recent PR I added a foreign key constraint, without adding `ON DELETE CASCADE`. This was preventing the user from being deleted if they had a GitHub App provider.

Fix auth delete when GitHub App installed

---

internal/config/server/github_app.go
internal/controlplane/handlers_githubwebhooks.go
internal/providers/mock/service.go
internal/providers/service.go
internal/providers/service_test.go

instead of reusing the same one we already use for repos
manually by setting the webhook secret in the config file and making sure that I can validate incoming messages with the right secret and can't with the wrong secret
```
provider:
github-app:
app_name: jakub-s-local-minder-test
app_id: 864067
user_id: 165174215
private_key: ".secrets/github-app.pem"
webhook_secret: "test5"
```

Use a separate webhook secret for the GH App

---

internal/profiles/validator.go

better than unknown error
```
$ cat ~/devel/playground/dependabot.yaml
---
version: v1
type: profile
name: dependabot-enabled-profile
remediate: on
alerts: on
context:
provider: github
repository:
- type: dependabot_configured
#name: dep_go
def:
package_ecosystem: gomod
schedule_interval: weekly
apply_if_file: go.mod
- type: dependabot_configured
#name: dep_py
def:
package_ecosystem: pypi
schedule_interval: weekly
apply_if_file: requirements.txt
$ ./bin/minder profile create -f ~/devel/playground/dependabot.yaml
Message: error creating profile from /Users/jakub/devel/playground/dependabot.yaml
Details: profile failed rule name validation: error in rule …
```

Nicer error message when creating profile with non-unique rule types missing names

---

internal/engine/actions/remediate/pull_request/pull_request.go
internal/engine/errors/errors.go

If there was no previous remediation status the Null DB type would
have had Valid:false and the actual value set to an empty string which
would trigger the default case of returning a generic error in
`RemediationStatusAsError`.
create a profile with remediate: on that uses a pull request remediation but
is already passing. It would end up in error.

Don't mark a PR remediation as error if no previous result exists

---

internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go
internal/controlplane/handlers_oauth.go
internal/controlplane/handlers_oauth_test.go
internal/controlplane/handlers_providers.go
internal/controlplane/handlers_repositories.go
internal/controlplane/handlers_repositories_test.go
internal/providers/store.go

Migrate more queries for providers to ProviderStore. This will make it easier to refactor away direct access to the provider table in subequent PRs.

Move more provider access methods to store

---

docs/docs/run_minder_server/run_the_server.md

The documentation outlines running `make migrateup` before running and OpenFGA instance. This results in the command failing as it tries to bind to a listening OpenFGA instance to create the model
This PR shuffles the order to prevent the failure

Fix order of instructions in running a server

---

database/query/repositories.sql
internal/db/repositories.sql.go
internal/db/repositories_test.go

Fix repository delete by name

---

database/migrations/000047_entity_profiles_views.down.sql
database/migrations/000047_entity_profiles_views.up.sql

This should avoid the issue we saw in staging where the view didn't inherit the default privileges for tables.  I did this as a drop/create on the "up" to remove the grants we put in place temporarily.

Set security_invoker=true to use permissions on the underlying tables when creating new view

---

docs/package.json
docs/yarn.lock

Seems like dependabot has trouble updating the docusaurus packages
one-by-one.
I ran this instead:
```
yarn add @docusaurus/core@3.2.1 @docusaurus/preset-classic@3.2.1
@docusaurus/theme-mermaid@3.2.1 @docusaurus/core@3.2.1
```
And checked that `yarn build` and `yarn serve` still works and I can
browse the documentation.
see above

Bump docusaurus packages to 3.2.1

---

.github/workflows/build.yml
.github/workflows/chart-publish.yml
.github/workflows/codeql.yml
.github/workflows/compose-migrate.yml
.github/workflows/deploy-doc.yml
.github/workflows/generation.yml
.github/workflows/image-build.yml
.github/workflows/license-check.yml
.github/workflows/lint.yml
.github/workflows/migrate-touch.yml
.github/workflows/pr-check.yml
.github/workflows/releaser.yml
.github/workflows/security.yml
.github/workflows/stalebot.yml
.github/workflows/test-deploy-doc.yml
.github/workflows/test.yml
.github/workflows/update-docs-cli.yml
.github/workflows/update-docs-dbschema.yml
.github/workflows/update-docs-helm.yml

This pr adds the complete version tags in our workflows and bumps two action version which were stuck pinned to commits in branches.
While fixing https://github.com/stacklok/minder/issues/2300 I noticed that the versions in the workflow tags in our workflows are not complete and this is preventing dependabot from updating them when bumping versions. This makes it hard to know  which revisions we're running.
Fixes #2300

Actions: Complete version tags in workflow comments 

---

internal/db/profiles_test.go

We recently suspected that one of our stored procedures is not behaving
as it should. This turned out to be false, but during debugging of the
stored procedure I already wrote a unit test for the behaviour that was
not working at the moment.
It makes sense to submit it in case we regress in the future.
run the test

Add a unit test for switch of a profile state to pending

---

cmd/dev/app/container/cmd_verify.go
cmd/dev/app/rule_type/rttst.go
cmd/dev/app/testserver/testserver.go
cmd/server/app/serve.go
cmd/server/app/webhook_update.go
deployment/helm/templates/deployment.yaml
internal/config/server/github_app.go
internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_providers.go
internal/controlplane/handlers_repositories.go
internal/controlplane/server.go
internal/engine/actions/remediate/gh_branch_protect/gh_branch_protect_test.go
internal/engine/actions/remediate/pull_request/pull_request_test.go
internal/engine/actions/remediate/remediate_test.go
internal/engine/actions/remediate/rest/rest_test.go
internal/engine/executor.go
internal/engine/executor_test.go
internal/engine/ingester/artifact/artifact_test.go
internal/engine/ingester/git/git_test.go
internal/engine/ingester/ingester_test.go
internal/engine/ingester/rest/rest_test.go
internal/providers/github/app/app.go
internal/providers/github/app/app_test.go
internal/providers/github/common.go
internal/providers/github/oauth/oauth.go
internal/providers/providers.go
internal/providers/service.go
internal/providers/service_test.go
internal/reconcilers/artifacts.go
internal/reconcilers/reconcilers.go

Add a fallback token that will be used when listing artifacts from a GitHub app provider, since the installation token cannot access that API.
This also adds rate limit handling to the `ListPackagesByRepository`.
The fallback token, generated from bot accounts, is already added to infra and AWS secrets manager for both staging and prod.
Fixes https://github.com/stacklok/epics/issues/280

Use fallback token for listing artifacts with GH App

---

cmd/cli/app/auth/auth_login.go
cmd/cli/app/auth/common.go
cmd/cli/app/auth/html/access_denied.html
cmd/cli/app/auth/html/generic_failure.html

When the user doesn't accept keycloak T&C, then KC redirects back to the
callback handler. Unfortunately the details are a bit sparse and the
only thing we get is the parameter `errorType` set to `access_denied`
This PR extends the Relaying Party with an error handler that aborts the
login process by sending the error parameter as an error-like type
upwards and displays an HTML rendered page in the login browser
Fixes: https://github.com/stacklok/epics/issues/297
1) enable ToC in your keycloak instance. In the left panel, select the right realm, then from the left menu select Authentication.
You'll see 'Terms and Conditions' in the list. Click both "Enabled" and "Set as default action".
2) `minder auth login`.
3) make sure you need to …

Handle when the user declines T&C in minder auth login

---

database/migrations/000049_repo_license_text.down.sql
database/migrations/000049_repo_license_text.up.sql

Noticed this while looking at the repositories schema. In Postgres, the internal representation of VARCHAR(n) and TEXT are identical. Text has the nice advantage of not being limited to a fixed size.

Use TEXT as type of license instead of VARCHAR(255)

---

cmd/cli/app/ruletype/ruletype_get.go

This implements the ability to pass a name when getting the rule type.
This is a lot easier than having to specifcy the rule type ID.

CLI: Get rule type by name

---

cmd/cli/app/ruletype/common.go

This prints the applicable entity as part of the table output
for rule types. A sample looks as follows:
```bash
$ minder ruletype get -n stacklok/trivy_action_enabled
+-------------------+---------------------------------------------------------------------------------------+
|     RULE TYPE     |                                        DETAILS                                        |
+-------------------+---------------------------------------------------------------------------------------+
| ID                | 2244c88f-0c07-4c52-be45-9191a77d085d                                                  |
+-------------------+---------------------------------------------------------------------------------------+
| Name              | stacklok/trivy_action_enabled …
```

CLI: Print applicable entity when getting rule type info

---

internal/controlplane/handlers_profile.go

I forgot to issue a profile update message on patching a profile. Since
the profile update message is currently nicely encapsulated in
`sendNewProfileEvent` which is a private method of the Profile service
and we already have PR #2990 that would move all of the Patch
functionality to that service and remove the current Patch handler
implementation, I decided to create a bespoke message for now.
This code will be removed once we merge PR #2990.
1) create a profile with remediate: off
2) patch the profile to have remediate: on
3) with this PR, the profile should re-evaluate

Issue a bespoke profile update message on patching a profile

---

internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go
internal/controlplane/handlers_profile.go
internal/controlplane/handlers_reconciliationtasks.go
internal/eea/eea.go
internal/eea/eea_test.go
internal/engine/entities/entity_event.go
internal/engine/executor.go
internal/engine/executor_test.go
internal/events/constants.go
internal/profiles/service.go
internal/reconcilers/entity_delete.go
internal/reconcilers/reconcilers.go
internal/reconcilers/repository.go
internal/repositories/github/service.go

* Attaches the webhook action event to the watermill message we publish
* Adds a new reconciler for processing entity `delete` events. Currently it has meaning only for artifact entities, but I've left it as a switch so if we decide to handle other events which mean a similar action for other entities we can easily extend it., i.e. closed for pull requests.
* Renamed and put all watermill event constants to be part of `./internal/events/constants.go`
* Added constants for webhook action events, i.e. "deleted", "opened", etc.
* Added handling for the use case when a webhook is deleted for a registered repo. 
Fixes https://github.com/stacklok/minder/issues/2927

Handle entity delete events, i.e. when a repo is deleted

---

internal/controlplane/handlers_artifacts.go
internal/controlplane/handlers_oauth.go
internal/controlplane/handlers_reconciliationtasks.go
internal/controlplane/handlers_repositories.go
internal/engine/executor_test.go
internal/logger/telemetry_store.go
internal/logger/telemetry_store_watermill.go
internal/reconcilers/entity_delete.go
internal/repositories/github/service.go

Relating to my PR for repositories, and Ozz's PRs for artifacts, add ProviderID to the telemetry struct. This is because there will be certain situations where we will not know the name, but know the ID instead.
I have changed some of the code to use ProviderID instead of Provider name where it made sense to do so. In some places, it is not possible yet, so I have left comments. In the controlplane, where the provider name is an input via the request context, I have used both - tracking the provider name input may still be useful for debugging.
***Mark the …

Use ProviderID in telemetry data

---

cmd/server/app/serve.go
internal/controlplane/handlers_projects.go
internal/controlplane/handlers_user.go
internal/controlplane/identity_events.go
internal/controlplane/identity_events_test.go
internal/controlplane/server.go
internal/projects/delete.go
internal/projects/delete_test.go
internal/providers/service.go
internal/service/service.go

This cleans up the providers when the user account is deleted.
It also instantiates the identity server event subscription in the `AllInOneService` so that it has access to the `ProviderService`.
Fixes #2958

Uninstall GitHub Apps when a user account is deleted

---

internal/engine/actions/remediate/gh_branch_protect/gh_branch_protect.go
internal/providers/github/common.go

Comparing the error message for a know string might seem hacky but
go-github does that internally too, so...
Fixes: #1992
create an empty repo and apply branch protection rules

Skip branch protection remediations for repos with no branches

---

internal/controlplane/handlers_githubwebhooks.go

The trigger for the reconciler was too greedy and would issue deletion events
on more entities than just repos. e.g. when a branch is deleted. This is not ideal.
Instead, this trims down the triggering of the event to just repo deletion events coming from GitHub.

Only run deletion reconciler on repo deleted events

---

cmd/cli/app/provider/provider.go
cmd/cli/app/provider/provider_enroll.go
internal/providers/github/oauth/oauth.go

Fixes #2898
Some additional changes have been made as well:
1) Make the flag to specify the class of provider specific to the enroll
command. The existing top-level provider flag is left intact, but
marked as deprecated.
2) The confirmation box is only shown for the legacy Github app workflow
as requested in the ticket.
3) The timeout duration is listed in the CLI output when the browser is
opened.
4) Small changes to message verbiage here and there.
***Outline how the changes were tested, including steps to …

Default to github-app in provider enroll

---

internal/controlplane/handlers_repositories.go
internal/providers/store.go

Our error message when trying to enroll a repository without a provider was less than ideal.
Before:
```
Message: Error getting list of remote repos
Details: NotFound means some requested entity (e.g., file or directory) was
not found.
```
After:
```
Message: Error getting list of remote repos
Details: no suitable provider found, please enroll a provider
```
minder repo register without a provider

A nicer error message when listing remote repos without an enrolled provider

---

.golangci.yml

I recently upgraded golangci-lint and started seeing:
```
WARN [config_reader] The configuration option `output.format` is
deprecated, please use `output.formats`
```
According to their example config:
https://github.com/golangci/golangci-lint/blob/master/.golangci.reference.yml#L75
We might even get away with not using any formats configuration as what
we're using is already the default, but let's fix the config name now to
get rid of the warning.
run `make lint`

Use output.formats.format in golangci.yaml

---

internal/engine/rule_type_engine.go

We were seeing a panic, and it's because we're reusing events in
zerolog [1]... this stops doing that for that function.
[1] https://github.com/rs/zerolog/issues/443

zerolog: Don't reuse event in `Eval` call

---

.mk/gen.mk
docs/docs/ref/cli/minder_completion_bash.md
docs/docs/ref/cli/minder_completion_zsh.md

Fixes #2626
Actual cause of this issue is that MDX A) needs some of the characters in the sample shell code to be escaped and B) even if you escape it, it wont render the line as markdown properly.
Do some unholy things with sed to work around this. Forgive me.

Fix CLI doc generation bug

---

internal/engine/eval/vulncheck/config.go

Configuring the OSV evaluator is a bit of a PITA, but at the same time,
the configuration is normally not really needed for public projects as
they would all use the same OSV instance and the same package databases.
Let's just hardcode sensible defaults so that profiles can be leaner and
UIs don't have to ask users to input all this data.
Create a very minimal profile:
```
version: v1
type: profile
name: acme-github-profile-pr-vuln-check
context:
provider: github
pull_request:
- type: pr_vulnerability_check
def: {}
```

Add sensible defaults to the OSV evaluator to allow running without any configuration

---

internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go
internal/controlplane/server.go

In order to list our GitHub App on the GitHub Marketplace, we need a webhook handler for Marketplace events.
This is a no-op handler because we don't need to react to marketplace events (e.g. purchases).
Fixes #3063

Add no-op handler for GitHub Marketplace events

---

internal/controlplane/handlers_githubwebhooks.go
internal/providers/providers.go

The following PR logs the token type:
* While creating the installation token
* During the ping received event. Since this is done only for the ping event, it is assumed that the sender is the app that installed the webhook on the repository. This way we can create a link between the repo ID and the webhook token type.

Log the token type while creating the installation token and during the ping received event

---

database/migrations/000051_artifact_projects_cascade_delete.down.sql
database/migrations/000051_artifact_projects_cascade_delete.up.sql

In case a project with an artifact was being deleted, the foreign key
would have prevented the deletion of the project.
As a user-facing effect, this meant that `auth login delete` no longer
worked if a user had any artifacts stored.
1. enroll a project, register a repo and make sure that an artifact is registered through a webhook or initial reconcile
2. minder auth delete

Fix deleting project with artifacts

---

internal/engine/eval/trusty/config.go

This is similar to 9187f9644e775cec9f6fe63a4919d8db15808440 just for
trusty. The point is again to not require any configuration to get the
Trusty evaluator up in the default configuration because configuring the
evaluator is currently quite painful from the UI.
```
version: v1
type: profile
name: pr-trusty-check
context:
provider: github
pull_request:
- type: pr_trusty_check
def: {}
```

Provide a default configuration for the Trusty evaluator

---

internal/engine/actions/remediate/pull_request/types_actions_replace_tags.go

This uses frizbee's builtin cache to store the found github actions
in-between file modifications.
We always had cache support but simply were not using it. This should
reduce the number of calls we do to GitHub.

Frizbee: Cache GitHub action entries

---

internal/engine/entities/entity_event.go
internal/engine/entities/entity_event_test.go
internal/engine/executor.go
internal/logger/telemetry_store_watermill.go
internal/reconcilers/entity_delete.go

Relates to #3071
This PR adds the ProviderID field to the event structure, and changes the executor to use the ProviderID if present. Note that the ProviderID is not actually set anywhere at this point: I am doing this changeover in phases to avoid backwards compatibility issues as we change the event structure.

Add ProviderID field to EntityInfoWrapper

---

internal/util/schemaupdate/schemaupdate.go
internal/util/schemaupdate/schemaupdate_test.go

We've been doing a bunch of changes to the defaults and descriptions to
make UI render better, but those are being flagged by minder ruletype
apply as incompatible because we require that the new ruletype is a
strict superset of the old one.
Let's ignore the description field as long as it's a scalar with a string
value and let's ignore the default field as long as it has a 'type'
sibling. These additional checks make sure that we don't accidentally
allow updating parameters that are named default or description.
Fixes: https://github.com/stacklok/minder/issues/3079
ruletype apply -f with ruletypes that change either only defaults or description (those should pass)
or change something else (those should fail)

Ignore description and defaults when validing ruletype updates

---

internal/authz/mock/simple_authz.go
internal/controlplane/handlers_user_test.go
internal/controlplane/identity_events.go
internal/controlplane/identity_events_test.go
internal/projects/delete.go

NOTE: This patch touches a bit delicate part of minder. Please review carefully - I was not super acquainted with the code earlier and I wouldn't be suprised if I missed something.
We've been occasionally hitting issues where `minder auth delete` would
delete the user entry but leave the project around. Recovering from this
state then requires database write permissions to manually clean up the
projects.
At least in the case that I reproduced by accident the flow went like
this:
- user issues auth delete
- the transaction starts
- the user projects are returned and contain a non-empty list
- the user entry is deleted from OpenFGA
- the user entry is staged for deletion from the DB as part of the
transaction
- one of the projects are attempted to be deleted, but the deletion
fails. This …

Do not delete user from OpenFGA in a DB transaction to avoid issues with minder auth delete

---

docs/docs/user_management/user_roles.md

Add docs for user roles

---

docs/docs/understand/remediations.md

Downstream overlays docs for ruletypes which means that when building
downstream docs the link to the secret_scanning ruletype was broken.
Let's just remove the link instead of creating yet another overlay.

Remove a link that is overlayed in downstream docs

---

docs/docs/how-to/add_users_to_project.md

just fixes a link, no other changes
build the docs, click the link

Use relative link to CLI docs, not localhost

---

cmd/cli/app/auth/auth_token.go
internal/util/helpers.go

This command allows you to retrieve a token from the identity provider
used by the given configuration. This is handy when trying to do work on
a direct API, for debugging, or for working with other tools in the
ecosystem (e.g. trusty).
It'll try to authenticate and print out a token to be used, or simply
read the token that's already in `credentials.json`.
An ideal flow would be `minder auth login` then `minder auth token`.

Add `minder auth token` command

---

cmd/dev/app/rule_type/rttst.go

I was debugging a ruletype change and found it handy to have the engine
debug logs dumped onto the console.
This patch adds a new parameter `--log-level` that defaults to `error`
and lets you set the log level for the evaluation of the engine.
```
AUTH_TOKEN=topsecret REGO_ENABLE_PRINT=true go run cmd/dev/main.go ruletype test --profile /Users/jakub/devel/playground/codeql-python.yaml --rule-type /Users/jakub/devel/minder-rules-and-profiles/rule-types/github/codeql_enabled.yaml --entity /Users/jakub/devel/playground/repository.yaml --log-level=debug
```

Allow setting log level for mindev ruletype test

---

internal/controlplane/handlers_oauth.go

I did not define this in my local configuration, and it led to some weird errors when enrolling a Github App provider - specificially, it creates a link with an empty app name which will lead to a 404 when the link is acceessed. This will at least return a 500 if the value is omitted, which makes the proble more explicit.

Return 500 if Github AppName is empty when enrolling provider

---

database/query/profiles.sql
internal/db/profiles.sql.go
internal/engine/profile.go

This patch has no functional changes, it is just a cleanup in our Go
database models that I didn't want to send before the recent release.
If sqlc generates a model for a query that joins over two tables, it
autogenerates column names that are represented as structure members, so
you end up with a single structure with members such as `ID` and `ID_2`.
This can be confusing and invite bugs. It's much cleaner to use
`sqlc.embed` to make sure that each table is represented by a separate
attribute in the models.
There is no tests for this functionality /right now in main/ but there are tests added in PR #2990, so maybe that one should go first.

Don't use SELECT * when joining profile tables

---

database/migrations/000053_provider_class_non_nullable.down.sql
database/migrations/000053_provider_class_non_nullable.up.sql
database/mock/store.go
internal/controlplane/handlers_oauth.go
internal/controlplane/handlers_providers.go
internal/controlplane/handlers_repositories.go
internal/db/models.go
internal/db/providers.sql.go
internal/db/providers_test.go
internal/db/querier.go
internal/eea/eea_test.go
internal/projects/create.go
internal/providers/classes.go
internal/providers/github/common.go
internal/providers/github/service/service.go
internal/providers/github/service/service_test.go

Undo migration #35 after discussion with Ozz and Jakub this morning. We want the provider class to store the concrete type of the provider, this will be used by the ProviderFactory.
After studying the code, there does not appear to be any situation in which this field will be null in the staging/prod DB.

Make provider class mandatory in DB

---

database/query/profiles.sql
internal/db/domain.go
internal/db/profiles.sql.go
internal/db/profiles_test.go

In the interest of time we merged labels filtering with some comments
not being addressed. This patch fixes that:
- exclude_labels now excludes any profiles containing any of the exclude
labels. Add a test for this new behaviour.
- fix confusing comment in LabelsFromFilter
- special-case wildcard matching to only return the wildcard
- sort the slice in test to avoid issues where the slices contain the
right elements, but in wrong order
`make test`

Address review comments for labels filtering

---

internal/artifacts/db.go
internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go
internal/controlplane/handlers_reconciliationtasks.go
internal/controlplane/handlers_repositories.go
internal/controlplane/handlers_repositories_test.go
internal/eea/eea.go
internal/eea/eea_test.go
internal/eea/entities.go
internal/engine/entities/entity_event.go
internal/engine/entities/entity_event_test.go
internal/engine/executor.go
internal/engine/executor_test.go
internal/logger/telemetry_store.go
internal/logger/telemetry_store_watermill_test.go
internal/reconcilers/repository.go
internal/reconcilers/run_profile.go
internal/repositories/db.go
internal/repositories/github/service.go
internal/util/helpers.go

Relates to #3071
This PR changes any code which creates an EntityInfoWrapper to use Provider ID instead of name. The name is still left as a field in the event for backwards compatibility purposes, and the consumer can still use the name to create the provider instance. However, the name is no longer populated.
Some other refactoring was carried out, specifically moving code from the helper package to more appropriate packages.
***Outline how the changes were tested, including steps to reproduce and any …

Use provider ID instead of name when sending events

---

internal/controlplane/handlers_profile.go
internal/controlplane/handlers_profile_test.go
internal/profiles/mock/service.go
internal/profiles/service.go

We used to use a bespoke PATCH handler to update profiles but the PATCH
method only allowed changing alert and remediate. We can make the code
simpler and allow more updates by modifying the existing profile using
the UpdateMask and then just relaying the update to the existing
UpdateProfile method of the Profile service.
Fixes: #2971
There are unit tests but you can also test with curl:
Adding a rule to a profile:
```
curl -XPATCH -H "Authorization: Bearer $MINDER_BEARER_TOKEN"
'http://localhost:8080/api/v1/profile/ce746798-c30c-46f3-8a12-0654747b49ec?context.project=1900c9f6-ef0f-43e4-8af7-108beb72de0e&context.provider=github'
-d '{"name":"dependabot-enabled-profile", "labels":[], "buildEnvironment":[], …
```

Allow full profile updates through the PATCH handler

---

internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go

Previously we would have returned a nil error but also a nil payload on
exhausting all previous secrets in a loop which would later error out when it
couldn't be parsed. That means that this bug has no security implications (we
would just get a 500 instead of a 400), but let's fix it nonetheless.
manually + a unit test

More descriptive error message when validating secrets with any of the fallback webhooks fails

---

deployment/helm/templates/deployment.yaml

Adds the ability to control configured Minder flags by creating a ConfigMap named `minder-flags` containing a key `flags-config.yaml` using [a GoFeatureFlag config file](https://gofeatureflag.org/docs/configure_flag/flag_format).
See https://gofeatureflag.org/editor for a UI editor for the same.
Fixes #3187
I used my brain, sorry!

Add Helm configuration for feature flags

---

docs/docs/developer_guide/feature_flags.md

Adds documentation on how to use feature flags during development.
Fixes #3187
No tests, sorry!

Add docs for using feature flags when developing Minder

---

deployment/helm/templates/deployment.yaml

Instead of relying on the config to set them.
Relates to: https://github.com/stacklok/infra/issues/954
I just verified that the env names are correct by running:
```
MINDER_WEBHOOK_CONFIG_WEBHOOK_SECRET_FILE=.secrets/webhook_secret MINDER_WEBHOOK_CONFIG_PREVIOUS_WEBHOOK_SECRET_FILE=.secrets/previous_secrets make run-server
```

Use webhook secrets from files

---

deployment/helm/templates/deployment.yaml

Here's what happened:
- I submitted PR #3177
- Ria submitted feedback inline, I accepted it. The suggestions were
merged into the remote branch.
- the patch had conflicts with main
- I resolved the conflicts locally and force-pushed to the remote branch. My
local branch didn't have Ria's suggestions and the force-push removed
them
This patch brings back Ria's suggestions so I included her as a
co-author.
Sorry!
Co-authored-by: Eleftheria Stein-Kousathana <eleftheria@stacklok.com>
Just visually.

Fix webhook secret file names

---

database/mock/store.go
database/query/repositories.sql
internal/controlplane/handlers_providers_test.go
internal/controlplane/handlers_repositories.go
internal/controlplane/handlers_repositories_test.go
internal/controlplane/server.go
internal/db/querier.go
internal/db/repositories.sql.go
internal/providers/github/manager/manager.go
internal/providers/manager/mock/fixtures/manager.go
internal/repositories/github/mock/service.go
internal/repositories/github/service.go
internal/repositories/github/service_test.go

Change the interface of the repo service so that it takes care of DB queries and provider instantiation. This moves various details about repo cleanup out of the controlplane.
As part of this, change the provider cleanup process to delete webhooks directly instead of deleting repos. This avoided a circular dependency, and more closely aligns with the idea that webhook management is a provider-specific detail.
Tested locally.
***Outline how the changes were tested, including steps to reproduce …

Refactor repo deletion to move db/provider logic behind interface

---

cmd/server/app/webhook_update.go

I was testing the webhook update locally and realized that it's too easy
to let the webhook update proceed with an empty secret. On the server
side we already have a similar check.
You'd pass the secret file with an env variable:
```
MINDER_WEBHOOK_CONFIG_WEBHOOK_SECRET_FILE=.secrets/webhook_secret ./bin/minder-server webhook update -p github
```
If you omit the secret file, you now get a failure, previously the tool would have proceeded with the update:
```
./bin/minder-server webhook update -p github
```

Warn about empty secret and skip the update in the webhook updater tool

---

internal/controlplane/server.go
internal/providers/github/app/app.go
internal/providers/github/app/app_test.go
internal/providers/github/clients/factory.go
internal/providers/github/manager/manager.go
internal/providers/github/oauth/oauth.go
internal/providers/github/oauth/oauth_test.go
internal/providers/providers.go

For a future PR, I want to be able to easily instantiate the GitHub client without going through the provider creation process. Specifically - when creating providers, we end up partially creating a provider, storing it in the database, and then use instantiate it to verify that the user IDs are correct. I want to change this so that we instantiate the client without the provider to make the call we need.
This splits the code for creating the github client out into its own factory. As a bonus - this removes some code which is duplicated between the oauth and app provider instantiation flows.
Validated locally against both app and oauth flows.
Explain the rationale and any background necessary for …

Implement GitHubClientFactory

---

internal/engine/ingester/artifact/artifact.go

This PR modifies the artifact ingester to return the attestation after verifying ingested sigstore bundles.
Fixes #https://github.com/stacklok/minder/issues/3210

Return verified attestation in verification results

---

internal/engine/ingester/artifact/artifact.go

This commit fixes a bug when trying to list images with   names in their reference. The github API expects the path segments after the org to be url escaped, for example:
`ghcr.io/org/name/with/slahes`
needs to be
`ghcr.io/org/name%2Fwith%2Fslahes`
TBD

Fix bug handling images with slashes in ref

---

internal/engine/ingester/artifact/artifact.go

This is a minor update that removes a useless condition from the code.

Bug: Remove impossible condition

---

internal/engine/ingester/artifact/artifact.go
internal/engine/ingester/artifact/artifact_test.go

This PR modifies the identity extraction function to preserve the full path of the attestation identity recorded in the attestation identity.
Trimming the path opens up a vulnerability as an attestation may be validated by a signature triggered from a workflow with the same filename as the expected one.
The identity extraction function is still timing the branch and tag from the identity which we should probably also not do but we handle it in the rule definition so probably we are ok. Further discussion is needed.
Added a unit test to test the treatment of the signer identity

Don't trim path from builder URI

---

internal/controlplane/handlers_oauth.go
internal/controlplane/handlers_projects.go
internal/controlplane/handlers_user.go
internal/controlplane/handlers_user_test.go
internal/controlplane/identity_events.go
internal/controlplane/identity_events_test.go
internal/controlplane/server.go
internal/projects/creator.go
internal/projects/creator_test.go
internal/projects/deleter.go
internal/projects/deleter_test.go
internal/service/service.go

This is part of a change which allows me to avoid some ugly hackery in my draft PR (#3221). Break Project creation/deletion out into a pair of dedicated structs/interfaces. Change the `ProjectFactory` function used in the GitHubProviderService from a method on the controlplane to a function which returns a function. This is needed for some additional cleanup introduced in a future PR.
Validated locally.
***Outline how the changes were tested, including steps to reproduce and any relevant …

Make Project Create/Delete a service

---

internal/engine/eval/trusty/actions.go
internal/engine/eval/trusty/config.go
internal/engine/eval/trusty/trusty.go
internal/engine/eval/trusty/trusty_rest_handler.go

This was a leftover from when trusty didn't have scores for some
packages at all, but it was not handled well. We tried to handle score 0
as missing.
Instead, let's use a `*float64` instead to distinguish between missing
score and score that is set but is zero.
See e.g. https://github.com/jakubtestorg/bad-python/pull/192 - there are two comments,
one from the buggy version where minder just skipped the dep with score 0 and
one where minder adds the comment.

Distinguish between score 0 and missing score in Trusty

---

internal/engine/actions/alert/alert.go
internal/engine/actions/alert/security_advisory/security_advisory.go
internal/engine/actions/remediate/gh_branch_protect/gh_branch_protect.go
internal/engine/actions/remediate/gh_branch_protect/gh_branch_protect_test.go
internal/engine/actions/remediate/pull_request/pull_request.go
internal/engine/actions/remediate/pull_request/pull_request_test.go
internal/engine/actions/remediate/remediate.go
internal/engine/actions/remediate/remediate_test.go
internal/engine/actions/remediate/rest/rest.go
internal/engine/actions/remediate/rest/rest_test.go
internal/engine/eval/eval.go
internal/engine/eval/homoglyphs/application/homoglyphs_service.go
internal/engine/eval/homoglyphs/application/invisible_characters_eval.go
internal/engine/eval/homoglyphs/application/mixed_scripts_eval.go
internal/engine/eval/trusty/trusty.go
internal/engine/eval/vulncheck/vulncheck.go
internal/engine/ingester/artifact/artifact.go
internal/engine/ingester/artifact/artifact_test.go
internal/engine/ingester/builtin/builtin.go
internal/engine/ingester/builtin/builtin_test.go
internal/engine/ingester/diff/diff.go
internal/engine/ingester/git/git.go
internal/engine/ingester/git/git_test.go
internal/engine/ingester/ingester.go
internal/engine/ingester/rest/rest.go
internal/engine/ingester/rest/rest_test.go
internal/providers/providers.go

When evaluating a policy, we instantiate a ProviderBuilder and then pass it around to various parts of the code. Once the specific trait is known, we get the specific trait we need from the ProviderBuilder.
While replacing the ProviderBuilder, I notice that there are many parts of the code where we continue to pass around the ProviderBuilder even though we know the specific provider trait which will be needed. I changed various code to explicitly require the provider trait it needs instead of taking the ProviderBuilder and getting an instance of the desired type. As a result of this change, test setup is simplified, and this will make my PR to replace the ProviderBuilder smaller.
Explain the …

Refactor engine code to use specific provider traits in more places

---

deployment/helm/templates/deployment.yaml
internal/flags/flags.go
internal/flags/flags_test.go

Fix crash when evaluating flags with `nil` GoFeatureFlag interface.  This is an interface of type `go-feature-flag.Provider`, with a `nil` value.  The interface itself is _not_ `nil`, because it has the type stored.
Fixes #3259
Added unit tests, verified they reproduced the panic, then fixed the panic.

Fix crash in 3259, add test

---

cmd/cli/app/repo/repo_register.go
go.mod
go.sum
internal/util/cli/multi_select.go

This also removes `survey` in favor of `bubbletea`.
Fixes #1134

Added utilities to implement multi-select choices

---

cmd/dev/app/rule_type/rttst.go
cmd/dev/app/testserver/testserver.go
cmd/server/app/serve.go
internal/engine/actions/actions.go
internal/engine/actions/alert/alert.go
internal/engine/actions/remediate/gh_branch_protect/gh_branch_protect_test.go
internal/engine/actions/remediate/pull_request/pull_request_test.go
internal/engine/actions/remediate/remediate.go
internal/engine/actions/remediate/remediate_test.go
internal/engine/actions/remediate/rest/rest_test.go
internal/engine/eval/eval.go
internal/engine/executor.go
internal/engine/executor_test.go
internal/engine/ingester/artifact/artifact_test.go
internal/engine/ingester/ingester.go
internal/engine/ingester/ingester_test.go
internal/engine/ingester/rest/rest_test.go
internal/engine/rule_type_engine.go
internal/service/service.go

Refactor engine to use ProviderManager. Various bits of refactoring along the way, including renaming some struct fields and variables for clarity.

Remove ProviderBuilder from engine

---

internal/flags/flags_test.go

Don flagged this issue the other day.  The simplest fix is to not run the sub-tests in parallel; I've also filed a comment on the upstream that it would be nice to be able to avoid the singleton, in the way that the `net/http` library has something like a "default ServeMux", but you can also create your own.
Fix in tests, the tests are the test.

Resolve test flake in flags_test

---

cmd/cli/app/profile/list.go

At the moment, there are some labels that minder uses internally, but we don't expose label managements to the end user. Therefore the `--label` flag in profile list is confusing. We should make the flag hidden. We should use cobra's hidden attribute to hide the flag.
Fixes #3300 
Run `make test`, there are failures but not entirely sure they are related to the change made in the PR, and may be due to a local setup issue. I could not see any test change needed to be made, it is my first PR so I welcome any correction to my understanding.
When building the CLI, the `label` flag does not appear anymore in the help information

hides CLI profile list label flag

---

internal/util/cli/multi_select.go

This behaviour is not configurable.
List of available repositories during the interactive execution of `minder repo register` is now sorted.
This change was suggested by @rdimitrov 
Ran the Minder CLI locally against Production and verified that the list of repositories presented to the user during interactive registration are sorted.

Multi select list is now ordered.

---

internal/verifier/sigstore/container/container.go

Without this, using another provider segfaults

verifier: Get local authenticator struct to return a usable authenticator

---

cmd/dev/app/rule_type/rttst.go

Note that dockerhub still doesn't fully work, but this sets up the pieces so we can start testing it.

Support dockerhub in `mindev ruletype test` sub-command

---

cmd/dev/app/image/cmd_verify.go
internal/engine/ingester/artifact/artifact.go
internal/engine/ingester/artifact/artifact_test.go
internal/verifier/sigstore/container/container.go
internal/verifier/sigstore/sigstore.go
internal/verifier/verifyif/mock/verifyif.go
internal/verifier/verifyif/verifyif.go

Since auth is related to the registry itself, this moves the registry
reference to the container authenticator struct instead.

verifier: Move registry to authenticator

---

cmd/dev/app/image/list_tags.go
go.mod
internal/engine/ingester/artifact/artifact.go
internal/engine/ingester/artifact/artifact_test.go
internal/engine/ingester/artifact/versioner.go
internal/engine/ingester/ingester.go
internal/providers/dockerhub/dockerhub.go
internal/providers/github/mock/github.go
internal/providers/oci/oci.go
internal/verifier/sigstore/container/container.go
internal/verifier/sigstore/sigstore.go
internal/verifier/verifyif/verifyif.go
pkg/providers/v1/providers.go

This modifies the ingester to change its behavior depending on whether
the provider is an OCI provider or a github one.
Closes: https://github.com/stacklok/minder/issues/3322

Make artifacts ingester work with both GitHub and OCI providers

---

internal/crypto/algorithms/aes256cfb.go
internal/crypto/algorithms/algorithm.go
internal/crypto/engine.go
internal/crypto/keystores/keystore.go
internal/crypto/models.go
internal/engine/executor_test.go

Relates to #3304
Implement an interface which hides the specifics of loading an encryption key. This allows us to use a secret store or a key store directly in future.
Right now, the implementation uses a single key loaded from the config. In my next PR, I will generalize it to support multiple keys. This will require a new config structure.

Initial KeyStore implementation

---

internal/engine/eval/trusty/actions.go
internal/engine/eval/trusty/actions_test.go
internal/engine/eval/trusty/config.go
internal/engine/eval/trusty/trusty.go
internal/engine/eval/trusty/trusty_rest_handler.go
internal/engine/eval/trusty/trusty_test.go

This PR surfaces the Trusty maliciousness data on the comment added by minder when analyzing dependencies. It also adds the required piping to add the data to the rest of the required low scored dependencies.
I've broken the Trusty evaluator to more scoped utility functions to make them more testable and added a few initial unit tests. It needs a little bit more mocking to write an integration test and the rest of the unit tests
I've simplified the comment template, we now have a single template instead of 3 and it is now pure markdown which is smaller. Here' is a screenshot of the output with malicious dependencies:
Demo PRs showing
- [A malicious dependency](https://github.com/puerco/demo-repo-python/pull/29)
- [A low score dependency](https://github.com/puerco/demo-repo-python/pull/27) …

Improve Trusty integration

---

pkg/api/protobuf/go/minder/v1/minder.pb.gw.go

Running `make gen` with the latest tooling results in this.

Regenerate minder protobuf gateway

---

database/migrations/000057_encrypted_redirect_jsonb.down.sql
database/migrations/000057_encrypted_redirect_jsonb.up.sql
internal/db/models.go
pkg/api/protobuf/go/minder/v1/minder.pb.gw.go

When creating the migration in a previous PR, I used TEXT instead of JSONB. This migration fixes this.
Since the column is not used, and I can't cast between TEXT and JSONB, I am recreating the column in a transaction.

Use JSONB for encrypted redirect URL

---

internal/engine/eval/trusty/actions.go
internal/engine/eval/trusty/trusty.go
internal/engine/eval/trusty/trusty_rest_handler.go
internal/engine/eval/trusty/trusty_test.go

This commit refactors the alternative dependency classification logic and makes it testable. I've added more tests to check the classification behavior and to verify the score matrix we pass to the PR template.

Trusty: Refactor alternative classification, add tests 

---

internal/controlplane/handlers_providers.go

This is a refactor that's split off PR #3348 and merging it will make my life easier while I'm maintaining the whole branch.
Relates: #3263

Reduce code duplication in provider handlers

---

internal/providers/github/common.go
internal/providers/github/mock/github.go
pkg/providers/v1/providers.go

This commit adds support for the checks API in the github provider.

Github provider: Add support for checks API

---

internal/engine/eval/homoglyphs/application/homoglyphs_service.go

The homoglyphs' prReviewHandler is causing too much noise when leaving a "green check" review after every commit.
Commits in their respective order show that no reviews were posted if no issues are found and vice-versa (posted if issues are found) (the feature was tested on a local server):
https://github.com/teodor-yanev/a-testrepo/pull/1/commits/df0fad3d546bb6b8bded53272024 …

Do not post a pr review if no homoglyphs are found

---

internal/crypto/algorithms/aes256cfb.go
internal/crypto/algorithms/aes256gcm.go
internal/crypto/algorithms/aes256gcm_test.go
internal/crypto/algorithms/algorithm.go
internal/crypto/engine.go
internal/crypto/engine_test.go

Fixes #3317
The GCM mode is recommended by OWASP and other authorities for secret encryption. As per @jhrozek's suggestion, use the cryptopasta implementation of AES-256-GCM (see link/copyright in code).
This PR does not actually make use of the new algorithm yet, this will be done in a future PR.

Implement AES-256-GCM encryption

---

internal/providers/dockerhub/manager.go
internal/providers/github/manager/manager.go
internal/providers/manager/manager.go
internal/providers/manager/manager_test.go
internal/providers/manager/mock/manager.go
internal/providers/mock/store.go
internal/providers/store.go

For both the provider auto-enrollment feature and for the OCI providers, we need
to create providers in the database. This PR implements the required provider store
and provider manager changes and will be followed by a patch to expose the functionality
through an RPC call.
Related: #3376
unit tests and as part of a larger patchset

Add provider store and provider manager code to create new providers

---

internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go
internal/controlplane/server_test.go
internal/providers/github/mock/fixtures/github.go
internal/providers/manager/mock/fixtures/manager.go

This PR is only about adding test coverage to GitHub webhook handler.
Fixes #3358

Enhanced GitHub webhook handler tests.

---

internal/engine/actions/actions.go
internal/engine/actions/alert/alert.go
internal/engine/rule_type_engine.go

The idea is to make artifact rules more re-usable. This detects if the
provider implements `GitHub` and if it doesn't it merely returns a no-op
alert engine. This is handy to be able to test `artifact_signature` rule
types with DockerHub or any othe provider that's not GitHub.

Skip alerts if provider does not support it

---

internal/providers/manager/manager_test.go

To test:
```
go test ./internal/providers/manager -race -run TestProviderManager_CreateFromConfig
```
Fixes #3397
see above

Fix data race in TestProviderManager_CreateFromConfig

---

internal/engine/eval/trusty/actions.go
internal/engine/eval/trusty/config.go
internal/engine/eval/trusty/trusty.go

Minder now has the capability to request changes in PRs when it finds something odd based on Trusty dependency data.
This PR  also introduces a new setting in the trusty ruletype configuration to disable blocking when malicious deps are detected (all power to the users, but why would you want that?!).
Fixes https://github.com/stacklok/minder/issues/3380
Part of https://github.com/stacklok/minder/issues/3379

Trusty: Support blocking PRs through reviews

---

cmd/server/app/root.go
go.mod
go.sum
internal/auth/oauth.go
internal/config/server/config.go
internal/config/server/github.go
internal/config/server/github_app.go
internal/config/server/identity.go
internal/config/server/oauth_client.go
internal/config/server/webhook.go
internal/controlplane/handlers_oauth.go
internal/controlplane/handlers_oauth_test.go
internal/controlplane/server.go

In the next PR (#3334) we need to move the OAuth config under providers
themselves, but in order to do that, we need to get rid of the oauth client
config code calling `viper.Get` directly or else we'll break all our tests.
This PR does that and gets rid of the Google OAuth configuration and other
now-unused code.
Because the next PR will move the OAuth client code around to providers, I
didn't get overboard with testing here.
Fixes #2798
make test and provider enroll

Move provider OAuth config under server.Config

---

.golangci.yml
docker/minder/Dockerfile
docker/reminder/Dockerfile
go.mod
tools/go.mod

- Bump go (toolchain) to v1.22.3
- Remove specific go version from the run configuration in .golangci.yml as the Default is to "use Go version from the go.mod file" (https://golangci-lint.run/usage/configuration/#run-configuration)
- Bump go base images to v1.22.3

Bump go to v1.22.3

---

pkg/mindpak/build/packer.go

fix mindpak's build.InitBundle() func to printf to separate lines, otherwise it confuses gotestfmt thinking tests that are using the func are failed
base on the [make test[-silent]](https://github.com/stacklok/minder/blob/586144c00ddd9f86d829f52721cdee0540fca38b/.mk/test.mk#L26-L32):
```
$ go test -json -race -v ./pkg/mindpak/build/ | gotestfmt
📦 github.com/stacklok/minder/pkg/mindpak/build
❌ TestPackerInitBundle (0s)
✅ TestPackerInitBundle/TestPackerInitBundle (0s)
wrote to /tmp/TestPackerInitBundleTestPackerInitBundle1680469268/001/manifest.json=== CONT  TestValidateInitOpts/invalid_name
✅ TestPackerInitBundle/TestPackerInitBundle#01 (0s)
✅ TestPackerInitBundle/TestPackerInitBundle#02 (0s)
wrote to /tmp/TestPackerInitBundleTestPackerInitBundle#012127442667/001/manifest.json--- PASS: …
```

Fix packer tests

---

.mk/test.mk
Makefile
examples/Makefile
examples/README.md

- sole make should only call help
- fix command concatenation and remove unnecessary end-of-line in
main Makefile
- add make clean to init-examples and aggregate it with main Makefile
- enable init-examples to be run from main Makefile and its own
Makefile

Fix Makefiles

---

internal/providers/github/common.go

We were accidentally skipping error returning since we had missed a
`return` statement in that function.

Actually return an error on branch protection get

---

internal/engine/actions/remediate/gh_branch_protect/gh_branch_protect.go

Branch protection remediation now checks if branch name is empty and gets the default branch if available.
If both are unavailable, remediation is skipped.
Co-authored-by: Juan Antonio Osorio <ozz@stacklok.com>
Fixes #3430 
Manually tested.

Branch protection remediation now uses default branch if none provided.

---

internal/engine/eval/trusty/actions.go
internal/engine/eval/trusty/actions_test.go
internal/engine/eval/trusty/config.go
internal/engine/eval/trusty/trusty.go
internal/engine/eval/trusty/trusty_rest_handler.go
internal/engine/eval/trusty/trusty_test.go

This PR adds support for blocking pull requests introducing pull requests.
It also adds support to show provenance data (historical and sigstore) when trusty supplies it for the new dependencies. 
Fixes #3379
Fixes #3382
Added a new test for the function that computes the provenance data 
Heres the new improved section showing the deprecated flag and the provenance data:

Trusty: Block on deprecated, expose provenance

---

docs/docs/ref/rules/pr_trusty_check.md

This PR updates the documentation of the trusty rule to match the last changes to the evaluator.
N/A

Updtae Trusty PR evaluator/ruletype documentation

---

internal/engine/eval/rego/fuzz_test.go

Adds a fuzz test for the rego evaluator.

Add fuzz test for rego evaluator

---

cmd/server/app/common.go
cmd/server/app/encryption.go
cmd/server/app/encryption_purge_sessions.go
cmd/server/app/encryption_rotate.go
cmd/server/app/migrate_down.go
cmd/server/app/migrate_up.go
cmd/server/app/webhook_update.go
database/mock/store.go
database/query/provider_access_tokens.sql
database/query/session_store.sql
internal/db/provider_access_tokens.sql.go
internal/db/querier.go
internal/db/session_store.sql.go

Fixes #3315
Implement CLI command which is used to migrate keys and algorithms. This will:
1) Open connection to the DB
2) Query for secrets which do not have the default key ID or algorithm 3) Decrypts and re-encrypts with new data
4) Wraps all the above in a transaction which asks permission before
commiting
State secrets in the session state table are deleted. Since they are short-lived secrets, there is no point in migrating them.
Tested locally.
***Outline how the changes were tested, including steps to …

Implement process for migrating keys and algorithms

---

internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go

Events of type "repository" having "action" delete must trigger the deletion of registered repositories. Given we use the same deserialization struct for both "repository" and "meta" events, we erroneously checked the received hook id against the one stored in the database, thus consistently failing.
Added fix, test case, and improved logs.
Fixes #3461 
* reproduced issue locally
* added test case

Events of type "repository" now avoid checking hook id.

---

cmd/server/app/common.go
cmd/server/app/encryption_rotate.go

This is helpful for debugging DB configuration issues in k8s.

Add extra debug logging for DB connection in minder-server

---

internal/crypto/engine.go
internal/crypto/engine_test.go
internal/crypto/keystores/keystore.go
internal/crypto/keystores/keystore_test.go

This addresses a bug preventing the decryption of old secrets when the default key has been rotated.

Use fallback key ID when key version is empty

---

internal/controlplane/handlers_githubwebhooks.go
internal/eea/eea.go

This change makes uniform use of details stored in ctx when writing logs in the webhook handler. Additionally, it also moves watermill message UUID logging key from "event" to "message_uuid" to use the same one as watermill.
* `make lint`
* local execution

Webhook handler always logs contextual information.

---

database/migrations/000060_rule_instances.down.sql
database/migrations/000060_rule_instances.up.sql
database/query/profiles.sql
internal/db/models.go
internal/db/profiles.sql.go

Rule instances are currently stored as serialized protobuf structures in the database, grouped by entity type. A separate join table exists to track the relationship between a profile-entity and the rule types which are used. This arrangement leads to some rather awkward code and database queries making the profile-related code in Minder more complex than it should be.
This PR adds in a definition of a dedicated rule instance table. Subsequent PRs will migrate data over to it and then change the codebase to query this table instead of the current tables. …

Define rule instance table for Minder

---

internal/engine/executor.go
internal/engine/executor_test.go

This makes it so that profiles now take into account the project
hierarchy when evaluating for an entity. That is, profiles that apply to
the entity via the hierarchy (same project and parents) are evaluated
when the executor gets an event.
This iterates in steps, so the profile may only use rule types that
exist in its same project. A Further iteration will also take the
hierarchy into account when searching for rule types.
Note that hierarchy operations are still under a feature flag, so this
is not generally available.
Closes: https://github.com/stacklok/minder/issues/3498

Consider project hierarchy in profile evaluation

---

internal/controlplane/handlers_providers_test.go
internal/providers/dockerhub/dockerhub.go
internal/providers/dockerhub/manager.go
internal/providers/github/manager/manager.go
internal/providers/manager/manager.go
internal/providers/manager/manager_test.go
internal/providers/manager/mock/manager.go

Not validating provider config before provider creation can have bad
consequences such as not being able to delete such provider because a
provider must be instantiated before it's deleted.
Related: #3510
manual + make test

Validate config before provider creation

---

cmd/cli/app/profile/common.go
cmd/cli/app/quickstart/quickstart.go
cmd/dev/app/rule_type/rttst.go
internal/controlplane/handlers_profile.go
internal/controlplane/handlers_ruletype.go
internal/engine/executor.go
internal/engine/rule_type_engine.go
internal/profiles/rule_names.go
internal/profiles/rule_validator.go
internal/profiles/rule_validator_test.go
internal/profiles/service.go
internal/profiles/util.go
internal/profiles/util_test.go
internal/profiles/validator.go
internal/reconcilers/run_profile.go
internal/ruletypes/service.go
internal/ruletypes/util.go
pkg/mindpak/reader/reader.go

A bunch of profile and rule type logic lives in the `engine` package. This PR moves those functions into the profiles and ruletypes packages.
This avoids circular dependencies in a future PR, and also groups logic for specific domain concepts in their own packages.

Move profile and ruletype logic out of engine package

---

cmd/cli/app/auth/auth_login.go
cmd/cli/app/auth/auth_token.go
cmd/cli/app/auth/common.go
cmd/cli/app/auth/offline_token/offline.go
cmd/cli/app/auth/offline_token/offline_get.go
cmd/cli/app/auth/offline_token/offline_revoke.go
cmd/cli/app/auth/offline_token/offline_use.go
cmd/cli/main.go

Moves the auth offline-token sub-command to a separate package.

Move auth offline-token to a separate package

---

database/mock/fixtures/store.go
internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go
internal/controlplane/handlers_reconciliationtasks.go
internal/controlplane/handlers_repositories_test.go
internal/engine/entities/entity_event.go
internal/engine/entities/entity_event_test.go
internal/events/constants.go
internal/reconcilers/entity_add.go
internal/reconcilers/entity_add_test.go
internal/reconcilers/entity_delete.go
internal/reconcilers/entity_delete_test.go
internal/reconcilers/messages/messages.go
internal/reconcilers/reconcilers.go
internal/reconcilers/repository.go
internal/repositories/github/mock/fixtures/service.go
internal/repositories/github/service.go
internal/service/service.go

Such events are triggered when a new repository is added to or removed
from the list of repositories accessible to the app.
Fixes #3267 

Webhook handler now processes installation_repositories events

---

internal/controlplane/handlers_oauth.go
internal/controlplane/handlers_oauth_test.go
internal/controlplane/handlers_providers.go
internal/controlplane/handlers_providers_test.go
internal/providers/github/service/service.go
internal/providers/github/service/service_test.go
internal/providers/manager/manager.go
internal/providers/manager/manager_test.go
internal/providers/providers.go

Adds a special error code as well as means to catch it in the provider
handlers on provider creation so that we disallow creating providers with bad
config.
Fixes #3510
unit tests + manual

Validate provider config when creating the OAuth provider or the GitHub App provider.

---

internal/controlplane/handlers_user.go

This PR populates the missing descriptions and display names of projects included in the user API.
Fixes #3178

User API: Add missing project display name and description

---

internal/crypto/fileName
internal/crypto/fuzz_test.go

The previous implementation would create a test file but never clean it up, which causes problems when running the tests locally.

Change fuzzing test to avoid leaving files around

---

internal/providers/github/service/mock/service.go
internal/providers/github/service/service.go
internal/providers/github/service/service_test.go

We now use the provided-agnostic code to create a github provider,
introduced in e578bf8b281c3c0e3ae842ec67341c030f26ced9, so let's remove
the unused code.
Related: #3263
make

Remove the now-unused CreateGitHubOAuthProvider

---

internal/controlplane/handlers_providers_test.go
internal/providers/dockerhub/dockerhub.go
internal/providers/dockerhub/manager.go
internal/providers/github/clients/app.go
internal/providers/github/clients/oauth.go
internal/providers/github/manager/manager.go
internal/providers/github/service/service.go
internal/providers/manager/manager.go
internal/providers/manager/manager_test.go
internal/providers/manager/mock/auth_manager.go
internal/providers/manager/mock/manager.go

Right now, we parse the user-provided provider configuration, but if it passes validation, we save the user-provided config verbatim. This means that if there are any extra keys, we save them as well because Go ignores extra attributes when unmarshalling JSON.
We need to fix this or else we risk our users flood our database with large configs.
Credit to @blkt for bringing this up.
Fixes #3543
manual + make test

Marshall provider config back to JSON from parsed structures to strip extra keys

---

database/migrations/000062_migrate_entity_profiles.down.sql
database/migrations/000062_migrate_entity_profiles.up.sql

Depends on #3486
This PR adds a migration script to move all rule instances created before PR #3486 to the rule_instances table.
Tested locally.

Migrate existing rule instances into rule_instances table

---

cmd/cli/app/auth/invite/invite.go
cmd/cli/app/auth/invite/invite_accept.go
cmd/cli/app/auth/invite/invite_decline.go
cmd/cli/app/auth/invite/invite_list.go
cmd/cli/main.go

The following PR adds new commands for `auth invite` - `list`, `accept <code>` and `decline <code>`
The command is set to hidden until the backend side is fully implemented.
Fixes: https://github.com/stacklok/minder/issues/3550

Minder CLI - New commands for auth invite - list, accept <code> and decline <code>

---

database/mock/store.go
database/query/profiles.sql
internal/db/profiles.sql.go
internal/db/querier.go
internal/projects/deleter.go
internal/projects/deleter_test.go

This avoids an issue which Ozz ran into where the `ON CASCADE DELETE` relationships would attempt to delete rows from rule_type before deleting from rule_instances. This would fail because there is a foreign key relation from rule_instances to rule_type which prevents deletion of in-use rule types.
The old entity_profile_rules table had a foreign key reference to rule_type marked as `ON DELETE CASCADE`, and relied on logic in the code to prevent the deletion of rule instances which are in use.
***Outline how …

Delete profiles before deleting project

---

database/migrations/000064_evaluation_history.down.sql
database/migrations/000064_evaluation_history.up.sql
internal/db/models.go

Fixes #3555
Implements the new database schema for storing evaluation history. Compared with the existing tables for profile/rule status, this will track every single evaluation, and not just the most recent state. This will be used to build an API for querying the history of evaluations for a given rule/entity pair.
Queries and logic to fill the tables will be implemented in the next PR.
Attach screenshots …

Define evaluation history schemas

---

cmd/reminder/app/start.go
config/reminder-config.yaml.example
database/migrations/000065_repo_reminder.down.sql
database/migrations/000065_repo_reminder.up.sql
database/migrations/000066_rule_evaluations_repo_index.down.sql
database/migrations/000066_rule_evaluations_repo_index.up.sql
database/mock/store.go
database/query/profile_status.sql
database/query/repositories.sql
internal/config/reminder/config.go
internal/config/reminder/config_test.go
internal/config/reminder/recurrence.go
internal/db/models.go
internal/db/profile_status.sql.go
internal/db/querier.go
internal/db/repositories.sql.go
internal/reminder/reminder.go
internal/reminder/reminder_test.go

Part - 2 #2262 
**Algorithm:**
1. Generate a random v4 `uuid` as starting point.
2. Iterate and pick repos until the end of the table is reached.
3. After end of table is reached, start iterating from the first row in the table.
Only the starting point is random; batch creation becomes sequential after one end of the table is reached. If after reaching the end of the table, the iteration point is selected randomly again, the coverage of all repos won't be guaranteed. 
***Outline how the changes were tested, including steps to …

Add batch creation logic for the reminder service

---

internal/config/server/provider.go
internal/engine/ingester/git/git_test.go
internal/providers/git/git.go
internal/providers/git/memboxfs/fs.go

It turns out that (in Minder, but not in the test), `Git.Clone` doesn't like sharing the filesystem between the workspace files and the git storer.
Manual testing to isolate the issue.  This can probably be fixed better, but we'd like to get the basic protection into main.
This will be validated by smoke tests, which caught the issue.

Fix Git.Clone after 35bab8f

---

internal/engine/actions/actions.go
internal/engine/errors/errors.go
internal/engine/rule_type_engine.go

Currently, if there's a panic caused by the evaluation of a policy or
execution of an action, Minder panics and restarts. This is not ideal.
We instead explicitly recover from panics and surface the error up to
the user.
A user will only see that there was an internal error in Minder, but a
relevant log entry will be written.

Recover from panics in policy engine

---

internal/engine/ingester/diff/parse.go
internal/engine/ingester/diff/parse_test.go

Or else malformed patches might cause us trouble.
added a test

Do not dereference go dependency fields without checking the length of fields first

---

.mk/develop.mk

This fixes the bootsrap target to run go generate in the  submodule directory
Fixes the error we're seeing in https://github.com/stacklok/minder/pull/3574
```
[puerco@babieco minder] 🦆❯ make bootstrap 
cd tools && go generate -tags tools ./tools.go
cd tools && go mod tidy && go install \
github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway \
github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2 \
google.golang.org/protobuf/cmd/protoc-gen-go google.golang.org/grpc/cmd/protoc-gen-go-grpc \
github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc \
github.com/sqlc-dev/sqlc \
github.com/norwoodj/helm-docs/cmd/helm-docs \
github.com/openfga/cli/cmd/fga \
go.uber.org/mock/mockgen \
github.com/mikefarah/yq/v4
cp -n config/config.yaml.example ./config.yaml || echo …
```

Fix tools/ bootstrap make target

---

.goreleaser.yaml

Fixes the annoying go mod tidy issue for goreleaser.

Fix the go mod tidy issue for goreleaser

---

.goreleaser.yaml

This commit runs `go generate` for tools in a subshell as pushd and popd are not available in the goreleaser action
/cc @rdimitrov 

Exec go generate in subshell

---

database/query/rule_types.sql
internal/controlplane/handlers_ruletype.go
internal/db/rule_types.sql.go
internal/engine/executor.go
internal/engine/executor_test.go
internal/profiles/service.go
internal/profiles/validator.go
internal/profiles/validator_test.go
internal/ruletypes/service.go
internal/ruletypes/service_test.go

Rule types are usable by projects down the hierarchy, this allows
someone in a child project to create a profile that uses rule types
approved in a parent project. This is very handy since folks with
permission to write profiles don't need to have permissions to write
rule types, they can simply use some already approved and created.
This also adds the constraint that rule type names are unique down the
hierarchy. That is, a user cannot create a rule type name that overrides
a rule type that exists in a parent project.
Fixes https://github.com/stacklok/minder/issues/3500

Take into account hierarchy when dealing with rule types

---

internal/engine/eval/trusty/trusty.go
internal/engine/eval/trusty/trusty_test.go

Handle possible `nil` values in the `activity` and `provenance` scores returned by the Trusty API.
The Trusty team made a change today that allowed nil values in the response, while previously they would alway return a float.

Handle nil values from Trusty API

---

database/migrations/000069_evaluation_history_modifications.down.sql
database/migrations/000069_evaluation_history_modifications.up.sql
internal/db/models.go

These relate to feedback from the design review, plus making some changes in light of writing code which uses these tables:
1) Use `ON DELETE CASCADE` for all foreign key references.
2) Use an array of timestamps to store the evaluation instances instead
of keeping them in a separate table.
3) Change some of the table names. The original names were not
particularly consistent or intuitive.
Since Minder does not use any of these tables at this point, there should be no impact from these changes.
***Outline how …

Various changes to the eval history schema service

---

cmd/cli/app/root.go
cmd/reminder/app/root.go
cmd/server/app/root.go
internal/config/utils.go
internal/config/utils_test.go
internal/util/helpers.go

This allows us to have a predictable configuration file when reading the
client minder configuration. The idea is that we could set up
`$XDG_CONFIG_PATH/minder/config.yaml` and that would serve as an entrypoint.
In the future, we could modify this if we want to dynamically change
the current working project.

Fall back to `$XDG_CONFIG_PATH/minder/config.yaml` when reading configuration

---

cmd/cli/app/root.go
cmd/cli/app/set_project/set_project.go
cmd/cli/main.go
internal/config/client/config.go
internal/config/client/identity.go
internal/config/common.go
internal/util/cli/cli.go

This allows us to easily switch between projects using the ID. Note that
there a further PR will allow us to switch between projects using the
name of an immediate child.
For usability, this adds the `minder sp` and `minder cd` aliases (note that `set-project` is what shows up in the help text).

Implement `set-project` subcommand

---

internal/controlplane/handlers_user.go

The following PR implements ListInvitations and ResolveInvitation APIs for UserService.

Implement ListInvitations and ResolveInvitation APIs for UserService

---

internal/controlplane/handlers_invites.go

The following PR implements the GetInviteDetails API for getting additional metadata info for invite codes. This is intended to be a public API accessed by unauthenticated users.

Implement GetInviteDetails

---

cmd/cli/app/auth/invite/invite_accept.go
cmd/cli/app/auth/invite/invite_decline.go
cmd/cli/app/auth/invite/invite_get.go

The following PR updates the `minder auth invite` CLI commands used for accepting, declining, listing and getting invitation info.
Will be made visible in a follow up once we merge all relevant PRs.

Update the auth invite CLI commands

---

cmd/cli/app/project/role/role_deny.go
cmd/cli/app/project/role/role_grant.go
cmd/cli/app/project/role/role_update.go

The following PR updates the project role CLI commands to support invitations

Update the project role CLI commands to support invitations

---

internal/authz/interface.go
internal/controlplane/handlers_authz.go
internal/controlplane/handlers_authz_test.go

The following PR update AssignRole, RemoveRole and add new UpdateRole handlers

Update AssignRole, RemoveRole and add new UpdateRole handlers

---

cmd/cli/app/provider/provider_update.go
cmd/cli/app/provider/provider_update_test.go

Update command allows changing configuration for provider on a per-field basis. It operates on a read-modify-write fashion, retrieving current configuration from the backend for modification.
Modification is done by reflection by walking over the struct's JSON tags. Implementation is recursive, but the maximum depth is determined by the deepest field in the configuration struct.
Argument parsing is trivial and assumes that arguments are either of the form `field1.field2.field3` (for `--unset-attribute`) or `field1.field2.field3=value` (for `--set-attribute`). The right parser for `value` is determined once the correct struct field is found.
It is not currently possible to modify `"github-app"` or `"github"` fields.
Fixes #3509
* unit …

Added minder provider update CLI command.

---

cmd/cli/app/provider/provider_update.go

We're able to infer which project ID to use if it's not specified
explicitly by inferring who the caller is and using their "root"
project.
Related: #3509
manually

Provider update should let back end infer the project ID

---

cmd/cli/app/repo/repo_register.go

Adds an optional --all flag to the repo-register command that issues an event to reconcile all available repositories.
Fixes: #3269
manually

Add an --all flag to the repo-register command

---

internal/auth/jwtauth.go

The following PR adds helper functions for getting token and mail from context
Split from #3689 

Add helper functions for getting token and mail from context

---

internal/entities/utils.go

Spotted by @eleftherias in smoke tests. When evaluating a PR, the repo ID is also passed around. This violated the assumption that only one entity type would be specified.
Change the logic so that we try and find a PR or artifact ID first, then a repo ID later.

Fix issue with multiple entity IDs

---

cmd/cli/app/auth/invite/invite_accept.go
cmd/cli/app/auth/invite/invite_decline.go
cmd/cli/app/project/role/role_grant.go
cmd/cli/app/project/role/role_grant_list.go
cmd/cli/app/project/role/role_update.go
database/mock/store.go
database/query/invitations.sql
internal/controlplane/handlers_authz.go
internal/controlplane/handlers_authz_test.go
internal/controlplane/handlers_invites.go
internal/controlplane/handlers_user.go
internal/db/invitations.sql.go
internal/db/querier.go
internal/flags/constants.go
internal/flags/flags_test.go

The following PR includes a few updates on the user management implementation. 
The changes that are introduced are:
* Moved the invite update logic to happen under the UpdateRole handler instead of being part of the AssignRole handler
* Added a few display names based on the FE feedback
* Reflected these changes on the CLI
* Refactored the part of create/deleting an invitation to ensure proper behaviour
* Added a protection so minder discards processing the invite if the user tries to accept an invite for a role he already has and another one where we delete his current role assignment and accept the new one ensuring he should have only one assignment per project.
* Fixed the missing invite code in ListRoleAssignments and a bug where the Sponsor field was empty
* Updated the `minder role …

Refactor UpdateRole and add display names to invite-related responses

---

cmd/cli/app/project/role/role_grant_list.go
cmd/cli/app/project/role/role_update.go
database/query/invitations.sql
internal/controlplane/handlers_authz.go
internal/db/invitations.sql.go

The following PR addresses the feedback from #3689. 
There'll be a follow up with some of the other items from that list.

Do not return the invite code when listing role assignments and set display name defaults

---

internal/controlplane/handlers_authz.go

The following PR adds a check in case the user is removing the last admin role of a project.

Do not allow removing the last admin role of a project

---

database/mock/store.go
database/query/eval_history.sql
internal/db/eval_history.sql.go
internal/db/querier.go
internal/engine/eval_status.go

This captures the alert and remediation statuses and stores them in the new tables.
Fixes #3556

Store alert and remediation history

---

database/mock/store.go
database/query/invitations.sql
internal/controlplane/handlers_authz.go
internal/db/invitations.sql.go
internal/db/querier.go

The following PR reuses the previous invite code when updating an invitation. This would allow for older invitations to still work. The initial email content may not reflect the new state, but we are okay with this (synced with Evan) there'll be a follow up email being send in case the role changed

Reuse the previous invite code when updating an invitation

---

docs/docs/about/roadmap.md
docs/docs/run_minder_server/run_the_server.md

Update the roadmap in our documentation.
Go check out the new roadmap page. 😁

Update roadmap in documentation

---

docs/README.md

The previous example `npm run serve -p 3001` was giving me errors.
follow the steps in the readme

Fix npm run serve example in the docs' README

---

internal/email/email.go

The following PR refactors the email template part to be included in the message payload. This way all potential clients will use the same content.

Include the email template in the event message

---

internal/controlplane/handlers_user.go

The following PR fixes and issue with sub-projects. Apparently when we create one we don't create role assignments for this sub-projects in openfga. This caused the backend to return an error when trying to build the user's project list info during `GetUser`.
This is a temporary fix, but perhaps the right way to fix it is to update the project create part and populate it with the right assignments

Do not try to fill roles if project has none

---

internal/controlplane/handlers_authz.go
internal/controlplane/handlers_invites.go

The following PR fixes and issue where the org display name was not the one set by the user during onboarding.
This fixes both email invitations and the invite confirmation pop-up.

Use the correct org display name for invitations

---

cmd/cli/app/project/role/role_grant_list.go
cmd/cli/app/project/role/role_update.go

The following PR includes the subject display name when listing or updating role assignments. Previously it was just the ID.

Show the subject display name along with the ID in minder role

---

docs/docs/ref/proto.md
docs/proto_template.tmpl
docs/src/css/custom.css

Running `docusaurus build` generates warnings on the generated protocol documentation, most are false positives, but three are correct (which were buried by the other false positives).
The false positives arise because we use our own anchors for linking things like request, response, and scalar types. However, docusaurus's link checker doesn't know about these generated anchors and emits false positives. This PR updates the generator to instead create React components to generate the titles and anchors, so that we can tell docusaurus about them. Its link checker will then not emit a false positive.
Then, the links to the types assume that we document all of them on this page. But the google.protobuf.* types are not documented by us. Create a `TypeLink` component that understands this …

Updates to the protocol documentation (and its generator)

---

internal/controlplane/handlers_user.go

This ensures the project display name is the one the user set during onboarding.
Similar to [#3750](https://github.com/stacklok/minder/issues/3750)

Fix project display name when listing invitations

---

internal/controlplane/handlers_user.go

This ensures the project display name is the one the user set during onboarding.
Similar to https://github.com/stacklok/minder/issues/3750

Fix project display name when resolving invite

---

database/migrations/000072_profile_selector_type.down.sql
database/migrations/000072_profile_selectors_type.up.sql
database/query/profiles.sql
internal/db/profile_selector_scan.go
internal/db/profiles.sql.go
internal/db/profiles_test.go
sqlc.yaml

Extend the Profile List database calls to include selectors
Since the profile selectors need to be included when listing profiles, we need to extend the two profile list calls to list selectors as well.
Because the selectors are stored in a different table, but we still need to retrieve them in the same Go struct defined in models, we define a new SQL type in a migration that represents the selectors and tell sqlc to use it in sqlc.yaml.
This new Go struct needs a Scan method as well to convert raw SQL rows into structs as well.
Co-authored-by: Michelangelo Mori <mmori@stacklok.com>
Fixes: #3721
There are unit tests and I tested the code as part of a larger branch, too.

Extend the Profile List database calls to include selectors

---

internal/util/cli/cli.go

Users in Spain (and possibly other regions) are experience continuous context timeouts, because requests to the gRPC endpoints on the server are taking longer than 10 seconds.
This increases the timeout, under the assumption that it's better for the CLI to be slow than to error.

Increase CLI context timeout to 20s

---

docs/docs/understand/alerts.md
docs/docs/understand/profiles.md
docs/docs/understand/providers.md
docs/docs/understand/remediations.md
docs/docs/understand/repository_registration.md
docs/docs/user_management/adding_users.md

The Minder Cloud docs server at https://docs.stacklok.com/minder/ adds a trailing slash to the URL path. This was causing some of our links to be broken.
Ref https://github.com/stacklok/docs/issues/238

Fix broken documentation links

---

database/query/profiles.sql
internal/db/profiles.sql.go
internal/db/profiles_test.go

We'll want to have the selectors in the reply to use in profile
handlers.
Relates: #3723
make test

GetProfileByProjectAndID includes selectors

---

internal/providers/artifact/versionsfilter.go
internal/providers/artifact/versionsfilter_test.go

This PR adds a length limit to the regular expressions we parse from user input to curve the complexity Minder
handles when compiling them to build a tag matcher.

Artifact tag matcher: Curb complexity when parsing regexps from user input

---

internal/authz/authz.go
internal/authz/authz_test.go
internal/authz/fuzz_test.go
internal/authz/interface.go
internal/controlplane/handlers_authz.go
internal/controlplane/handlers_authz_test.go
internal/controlplane/handlers_user.go
internal/controlplane/identity_events_test.go
internal/projects/creator.go
internal/projects/deleter.go
internal/projects/deleter_test.go

* Sort the authz roles in ListRoles response
* Renames a few variables to fix linter warnings 
Fixes #3855 

Sort the authz roles in ListRoles response

---

internal/db/domain.go
internal/profiles/util.go

Extends the `MergeDatabaseGetIntoProfiles` and `MergeDatabaseListIntoProfiles`
functions to include selectors. These will be useful later when we extend the
profile handlers.
- **Extend the ProfileRow interface for selectors**
- **Add selectors to profile in `MergeDatabaseListIntoProfiles`**
- **`MergeDatabaseGetIntoProfiles` includes selectors**
Related: #3723
as part of a larger branch. We'll be able to add tests when we extend the Profile service
and extend the handlers.

Extend the db-to-pb profile code to include selectors

---

internal/controlplane/handlers.go

This change aims to add a little more introspection on why health check might fail. It's meant to help in scenarios like e.g. when Minder goes CLBO because of liveness check failures. Currently, it is hard to tell whether this is because of lack of resources, most likely CPU, or because it fails to connect to the database.

CheckHealth RPC now logs error when failing.

---

internal/db/eval_history.sql.go
internal/db/models.go
internal/db/types.go
internal/history/service.go
internal/history/service_test.go
sqlc.yaml

Prior to this PR, sqlc was unable to map `TIMESTAMPZ[]` to `[]time.Time` due a limitation in the `pq` driver. This PR leverages a suggested fix from a Github issue in the `pq` repo.

Fix issues with mapping of `TIMESTAMPZ[]` postgres type

---

database/query/eval_history.sql
internal/db/eval_history.sql.go
internal/history/models.go
internal/history/models_test.go

Filtering on entity name was not accounting for repo owner in case of repositories. Additionally, wrong values for enumerations were reported as internal errors rather than validation errors.
Unit tests and manual tests.

ListHistoryEvaluation filtering fixes.

---

internal/controlplane/handlers_evalstatus.go

It is currently valued at the same as the default page size. We might raise it once we have more details about the performance impact of the endpoint.
Manually tested.

ListEvaluationHistory now enforces max page size.

---

cmd/dev/app/rule_type/rttst.go
internal/engine/actions/alert/alert.go
internal/engine/actions/alert/security_advisory/security_advisory.go
internal/engine/executor.go
internal/engine/interfaces/interface.go
internal/engine/rtengine/engine.go
internal/logger/telemetry_store.go
internal/logger/telemetry_store_test.go
internal/profiles/rule_validator_test.go

These changes will simplify some upcoming PRs. They include:
1) Moving the rule type engine into its own sub package. 
2) Removing the rule type PB struct from the evaluation parameters. The
alerting code currently accesses the rule type information by
multiple paths (some of it is passed to the constructor for the
alert, and other bits from the evaluation parameters). By picking a
single way to pass the rule type around, changes for caching are
simplified.
Changes validated locally.
***Outline how the …

Some prep work for further changes to the executor

---

cmd/cli/app/provider/provider_update.go
cmd/cli/app/repo/repo_register.go
internal/util/cli/providerconfig.go

When registering all repositories, what the user really means is
"register all future and current repositories. The current invocation of
the call only registered all current ones. Let's also flip the option to
register all future repositories at the same time.
Fixes: #3817
1. `minder provider get` should either show the auto registration is set to false or not set at all
2. `minder repo register --provider=$NAME --all`
3. `minder provider get` again should show the auto registration is seat to true
Note: `minder repo register --all` currently requires the provider name to be passed. We should fix the command to iterate over providers that implement the RepoLister trait instead.

Set the auto_registration.entities.repository.enabled option to true when calling repo register --all

---

cmd/cli/app/provider/provider_get.go

We used to only print provider config if there was any on `provider
get`. That's not very user-friendly in case the user enables
auto-registration and then runs provider get to see what had changed.
In the usual case where there's no config, we don't print anything. If
there is configuration, we print key-value pairs for each config option.
The key-value pairs work fine for now since we have a low number of
config options. In the future, once our config gets more complicated, we
should just switch to printing the config as YAML, but for now this
looks awkward and the table gets too vertically long for just one
option.
Fixes: #3816
```
minder provider update --set-attribute=auto_registration.entities.repository.enabled=false --name=github-app-jakubtestorg
minder provider get -n …
```

Print provider config in provider get, if any

---

internal/engine/executor.go
internal/engine/metrics.go

This adds metrics for timing evaluations - both at the per profile and per entity level. I plan on introducing some changes which may change the performance of evaluation, and I would like some metrics to be able to reason about these changes.

Track evaluation times in executor

---

internal/engine/eval_status.go
internal/engine/interfaces/interface.go

The execution ID is very handy to link together a single run when
debugging Minder. Unfortunately, it's not set everywhere... so let's do
that! This way, we'll be able to better debug minder throughout the
execution of policy for an entity.

Add Execution ID in the executor's evaluation param logs

---

internal/engine/metrics.go

From experimentation, it seems that attributes of the same name in
different metrics are shared. This leads to, for example, alert status
types showing up in the remediation graph.

Give metric attributes unique names

---

database/migrations/000075_evaluation_history_no_dedupe.down.sql
database/migrations/000075_evaluation_history_no_dedupe.up.sql
database/mock/store.go
database/query/eval_history.sql
internal/db/eval_history.sql.go
internal/db/models.go
internal/db/querier.go
internal/history/service.go
internal/history/service_test.go

I have run into a number of issues involving pq and sqlc's ability to deal with postgres timestamp arrays. At this point, rather than invest further effort, I have decided to remove the deduplication feature for now. Since this will only be useful at the point where we use reconciliation more extensively, I would prefer to reintroduce this functionality once we have more data to back up its utility.
Attach …

Remove deduplication logic in evaluation history

---

internal/engine/handler.go
internal/engine/handler_test.go
internal/flags/flags.go

Update entity evaluation to propagate message context and include data for flag evaluation in the context.
Update flag evaluation context to store user in the same form as project and provider, and make the project ID the primary targeting key for providers that need it (not GoFeatureFlag).  Since no one is probably using the current fine-grained targeting, this should be okay.

Use project as targeting key, propagate message context through entity evaluation

---

cmd/cli/app/profile/status/status_get.go

This commit marks `entity-type` as required in
`minder profile status get` to avoide sending
`ENTITY_UNSPECIFIED` to the API (which always fails).

Require entity-type in profile status get to avoid permafail

---

internal/controlplane/handlers_authz.go
internal/controlplane/handlers_authz_test.go
internal/invites/mock/service.go
internal/invites/service.go
internal/invites/service_test.go
internal/roles/mock/service.go
internal/roles/service.go
internal/roles/service_test.go

This adds tests for the `RemoveRole` handler and moves the invite and role assignment deletion logic to its respective services.
Ref #3673

Add tests for RemoveRole

---

internal/providers/github/common.go

URL-escaping is already happening within the go-github library, so we
don't need to do it twice. Doing it twice causes minder to not be able
to retrieve the package versions since indeed that resource is non-existent.
Fixes #3914
***Outline how the changes were tested, including steps to reproduce and any relevant configurations.

Don't URL escape the package name when getting versions

---

internal/controlplane/handlers_authz.go
internal/controlplane/handlers_authz_test.go
internal/invites/mock/service.go
internal/invites/service.go
internal/invites/service_test.go
internal/roles/mock/service.go
internal/roles/service.go
internal/roles/service_test.go

This adds unit tests for `AssignRole` and moves the invite and role creation logic to their respective services.
Fixes #3673

Add tests for AssignRole

---

internal/engine/eval/eval.go
internal/engine/executor.go
internal/engine/rtengine/cache.go
internal/engine/rtengine/cache_test.go

This addresses a potential race condition I discovered while working on another task. If a rule instance with a new rule type is added to a profile after the rule type cache is populated, but before the profiles and rule instances are queried, the evaluation will fail because the new rule type will be missing from the cache.
This changes the logic to query for rule types which are not found in the cache, and create a new rule type engine instance and cache it if we get a result.
**Alternatives Considered**
I could simplify this to remove the pre-population and query the database for each rule type when we encounter it first. This would simplify the logic, but at the expense of throwing away the performance gains from loading most of the rules we need in one query.
***Provide a brief …

Fix potential race condition in rule type engine cache

---

cmd/cli/app/history/history_list.go
internal/util/cli/styles.go

This change adds two flags to `minder history list` command, namely `--cursor`, which lets the user specify the cursor to a specific page of the list, and `--size`, which lets the user specify the number of items to retrieve. The two flags can be used independently from one another.
For obvious reasons, code was also added to print the cursors. I picked an arbitrary position, but reviewed the style with James to ensure some degree of uniformity with the rest of the product.
Fixes #3913
Manual tests.

Add support for cursors to `minder history list`.

---

cmd/cli/app/project/role/role_grant.go
cmd/cli/app/project/role/role_update.go

The following PR adds support for setting the output format for commands `role grant` and `role update`.

Add format output for role grant and update

---

cmd/cli/app/history/history_list.go

This change adds `--from` and `--to` optional flags, which let the customer specify a time window for evaluation times. Allowed formats are those supported by the library we're currently using (viper) and are listed [here](https://github.com/spf13/cast/blob/48ddde5701366ade1d3aba346e09bb58430d37c6/cast_test.go#L934-L952).
Fixes #3927
Manual tests.

Add from/to filters to `minder history list`.

---

database/query/eval_history.sql
internal/controlplane/handlers_evalstatus.go
internal/db/eval_history.sql.go
internal/history/service_test.go

The id returned as id of the entity is the wrong one and must be fixed. This will probably be followed up by another pull request addressing the need to return the evaluation id.
Fixes #3932
Manual tests.

Fix entity id in ListEvaluationHistory RPC.

---

internal/controlplane/handlers_evalstatus.go

The removed lines cause an error when trying to convert a correctly typed variable into the same itself. Previously, `row.EntityType` was a string and could be converted correctly.
I introduced the bug a couple commits before.
Manual tests.

Remove unnecessary type conversion causing errors.

---

internal/db/profile_selector_scan.go
internal/db/profiles_test.go

Let's not return the description quoted to the user.
Related: #3723
manual + there's a unit test

Trim quotes when returning selector comments

---

internal/controlplane/handlers_evalstatus.go
internal/controlplane/handlers_evalstatus_test.go

This adds minimal test coverage to evaluation history log entries conversion in order to prevent issues like the one solved by commit 5ad938d8b2c8.
Unit tested.

Add tests to evaluation log entries conversion.

---

cmd/dev/app/rule_type/rttst.go

Let's make our life easier when developing profiles by making selectors
available in mindev
Fixes: #3726
```
AUTH_TOKEN=youdliketoknowwouldntyou go run cmd/dev/main.go ruletype test --profile /Users/jakub/devel/playground/ghas-selectors.yaml --rule-type /Users/jakub/devel/minder-rules-and-profiles/rule-types/github/secret_scanning.yaml --entity /Users/jakub/devel/playground/repository.yaml --log-level=debug
Profile valid according to the JSON schema!
{"level":"info","eval_status":"skipped","action":"remediate","Timestamp":1721397355551920000,"message":"action is off, skipping"}
{"level":"info","eval_status":"skipped","action":"alert","Timestamp":1721397355551935000,"message":"action is off, skipping"}
Error: error evaluating rule type: evaluation skipped: entity not selected by selectors …
```

Make selectors available in mindev

---

database/mock/store.go
database/query/selectors.sql
internal/db/querier.go
internal/db/selectors.sql.go
internal/db/selectors_test.go

We'll do a dumb but easy way of updating selectors - we'll drop all
current for the profile being updated and re-add them.
Relates: #3723
there is a test + I cherry-picked the patch out of a larger branch

Add a DB function to delete all selectors for a profile

---

internal/controlplane/handlers_profile_test.go
internal/profiles/service.go

Expands the profile handlers code with adding support for selectors so
that all the usual CRUD operations on profiles work with selectors, too.
The update code is not smart - I think that's OK for now. We can
optimize later when we see that selectors are modified often.
Fixes: #3723
manual testing + unit tests

Expand profile handlers with selector support

---

cmd/dev/app/rule_type/rttst.go
internal/engine/actions/actions.go
internal/engine/actions/alert/noop/noop.go
internal/engine/actions/alert/security_advisory/security_advisory.go
internal/engine/actions/remediate/gh_branch_protect/gh_branch_protect.go
internal/engine/actions/remediate/noop/noop.go
internal/engine/actions/remediate/pull_request/pull_request.go
internal/engine/actions/remediate/rest/rest.go
internal/engine/interfaces/interface.go
internal/profiles/models/models.go

PR #3899 accidentally removed a call to GetOnOffState, which allows individual actions to override the remediation and alerting status in the profile. This leads to some unusual behaviour, such as attempting to run the noop alerts and remediations instead of skipping them. This PR reinstates the calls to GetOnOffState, but changes the function to accept the ActionOpt status for that action type instead of taking a pointer to the entire profile.
***Outline how the changes were tested, including steps to …

Respect the action overrides

---

internal/roles/service.go
internal/roles/service_test.go

The following PR adds an additional check caught by the smoke test where Minder returned a positive response in case there was no existing role assignment and we tried to remove it.

Ensure role exists before we try to remove the role assignment

---

database/mock/store.go
database/query/profiles.sql
internal/db/profiles.sql.go
internal/db/querier.go
internal/engine/actions/alert/security_advisory/security_advisory.go
internal/profiles/service.go

PR #3903 replaced the one part of minder which queried the data in the `entity_profile_rules` table. This PR removes the code which adds and removes entries to this table. A future PR will drop the table outright.

Remove use of `entity_profile_rules` table

---

internal/history/service.go
internal/history/service_test.go

Fixes #3966
Fixed unit tests.
Manually tested as follows
```shell
$ minder history list -s 3 -o json | jq '.data[] | "\(.evaluatedAt),\(.id)"' | tr -d \"
2024-07-23T14:18:42.386278Z,f7e32737-1995-4825-b22b-4a0746d92472
2024-07-23T14:18:42.367654Z,e49b6912-b52b-4016-ab8b-3210a9cb6947
2024-07-23T14:18:42.347620Z,b7bef1c7-8d09-4de7-bc87-fcc2d2ecfbb2
$ minder history list -s 3 -c KzE3MjE3NDQzMjIzNDc2MjA= -o json | jq '.data[] | "\(.evaluatedAt),\(.id)"' | tr -d \"
2024-07-23T14:18:42.333747Z,7c197aec-b6d5-4ee7-a470-df612abddcca
2024-07-23T14:18:42.321212Z,a1f70e3d-8eb2-41ba-be84-7a563fbf6483 …
```

Align sort inversion with pagination direction.

---

docs/docs/how-to/artifact_signatures.md
docs/docs/how-to/create_profile.md
docs/docs/how-to/create_project.md
docs/docs/how-to/pr_reviews.md
docs/docs/how-to/remediate-pullrequest.md
docs/docs/how-to/setup-alerts.md
docs/docs/how-to/setup-autoremediation.md
docs/docs/understand/projects.md
docs/docs/user_management/adding_users.md
docs/docs/user_management/user_roles.md

Document the new user invitations feature
Fixes #3795 
N/A

Add docs for user management and invitations

---

database/query/eval_history.sql
internal/db/eval_history.sql.go
internal/history/models.go
internal/history/models_test.go

Currently, ListEvaluationHistory RPC forces the client to either specify both from and to or none of them, but the logic behind the extracted data would allow them to be specified independently.
This change decouples from and to, making the underlying statement a tiny bit more uniform.
Unit tests and manual tests.

Decouple from/to filtering in history log RPC.

---

database/mock/store.go
internal/db/store.go
internal/engine/eval_status.go
internal/engine/executor_test.go

Remove the feature flag gating of the database operations which store the evaluation history. Change the unit tests in order to stub out these operations.

Log evaluation history by default

---

cmd/cli/app/history/history_list.go

ListEvaluationHistory RPC accepts multiple entries for string-like filters, e.g. evaluation statuses, profile names, etc. While minder CLI internally manages those filters as slices, viper is not configured to accept repeated options.
This change makes it possible to provide `--profile-name`, `--entity-name`, `--entity-type`, `--eval-status`, `--remediation-status`, and `--alert-status` options multiple times with different values, all of which will eventually be passed to the backend as filters.
Fixes #3978
Manually tested against local and staging environment.

Accept filters multiple times in `history list`.

---

database/query/eval_history.sql
internal/db/eval_history.sql.go

Entity type was added to `evaluation_rule_entities` table by commit 1ceab64. This introduced an ambiguity in the evaluation log query that was previously implicitly using entity type from `rule_instances` table. The newly introduced column is not yet filled, so we're just making the statement unambiguous by explicitly adding a reference to the table previously used.
Manual tests.

Disambiguate entity type in history log query.

---

database/migrations/000078_latest_status_profile_id.down.sql
database/migrations/000078_latest_status_profile_id.up.sql
database/query/eval_history.sql
internal/db/eval_history.sql.go
internal/db/models.go
internal/engine/eval_status.go
internal/engine/executor_test.go
internal/history/mock/service.go
internal/history/service.go
internal/history/service_test.go

Adding this information to the `latest_evaluation_statuses` table simplifies the process of changing the profile status queries to use the evaluation history tables instead of the old tables I am trying to replace.

Add profile ID to `latest_evaluation_statuses`

---

cmd/dev/app/rule_type/rttst.go
internal/engine/selectors/selectors.go
internal/engine/selectors/selectors_test.go

This is just a small refactoring that makes future patches easier to apply.
The function was only ever returning nil anyway and it would make using
it in minder easier as well
just make to be honest

Change selectors.New to not return an error

---

database/migrations/000079_rule_evaluations_evaluation_history.down.sql
database/migrations/000079_rule_evaluations_evaluation_history.up.sql
database/query/profile_status.sql
internal/db/models.go
internal/db/profile_status.sql.go
internal/engine/eval_status.go
internal/engine/executor_test.go
internal/history/mock/service.go
internal/history/service.go
internal/history/service_test.go

In order to replace the old evaluation status tables, we need to migrate any evaluation statuses to the new tables which predate the introduction of the new evaluation history tables. In order to simplify this migration, create a foreign key link from `rule_evaluations` to `evaluation_rule_entities` (the latter is essentially the new equivalent of the former). A foreign key reference to `rule_instances` is also added, this is also to simplify the migration.
This PR also fixes some issues with the migration introduced in this previous PR.
Tested locally. …

Add `rule_entity_id` to `rule_evaluations`

---

cmd/server/app/history.go
cmd/server/app/history_purge.go
cmd/server/app/history_purge_test.go
database/mock/store.go
database/query/eval_history.sql
internal/db/eval_history.sql.go
internal/db/querier.go

This command is used to manage the life cycle of the history log. The business requirement is to delete all records older than 30 days maintaining the most recent one for each entity/rule pair even if older than 30 days.
Implementing this requirement mandates the processing of the whole set of records older than 30 days, which cannot be processed in chunks without creating arbitrary holes in the history. As a first approximation, the proposed implementation loads all records in RAM, filters out the ones to keep, and issues a series of deletions of up to 1000 records each. A test was added to keep track of the record size. A future improvement would be to spill records to secondary storage, where we would perform sorting and filtering, but it was overly complex and unjustified at this …

Add history purge command to minder server cli.

---

internal/engine/selectors/mock/selectors.go
internal/engine/selectors/selectors.go
internal/engine/selectors/selectors_test.go

In order to tell the user what's wrong with a selector they are about to
take into use, let's introduce a structured way of returning errors to
the selector API.
The errors can be represented as JSON in order for clients to be able to
parse the error without knowing much about the type.
Related: #3725
with the added unit tests and as part of a larger topic branch

Return structured errors from the selectors API

---

cmd/dev/app/rule_type/rttst.go
database/mock/store.go
database/query/profiles.sql
internal/db/profiles.sql.go
internal/db/profiles_test.go
internal/db/querier.go
internal/engine/executor.go
internal/engine/executor_test.go
internal/engine/selectors/mock/selectors.go
internal/engine/selectors/selectors.go
internal/engine/selectors/selectors_test.go
internal/profiles/models/models.go
internal/profiles/store.go
internal/service/service.go

- **Change the BulkGetProfilesByID DB query to return an embedded profile** - This will make it easier to extend what the query returns
- **Extend the BulkGetProfilesByID DB query with selectors** - This is to return the selectors at the same time as querying the profiles from the DB and be able to use them in the executor.
- **Extend the ProfileAggregate structure with selectors** - returns the selectors to the engine through the ProfileAggregate struct
- **Change the selector's NewSelectionFromProfile API to accept the structure from the models API** - This will make it easier to use the method in the executor
- **Integrate the selectors into the executor** - When an entity is not selected for a profile, let's save that into a  profile-global status override and use that for all the …

Take selectors into use in executor

---

internal/controlplane/handlers_profile_test.go
internal/engine/selectors/selectors.go
internal/profiles/service.go
internal/profiles/validator.go
internal/service/service.go

This is a minimal patch to surface selector errors through profile
handlers to clients. It does not expose the structured data (e.g. which
line and which column did the error occur at). I started working on
that, but realized that that's a bigger endevor that ought to be
implemented separately.
Fixes: #3987
by calling the profile handlers, both grpc through the minder client and HTTP through curl:
```
curl -vv -H "Authorization: Bearer $MINDER_BEARER_TOKEN" 'http://localhost:8080/api/v1/profile' --data-binary @/Users/jakub/devel/playground/ghas-selectors-check-error.json
```

Surface selector check errors to handlers

---

internal/engine/selectors/selectors_test.go

I realized we don't have any test case for multiple selectors, let's fix
that
Fixes: #4016
make test

Extend test cases for selectors with multivalued selections

---

database/migrations/000082_backfill_latest_eval_profile_id.down.sql
database/migrations/000082_backfill_latest_eval_profile_id.up.sql
internal/db/eval_history.sql.go
internal/db/models.go
internal/history/service.go

Backfill this column and make it non nullable. Note that due to the sequencing of production deploys, there should not be any `latest_evaluaion_statuses` rows in production which do not have a `profile_id` - this migration is only relevant for staging and local dev environments.

Backfill `latest_evaluation_statuses` with `profile_id`

---

database/migrations/000084_eval_status_checkpoint.down.sql
database/migrations/000084_eval_status_checkpoint.up.sql
internal/db/eval_history.sql.go
internal/db/models.go

This adds the checkpoint as a `JSONB` structure in the database. This has
been indexed using a `GIN` index for efficient JSON lookups once we
hook this up to the application.

Add entity evaluation checkpoint to the database

---

internal/entities/checkpoints/checkpoints.go
internal/entities/checkpoints/checkpoints_test.go

This adds initial Checkpoint structures which go in relation to the Entity Evaluation
Checkpoints proposal. The idea is that this structure may be extended to add additional
checkpoints that serve whatever other entities we require.

Add initial structures for entity checkpoints

---

go.mod
go.sum
internal/email/awsses/awsses.go
internal/service/service.go

The following PR fixes the migration we did to `aws-sdk-go-v2` which caused the email sending service to stop working for minder.
Fixes https://github.com/stacklok/minder/issues/4045

Fix the AWS SES migration to sdk v2

---

internal/profiles/validator.go
internal/profiles/validator_test.go

Previously, minder required rule names to be unique within an entity type, but did so in a case-sensitive manner. Minder's API expects rule names to be unique in a case-insensitive manner. This changes the validation logic to prevent new rule instances from being created if they are not unique in a case insensitive manner.

Change profile validation to enforce case insensitive unique rule names

---

database/migrations/000085_eval_history_changes.down.sql
database/migrations/000085_eval_history_changes.up.sql
database/query/profile_status.sql
database/query/rule_instances.sql
internal/db/models.go
internal/db/profile_status.sql.go
internal/db/rule_instances.sql.go

Adds:
* Lower case index to rule instance names - this is needed since we will need the ability to query rule names in a case insensitive manner (see migration 31)
* A "migrated" column to rule_evaluations. This will be used to figure out which entries in the rule_evaluations table need to be copied across to the evaluation_rule_entities table.

Additional DB migrations needed for evaluation history switchover

---

database/query/eval_history.sql
internal/db/eval_history.sql.go
internal/engine/eval_status.go
internal/engine/executor_test.go
internal/engine/ingester/artifact/artifact.go
internal/engine/ingester/builtin/builtin.go
internal/engine/ingester/diff/diff.go
internal/engine/ingester/git/git.go
internal/engine/ingester/git/git_test.go
internal/engine/ingester/rest/rest.go
internal/engine/ingester/rest/rest_test.go
internal/engine/interfaces/interface.go
internal/entities/checkpoints/checkpoints.go
internal/entities/checkpoints/checkpoints_test.go
internal/history/mock/service.go
internal/history/service.go
internal/history/service_test.go

This starts adding ingest checkpoint data into the history log.
The main benefit here is that we'd have commit/branch information for git-related ingests.
artifacts require a little more work and will be handled in a separate PR.

Persist checkpoints in evaluation history db

---

go.mod
go.sum

This commit bumps the trusty GO SDK to v0.2.0 to use the new provenance fields from the Trusty API response.
Fixes https://github.com/stacklok/minder/issues/4068
This is a small version bump to pull in the latest changes in the trusty SDK

Bump trusty client to trusty-sdk-go@v0.2.0

---

go.mod
go.sum
internal/engine/eval/trusty/trusty.go

Update to the latest version of the trusty sdk, which doesn't require setting the http client.
Fix #4081

Bump trusty-sdk to v0.2.1

---

database/query/eval_history.sql
internal/db/eval_history.sql.go
internal/engine/eval_status.go
internal/engine/executor_test.go
internal/engine/ingester/artifact/artifact.go
internal/engine/ingester/builtin/builtin.go
internal/engine/ingester/diff/diff.go
internal/engine/ingester/git/git.go
internal/engine/ingester/git/git_test.go
internal/engine/ingester/rest/rest.go
internal/engine/ingester/rest/rest_test.go
internal/engine/interfaces/interface.go
internal/entities/checkpoints/checkpoints.go
internal/entities/checkpoints/checkpoints_test.go
internal/history/mock/service.go
internal/history/service.go
internal/history/service_test.go

This starts adding ingest checkpoint data into the history log.
The main benefit here is that we'd have commit/branch information for git-related ingests.
artifacts require a little more work and will be handled in a separate PR.

Persist checkpoints in evaluation history db. Try 2

---

database/migrations/000087_set_migrated_flag_rule_evaluations.down.sql
database/migrations/000087_set_migrated_flag_rule_evaluations.up.sql

After testing in staging, I found that the migration to set the `migrated` column did not work as expected. The intention was that any rows in `rule_evaluations` which have the same combination of rule instance ids and entity ids should be marked as migrated, as they refer to the same evaluations. This migration addresses this problem.
Tested against staging (with a rollback)
Attach screenshots if …

Fix migrated column on rule evaluations

---

identity/config/stacklok.yaml

Update Keycloak config in local docker image to allow for unmanaged attributes. Without this the attributes `gh_id` and `gh_login` weren't getting mapped into the token correctly, which was causing problems when looking up the user.
Fixes #4084
note: It is intentional that there's a JSON string in the YAML file. It would be nice if they offered a better configuration option, but this is the way to do it for now.

Allow unmanaged attributes in KC for local dev

---

database/migrations/000088_fix_rule_instance_id.down.sql
database/migrations/000088_fix_rule_instance_id.up.sql

When this column was backfilled originally, the update statement lacked some of the fields needed to make sure that the join from rule_evaluations to rule_instances was a 1-1 mapping. This led to the wrong rule_instance_id being attached to the rule_evaluations table. Note that this value is not currently used for anything, so the impact was negligible.
This re-runs the backfill with all fields matching to ensure the correct ID is used.
Validated in staging.
***Outline how the changes were tested, including …

Fix rule_instance_id column on rule_evaluations

---

tools/go.mod
tools/tools.go

Prior to this commit, the go mock dependency was implicitly added by the openFGA dependency.
The latest openFGA update removed the implicit dependency and caused our CI to fail (see https://github.com/stacklok/minder/actions/runs/10347230154/job/28637107802?pr=4112)

Make go mock an explicit dependency in tools

---

database/query/profile_status.sql
internal/db/profile_status.sql.go

This query is always called after an upsert into the evaluation history table, so migrated should always be set to true. Due to the lack of the update in the `ON CONFLICT DO UPDATE` clause, we ran into a situation where unmigrated rows in rule_evaluations were being implicitly migrated by the policy migration (i.e. the code was creating a corresponding row in evaluation_rule_entities) but the migrated flag was still set to false. The migration script would then attempt to copy the data to the evaluation_rule_entities table, which would error out because the data for that rule/entity pair already existed.
List dependencies required by …

Change rule_evaluations upsert to set `migrated` to true

---

docs/docs/how-to/profile_selectors.md

Add documentation for profile selectors

---

database/migrations/000091_entity_project_fk.down.sql
database/migrations/000091_entity_project_fk.up.sql

This was missing the `ON DELETE CASCADE` option from the foreign key
constraints for project ID and provider ID references. These are
important since they ensure that project and provider deletion clean up
resources as needed.

Ensure `ON DELETE` is properly set for the central entities table

---

internal/controlplane/handlers_authz.go
internal/controlplane/handlers_authz_test.go
internal/controlplane/handlers_oauth.go
internal/controlplane/handlers_providers.go
internal/controlplane/handlers_repositories.go
internal/controlplane/handlers_ruletype.go
internal/engine/eval/jq/jq.go
internal/engine/eval/rego/result.go
internal/engine/eval/trusty/trusty.go
internal/engine/eval/vulncheck/vulncheck.go
internal/roles/service.go

The latest golangci-lint version is reporting issues, this PR fixes
them.

Address linter issues coming from govet

---

internal/auth/jwt/jwtauth.go

Fixes:
```
internal/auth/jwt/jwtauth.go:146:32: SA1029: should not use empty
anonymous struct as key for value; define your own type to avoid
collisions (staticcheck)
return context.WithValue(ctx, userTokenContextKey, token)
^
```
make lint and auth

Define own type around struct{} to work around linter warning

---

.trivyignore

We've evaluated this and have determined we're not vulnerable.

Add CVE-2024-42473 to trivyignore

---

database/migrations/000093_profile_status_trigger.down.sql
database/migrations/000093_profile_status_trigger.up.sql
internal/db/profiles_test.go

Remove the existing triggers on rule_evaluations and rule_details_eval.
Replace with triggers on latest_evaluation_statuses. Tweak the trigger
logic to work on the new tables.

Calculate profile status based on evaluation history tables

---

database/query/entities.sql
internal/db/entities.sql.go

The `ON CONFLICT DO NOTHING` clause we used previously would have caused
the SQL query to return "No rows in result set". Let's pretend we do an
update by setting an ID to its own value to trigger the `RETURN` clause.
smoke tests

Do a noop update when updating the entities table

---

cmd/dev/app/rule_type/rttst.go
database/query/profile_status.sql
internal/controlplane/handlers_evalstatus.go
internal/controlplane/handlers_evalstatus_test.go
internal/controlplane/handlers_profile.go
internal/db/profile_status.sql.go
internal/db/profiles_test.go
internal/engine/actions/actions.go
internal/engine/actions/alert/security_advisory/security_advisory.go
internal/engine/actions/remediate/pull_request/pull_request.go
internal/engine/errors/errors.go
internal/util/cli/table/simple/simple.go

Depends on: #4065 
This change allows most of the functionality which previously used the `rule_evaluations` (and related) tables to use the new evaluation history tables instead.
Change in API behaviour: `GetProfileStatusByName` previously returned repo information when querying Github pull requests and artifacts. This behaviour relied on a quirk of the old rule evaluation tables, and is no longer carried forward in the new implementation.
***Outline how the changes were tested, including steps to reproduce …

Change profile/rule status queries to use evaluation history table

---

internal/entities/properties/constants.go
internal/entities/properties/properties.go
internal/entities/properties/properties_test.go
internal/providers/github/mock/github.go
internal/providers/github/properties.go
internal/repositories/github/service.go
internal/repositories/github/service_test.go
pkg/providers/v1/providers.go

This PR adds a new provider interface for fetching properties as well as its implementation for the github provider. The interface returns new Property types which are convenience types to allow returning Go types from the unstructured properties returned by the providers. Lastly, the PR adds constants for the currently used properties, either generic entity properties, generic repo properties or github-specific repo properties.
Closes: https://github.com/stacklok/minder/issues/4165

Provider properties interface

---

.gitignore
internal/engine/actions/alert/security_advisory/security_advisory.go

If there is no prior alert state for a rule/entity pair, an empty db result struct is passed around in the evaluation context. Due to a change from an inner join to a left join, the field's type changed from a pointer to a byte slice to just a byte slice. In the empty case, this means that the alert metadata is represented by an empty byte slice instead of a nil. Change the code to check for empty length in addition to nil-ness.
***Outline how the changes were tested, including steps to reproduce and any …

Check for non-empty length of previous metadata

---

database/mock/store.go
database/query/profile_status.sql
database/query/repositories.sql
internal/controlplane/handlers_profile.go
internal/db/profile_status.sql.go
internal/db/querier.go
internal/db/repositories.sql.go

The `GetProfileStatusByName` URL returns a bunch of information about profiles, including the URL of GHSA alerts if one was created. Minder does not store this URL in the DB, and instead creates it on the fly in the handler code. This assumed that the repo name and owner was returned from the `ListRuleEvaluationsByProfileId` SQL query for all entities, not just repositories.
Since my recent changes removed the link between evaluation history and repositories for artifacts and pull requests, this logic stopped working. This works around the problem by querying the DB explicitly.
Ideally, the URL would be stored in the database as part of the alert metadata. This handles, for example, self-hosted Github, or indeed, alerts other than GHSAs. I consider that a longer term change which requires …

Fix issue with Alert URLs for pull requests and artifacts

---

internal/providers/github/properties.go
internal/repositories/github/service.go

We used to store repo license since
5a78abc38d3608b9e77d11042aaaf6eea04f6763 but then stopping saving the
attribute in d68e8e697dcd36f8c1fd9ec9d8a894903c4f2827. We still have
ruletypes that rely on that attribute, so let's just re-add it.
Side-note: Saving generic attributes will get way easier once we
implement properties fully.
manually

Store repo license again

---

internal/engine/actions/remediate/remediate_test.go
internal/engine/actions/remediate/rest/rest_test.go
internal/engine/ingester/git/git_test.go
internal/engine/ingester/rest/rest_test.go
internal/engine/rtengine/cache_test.go
internal/providers/dockerhub/dockerhub.go
internal/providers/git/git.go
internal/providers/github/ghcr/ghcr.go
internal/providers/github/mock/github.go
internal/providers/gitlab/gitlab.go
internal/providers/http/http.go
internal/providers/oci/oci.go
internal/providers/selectors/mock/interface.go
internal/providers/selectors/selector_entity_test.go
internal/providers/testproviders/doc.go
internal/providers/testproviders/git.go
internal/providers/testproviders/rest.go
internal/repositories/github/service.go
internal/repositories/github/service_test.go
pkg/providers/v1/providers.go

This effectively enforces that providers **must** implement properties fetching as part of their implementation.

Move properties fetcher methods into Provider

---

internal/entities/properties/properties.go
internal/entities/properties/properties_test.go

Since all the providers that do not explicitly implement properties
interface return `nil, nil`, it might be a good idea to implement a nil
receiver for Properties.
make test

Allow nil receiver on Properties

---

.gitignore
database/mock/store.go
internal/db/store.go
internal/engine/actions/actions.go
internal/engine/actions/alert/security_advisory/security_advisory.go
internal/engine/actions/remediate/pull_request/pull_request.go
internal/engine/errors/errors.go
internal/engine/eval_status.go
internal/engine/executor_test.go
internal/engine/interfaces/interface.go

The rule engine has a copy of the previous evaluation state as part of its context. Prior to this PR, if there is no previous state for a rule/entity pair, an empty struct would be passed around. This requires each part of the code which uses the previous state (particularly remediations and alerts) to test if the fields in the state struct are the default value. This problem was highlighted in PR #4089 when the types of some the fields changed, requiring the code to be changed to have different default checks.
This PR changes the logic so that a nil pointer is returned if there is no existing state. This makes the check for a lack of previous state to be consistent irrespective of the fields needed or their type.
***Provide a brief overview of the changes and the issue being addressed. …

Use nil evaluation state if there is no previous evaluation

---

cmd/dev/app/rule_type/rttst.go
database/mock/store.go
database/query/profile_status.sql
database/query/repositories.sql
internal/controlplane/handlers_evalstatus.go
internal/controlplane/handlers_evalstatus_test.go
internal/controlplane/handlers_profile.go
internal/db/profile_status.sql.go
internal/db/profiles_test.go
internal/db/querier.go
internal/db/repositories.sql.go
internal/engine/actions/actions.go
internal/engine/actions/alert/security_advisory/security_advisory.go
internal/engine/actions/remediate/pull_request/pull_request.go
internal/engine/errors/errors.go
internal/util/cli/table/simple/simple.go

Out of the three commits which were reverted, one of them was replaced by #4197 which solves the problem at source. This will undo the other two. Some changes were made to fit with the changes introduced by #4197 
Validated against smoke tests by @rdimitrov. I also ran the failing smoke tests against this branch locally.

Reapply reverted commits

---

database/mock/store.go
database/query/entities.sql
internal/db/entities.sql.go
internal/db/querier.go

- **Add the sqlc-generating comment to GetEntityByName** - We forgot the comment that makes sqlc generate the code.
- **Do not lowercase when searching an entity by name** -  I don't think lowercasing is the responsibility of the database layer, it should be the provider who should return the entity information lowercased through the naming interface.
in follow up code, right now the code is unused

Two fixes for GetEntityByName

---

cmd/server/app/history_purge_test.go
cmd/server/app/migrate_up.go
database/migrations/000095_eval_central_entities.down.sql
database/migrations/000095_eval_central_entities.up.sql
database/mock/store.go
database/query/eval_history.sql
internal/db/eval_history.sql.go
internal/db/eval_history_test.go
internal/db/models.go
internal/db/profiles_test.go
internal/db/querier.go
internal/db/repositories_test.go
internal/history/service.go

This starts populating the relevant data so we can migrate to using the
central table in a further increment. Note that this is merely adding data
and not changing any logic as of yet. The idea is to start populating
and get us to a point where we can remove the NULL constraint.
Fixes https://github.com/stacklok/minder/issues/4170

Add reference to central entities table in new rule eval history tables

---

internal/engine/eval/vulncheck/pkgdb.go
internal/engine/eval/vulncheck/pkgdb_test.go
internal/engine/eval/vulncheck/vulndb.go
internal/engine/eval/vulncheck/vulndb_test.go
internal/engine/ingester/diff/parse.go
internal/engine/ingester/diff/parse_test.go

The PyPI specification states that python package names should be normalized https://packaging.python.org/en/latest/specifications/name-normalization/#name-normalization.
The package names in `requirements.txt` do not necessarily adhere to the normalization rules, but the response from OSV does. 
This was causing our PR review handler to fail in some cases, because it could not figure out which line in the diff needed to be changed, since there was no exact match.
This changes the matcher to use normalized names when looking for PyPI dependencies in the PR diff.
Fixes #2605

Consider that pypi package names may be normalized

---

internal/providers/dockerhub/dockerhub.go
internal/providers/github/entity_name.go
internal/providers/github/ghcr/ghcr.go
internal/providers/github/mock/github.go
internal/providers/github/properties.go
internal/providers/gitlab/gitlab.go
internal/providers/selectors/mock/interface.go
internal/providers/selectors/selector_entity_test.go
internal/providers/testproviders/git.go
internal/providers/testproviders/rest.go
pkg/providers/v1/providers.go

entity names are provider specific. This makes it so that providers must
have an interface to name an entity so it can be set in the properties
and ultimately stored in Minder.
Closes: #4166

Add interface for the provider to get a name for an entity

---

cmd/cli/app/provider/provider_enroll.go
cmd/server/app/history_purge_test.go
database/query/eval_history.sql
internal/crypto/nonce.go
internal/db/embedded/testdb.go
internal/db/entity_execution_lock.sql_test.go
internal/db/eval_history.sql.go
internal/engine/ingester/diff/diff.go
internal/history/service.go
internal/util/cli/styles.go
internal/util/helpers.go
internal/util/rand/random.go

The new version of golangci introduces integer overflow checks. A number of such issues were reported in Minder upon update.
Fixed through a mixture of type changes, explicit checks, and ignoring the linter in places where I was confident that we would never hit an overflow in practice.

Fix integer overflow lint errors

---

database/migrations/000097_entity_instance_not_null.down.sql
database/migrations/000097_entity_instance_not_null.up.sql
database/query/entity_execution_lock.sql
internal/db/entity_execution_lock.sql.go
internal/db/entity_execution_lock.sql_test.go
internal/db/eval_history.sql.go
internal/db/eval_history_test.go
internal/db/models.go
internal/db/profiles_test.go
internal/eea/eea.go
internal/eea/eea_test.go
internal/history/service.go

These were nullable as we were introducing them into minder. Now that
we've ensured they're everywhere, we can enforce them as not null.
Fixes #4219

Enforce central entity ID in EEA and rule eval tables

---

database/migrations/000098_properties_id_gen_default.down.sql
database/migrations/000098_properties_id_gen_default.up.sql

We don't want to put the onus on the user to generate the ID.
as part of a larger branch

Generate default ID for properties, ensure the ID is not NULL

---

config/server-config.yaml.example
internal/controlplane/handlers_oauth.go
internal/controlplane/handlers_oauth_test.go
internal/providers/github/common.go
internal/providers/github/mock/common.go
internal/providers/github/service/mock/service.go
internal/providers/github/service/service.go
internal/providers/github/service/service_test.go

This PR addresses the issue #2723 . When enrolling a provider, the owner flag is not validated. Incase the owner flag is invalid or the token has no access to the owner/organization during provider enrollment, the repo registration will fail which is a later step in the process. The change includes checking for a valid GH organization (passed as owner flag) that matches the owner flag and ensure the token has access to the GH organization.
I created a type struct to make Git API calls prior to actual provider enrollment flow, also created an interface to be able to mock the tests. …

Add owner flag validation during provider enrollment

---

database/migrations/000099_eea_entity_instance_idx.down.sql
database/migrations/000099_eea_entity_instance_idx.up.sql
database/mock/store.go
database/query/entity_execution_lock.sql
internal/db/entity_execution_lock.sql.go
internal/db/querier.go
internal/eea/eea.go
internal/engine/eval_status.go
internal/engine/executor.go
internal/engine/executor_test.go
internal/engine/interfaces/interface.go

This replaces the logic from the EEA from the convoluted per-entity
column to use a single reference from the central entitites table.
Closes: https://github.com/stacklok/minder/issues/4168

Use central entities table for EEA logic

---

.goreleaser.yaml

Ozz noticed that we hadn't included the sigstore certs needed to validate our signatures.  Since we're using keyless signing, we make up public and private keys for the certificate on the spot, so we need to store the public key after the signing, or the signature is useless.  It [appears that we may need the `certificate` field set](https://goreleaser.com/customization/sign/#usage) to upload these certs.
A few grumpy-man-yelling-at-clouds issues:
1. From the [action output](https://github.com/stacklok/minder/actions/runs/10484616388/job/29039268397), it appears that we go and get a new certificate for _each_ artifact, rather than using one cert to sign all the artifacts.
2. Actually verifying the blobs with `cosign verify-blob` is not well documented; I used something like:
```
cosign …
```

Add certificate definition to upload sigstore cert(s) from cosign

---

cmd/dev/app/rule_type/rttst.go

This is needed for it to work... as it seems the viper name has clashed
with other subcommands in that binary.

Make `ruletype test` token's viper path unique

---

internal/entities/properties/properties.go
internal/entities/properties/properties_test.go

We started using structpb.Value to hold the payload of our properties,
but since the Value type is expected to be directly serialized to a JSON
value, all numerical values are treated as float64.
Because we also want to store int64 values, we need to treat them
separately, by storing them as objects instead with the integer value
stringified.
Related: #4171
mostly unit tests

Handle int64 and uint64 in properties by wrapping it

---

internal/entities/properties/properties.go
internal/entities/properties/properties_test.go

Uses the new Go 1.23 feature to implement an iterator over properties.
This will simplify the future code.
Related: #4171
part of a larger branch

Add an Iterator over Properties

---

database/query/entities.sql
internal/db/entities.sql.go
internal/db/entities_test.go

Our database getter wouldn't handle the case where different entities
have the same name. Let's add the entity type as a parameter for the
getter.
Related: #4171
make test + part of a larger branch

GetEntityByName must accept the type, too

---

database/migrations/000100_rule_type_add_state_column.down.sql
database/migrations/000100_rule_type_add_state_column.up.sql
internal/db/models.go
internal/db/rule_types.sql.go

The new `release_phase` column of `rule_type` table contains release phase information about the rule type, being one of `alpha`, `beta`, `ga`, or `deprecated`. The available states are defined as an enumerated type.
Fixes #4242
Fixes #4243
Manually tested up and down migration.

Add `release_phase` column to `rule_type` table.

---

cmd/cli/app/ruletype/common.go
cmd/cli/app/ruletype/ruletype_create.go
cmd/cli/app/ruletype/ruletype_list.go

CLI commands `minder ruletype list`, `minder ruletype get`, and `minder ruletype create` now show release phase information if available.
Fixes #4244 
Manual tests.

Show rule type release phase.

---

internal/controlplane/handlers_entities.go
internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go
internal/reconcilers/entity_add.go
internal/reconcilers/entity_add_test.go
internal/reconcilers/entity_delete.go
internal/reconcilers/entity_delete_test.go
internal/reconcilers/messages/messages.go

Webhook handlers should pack all the necessary information to allow Minder Core to process creations, deletions, and reconciliations of entities, regardless of their kind. To achieve extensibility, (a) entities cannot be part of the message topic used for communication, and (b) messagess cannot be tied to specific entities.
To achieve that, reconciler handlers must dispatch an event to provider-specific code, shipping the minimal mandatory information explicitly (i.e. project id and provider id), and entity specific information in an opaque, provider-specific way.
This change introduces a bit of boilerplate to decouple message handling from provider-specific code, but does not move the code from the reconciler to the provider.
Fixes #4247 …

Decouple minder core from entities.

---

internal/engine/ingester/rest/rest.go
internal/entities/checkpoints/checkpoints.go
internal/entities/checkpoints/checkpoints_test.go

This adds the URL and HTTP method to the checkpoint information. This is
handy to know what path, method and even API version was used at a given
time when evaluating an entity.

Checkpoint: Add HTTP URL and Method to HTTP/REST ingester

---

cmd/cli/app/ruletype/common.go
cmd/cli/app/ruletype/ruletype_list.go

The following PR shows the `can_remediate: false` property in the `ruletype list, apply and create` tables. The table from `ruletype get` is different (row based) and we already show `Remediate: unsupported`. This is shown in case the ruletype has an empty/null `Remediation` field in its Def section (which in practice means no remediation support).
Fixes #4240 

Show can_remediate: false for the ruletype cli commands

---

database/query/entity_execution_lock.sql
internal/db/entity_execution_lock.sql.go
internal/db/entity_execution_lock.sql_test.go
internal/eea/eea.go

This removes the usage of the per-entity tables from the EEA queries to
rely solely on the entity instances table. A further PR will remove the
columsn from that table.
Related-to: #4169

EEA: Rely solely on entity instances table

---

cmd/cli/app/profile/table_render.go
internal/controlplane/handlers_profile.go
internal/util/cli/table/simple/simple.go

Add the rule display name to the detailed profile status table view.
Also, remove the rule ID from this view to make more room.
Ref #4251

Add rule display name to profile status table

---

go.mod
go.sum
internal/controlplane/handlers_ruletype.go

We're currently treating `guidance` as a plain string, storing it unmodified.
This change introduces some controls ensuring that guidance is valid markdown before storing it in the database. Since any valid UTF-8 string is valid markdown, the check is a bit redundant at the moment and ensures that it is parseable and renderable as HTML.
Additionally, we limit its size to 10kB, which is far more than enough given the current rule types have a `guidance` field shorter than 1kB.
Fixes #4286
Manual tests.

Validate rule type `guidance` as markdown.

---

database/mock/store.go
database/query/entitlements.sql
database/query/profiles.sql
database/query/repositories.sql
internal/controlplane/handlers_projects.go
internal/db/entitlements.sql.go
internal/db/profiles.sql.go
internal/db/querier.go
internal/db/repositories.sql.go
internal/logger/telemetry_store.go
internal/logger/telemetry_store_test.go
internal/projects/deleter.go
internal/projects/deleter_test.go

In order for us to be able to calculate customer churn, we need to keep track of the deleted projects/accounts on Minder and the relevant metadata from a business perspective.
Fixes https://app.zenhub.com/workspaces/minder-sprints-666857b34fcef725d2efba7c/issues/gh/stacklok/infra/1906

Project deletion metadata audit log

---

database/migrations/000102_properties_upstream_id_index.down.sql
database/migrations/000102_properties_upstream_id_index.up.sql
database/mock/store.go
database/query/entities.sql
internal/db/entities.sql.go
internal/db/entities_test.go
internal/db/entity_helpers.go
internal/db/projects_test.go
internal/db/querier.go
internal/db/store.go

Adds a utility database function to search entities by ID. Because we
store entity properties as JSON, we add a GIN index.
Testing with 50.000 entities we get the following performance:
```
Nested Loop  (cost=30.39..109.45 rows=5 width=87) (actual time=0.290..0.292 rows=1 loops=1)
->  Bitmap Heap Scan on properties p  (cost=30.10..67.90 rows=5 width=16) (actual time=0.216..0.218 rows=1 loops=1)
"        Recheck Cond: (value @> '{""value"": ""MBymWMNbcv"", ""version"": ""v1""}'::jsonb)"
Filter: (key = 'upstream_id'::text)
Heap Blocks: exact=1
->  Bitmap Index Scan on idx_properties_value_gin  (cost=0.00..30.10 rows=10 width=0) (actual time=0.174..0.175 rows=1 loops=1)
"              Index Cond: (value @> '{""value"": ""MBymWMNbcv"", ""version"": ""v1""}'::jsonb)"
->  Index Scan using …
```

Get entity by attribute

---

internal/db/entities_test.go
internal/db/projects_test.go

I instrumented one of the tests to inject a lot of entries to measure DB
query performance. I then promptly submitted the code without removing
it.
make test

Remove test code from..tests.

---

database/migrations/000103_eea_rm_per_entities_columns.down.sql
database/migrations/000103_eea_rm_per_entities_columns.up.sql
internal/db/entity_execution_lock.sql.go
internal/db/models.go
internal/eea/eea.go
internal/eea/eea_test.go
internal/eea/entities.go
internal/engine/entities/entity_event.go

Now that the queries aren't using it and the main logic actually uses
the central entity instances table, we can drop these.
Closes: https://github.com/stacklok/minder/issues/4169

Finally remove per-entity columns from EEA

---

go.mod
internal/controlplane/handlers_ruletype.go
internal/controlplane/handlers_ruletype_test.go
internal/ruletypes/mock/fixtures/service.go

This change uses `bluemonday` library to perform strict validation of `guidance` field of rule types. In case sanitized input is different from the input itself, rule type creation/update is rejected returning a meaningful error message.
The way input is sanitized is in line with the way it is rendered in the CLI by the `glamour` library.
Manual tests.

Validate rule `guidance` strictly.

---

internal/reconcilers/repository.go
internal/reconcilers/run_profile.go

Refreshing the repositories ensures that when the requests get to the
executor, the properties will have been fetched.
Related: #4173
manual

Refresh properties before reconcile and profile init

---

internal/profiles/service.go

We would return a UserVisibleError when updating selectors, but then
overwrite it in the caller who caled the validation, which resulted in
the server returning a 500 HTTP code to the client.
```
curl -XPUT -vv -H "Authorization: Bearer $MINDER_BEARER_TOKEN" 'http://localhost:8080/api/v1/profile' --data-binary @/Users/jakub/devel/playground/selectors/repro.json
```

Don't overwrite UserVisibleError when updating selectors fails

---

cmd/cli/app/ruletype/common.go

We recently added the possibility to display `can_remediate` and `release_phase` pills, if available, near to rule type name. If no pills were available, we erroneously displayed `()`.
Manual tests.

Fix rule type name that has no pills.

---

internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go
internal/controlplane/handlers_oauth_test.go
internal/controlplane/handlers_ruletype_test.go
internal/controlplane/server.go
internal/controlplane/server_test.go
internal/providers/github/mock/fixtures/github.go
internal/providers/github/properties.go
internal/providers/github/properties/fetcher.go
internal/providers/github/properties/pull_request.go
internal/providers/github/properties/repository.go
internal/service/service.go

- **Slight generalization of the GH property fetching** - The implementation of FetchProperty and FetchAllProperties for GitHub was not generic enough as it required that the properties contain the `name` key. For some properties, like pull request, the provider must fetch by other keys, so let's just pass the properties to the wrapper and let the wrapper error out if the get-by-properties don't contain the necessary data for fetching the property.
Also moves the propertyOrigin struct to the generic fetcher.go source to make it clearer that it's to be reused by other entities. Finally the `AllPropertyWrappers` and `WrapperForProperty` methods are now implemented by a common structure that the per-entity structures just embed to reduce code duplication.
- **Add a pull request entity module …

Handle pull requests as general entities

---

database/query/entities.sql
internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go
internal/db/entities.sql.go
internal/db/entities_test.go
internal/entities/properties/service/mock/service.go
internal/entities/properties/service/service.go
internal/entities/properties/service/service_test.go
internal/repositories/github/service.go
internal/repositories/github/service_test.go

The `entity_instances` table has the following index:
```
UNIQUE(project_id, provider_id, entity_type, name)
```
let's pass in the provider ID to take the index into account
make test

Pass Provider ID to the GetEntity calls from the provider service

---

internal/controlplane/handlers_githubwebhooks.go
internal/providers/github/properties/pull_request.go

- **Save the refreshed PR properties, not the lookup ones** - I mixed up the properties that we use to look up the PR and those that we actually fetch from the provider. Let's save those that we use to look up the PR to ensure that we have all the data available. In this particular case, we were missing the SHA.
- **GitHub's PR number is not int64, but our protobuf is** - Our protobuf defines the PR number as int64, but I didn't notice that the GH API returns the PR number as plain int. It's easiest to upcast the GH value to int64.
manually followed the steps in our smoke tests

Fix two bugs in PR properties

---

internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go
internal/providers/github/properties.go
internal/providers/github/properties/artifact.go
internal/providers/github/properties/fetcher.go
internal/providers/github/properties/pull_request.go
internal/providers/github/properties/repository.go

- **Add isOrg to the property wrapper signature** - The wrapper for artifacts will call a different github provider call depending on whether we need to fetch an property for a user artifact or an organizational artifact. Let's extend the wrapper with a bool to allow that.
- **Add property fetching for artifacts** - Adds the properties that will be fetched and stored for artifacts as well as the wrapper fetching it.
- **Use properties for artifacts in the github webhook** - Amends the webhook code to refresh artifact properties in the webhook handler and store them for later use.
Fixes #4399
manual + make test. Will run the smoke tests

Store properties for artifacts

---

internal/controlplane/handlers_evalstatus.go

We were not returning user visible errors, making it hard for the user to understand what was wrong with the input.
Manual tests.

Improve errors returned by history list endpoint.

---

cmd/server/app/history_purge_test.go
database/migrations/000104_rm_one_entity_id_constraint.down.sql
database/migrations/000104_rm_one_entity_id_constraint.up.sql
database/mock/store.go
database/query/eval_history.sql
database/query/profile_status.sql
database/query/repositories.sql
internal/controlplane/handlers_evalstatus.go
internal/controlplane/handlers_evalstatus_test.go
internal/controlplane/handlers_profile.go
internal/db/eval_history.sql.go
internal/db/eval_history_test.go
internal/db/profile_status.sql.go
internal/db/profiles_test.go
internal/db/querier.go
internal/db/repositories.sql.go
internal/db/repositories_test.go
internal/db/store.go
internal/engine/eval_status.go
internal/engine/executor_test.go
internal/entities/models/models.go
internal/entities/properties/service/mock/service.go
internal/entities/properties/service/service.go
internal/history/mock/service.go
internal/history/models.go
internal/history/service.go
internal/history/service_test.go
internal/repositories/github/service.go
internal/service/service.go

This is another step into moving away from the central entity tables and
into the new per-entity tables.
Fixes #4316

Decouple legacy entity tables from results queries

---

internal/controlplane/handlers_evalstatus.go
internal/entities/properties/properties.go
internal/entities/properties/properties_test.go
internal/entities/properties/service/service.go
internal/entities/properties/service/service_test.go

- **Add a setter for properties** - Adds a utility function to set a property so that we don't have to construct a map to construct properties to merge properties.
- **Derive the name property from entity name for entities that have not migrated fully** - We have entities in the database that have an entity instance, but no corresponding property because they have not been migrated properly. In that case, we can't use properties to refresh the entity because the properties are not there. The entity itself has a name, though, so let's use it to backfill the name property so that the properties object can always be used to refresh the rest.
- **Improve error message** - This would actually tell us what entity failed to refresh
unit tests

Fix entity refresh for entities that have not been migrated

---

internal/providers/github/properties/artifact.go

If the artifact name had contained a slash, we would have failed to
parse it. Treat the owner as what's up to the first slash and the rest
as the artifact name.
I used this artifact for testing: https://github.com/jakubtestorg/demo-repo-go/pkgs/container/demo-repo-go%2Fimage

Fix splitting artifact name property

---

internal/reconcilers/entity_delete.go
internal/reconcilers/entity_delete_test.go

We've seen this in minder cloud staging:
```
587a40169630","topic":"internal.entity.delete.event","handler":"github.com/stacklok/minder/internal/reconcilers.(*Reconciler).handleEntityDeleteEvent-fm-internal.entity.delete.event","component":"eventer","Timestamp":1725611382257727611,"message":"Found
error handling message"}
{"level":"error","component":"watermill","exception.message":"error
deleting repository from DB: error retrieving repository
e0e9fdde-bb2d-4a1d-9e0f-b8f5c006b42a in project
a5d7a1e4-f6a9-4282-8cc6-1a0e1613d1ae: sql: no rows in result
set","retry_no":3,"max_retries":3,"wait_time":0,"elapsed_time":105398463,"Timestamp":1725611382257739431,"message":"Error
occurred, retrying"}
```
added a unit test

Ignore sql.ErrNoRows on deleting repos by ID

---

docker/minder/Dockerfile
docker/reminder/Dockerfile
go.mod
tools/go.mod

When I upgraded to 1.23.0, I forgot to upgrade tools. Let's migrate to
the latest version and also upgrade the version for tools at the same
time.
The SHAs in Dockerfiles were generated by:
```
frizbee image golang:1.23.1
```
make build, make bootstrap, make run-docker

Bump Go to 1.23.1 including tools

---

internal/logger/logger_setup.go

We don't print log lines, yet go requires a fair amount of code duplication, making it harder to find the impacted code.
This change configures the logger to always log line numbers in log messages.
Manual tests.

Report line numbers in log messages.

---

cmd/server/app/webhook_update.go
internal/controlplane/handlers_oauth_test.go
internal/controlplane/handlers_providers_test.go
internal/engine/executor_test.go
internal/providers/manager/manager.go
internal/providers/manager/manager_test.go
internal/providers/ratecache/cache.go
internal/service/service.go
internal/util/cache/cache.go
internal/util/cache/expiration_cache_test.go
internal/util/cache/expirationcache.go

This generalized the expiration cache that was first introduced for REST
clients and introduced it as a general caching mechanism.
Subsequently, this was used to implement a 1 min cache for provider
fetching. This optimizes for cases where the provider is fetched
frequently for a single operation. Now there's no need to go multiple
times to the database.
Fixes #4391

Implement caching of providers on the provider manager

---

internal/controlplane/handlers_user.go
internal/controlplane/handlers_user_test.go
internal/projects/creator.go
internal/projects/creator_test.go

On the first user registration, a provider entry is created in the database. Although, the provider cannot be used to register repos due to the lack of credential. As part of this change, the default provider will not be created and user will continue with provider enroll step.
#4213 
After the first user login, verify the provider list returns empty. Continue with provider …

Don't pre-create github provider on registration

---

internal/crypto/nonce.go
internal/db/embedded/testdb.go
internal/entities/properties/properties.go
internal/events/eventer_test.go

Fix errors like https://github.com/stacklok/minder/actions/runs/10780415122/job/29912980252?pr=4382
Read the errors and fixed them.

Fix golangci-lint warnings

---

internal/entities/properties/properties.go
internal/entities/properties/properties_test.go
internal/entities/properties/service/service.go
internal/providers/github/properties.go
internal/providers/github/properties/artifact.go
internal/providers/github/properties/artifact_test.go
internal/providers/github/properties/repository.go

We had difficulties locating bugs because we didn't have enough insight
into what properties are being used and what is being called. Let's add
some more debugging.
manual

Add better debugging to the properties service and fetcher

---

internal/controlplane/handlers_evalstatus.go
internal/controlplane/handlers_profile.go
internal/entities/properties/service/service.go
internal/entities/properties/service/service_test.go
internal/repositories/service.go

- **Don't fail if lookupProperties include upstream ID but the entity does not** - We recently enhanced the property service to include lookup by ID in the cache, which is great, but we didn't handle the case where the lookup properties included the upstream ID but the entity properties in the database did not. In that case we should fall back to looking the property by name.
- **Don't return provifv1.ErrEntityNotFound from the property service** - It was irritating to have to handle two return codes. The caller really doesn't care why was the entity not found, just that it was not found.  Let's conver the provider NotFound into service Not found so that the callers have one less error to handle.
Fixes #4431
I added a unit test. I need to …

Fix retrieving properties by upstream ID and name

---

internal/providers/gitlab/gitlab.go
internal/providers/gitlab/properties.go
internal/providers/gitlab/properties_test.go

This adds a simple implementation of getting the name for an entity
based on given properties. This also introduces the first properties for
the GitLab provider, which are the group and project.
Related-To: https://github.com/stacklok/minder/issues/4331

Implement getting entity name for gitlab provider

---

internal/providers/github/common.go
internal/providers/github/properties/artifact.go

For some reason, the Go github API doesn't escape package names when
listing user packages:
https://github.com/google/go-github/blob/662da6f8e9f32b7da649ad0bfac19948e5acdd85/github/users_packages.go#L58
but does so when listing org packages:
https://github.com/google/go-github/blob/662da6f8e9f32b7da649ad0bfac19948e5acdd85/github/orgs_packages.go#L48
This tripped us up when trying to refresh properties of a package that
belonged to a user and had e.g. a slash in the name.
It seems that evaluating these packages did not work since we upgraded to
github-go v60 as we had the same bug in the ingester and the properties
changes just made the bug more prominent in the sense that it would manifest
already in the handlers.
Fixes: #4444
Using a fork of https://github.com/ethomson/calculator

The Go GitHub API doesn't seem to escape user package names, only org package names

---

internal/providers/github/installations/installations.go

This change increases the timeout when deleting installations from 30 seconds to 1 minute.
Manual tests.

Increase timeout when deleting installations.

---

go.mod
go.sum
internal/providers/gitlab/gitlab.go
internal/providers/gitlab/properties.go
internal/providers/gitlab/properties_test.go
internal/providers/gitlab/repository_properties.go

This does a very basic implementation of fetching the base propertiesf
or a repo in gitlab.
Closes: #4330

Implement properties fetch for GitLab

---

.github/dependabot.yml

We had issues where we pushed an update of a single otel library without
updating the rest. This should make sure we update them in lockstep.
N/A but hopefully we get a PR soon as we are behind the otel versions

Group otel dependency updates into single PRs

---

internal/controlplane/handlers_evalstatus.go
internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go
internal/controlplane/handlers_profile.go
internal/entities/properties/service/helpers.go
internal/entities/properties/service/mock/service.go
internal/entities/properties/service/service.go
internal/entities/properties/service/service_test.go
internal/history/service.go
internal/history/service_test.go
internal/repositories/service.go
internal/repositories/service_test.go

- **Pass a transaction handle to RetrieveAllProperties and RetrieveAllPropertiesForEntity** - These interface methods wouldn't take transaction into account.
- **Call an explicit commit in ListEvaluationHistory handler** - We refresh the properties in the historical evaluation endpoint (which btw should just be temporary to convert from the old tables to the new general tables) and missed the fact that the handler starts a transaction and then always rolls back - that was probably a way to keep consistence.  This means that the transactions that refresh properties are rolled back and on next call fetched again. This hurts performance quite a bit on repeated listHistory calls.
Fixes: #4393
by calling the list history endpoint with expired entities

Handle calling the property service in transaction better

---

internal/controlplane/handlers_evalstatus.go
internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_profile.go
internal/engine/executor.go
internal/entities/properties/service/helpers.go
internal/entities/properties/service/mock/service.go
internal/entities/properties/service/options.go
internal/entities/properties/service/service.go
internal/entities/properties/service/service_test.go
internal/history/service.go
internal/repositories/service.go

Instead of passing the db store and other optional values as
explicit paramters, this introduces options to the properties service.
This allows us to start building queries in a more dynamic way.
The querier is passed always now as an option.
Disregarding stale data was introduced as an option, and it was also
used in the places it's needed, that is, in GET calls.

Add "options" to properties service calls

---

cmd/dev/app/rule_type/rttst.go
internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go
internal/entities/properties/service/mock/service.go
internal/entities/properties/service/service.go
internal/providers/github/entities.go
internal/providers/github/mock/github.go
internal/providers/github/properties/pull_request.go
pkg/providers/v1/providers.go

This will help us get rid of database and/or property calls in the
webhook handler.
Related: #4327
make test

Add a new ProtoMessageConverter provider interface to convert entities to typed protobuf messages

---

internal/controlplane/server.go
internal/providers/dockerhub/webhook.go
internal/providers/github/entities.go
internal/providers/github/manager/webhook.go
internal/providers/gitlab/manager/webhook.go
internal/providers/manager/manager.go
internal/providers/manager/mock/auth_manager.go
internal/providers/manager/mock/manager.go

This adds per provider class paths so each provider class will bring
it's own webhook handling. GitHub is a slightly special case... so we
handle it separately for now.
Note that this will require folks changing their configuration to remove
`github` as a suffix on deployments. If nothing is changed, this should
be a no-op as it does not re-append `github` in the path.
Related-To: #4329

Add general webhook registration mechanism

---

internal/controlplane/server.go

The slash was missing and is the reason we were getting:
```
2024/09/13 11:30:01 ERROR: Failed to extract ServerMetadata from context
```

Fix missing slash in github webhook path

---

internal/profiles/service.go
internal/profiles/util.go
internal/profiles/util_test.go

Currently, clients of the API are required to derive the profile name from the display name using various transformations. This results in duplicated logic across the ecosystem, increasing complexity and potential inconsistencies.
This commit scopes the logic to derive the profile name from the display name to the ProfileService.CreateProfile endpoint. By centralizing this logic, we reduce redundancy and simplify client code. Clients of the API are no longer need to implement logic to deriive the profile name when creating a new profile.
Fixes #2943 

Derive profile name from display name in `ProfileService.CreateProfile`

---

internal/providers/gitlab/gitlab.go
internal/providers/gitlab/gitlab_rest.go
internal/providers/gitlab/manager/manager.go
internal/providers/gitlab/properties.go
internal/providers/gitlab/properties_test.go
internal/providers/gitlab/repo_lister.go
internal/providers/gitlab/repository_properties.go

This adds the needed pieces for the GitLab provider to do entity
registration. In the case of repos, this was the implementation of the
repo lister trait.
Closes: https://github.com/stacklok/minder/issues/4331

Implement basic repo registration with gitlab

---

internal/repositories/service.go
internal/repositories/service_test.go

this may be a transcient error, so let's not fail and allow minder to
delete it.
This may result in a dangling webhook registration in github. Which is
not too problematic since Minder detects and is able to overwrite them.
Fixes: #3518

Don't fail on deregistering a repo on repo delete

---

docs/docs/how-to/profile_selectors.md

Fix some minor typos on the profile selectors documentation page.

Fix typos in profile selectors doc

---

docs/docs/understand/rule_evaluation.md

The new rule evaluations page added in #4481 has three links to the secret_scanning rule page that are missing the .md extension. These worked in the minder-docs.stacklok.dev build but caused the Docusaurus build to fail on a broken link error for the cloud docs overlay.
Confirmed links are working via local preview.

Add missing extension to docs links

---

database/migrations/000106_ancillary_evaluation_indexes.down.sql
database/migrations/000106_ancillary_evaluation_indexes.up.sql

Provider deletion, or entity deletion in general, runs into performance problems without this indexes as two triggers for constraint were executing full table scans on pretty crowded tables.
These two indexes solve that problem.
Tested in sandbox.

Add ancillary indexes to improve deletion.

---

internal/engine/entities/entity_event.go
internal/engine/entities/entity_event_test.go

These will make it easier to construct EntityInfoWrapper messages from
the new entity handlers.
Related: #4327
make test + part of a larger branch

Add two more generic methods for EntityInfoWrapper

---

internal/engine/actions/alert/security_advisory/security_advisory.go

Fixes https://github.com/stacklok/minder/issues/4349
Use shortfailure message for an alert title.

Use shortfailure message for alert title

---

cmd/cli/app/provider/provider_get.go
cmd/cli/app/provider/provider_list.go
cmd/cli/app/repo/repo_reconcile.go
cmd/cli/app/repo/repo_register.go
cmd/dev/app/image/list.go
cmd/dev/app/image/list_tags.go
cmd/server/app/history_purge.go
cmd/server/app/history_purge_test.go
internal/auth/keycloak/keycloak_test.go
internal/authz/mock/noop_authz.go
internal/controlplane/handlers_providers_test.go
internal/engine/eval/eval.go
internal/engine/eval/homoglyphs/application/homoglyphs_service.go
internal/engine/eval/homoglyphs/application/mixed_scripts_eval.go
internal/engine/eval/homoglyphs/domain/mixed_scripts.go
internal/engine/eval/homoglyphs/domain/mixed_scripts_test.go
internal/engine/eval/vulncheck/vulncheck.go
internal/providers/credentials/github_installation_token_credential.go
internal/providers/manager/manager_test.go

I noticed a lot of usages of `fmt.Printf` or `fmt.Println` throughout
the codebase. While this does the trick, it loses a lot of context that
we'd ideally have.
This switches to using logging functions that keep context and give us
extra data that's useful for debugging.

Use appropriate logging functions were possible

---

internal/engine/eval/vulncheck/report.go
internal/engine/eval/vulncheck/review.go
internal/engine/eval/vulncheck/review_test.go

When replying to a single line, github always prepends the context "before"
the line unless replying with a suggestion. This gets confusing when replying
to a line deeper in a diff especially the last line as we can't pinpoint a
single line to reply to.
To improve the UX a little bit, we include the package name with the
package we are replying to so that the user can tie the comment better
to the actual line.
Pair-Programmed-With: Michelangelo Mori <mmori@stacklok.com>
Fixes: #4529 
manual

Include the name of the package for which we couldn't find a fix

---

internal/engine/eval/trusty/actions.go

Some trailing `</details>` tag in trusty PR comments were misplaced because they were missing a `\n` before them, causing the dependency list to be a tree instead.
Manual tests.

Fixed wrong indentation of HTML in PR comments.

---

docs/docs/how-to/profile_selectors.md
internal/providers/github/properties/pull_request.go

This allows us to write selectors like:
```
selection:
- entity: pull_request
selector: pull_request.properties['github/pull_author_login'] != 'jhrozek'
comment: "We trust Jakub. Don't check his PRs"
```
manually

Add github/pull_author_login as a property for PRs

---

internal/db/profile_selector_scan.go
internal/db/profile_selector_scan_test.go

`encoding/csv` allows us to handle selectors with commas in them which
our naive parser embarassingly didn't such as:
```
repository.properties['github/primary_language'] in ['TypeScript', 'Go']
```
Fixes: #4514
unit test plus using that selector

Use encoding/csv to when parsing selector record

---

internal/providers/dockerhub/dockerhub.go
internal/providers/github/entities.go
internal/providers/github/ghcr/ghcr.go
internal/providers/github/mock/github.go
internal/providers/gitlab/registration.go
internal/providers/selectors/mock/interface.go
internal/providers/selectors/selector_entity_test.go
internal/providers/testproviders/git.go
internal/providers/testproviders/rest.go
pkg/providers/v1/providers.go

This adds an interface that's meant to re-register an entity. This is
useful when updating a certain part of the entity registration. The only
use-case we have right now is secret rotation. So this is what was
effectively implemented.
This merely implemented the functions for the GitLab and GitHub
providers. The webhook update sub-command will be updated to take it
into use in a subsequent patch.

Add `ReregisterEntity` to provider interface

---

internal/controlplane/handlers_evalstatus.go
internal/controlplane/handlers_profile.go
internal/controlplane/handlers_providers_test.go
internal/engine/executor.go
internal/engine/executor_test.go
internal/entities/properties/service/helpers.go
internal/entities/properties/service/mock/service.go
internal/entities/properties/service/service.go
internal/entities/properties/service/service_test.go
internal/history/service.go
internal/history/service_test.go
internal/providers/github/manager/manager.go
internal/repositories/service.go
internal/repositories/service_test.go

When processing a webhook payload, we typically only have the
information from the webhook payload available which is to say
information about the upstream entity. We even don't know exactly which
provider and which project are we handling.
We used to sort of wing it in the github webhook handler and were just
searching by upstream ID as if it was globally unique, but that no
longer works with the introduction of multiple providers where several
entities might have the same upstream ID, just in different providers.
To handle that, we add a new method to the properties service that
searches by upstream ID with a hint. At the moment, the interface
supports providerID, projectID and provider implements as a hint.
The immediate use is that the github provider will search by the
upstream ID …

Add a method to retrieve an entity by upstream ID with a hint

---

database/mock/fixtures/store.go
internal/entities/handlers/handler.go
internal/entities/handlers/handler_test.go
internal/entities/handlers/message/message.go
internal/entities/handlers/message/message_test.go
internal/entities/handlers/strategies/entity/add_originating_entity.go
internal/entities/handlers/strategies/entity/common.go
internal/entities/handlers/strategies/entity/del_originating_entity.go
internal/entities/handlers/strategies/entity/get_by_upstream_props.go
internal/entities/handlers/strategies/entity/refresh_by_upstream_props.go
internal/entities/handlers/strategies/message/empty.go
internal/entities/handlers/strategies/message/entity_info_wrapper.go
internal/entities/handlers/strategies/message/minder_entity.go
internal/entities/handlers/strategies/strategies.go
internal/entities/models/models.go
internal/entities/properties/service/mock/fixtures/fixtures.go
internal/events/constants.go
internal/events/stubs/eventer.go
internal/service/service.go

These will be used in webhook handlers instead of calling the property
service directly. The handlers follow the same base logic, just with
"pluggable" ways of retrieving the entity, converting the entity to
properties and which handler to call next.
The test coverage is not great yet, but I did test the handlers manually
outside the tests I have in another branch and they seemed to work well.
I will be adding more tests as this PR is reviewed.
Related: #4327
some unit tests are added in this PR, but I'll add more. Most of the testing has been manual as part of another branch.

Add new watermill handlers that get or refresh entities by properties and call another handler

---

internal/events/nats/natschannel_test.go

While introducing the NATS driver is a gret idea and will allow us to
scale better, the tests are still a bit flaky and require us to
reschedule our CI tests quite often.
Let's disable them temporarily
Related: #4542
N/A

Disable the NATS tests temporarily again

---

internal/engine/errors/errors.go
internal/engine/errors/errors_test.go
internal/engine/eval/templates/templates.go
internal/engine/eval/templates/vulncheckTemplate.tmpl
internal/engine/eval/vulncheck/vulncheck.go
internal/engine/eval/vulncheck/vulncheck_test.go

This change extends error type available for use in evaluation engines with support for go templates. This error type supports rendering complex templates along with the usual string rendering. Despite the type itself being the same, a new constructor was added to avoid a bigger refactoring. Ideally, the old constructor should be deprecated and all places returning an `ErrEvaluationFailed` error should use the new one instead.
Templates are internal to Minder and cannot be customized by the end user. Also, template engine choice was arbitrary and can be changed at any time.
Fixes #4525
Fixes #4526
Unit tests.

Add template support to evaluation details.

---

internal/entities/handlers/message/message.go
internal/entities/handlers/message/message_test.go
internal/entities/handlers/strategies/entity/common.go

This will be useful for the gitlab provider
Fixes: #4557
make test

Add hint by provider class to the refreshAndDo handler

---

internal/providers/gitlab/manager/manager.go
internal/providers/gitlab/manager/webhook.go
internal/providers/gitlab/manager/webhook_handlers.go
internal/providers/gitlab/properties.go
internal/providers/gitlab/repository_properties.go
internal/service/service.go

This implements the initial event handling for Gitlab.
Fixes: https://github.com/stacklok/minder/issues/4329

Implement Gitlab event handling

---

cmd/dev/README.md
cmd/dev/app/rule_type/rttst.go
cmd/dev/examples/pull_request.yaml
cmd/dev/examples/repository.yaml
cmd/dev/examples/versioned_artifact.yaml
internal/entities/models/models.go
internal/entities/properties/properties.go
internal/entities/properties/properties_test.go

While working on the PR rule types (upcoming), I started to write my own tool before being reminded of `mindev`.  Our documentation had bit-rotted a little bit, but Jakub and Ozz helped straighten me out.
Manual test runs like the following:
```
TEST_AUTH_TOKEN="$(gh auth token)" go run ./cmd/dev ruletype test -e cmd/dev/examples/repository.yaml -p ../minder-rules-and-profiles/profiles/github/ghas.yaml -r ../minder-rules-and-profiles/rule-types/github/secret_push_protection.yaml
```

Update documentation for mindev, and add some handy debugging methods

---

internal/config/server/events.go
internal/events/sql/postgres.go

It turns out that Watermill SQL maintains an internal timeout on message delivery, and retries messages which take longer than the timeout.  On one hand, this feels like good infrastructure practice, but it interferes with related Watermill middleware for retries and handling poison messages.  One example of this is `AckDeadline`:
> AckDeadline is the time to wait for acking a message.
> If message is not acked within this time, it will be nacked and re-delivered.
>
> When messages are read in bulk, this time is calculated for each message separately.
>
> If you want to disable ack deadline, set it to 0.
> Warning: when ack deadline is disabled, messages which are not acked may block PostgreSQL subscriber from reading new messages
> due to not increasing …

Allow customizing AckDeadline to allow for long-running sets of retries

---

internal/entities/handlers/handler_test.go

We were passing around a pointer-to-data to a bunch of different tests, each of which did their own setup on the pointed-to data while declaring that they were `t.Parallel()`.
Everybody gets their own copy of the data!
```
WARNING: DATA RACE
Write at 0x000002a873d8 by goroutine 15:
github.com/stacklok/minder/internal/entities/handlers.buildEwp()
/home/runner/work/minder/minder/internal/entities/handlers/handler_test.go:124 +0x7e
github.com/stacklok/minder/internal/entities/handlers.TestRefreshEntityAndDoHandler_HandleRefreshEntityAndEval.func1()
/home/runner/work/minder/minder/internal/entities/handlers/handler_test.go:210 +0x6f
github.com/stacklok/minder/internal/entities/handlers.TestRefreshEntityAndDoHandler_HandleRefreshEntityAndEval.func7() …
```

Fix data race in internal/entities/handlers/handler_test.go

---

internal/engine/errors/errors_test.go
internal/engine/eval/templates/vulncheckTemplate.tmpl
internal/engine/eval/vulncheck/vulncheck_test.go

It currently looks weird in the UI, we'll get rid of them for now.
Unit tested.

Remove backticks in `vulncheck` details template.

---

identity/config/stacklok.yaml
internal/controlplane/identity_events.go
internal/controlplane/identity_events_test.go
internal/providers/gitlab/properties_test.go
internal/service/service.go

It turns out that users deleted through the Keycloak API don't show up in the "User Events" queue, but instead show up in a different "admin events" queue.  We should handle those deletions as well.
Fixes https://github.com/stacklok/minder-stories/issues/29
Manual testing and added a unit test.  Note that the code generally follows the same form as user events, but with a different schema and different URL endpoint.  I did not make a lot of effort to de-duplicate the two codepaths.

Handle users deleted through the Keycloak management API, as well as through the Keycloak UI

---

internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go

We added new watermill handlers that allow to refresh and evaluate a
generic entity with properties. This is the first patch in a series that
takes these handlers into account with the eventual goal of removing all
the bespoke code from the GitHub webhook handler and eventually remove
direct database access from the webhook handler.
I'll expand the same method for the other webhook events we issue, but
let's do small PRs so we can have some test runs in between them and
revert in case of issues.
Related: #4327
I ran a subset of smoke tests that target repos and made the unit tests pass.

Use the new handlers when evaluating repo webhooks

---

internal/db/otel_test.go

This change adds a test that tries to limit runtime panics in staging by checking some known cases that we encountered
recently. Unfortunately, testing cannot be extensive, but should prevent us from merging broken PRs from dependabot.
Fixes #4534
Unit tested.

Test otel instrumentation for panics.

---

internal/entities/properties/service/service.go
internal/providers/dockerhub/dockerhub.go
internal/providers/github/ghcr/ghcr.go
internal/providers/github/mock/github.go
internal/providers/noop/noop.go
internal/providers/selectors/mock/interface.go
internal/providers/selectors/selector_entity_test.go
internal/providers/testproviders/git.go
internal/providers/testproviders/rest.go
pkg/providers/v1/providers.go

We were doing a lot of repetition in our test providers, so this
implemented a `noop` provider that fills in the signature as needed.
This also moved the `EntityToProtoMessage` function to be a top-level
provider function in the interface. While this is temporary, it's useful
to know this needs to be defined while we move everything to the general
protobuf interface.

Clean up test providers and move `EntityToProtoMessage` as top-level interface function

---

internal/controlplane/handlers_oauth.go

As of today, we only store the access token and use that for provider
authentication. This ensures we're also persisting the refresh token and
expiry so we could leverage these in case re-authentication is needed.
Note that re-authentication will be handled in a separate PR.

Store provider's refresh token and expiry if possible

---

.github/dependabot.yml

This should make merging dependabot PRs about tracing easier to handle.

Group otel-related updates into single PRs.

---

internal/controlplane/handlers_providers_test.go
internal/providers/github/manager/manager.go

This separates the providers a little further by always assuming that if
the github app provider class is used, you should only check for the
github app credentials (which require an installation ID).
This will thus reduce the number of database calls we do when
instantiating the provider, since Minder will now do the right thing.

GitHub: don't try to use OAuth token for github-app provider

---

internal/providers/gitlab/manager/manager.go
internal/providers/gitlab/manager/manager_test.go

Gitlab uses shorter lived tokens than github, this adds the logic to
handle a token refresh.
At the moment this is done within the gitlab provider manager. While
this works for now, we might want to determine whether we make this a
more general pattern, or keep handling this within each provider.
Closes: #4605

gitlab: Handle token refresh

---

internal/entities/handlers/strategies/entity/refresh_by_upstream_props.go

When refreshing entity by upstream ID, we would have started a
transaction and passed the TX handle to the GetEntity call, but not to
the subsequent RetrieveAllPropertiesForEntity call.
this is covered by unit test + smoke tests

Pass along transaction to RetrieveAllPropertiesForEntity

---

internal/providers/gitlab/gitlab_rest.go
internal/providers/gitlab/gitlab_rest_test.go

This allows us to reliably pass query parameters in the gitlab REST
trait. Else, we'd get everything URL-encoded and it would not work.

gitlab: Handle query parameters in REST trait

---

internal/controlplane/handlers_reconciliationtasks.go
internal/entities/handlers/handler.go
internal/entities/handlers/handler_test.go
internal/entities/handlers/message/message.go
internal/entities/handlers/message/message_test.go
internal/entities/handlers/strategies/entity/refresh_by_id.go
internal/entities/properties/service/mock/fixtures/fixtures.go
internal/events/constants.go
internal/reconcilers/entity_delete_test.go
internal/reconcilers/messages/messages.go
internal/reconcilers/reconcilers.go
internal/reconcilers/repository.go
internal/reconcilers/repository_test.go
internal/reminder/messages/messages.go
internal/reminder/reminder.go
internal/reminderprocessor/reminder_processor.go
internal/repositories/service.go
internal/service/service.go

- **Rename WithOwner to WithOriginator** - We renamed Owner to Originator in the new refresh-and-do handlers, but forgot to rename the method that sets that attribute.
- **Add a new Get-By-ID-Refresh-And-Do handler** - Since we have the entity ID available, we don't need to refresh by upstream ID, but by entity ID. To do that, we add a new handler that does just that.
- **Use NewEntityRefreshAndDoMessage instead of calling RefreshRepositoryByUpstreamID in reconcilers** - Gets rid of the RefreshRepositoryByUpstreamID request that we are tryign to phase out in favour of the generic new handlers. This will also allow the reconcile handler to be useful for the github reconciler.
- **Handle messages with no entityID** - since we changed the format of the reconcile message, we check if the …

Remove RefreshRepositoryByUpstreamID from the repo reconciler

---

database/mock/fixtures/store.go
database/mock/store.go
database/query/entities.sql
internal/db/entities.sql.go
internal/db/entities_test.go
internal/db/querier.go
internal/reconcilers/run_profile.go
internal/reconcilers/run_profile_test.go

- **Use generic message forwarding to initialize the profile instead of entity-specific database searches** - Because we were bound to entity-specific protobuf types and didn't have a good way of iterating over all entities, we used to enumerate all repos and then all artifacts just to marshall them and send off to the evaluator. With generic entities we can simply enumerate all entities and send them off for refresh and forwarding to the evaluator.
Fixes: #4621
unit test + manually

Use generic refresh and message forwarding to evaluator for profile init

---

internal/entities/properties/service/helpers.go
internal/entities/properties/service/service_test.go

the `matchEntityWithHint` attempts to look for an entity using
identifying properties. For PRs, the upstream ID is not sufficient since
it's an integer that will clash with other PRs. In this case, we should
instead continue the search and search by name which is more unique.

properties service: Don't fail if multiple entries are found

---

internal/controlplane/handlers_profile.go

The `profile status list` subcommand uses properties to print out entity
info. Historically it was just using the GH specific properties. This
prints out the general name as well so this can work with Gitlab.

Print entity status name if available

---

internal/engine/eval/eval.go
internal/engine/eval/homoglyphs/application/homoglyphs_service.go
internal/engine/eval/homoglyphs/application/invisible_characters_eval.go
internal/engine/eval/homoglyphs/application/mixed_scripts_eval.go
internal/engine/eval/jq/jq.go
internal/engine/eval/rego/eval.go
internal/engine/eval/trusty/trusty.go
internal/engine/eval/vulncheck/vulncheck.go
internal/engine/executor.go
internal/engine/options/options.go
internal/engine/rtengine/cache.go
internal/engine/rtengine/engine.go
internal/flags/constants.go

This change adds feature flag `vulncheck_error_template`, which is currently used by the `vulncheck` evaluator to determine whether to produce "legacy" message format (i.e. comma separated list of package names) or markdown (i.e. unordered list of package names).
Additionally, this change adds support for options when creating new evaluation engines, making them easier to extend and possibly test.
The change is backwards compatible.
Manual tests.

Add feature flag for improved evaluation details.

---

internal/events/eventer.go
internal/events/gochannel/gochannel.go
internal/events/sql/postgres.go

In a couple cases, watermill was provided with its default logger which outputs unstructured strings.
This change configures `sql` and `go-channel` watermill drivers with a wrapped zerolog instance.
Manual tests.

Pass correct logger to watermill.

---

internal/controlplane/handlers_entities.go
internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go
internal/entities/handlers/strategies/message/minder_entity.go
internal/reconcilers/entity_add.go
internal/reconcilers/entity_add_test.go
internal/reconcilers/entity_delete.go
internal/reconcilers/entity_delete_test.go
internal/reconcilers/messages/messages.go

As a follow-up to this PR, I want to use the NewGetEntityAndDeleteHandler for handling repo deletions
and in general I want to get rid of calls to `fetchRepo()`. This is a prep PR that makes the
`MinderEvent` messages more generic and let them work with properties.
- **Remove unused setters of repoID attribute for entity reconciliation** - This just simplifies the code
- **Use minderv1.Entity instead of a string and check the entity type for repos** - Using just strings is error prone. We might need to revisit this as we make entities completely pluggable, but we're not there yet and I don't like to add strings comparison. At the same time I want to only run the entity_add handler on repositories.
- **Use generic properties instead of repoName/repoOwner when adding entities** - The …

Simplify the entity_add handlers in preparation for using the NewGetEntityAndDeleteHandler"

---

internal/entities/handlers/handler.go
internal/entities/handlers/handler_test.go
internal/entities/handlers/strategies/message/entity_info_wrapper.go
internal/entities/handlers/strategies/message/minder_entity.go

Since the github webhook handler won't have access to the properties and
the properties will be refreshed and read later on, we'd lose the
ability to not evaluate messages from private or archived repositories.
We do check for the private and archived flags at repo registration, but
since a repo can go private or be archived later, this is not enough.
Let's check for these properties after retrieving the entity and before
forwarding it on.
Fixes: #4666
I created a public repo then made it private.

Do not forward messages for archived and/or private repos

---

internal/reconcilers/entity_delete_test.go
internal/reconcilers/reconcilers.go
internal/reconcilers/repository.go
internal/reconcilers/repository_test.go
internal/reconcilers/run_profile_test.go
internal/service/service.go

The GitHub API doesn't allow us to list packages for repos, only for
organizations. We tried to work around that by listing packages for the
org and then filtering by the repository attribute, but this does not scale well.
Moreover, we agreed that going forward we'd like to register and enroll
packages in a similar way that we do register and enroll repositories.
Fixes: #4618
just made sure that repo register works.

Remove reconciling of artifacts during repo reconciliation

---

internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go

More bespoke code removal!
This time it comes with a caveat. Because we can't pass along the
version of the artifact, the artifact evaluator is going to evaluate all
artifacts. But I don't see any other way at the moment.
Fixes: #4667
manual + unit tests + I ran these two smoke tests
- `artifact_signature`
- `artifact_attestation_slsa`

Use the originating handlers for handling package published messages in the github webhook

---

internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go
internal/entities/handlers/handler_test.go
internal/reconcilers/entity_delete.go
internal/reconcilers/entity_delete_test.go
internal/service/service.go

- **Add test coverage for NewGetEntityAndDeleteHandler** - Before we enable this handler, let's add tests
- **Special case service.ErrEntityNotFound, not sql.ErrNoRows** - Since we switched to using entities, deleting a non-existent repository returns `service.ErrEntityNotFound`, not `sql.ErrNoRows`. Ignoring the wrong error code caused us to retry the message needlessly.
- **Drop the use of fetchRepo and its RefreshRepositoryByUpstreamID when deleting a repository** - This removes one more usage of the old handler and one more database access from the webhook handler.
Fixes: #4682
by adding and deleting repos and enrolling all repos

Drop the use of fetchRepo and its RefreshRepositoryByUpstreamID when deleting a repository

---

.trivyignore

Add `CVE-2024-47534` to trivyignore file

---

internal/util/safe_template.go
internal/util/safe_template_test.go

These are handy to deal with properties in protobufs within minder's
templates.

Add template mapping functions

---

cmd/cli/app/profile/table_render.go
go.mod
internal/profiles/util.go
internal/providers/gitlab/gitlab.go
internal/providers/gitlab/manager/webhook.go
internal/providers/gitlab/manager/webhook_handlers_releases.go
internal/providers/gitlab/properties.go
internal/providers/gitlab/release_properties.go

This adds preliminary support for the `Release` entity within the gitlab provider.
A release is based on a tag and has branch information (critical for remediating the flow).
Note that it requires https://github.com/stacklok/minder/pull/4704 to merge beforehand.

Gitlab: Add support for the `Release` entity

---

database/migrations/000107_entity_properties_timestamp_tz.down.sql
database/migrations/000107_entity_properties_timestamp_tz.up.sql

The Postgres `TIMESTAMP` type records a date and time irrespective of (ignoring) timezone.  This aligns with the SQL standard, but they also have a `TIMESTAMP WITH TIME ZONE` (aka `TIMESTAMPTZ`) which _is_ timezone aware.  It turns out that `lib/pq` (at least) _stores_ `time.Time` values into the database using local time for `TIMESTAMP` columns, but reads back the columns in the zero-timezone.  In PDT (UTC+7), this results in reading back times which are 7 hours later than when they were stored.  This mostly doesn't bother our code and tests at the moment, but it _does_ break tests in `internal/entities/properties/service`, which use `updated_at` as a cache validation mechanism.
This PR migrates the `TIMESTAMP` fields added in `000090` to `TIMESTAMPTZ` in a way which should avoid table …

Set entity columns to be 'timestamp with time zone' to avoid TZ-related test failures

---

internal/entities/models/models.go
internal/entities/properties/properties.go
internal/entities/properties/service/entitycache.go
internal/history/service.go

This adds a wrapper that is able to cache entities for cases that need
to iterate them. This is handy for one-off calls like getting the
history of executions or showing reports. This way, we don't need to
query the database multiple times.
This cache is persistent, so it's only relevant for one execution.

Implement an entity cache for the properties service

---

internal/engine/ingester/diff/diff.go

This was causing errors during evaluations of rules that cast `res.Object` like
https://github.com/stacklok/minder/blob/main/internal/engine/eval/homoglyphs/application/homoglyphs_service.go#L84
Manual tests.

Fix diff full ingester double deref.

---

internal/controlplane/handlers_evalstatus.go
internal/entities/properties/properties_test.go
internal/entities/properties/service/service_test.go

Adds a bunch of tests for the new property module (the arrow needs to keep pointing up :-))
and uses the module in ListEvaluationResults
Related: #4690
```
curl -XGET  -H "Authorization: Bearer $MINDER_BEARER_TOKEN" 'http://localhost:8080/api/v1/results?provider=github-app-jakubtestorg&context.project=88eb1151-5a5b-4c14-9c2e-2bc359c0db94&profile=f375e42e-07ff-4a2b-9f6c-ff98be57fc2c'
```

Use the new property cache in ListEvaluationResults

---

internal/controlplane/handlers_githubwebhooks.go
internal/controlplane/handlers_githubwebhooks_test.go
internal/entities/handlers/handler.go
internal/entities/handlers/handler_test.go
internal/entities/handlers/message/message.go
internal/entities/handlers/message/message_test.go
internal/entities/properties/properties.go
internal/entities/properties/properties_test.go

- **Add Property.Equal** - Comparing properties will be useful to check if a matching property is a subset of the retrieved properties.
- **Add WithMatchProps to the HandleEntityAndDoMessage** - We'll match the received entity on these properties
- **Don't forward entity if it doesn't match message.MatchProps** - After receiving an entity, check if the `message.MatchProps` map is set.  If yes, make sure that it is a subset of the properties of the entity just received. If it is not, drop the message.  This will allow us to restrict forwarding the message by properties set by the caller.
- **Use the handler forwarding to evaluate repository/meta messages** - Instead of fetching the repo directly in the handler and forwarding to a handler, create a NewEntityRefreshAndDoMessage message and …

Remove database use from handleRelevantRepositoryEvent

---

.github/dependabot.yml

Current dependabot configuration leaves out `.../otel` because it lacks the trailing slash.
Dependabot config.

Fix dependabot grouping of otel dependencies.

---

internal/controlplane/server.go
internal/logger/logging_interceptor.go

This change adds a GRPC interceptor that fetches the header `Grpc-Metadata-Request-Id` and adds it to the logger. It also returns the request id to the client in the header, which is helpful for debugging.
Fixes #4611 
Manual tests.

Add request id to logs.

---

cmd/cli/app/auth/auth_login.go
cmd/cli/app/quickstart/quickstart.go
cmd/cli/app/root.go
internal/util/cli/cli.go
internal/util/cli/rpc_client.go

This change adds a `-v/--verbose` flag that causes Minder CLI to output request ids to standard error.
It's worth noticing that some commands (e.g. `minder ruletype create` and `delete`) issue multiple calls to Minder BE and thus output request ids multiple times.
Fixes #4612
Manual testing.

Display request ids in the CLI.

---

.github/workflows/releaser.yml
.goreleaser.yaml
README.md
docs/docs/getting_started/install_cli.md

The following PR updates the release process so we no longer push a custom formula to `stacklok/tap`. Instead, we rely on brew's automation to catch the new release of the minder CLI and updates its entry in the `homebrew-core` repo. Currently this happens every 3 hours.
Related: https://github.com/mindersec/minder/issues/4753

Deprecate pushing a brew formula to stacklok/tap

---

.github/workflows/migrate-touch.yml

This reverts commit aaa57c7f5b707a003ce64aa2816dba495a89005c.
Following up to https://github.com/mindersec/minder/pull/4764, this PR restores the migration check workflow that was temporarily removed to help merge the boilerplates.

Revert "Temporarily remove migration check"

---

cmd/cli/app/ruletype/common.go
cmd/dev/app/rule_type/lint.go
internal/util/cli/cli.go

These files are not actually rule types and will make linting and
applying rule types fail.

Rule Types: Skip `.test.yml` files when linting/applying

---

internal/engine/eval/trusty/config.go
internal/engine/eval/trusty/trusty_test.go
internal/engine/eval/vulncheck/config.go

We had previously added a function that defaulted the rule configuration if it was empty, in order to make the experience smoother for the UI user.
Since then, the UI has made a change that doesn't send an empty configuration by default, and instead sets some of the fields.
This change ensures that any fields that are unset get a default value.
We should consider moving default values to the rule schema itself, and marking the field as required, but that will be done as part of a larger rule validation epic.
Fixes https://github.com/mindersec/minder-rules-and-profiles/issues/184

Change defaults for pull request rules

---

cmd/dev/app/rule_type/ruletype.go
cmd/dev/app/rule_type/validate_update.go

`mindev ruletype validate-update` (or `mindev ruletype vu` for short)
takes two YAML files and validate if the rule type can be updated (or
not).
```
$ mindev ruletype validate-update -h
The 'ruletype validate-update' subcommand allows you to validate an update of a rule type
definition
Usage:
mindev ruletype validate-update [flags]
Aliases:
validate-update, vu
Flags:
-a, --after string    file to read rule type definition from
-b, --before string   file to read rule type definition from
-h, --help            help for validate-update
```
If the validation succeeds, we should just get a "zero" return value.
```
$ mindev ruletype vu -b before.yaml -a after.yaml
```
If it fails, we should get the reasoning, and a non-zero return value:
```
$ mindev ruletype vu -b before.yaml -a after.yaml …
```

mindev: Add new subcommand to validate ruletype updates

---

cmd/cli/app/ruletype/common.go
cmd/cli/app/ruletype/ruletype_apply.go
cmd/cli/app/ruletype/ruletype_create.go
internal/util/cli/cli.go
internal/util/helpers.go
pkg/api/protobuf/go/minder/v1/api.go

This changes the behavior of these commands...
If we only give one file or standard input, it will actually parse
and fail if it's not a minder resource (you probably REALLY wanted
to apply that file).
If it's a directory, it'll try to be smart and apply as much as it can.
It all depends on if the file was expanded or not.
Consequently, this fixes the issue we used to have with test files in
the `minder-rules-and-profiles` repo.
Co-Authored-By: Michelangelo Mori <mmori@stacklok.com>

Make `minder ruletype` `apply`/`create` smarter

---

cmd/dev/README.md
docs/docs/how-to/mindev.md

The mindev entity schema is well documented (https://github.com/mindersec/minder/tree/main/cmd/dev/examples) but it's rather hard to discover. Update the mindev README and our documentation to point to it.

Document mindev entity schema

---

internal/engine/executor.go

Currently, mostly of the rule evaluation logs don't include information about things like `project_id` or `entity_id`, which makes it hard to find specific error logs about a particular instance.  We _do_ have a single log message that indicates that the rule evaluation is started, but then a bunch of logs happen that don't clearly link back to the `entity evaluation - started` message.
Manual only, sorry!

Propagate project and entity information to rule evaluation logs

---

cmd/cli/app/ruletype/ruletype_apply.go
cmd/cli/app/ruletype/ruletype_create.go
cmd/dev/app/rule_type/lint.go
internal/util/helpers.go

We recently changed the behaviour of `minder ruletype create` and `apply` to ignore files that do not define rule types. This allowed us to add test files to `mindersec/minder-rules-and-profiles`, but it in turn broke `mindev`.
This change makes `mindev` behave like `minder` by splitting folder walk from ruletype validation.
Fixes #4819
Manually ran the following commands pre- and post-fix.
```
mindev ruletype lint -r ~/stacklok/minder-rules-and-profiles/rule-types/ --skip-rego
mindev ruletype lint -r ~/stacklok/minder-rules-and-profiles/rule-types/common/license.yaml --skip-rego
minder ruletype create -f ~/stacklok/minder-rules-and-profiles/rule-types/
```

Fix `mindev ruletype lint`.

---

internal/engine/actions/remediate/gh_branch_protect/gh_branch_protect.go
internal/engine/actions/remediate/gh_branch_protect/gh_branch_protect_test.go

I spent a lot of time in https://github.com/mindersec/community/pull/6/commits/728938ef8ff4c67c5bb1f4318d33f30ea3d64881 banging my head on figuring out that you need to create a `branch` param for the `gh_branch_protection` remediation.  Since the param is allowed to be `""` (at which point we use the repo's default branch), let's not require the parameter at all.
Later: we need to figure out a mechanism to flag and validate these sorts of constraints at rule type create time, rather than at rule eval time.
I added a unit test.

Simplify logic for required branch parameter to gh_branch_protection

---

internal/events/nats/natschannel_test.go

I noticed `natschannel_test` failing in a CI run (which seem to run on a slower CPU than my MacBook).  I was able to reproduce with `-count 1000` with some background adversarial tasks.  Putting in a forced scheduler transition (aka `time.Sleep`) after closing the subscriber seemed to prevent losing the third message (it was always the third message, which made me suspect the lines just before that publish).
`go test -count 1000 ./internal/events/nats` while running `go test -count 2 ./...` in parallel in another window.

Fix a 0.2% natschannel_test flake with some forced scheduler sleeps

---

database/mock/store.go
database/query/subscriptions.sql
internal/db/querier.go
internal/db/subscriptions.sql.go

The following PR fixes a bug in the query. The query parameters were all mixed up and reused for different columns.

Fix the set bundle version query for the subscriptions table

---

README.md

Update all docs links to https://mindersec.github.io/ instead of Stacklok minder docs links

Fix docs references in README.md

---

.mk/develop.mk
docs/docs/developer_guide/get-hacking.md

I wanted to run `make run-docker services=minder` to only reload minder without tearing down keycloak, openfga, or the postgres DB.  Unfortunately, `run-docker` depends on `run-docker-teardown`, which didn't qualify the services being shut down.  This fixes that, so you can iterate with the prevous command.
I've been using this to speed up my manual test loop.

Have run-docker-teardown respect services variable

---

internal/flags/flags.go
internal/service/service.go

When merging #4784, I missed that I needed to update `services.go` to pass the flag client.  This led to a `nil` interface in `Bool()` and a panic.
This shows up real fast as a failure to publish messages when running the server.  The panic is caught, but no message is published.

Fix nil flag client, and warn about use in future

---

cmd/cli/app/profile/table_render.go
internal/util/cli/table/simple/simple.go

This sorts the list of profile statuses by entity, rather than mixing all rule types and entities together in database order.  I'll include a before/after screenshot, but this makes it much easier (for me) to interpret the output of `minder profile status list --detailed -n <my-one-profile>`
Before (note that some rows combine multiple entities under one rule type, but the same rule type is also repeated later):
After (I also did some formatting to narrow the table by combining columns using newlines to separate related data):
Manual testing by running the command.

Sort profile status table by entities

---

internal/engine/eval/trusty/trusty_test.go

This makes explicit use of a type from Trusty SDK library instead of a hand-rolled one which made migrating files around the SDK library itself harder.
Unit tested.

Fix type from `trusty-sdk-go`.

---

go.mod
go.sum
internal/engine/eval/trusty/actions.go
internal/engine/eval/trusty/actions_test.go
internal/engine/eval/trusty/trusty.go
internal/engine/eval/trusty/trusty_test.go

The latest release only moves some files around, maintaining the same public interface. Packages `pkg/types` and `pkg/client` are deprecated in favor of `pkg/v1/types` and `pkg/v1/client`, respectively, and `pkg/v2` will be added soon.
It builds.

Bump `trusty-sdk-go` to latest release.

---

internal/util/rand/random.go
internal/util/rand/random_test.go
pkg/profiles/service.go

Fixes the linting issues raised by v1.62

Fix linting errors for golangci-lint v1.62

---

cmd/cli/app/quickstart/embed/secret_scanning.yaml

The following PR updates the embedded secret_scanning ruletype used in quickstart.
Eventually we may want to update the command and reuse the already existing stacklok prefixed ruletype.

Update the embedded secret_scanning ruletype used in quickstart

---

internal/util/jsonyaml/jsonyamlutils.go
internal/util/jsonyaml/jsonyamlutils_test.go

We were using the default, which is 4. This gets the output to be quite
verbose. The standard is to use 2 spaces, so let's use that when
printing YAML in Minder.

Print YAML with 2 spaces for indentation

---

cmd/cli/app/ruletype/ruletype_apply.go
cmd/cli/app/ruletype/ruletype_create.go

We had added that ability in the initial implementation, but had lost it
once we started skipping files more thoroughly. This recovers that.

Allow creating/applying ruletypes from standard input

---

internal/util/schemaupdate/schemaupdate.go
internal/util/schemaupdate/schemaupdate_test.go

The properties validation was validating the envelope instead of the
actual properties. This lead to issues of us not being able to
accurately update required fields, even if this was allowed by previous
checks.
By fixing this, we now have better validation and updates are no longer an issue for rule types.

Fix properties update validation

---

database/mock/store.go
database/query/entitlements.sql
internal/controlplane/handlers_projects.go
internal/controlplane/handlers_user_test.go
internal/db/entitlements.sql.go
internal/db/querier.go
internal/projects/creator.go
internal/projects/creator_test.go
internal/projects/features/features.go
internal/service/service.go
pkg/config/server/config.go
pkg/config/server/features.go

This PR adds the functionality of automatically creating entitlements records for new projects. This will be done for both project creation paths - parent and sub-projects. 
The process is as follows:
1) In the config we have (e.g.:)
```
features:
role_feature_mapping:
stacklok-employees: "stacklok"
default-roles-stacklok: "default"
offline_access: "offline"
```
2) From the user's JWT, we get Keycloak-related data in the form of:
```
"realm_access": {
"roles": [
"stacklok-employees",
"default-roles-stacklok",
"offline_access",
"uma_authorization"
]
},
```
3) For each of the three …

Add entitlements assignment at the time of project creation

---

pkg/profiles/validator_test.go

The following PR fixes the unit tests validating for required rule type fields

Fix the unit tests validating for required rule type fields

---

internal/engine/eval/rego/datasources.go

I accidentally passed the unparsed object, which will not validate
correctly.

Use correct structure to validate data sources input

---

go.mod
internal/engine/eval/trusty/actions.go
internal/engine/eval/trusty/actions_test.go
internal/engine/eval/trusty/trusty.go
internal/engine/eval/trusty/trusty_test.go

This change aims to limit the impact of changes deriving from Trusty SDK to fewer lines of code. Specifically, business logic implemented in Trusty evaluation engine looks into the response as returned by the SDK itself, making it harder to move to Trusty API v2.
Note: this change is meant to be bug-compatible with the current Trusty evaluation engine.
Manual testing and unit testing.

Decouple Trusty engine from Trusty SDK structs.

---

go.mod
go.sum
internal/datasources/factory.go
internal/datasources/rest/handler.go
internal/datasources/rest/handler_test.go
internal/datasources/rest/rest.go
internal/util/schemaupdate/schemaupdate.go
internal/util/schemavalidate/validate.go
pkg/datasources/v1/datasources.go
pkg/datasources/v1/mock/datasources.go
pkg/profiles/rule_validator.go

This adds an initial implementation of the REST datasource driver. This
allows the user to register multiple REST endpoints to call a data
soruce and thus interact with it.
This initial implementation left several TODO items which need to be
addressed before unleashing the implementation.

Implement REST datasource driver

---

database/migrations/000108_data_sources.down.sql
database/migrations/000108_data_sources.up.sql
internal/db/models.go

This migration adds support for three additional tables, `data_sources` and `data_sources_functions` containing the definition of a single data source in a many-to-one relationship, and a `rule_type_data_sources` table representing the many-to-many relationship between rule types and data sources.
Manually tested that `migrate up` and `migrate down` work as expected.

Add migration for data sources.

---

internal/controlplane/common.go
internal/controlplane/handlers_authz.go

The getter interfaces for v2-context-only resources was incorrect and it
expected us to have a parameter called contextv2. This won't work for
our use-cases.
This fixes the accessor, thus making the compat middleware work.

Expect `GetContext` for context v2 resources

---

.trivy.yml
.trivyignore
.trivyignore.yaml

This PR adds trivy's own cache dir to the scan ignore list to fix the flaking trivy scan
N/A

Add Trivy's own cache to ignore list

---

cmd/cli/app/auth/auth_login.go

The following PR fixes the `auth login` command which was failing every time one logs in.
This was caused by the fact that we were passing a gRPC connection through the wrapper which did not had the credentials embedded in it (the login step happens after that). The fix is to ignore the conn from the wrapper and recreate it after the login step is completed. This way the credentials are properly loaded.
Fixes: https://github.com/mindersec/minder/issues/4988

Fix the failing auth login command due to missing credentials

---

database/migrations/000109_data_sources_project_id.down.sql
database/migrations/000109_data_sources_project_id.up.sql
internal/db/models.go

Tables `data_sources_functions` and `rule_type_data_sources` added by migration 108 lacked a reference to their containing project.
This change adds `project_id` foreign key in the style of `rule_instances` in order to avoid future mistakes like exposing resouces by id to users that don't have rights on the containing project.
Manually ran `migrate up` and `migrate down` in a database containing a few records. The aim of the test was to verify that the calculated project id was correct.

Add project id foreign key to data sources tables.

---

go.mod
go.sum
internal/engine/eval/trusty/actions.go
internal/engine/eval/trusty/trusty.go
internal/engine/eval/trusty/trusty_test.go

This change migrates `trusty` evaluation engine to use Trusty v2 API. Most of the changes apply to the intermediate representation we recently added to decouple Trusty from Minder, but some additional changes were required due to some fields becoming optional and nullable.
Note: this change is again meant to be bug-compatible with the current evaluation engine, so we treat the lack of `"score"` as a score of `0`, thus triggering false positives as done by the current engine. The idea is to build on top of this to fix known issues of the engine before migrating it to Data Sources.
Fixes stacklok/minder-stories#77
Updated unit tests, ran smoke tests locally.

Migrate trusty eval engine to Trusty v2 API.

---

internal/datasources/factory.go
internal/datasources/service/convert.go
internal/datasources/service/helpers.go
internal/datasources/service/options.go
internal/datasources/service/service.go
internal/datasources/service/service_test.go
pkg/datasources/v1/datasources.go

This implements the aforementioned missing function.
Fixes https://github.com/mindersec/minder/issues/5048

Implement `BuildDataSourceRegistry` in data sources service

---

cmd/dev/app/rule_type/rttst.go

This allows us to easily test data sources with `mindev`

`mindev`: Add ability to parse and use data sources

---

internal/datasources/service/service.go
internal/datasources/service/service_test.go

Fixes https://github.com/mindersec/minder/issues/5044

Datasource Service Create

---

database/mock/store.go
database/query/datasources.sql
internal/db/datasources.sql.go
internal/db/querier.go

The following PR adds a query for getting all rule types referencing an existing data source id scoped for a given project.
Ref. https://github.com/mindersec/minder/issues/5045

Add ListRuleTypesReferencesByDataSource db query

---

internal/datasources/service/service.go
internal/engine/executor.go
internal/engine/rtengine/cache.go
internal/engine/rtengine/cache_test.go

This hooks data source registration into Minder's policy engine. This is
done by populating individual data source registries into each rule type
engine, which pertains to a single rule type. This way, each rule type
would only have access to the data sources it instantiates.
This also caught a segfault we were unaware of. For some reason, the
builder of the ruletype engine cache was not populating all the needed
members of the struct which would segfault in case the cache did not
have a hit. This fixes that.
Closes: https://github.com/mindersec/minder/issues/5043

Instantiate data sources from the policy engine

---

internal/datasources/service/service.go
internal/datasources/service/service_test.go

The following PR implements the delete handler for the datasource service.
Fixes: https://github.com/mindersec/minder/issues/5045

Implement the Delete handler for the datasource service

---

internal/api/api_test.go

Add test for API field validation

---

internal/controlplane/handlers_ruletype.go
internal/controlplane/handlers_ruletype_test.go
internal/datasources/service/mock/fixtures/service.go

Rules can now specify a list of data sources names that they need for their evaluation. This change ensures that data sources required by the rule are available when creating the rule.
A similar change is being added in the code path implementing data source deletion ensuring that a data source is not deleted if there exist rules depending on it.
Fixes #5049
Unit tested.

Validate Data Sources when creating rules.

---

internal/datasources/service/mock/service.go
internal/datasources/service/service.go

This was not used and instead the functionality was coded on the rule
type control plane file in https://github.com/mindersec/minder/pull/5068

Remove `ValidateRuleTypeReferences` from data sources service

---

database/migrations/000110_rule_rtype_data_sources_cascading_delete.down.sql
database/migrations/000110_rule_rtype_data_sources_cascading_delete.up.sql

This migration recreates the foreign key constraint to delete rows from `rule_type_data_sources` when a record is deleted from `rule_type`.
Note that it is safe to just drop and recreate the constraint as the previous version prevented the deletion of rule types if they referenced a data source, so it was not possible to have dangling records.
Tested both
* `minder-server migrate up -n 1 -y`
* `minder-server migrate down -n 1 -y`

Fix on delete cascade in `rule_type_data_sources`.

---

internal/deps/extractor.go
internal/deps/scalibr/scalibr.go
internal/deps/scalibr/scalibr_test.go
internal/engine/ingester/deps/deps.go
internal/engine/ingester/deps/deps_test.go

This PR changes the dependency ingester to use a generic extractor abstraction. The goal is to make the dependency analysis more pluggable to allow us to easily switch backends. This PR breaks the change into three commits:
1. 09685cf108b90659044ad144bc7807514c962885 introduces a new dependency extractor abstraction
1. f8249b2c9e0eda8f500b78fa384af2f771601cda creates an extractor implementation with osv-scalibr based on the current ingester
1. 1bd70b92cbc7473efd1ca8dac9518f648d42ec5e removes the scalibr-specific logic from the deps ingester to use the new abstraction  (defaulting to scalibr), the tests are now ported to the new implementation.
***Outline how the changes were tested, including steps to reproduce and any relevant …

Introduce a dependency extractor abstraction

---

internal/engine/eval/rego/datasources.go
internal/engine/eval/rego/eval.go

This PR modifies the data source init logic to delay the rego function registration until the ingestion results are available.
We also wire the ingestion results to the data source initialization in preparation to pass them to the DS `Call()` method but it stops there to isolate the Call() update into its own PR to discuss (#5093).
Fixes #5088
/cc @JAORMX 

Delay data sources initialization, wire ingestion to init

---

internal/datasources/rest/handler.go
internal/datasources/rest/handler_test.go
internal/engine/eval/rego/datasources.go
internal/engine/eval/rego/rego_test.go
pkg/datasources/v1/datasources.go
pkg/datasources/v1/mock/datasources.go

This PR builds on https://github.com/mindersec/minder/pull/5091 and modifies the data source `Call()` signature to receive a context in the function call.
We also modify the data sources init to pass the ingestion results which are now available to all data sources drivers.
This PR breaks the work in the **last three commits** (ignore the rest, they will be gone after rebasing):
1. fc096ea2f0ff2d81a696c831cc3ece14b4fcf4d0 modifies the data source `Call()` function to take a context 
2. 2663d0071371ab9d0a04de08ef9f0cce766f99f6 regenerates the mocks and updates the tests
3. …

Pass context with ingestion to data sources

---

database/mock/store.go
database/query/datasources.sql
internal/db/datasources.sql.go
internal/db/querier.go

This statement is necessary to allow updates on Rule Types. Since an update does not modify the ID, we can't expect cascading deletes to happen, and thus have to perform the cleanup manually.
Autogenerated code.

Add delete statement for `rule_type_data_sources`.

---

internal/controlplane/handlers_datasource.go
internal/datasources/service/tx.go

This commit fixes a panic in the data source transaction subsystem when options are nil.
Fixes: https://github.com/mindersec/minder/issues/5113
This pr modifies the `beginTx()` in the transaction logic of the data sources to initialize an options set if none is passed. We also make sure that the read-only methods (list/get) retrieve initialize their transactions as read only.

datasource :Fix panic in transaction subsystem

---

internal/controlplane/handlers_datasource.go
internal/controlplane/handlers_datasource_test.go

We do some smart stuff in the middleware for the server to determine the
target project in case the user does not specify it. We're not so smart
in persisting that to the create/update requests. This fixes that; Making
creates/updates work without needing to explicitly specify a project ID.

Default project ID for data source create/update

---

cmd/cli/app/datasource/common.go
cmd/cli/app/datasource/get.go
cmd/cli/app/datasource/list.go
pkg/api/protobuf/go/minder/v1/datasources.go

This adds a helper function to the data sources protobuf struct to get a
string representation of the driver. This is handy for clients to be
able to render relevant info about data sources.

Get data source string from protobuf struct

---

docs/docusaurus.config.js
docs/src/css/custom.css

Docs style fixes:
- Fixes the black background in dark mode, which was only applying to the initial window height and would scroll off leaving the dark gray footer color behind. See screenshots below.
- Sets the primary colors for the Redocusaurus plugin to match the light/dark themes on the rest of the docs.
- Minor consolidation of style classes and formatting of the CSS file.
| Background before | Background after |
| :---------------- | :--------------- |
| <img width="1167" alt="image" src="https://github.com/user-attachments/assets/7db28fa6-e6c1-4a87-9e9a-f2ad0d964384"> | <img width="1167" alt="image" src="https://github.com/user-attachments/assets/bca1cf85-c85b-41be-a033-55135b8d54d0"> |
| API docs before | API docs after |
| …

Fix dark mode background and API doc colors

---

internal/engine/actions/actions.go
internal/engine/actions/alert/alert.go
internal/engine/actions/alert/noop/noop.go
internal/engine/actions/alert/security_advisory/security_advisory.go
internal/engine/actions/alert/security_advisory/security_advisory_test.go
internal/engine/actions/remediate/gh_branch_protect/gh_branch_protect.go
internal/engine/actions/remediate/gh_branch_protect/gh_branch_protect_test.go
internal/engine/actions/remediate/noop/noop.go
internal/engine/actions/remediate/pull_request/pull_request.go
internal/engine/actions/remediate/pull_request/pull_request_test.go
internal/engine/actions/remediate/remediate.go
internal/engine/actions/remediate/remediate_test.go
internal/engine/actions/remediate/rest/rest.go
internal/engine/actions/remediate/rest/rest_test.go
internal/engine/executor.go
internal/engine/interfaces/interface.go
internal/logger/telemetry_store.go
internal/logger/telemetry_store_test.go

Currently, action settings are passed around via a complex dance of
getter/setter functions that span multiple places in the executor.
However, this is not necessary, as we've already read these settings at
the beginning of execution, and can just set them in place where we need
them.
This simplifies this logic and leverages the aggregate profile structure
to set this. It also enforces the setting as part of the action driver
initiatlization.

Simplify propagation of action settings

---

internal/providers/github/webhook/handlers_githubwebhooks_test.go
internal/providers/github/webhook/handlers_pull_requests.go

We should just try to re-evaluate the PR instead of creating a new
entry.
Fixes #5139

Handle synchronize events for pull requests in github

---

internal/engine/ingester/deps/deps.go

This allows us to auto-discover a default branch if the user does not
set it. The previous setup was forcing that we'd always use the
"default" branch, thus bypassing autodiscovery.
It also had segfaults in the case where the repo configuration was not
set.

Don't force default branch in deps ingest and fix segfaults

---

docker/minder/Dockerfile
docker/reminder/Dockerfile
docs/docs/run_minder_server/run_the_server.md
go.mod
tools/go.mod

- bump go (toolchain) to v1.23.4
- bump go base images to v1.23.4
- update prerequisites in docs
Successfully tested locally with `make test` and `make build`.

Bump go to v1.23.4

---

.goreleaser.yaml

The following PR updates winget-pkg releaser details and forked repo reference to https://github.com/mindersec/winget-pkgs.
Ref. https://github.com/stacklok/minder-stories/issues/165

Update winget-pkg releaser details and forked repo reference

---

.gitignore
docker-compose.yaml

Bump components for local development environment to current version in docker-compose.yaml:
- postgres to v17.2-alpine (from: https://hub.docker.com/_/postgres)
- ~keycloak to v26.0.7 (from: https://quay.io/repository/keycloak/keycloak?tab=tags)~
- ~keycloak-config-cli to v6.2.1 (from: https://hub.docker.com/r/bitnami/keycloak-config-cli)~
- openfga to v1.8.~0~1 (from: https://hub.docker.com/r/openfga/openfga)
- nats to v2.10.22 (from: https://hub.docker.com/_/nats)
note re:keycloak: comment https://github.com/mindersec/minder/pull/5152#pullrequestreview-2483980357 below
Bonus: remove redundant entry in .gitignore.
Successfully tested locally:
```
$ make run-docker
Running docker compose down ...
Running docker compose up ...
Building the …
```

Bump components' versions in docker-compose.yaml

---

internal/controlplane/handlers_ruletype.go
pkg/ruletypes/service.go
pkg/ruletypes/service_test.go

When trying to create a rule type with data sources, we verify that the
data sources must exist. In case they don't the error is now surfaced to
the user.
Closes #5148

Inform user that datasource is not found when creating rule type

---

internal/entities/properties/constants.go
internal/providers/github/properties/pull_request.go
internal/providers/gitlab/properties.go
internal/providers/gitlab/pull_request_properties.go

The source and target PR information, as well as the upstream URL have
been promoted to top level properties.
The GitLab provider now fills these in by default and uses them to
populate the PR protobuf.
The GitHub provider fills in the properties in, but currently does not
leverage them; this will be done after some rollout time.

Promote pull request properties

---

cmd/cli/app/repo/repo_register.go
internal/util/cli/providerconfig.go

The following PR fixes enabling repo auto registration. 
It got broken because of the recent proto validations we added, but this was hidden because we were also ignoring the errors and were always returning a message indicating a successful result.
Fixes https://github.com/mindersec/minder/issues/5166

Fix enabling repo auto registration for providers

---

deployment/helm/templates/ingress.yaml

This is necessary to test Data Sources in staging. The lack of it causes a confusing `HTTP 464` error with message `malformed header: missing HTTP content-type`.
Not tested, just a hunch.

Add ingress configuration for data sources.

---

cmd/dev/app/rule_type/rttst.go
internal/engine/actions/alert/pull_request_comment/pull_request_comment.go
internal/engine/actions/alert/pull_request_comment/pull_request_comment_test.go
internal/engine/eval/homoglyphs/application/invisible_characters_eval.go
internal/engine/eval/homoglyphs/application/mixed_scripts_eval.go
internal/engine/eval/jq/jq.go
internal/engine/eval/jq/jq_test.go
internal/engine/eval/rego/eval.go
internal/engine/eval/rego/lib_test.go
internal/engine/eval/rego/rego_test.go
internal/engine/eval/trusty/trusty.go
internal/engine/eval/vulncheck/vulncheck.go
internal/engine/executor.go
internal/engine/interfaces/interface.go
pkg/engine/v1/interfaces/interfaces.go
pkg/engine/v1/rtengine/engine.go
pkg/engine/v1/rtengine/engine_test.go

Return a structured result from the evaluation engine, as well as an error.
A followup PR will update each of the evaluation engines to return a useful structured result, currently it is left empty for the sake of making the PR easier to review.
Unit tests were updated according to the change.

Add `EvaluationResult` as rule evaluation result.

---

internal/engine/actions/alert/pull_request_comment/pull_request_comment.go
internal/engine/eval/rego/eval.go
internal/engine/eval/rego/rego_test.go
internal/engine/eval/rego/result.go

Output the list of violations from the rego constraints evaluation engine.
This lets us use the violations in the `pull_request_comment` alert type.
For example, when using the json violation format:
```
eval:
type: rego
rego:
type: constraints
violation_format: json
def: |
package minder
import future.keywords.in
import future.keywords.if
violations[{"msg": msg}] if {
files_in_repo := input.ingested.files
some current_file in files_in_repo
msg := sprintf("File found: %s", [current_file.name])
}
alert:
type: pull_request_comment
pull_request_comment:
review_message: |
{{- range .EvalResultOutput }}  
- {{ .msg }}
{{- end }}
```
Or for the default, `text` violation format:
```
eval:
type: rego
rego:
type: constraints
def: |
package minder
import future.keywords.in
import future.keywords.if …
```

Return EvalResults from rego constraints evaluation

---

internal/entities/properties/constants.go
internal/providers/github/entities.go
internal/providers/github/properties/fetcher.go
internal/providers/github/properties/release.go
internal/providers/github/webhook/handlers_releases.go
internal/providers/github/webhook/hook.go

Support the release entity for the GitHub provider

---

internal/providers/github/clients/app.go

This reverts commit 9286b3173e53065ad0ee4013cd09ea83bd86fd6a.
This was breaking provider enrolment. We are abusing this function by using it for both the bot App user and the enrolling real user. We should refactor, but reverting for now.

Revert "Actually attempt to get the GitHub app's user ID (#5214)"

---

internal/engine/eval/rego/eval.go

This change adds the entity's properties as defined by the provider to the REGO evaluation context, making it possible to use them as arguments to e.g. data sources.
Manual tests.

Add entity properties to rego evaluation context.

---

internal/engine/ingester/deps/deps.go

If the user would forget to set the parameters, the deps ingest would
fail saying that the filter is invalid. This is not ideal for the user
since we should just set reasonable defaults.
This fixes that!
We now default to `new_and_updated`  if no filter configuration is set.

Enforce defaults in `deps` ingest pull request configuration

---

docs/docs/how-to/writing-rules-in-rego.md

We added several new Rego functions, but didn't put them in the documentation.
(There are some other cases of this as well, for example, we don't have a doc with the ingest types.)
Long-term, we should figure out how to auto-generate these, but for now, I've manually updated them.
N/A, though I've used almost all of these functions.

Update docs with newly-added rego functions

---

cmd/server/app/history_purge.go

The command `minder history purge` supports specifying a custom batch size via `--batch-size/-s` option. The short version `-s` overlaps with the short version of `--db-sslmode`, which is a root-level option.
This change solves the overlap by removing the short option from `minder history purge`.
Manual tests.

Remove short flag from `history purge` command.

---

database/migrations/000111_data_sources_subscription_id.down.sql
database/migrations/000111_data_sources_subscription_id.up.sql
database/query/datasources.sql
internal/controlplane/handlers_datasource.go
internal/controlplane/handlers_datasource_test.go
internal/datasources/service/helpers.go
internal/datasources/service/mock/service.go
internal/datasources/service/service.go
internal/datasources/service/service_test.go
internal/db/datasources.sql.go
internal/db/models.go
internal/marketplaces/namespaces/validation.go
pkg/ruletypes/service_test.go

This is the first PR for adding subscriptions to data sources, allowing them to be part of a bundle.
This PR focuses on the database operations and service layer.
A followup PR will add the functions to import data sources from the bundle, and additional validation.

Add support for subscriptions to data sources

---

internal/controlplane/handlers_oauth.go
internal/controlplane/handlers_oauth_test.go

Currently, it is possible to set an arbitrary redirect URL after completing Minder login.  Limit this to localhost (for CLI), or known endpoints in our config.
Added unit tests -- I'm wondering if we should put this behind a configuration option as well for easier rollback if I got something wrong.

Limit allowed redirect URLs from GetAuthorizationURL

---

internal/engine/eval/rego/eval.go
internal/engine/eval/rego/http.go
internal/engine/eval/rego/http_test.go

Use a new feature in OPA v1.0.0 to patch the HTTP roundtripper to only send to public IP addresses.
Manual testing and then added unit tests, then figured out what `raise_error` actually does in `http.send`: https://github.com/open-policy-agent/opa/issues/5805 (hint: it doesn't fail the whole rule and return an error, it just drops that particular branch of evaluation...)

Limit http.send in rego evaluation to "normal" public IPs.

---

internal/controlplane/handlers_oauth.go

It turns out that I was a bit too zealous on the redirect URL protection.  Fixes https://github.com/mindersec/minder/pull/5282/files#r1913339896
I read the code, sorry!

Fix localhost detection for URL redirect protection

---

internal/engine/eval/rego/lib.go
internal/engine/eval/rego/lib_test.go

This introduces `parse_toml` to our rego library. It allows us to parse
TOML files in order to more easily write policies for things like
`pyproject.toml`.

Introduce rego function to parse TOML files

---

cmd/dev/app/datasource/datasource.go
cmd/dev/app/datasource/generate.go
cmd/dev/app/root.go
go.mod
go.sum

This adds the following command: `mindev datasource generate ...`
The aforementioned command will read a swagger doc (OpenAPI v2) and will
generate the appropriate data source definition out of it.
I went for v2 since there was an easy-to-use implementation ready.
Adding v3 support is left as a TODO item.
Here's a demo of how usage would look like:
```
$ cat sample.yaml
swagger: "2.0"
info:
title: Sample API
description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
version: 0.1.9
basePath: http://api.example.com/v1
paths:
/users:
get:
summary: Returns a list of users.
description: Optional extended description in CommonMark or HTML.
responses:
"200": # status code
description: A JSON array of user names
content:
application/json: …
```

mindev: Add utility to generate a data source definition from a Swagger doc

---

internal/controlplane/handlers_datasource.go
internal/controlplane/handlers_datasource_test.go
internal/controlplane/handlers_user.go
internal/datasources/service/mock/fixtures/service.go
internal/datasources/service/mock/service.go
internal/datasources/service/service.go
internal/datasources/service/service_test.go
internal/marketplaces/bundles/mock/fixtures/reader.go
internal/marketplaces/bundles/mock/reader.go
internal/marketplaces/factory.go
internal/marketplaces/service.go
internal/marketplaces/subscriptions/mock/service.go
internal/marketplaces/subscriptions/service.go
internal/marketplaces/subscriptions/service_test.go
internal/projects/creator.go
internal/providers/github/service/mock/service.go
internal/providers/github/service/service.go
internal/providers/github/service/service_test.go
internal/service/service.go
pkg/mindpak/bundle.go
pkg/mindpak/bundle_test.go
pkg/mindpak/mindpack.go
pkg/mindpak/reader/reader.go
pkg/mindpak/reader/reader_test.go
pkg/mindpak/testdata/no-data-sources/profiles/branch-protection-github-profile.yaml
pkg/mindpak/testdata/no-data-sources/rule_types/branch_protection_enabled.yaml
pkg/mindpak/testdata/t2/data_sources/osv.yaml

This allows Minder to create data sources from a bundle when a new user registers.
A part of this PR involves changing the parameter type in several functions from a `db.Querier` to a `db.ExtendQuerier`, making it more specific.

Support data sources in bundles

---

docs/docs/understand/key_concepts.md

This adds a new page that gives an overview of the different concepts in
Minder. It starts adding the items that were recently implemented and
are yet to be documented

Add "Key Concepts" documentation

---

internal/datasources/rest/handler.go
internal/datasources/rest/handler_test.go
internal/datasources/structured/handler.go
internal/datasources/structured/handler_test.go
internal/engine/eval/rego/datasources.go
internal/engine/eval/rego/rego_test.go
pkg/datasources/v1/datasources.go
pkg/datasources/v1/mock/datasources.go

While working on #5094, I discovered that there was some over-use of `any` and reflection that (IMO) made the code harder to understand.  This hopefully contributes to polishing datasources for release.
Tested with `go test`, which was helpful for finding all the places where signatures changed.  Otherwise, this should be a no-op.

Datasource cleanup: introduce some types and avoid pass-by-context

---

internal/engine/eval/rego/lib.go
internal/engine/eval/rego/lib_test.go
internal/flags/constants.go

#5094 attempted to add a data source for extracting dependencies.  On reflection, this seems simpler to implement as a standard rego function (available in all projects without needing to create a specific data source).
Fixes #5090
Added unit tests.

Add dependency extraction functions

---

.gitattributes
buf.gen.yaml
docs/.markdownlint-cli2.jsonc
docs/.prettierignore
docs/docs/ref/proto.mdx
docs/eslint.config.mjs
docs/proto_template.tmpl

Renames the `proto.md` generated reference doc to `proto.mdx`.
Future proofing: The file has inline JSX. Docusaurus currently renders all .md and .mdx with the MDX compiler so this works, but the next major version will change this (.md will be compiled with CommonMark instead; [reference](https://docusaurus.io/docs/migration/v3#using-the-mdx-extension)).
Ran `make gen` to confirm the .mdx file is generated as expected and the docs site builds.

Update generated proto reference doc to .mdx

---

internal/engine/eval/rego/lib.go

This moves all the large, helpful Golang comments into the `Function.Description` field.  The next step will be to convert all the existing `func(*interfaces.Result) func(*rego.Rego)` functions to entries in a list, like so:
```golang
type vfsFunc(billy.Filesystem) rego.BuiltinDyn
type FunctionEntry struct {
// The rego function definition (metadata)
decl *rego.Function
// Only one of the following should be set:
// A bare function implementation which does not need a vfs
bareImpl rego.BuiltinDyn
// A function implementation that should receive the current vfs
vfsImpl  vfsFunc
// A function implementation that sohuld receive the pre-change vfs
baseImpl vfsFunc
}
```
In that PR, we can then convert the existing initialization to:
```golang
var MinderRegoLib = []FunctionEntry{
FileExists, …
```

Relocate comments to rego.Function.Description in preparation for auto-generating documentation.

---

internal/util/helpers_test.go

Currently helper functions in Util lacks test coverage
This commit adds test coverage helper functions in Util
Ref #4380

Add additional test coverage for helper functions in Util

---

internal/controlplane/handlers_profile_test.go
pkg/engine/selectors/selectors.go

When an entity type does not have a specific CEL environment, fall back to the generic environment.
Fix #5375

Fall back to generic env for selectors

---

internal/util/cli/cli_test.go
internal/util/cli/credentials_test.go

This is an attempt to fix the tests that are continuously failing, for example https://github.com/mindersec/minder/actions/runs/13108294785/job/36571707787
This should indicate if the lock in `setEnvVar` is the cause, or if it's something else.

Run tests that set env sequentially

---

cmd/cli/app/auth/auth_login.go
cmd/cli/app/root.go

Added to check to ensure config file actually exists if flag is used. 
Fixes #4513 
**No flag (minder auth login) - SAME AS PREVIOUSLY**
Works as intended
**Flag + no file (minder auth login --config) - SAME AS PREVIOUSLY**
Usage 
“Details: flag needs an argument: --config”
**Flag + non-existant file (minder auth login --config blah) - FIXED**
Message: Config file does not exist
Details: file blah not found
**Flag + valid file (minder auth login --config config.yaml) - SAME AS PREVIOUSLY**
Works as intended
**Flag + invalid file(minder auth login --config go.sum) - SAME AS PREVIOUSLY**
Error reading config file: While parsing config: yaml: unmarshal errors:
line 1: cannot unmarshal !!str `buf.bui...` into map[string]interface {}
Still took …

Adds check to ensure config file exists. Fixes: #4513

---

internal/controlplane/handlers_authz.go
internal/controlplane/handlers_authz_test.go
internal/roles/mock/service.go
internal/roles/service.go
internal/roles/service_test.go

In #5385, I conflated the `user_management` and `machine_accounts` flags for enabling direct grants.  Unfortunately, this was incorrect, and our smoke tests started to fail when I set the `machine_account` flag.  This should allow re-enabling `machine_accounts`, while still having smoke tests pass.
Fixes #5145
In penance, I updated the AssignRole test to cover the new cases I'd introduced.

Fix check for direct rule grant, add unit tests for same

---

docs/docs/how-to/custom-rules.md
internal/controlplane/handlers_ruletype.go
internal/engine/actions/alert/pull_request_comment/pull_request_comment.go
internal/flags/constants.go

- Remove the feature flag
- Add docs
- Fix bugs
Fix #5432

Release PR comment alert type

---

MAINTAINERS.md

We managed to duplicate MAINTAINERS.md when we created `mindersec/community`.  Point to the maintainer list in that repo.
N/A

Update maintainer list to point to community

---

cmd/server/kodata/templates/invite-email.html.tmpl
cmd/server/kodata/templates/invite-email.txt.tmpl
internal/email/email.go
internal/invites/service_test.go

The current email template contents are both hard-coded and Stacklok-specific.  Move these to `kodata`, so that other users can customize their own email templates.
I also noticed that we were using `NewSafeHTMLTemplate` for the text body, and re-parsing the templates every time -- this is now moved to module-level initialization (this means you need to restart the server to pick up new templates, but this seems reasonable given that other config requires a restart
Unit tests (so far) -- will do some integration testing after merge.

Move email templates to data

---

cmd/cli/app/auth/auth_token.go
cmd/cli/app/auth/offline_token/offline_use.go
cmd/cli/app/root.go
internal/controlplane/handlers_token.go
internal/controlplane/server.go
internal/util/cli/credentials.go
internal/util/cli/credentials_test.go
internal/util/cli/rpc_client.go
pkg/config/client/config.go
pkg/config/common.go
pkg/config/server/identity.go

With these changes, I no longer need to set the client-side `identity` parameters, and I can call Minder as:
```
./bin/minder --grpc-host localhost --grpc-port 8090 --grpc-insecure auth login
```
And it will log in with the local keycloak instance.  For other production instances, it should be possible to simply use `--grpc-host` to select them, and not need to explicitly know about their Keycloak configuration.  (And, at some point, it could be non-keycloak...)
On the server side, this requires something like the following `identity` configuration:
```yaml
identity:
server:
issuer_url: http://keycloak:8080 # Use http://localhost:8081 instead for running minder outside of docker-compose
issuer_claim: http://localhost:8081/realms/stacklok # This needs to match keycloak's configured issuer, …
```

Determine authentication host based on WWW-Authenticate header

---

deployment/helm/templates/routes.yaml

This will teach me to read docs and assume that they know what they are talking about (spoiler: it did not).
It turns out that without a GRPCRoute, we get _different_ strange errors of the form:
```
Details: error retrieving user rpc error: code = Unimplemented desc = unexpected HTTP status code received from server: 404 (Not Found); transport: received unexpected content-type "application/json"
```
Fixes #5503
I used some manual route loading on `api.custcodian.dev` to test the following:
```
./bin/minder --grpc-host api.custcodian.dev auth login
curl -i https://api.custcodian.dev/api/v1/user
```
Both seem to be working correctly with this configuration, which _should_ enable the robot tests and the UI to do the same.

Fix GRPC routing as well as HTTP routing

---

cmd/cli/app/auth/offline_token/offline_use.go

I broke the token exchange URL for `offline token use` in #5502 when I changed `RefreshCredentials` to no longer append `protocol/openid-connect/token` to the supplied URL, but I forgot to fix up `offline_use.go` properly.  (I fetched the realm URL properly, but I didn't move the token URL addition to the outer layer.)  Added a TODO on cleanup to match the one in `GetToken` in the `internal/util/cli` library.
Our smoke tests use this, so `minder@main` was failing.

Fix token URL for offline token use

---

pkg/config/client/config.go

Apparently I let GenAI have a bit too much fun, and it generated GRPC addresses like `staging.stacklok.dev: 443`.  Remarkably, this appears to _work_ on Darwin (MacOS), Windows, and Linux according to manual testing, but it still seems weird.
Tested manually.  Will try to add some unit tests for this at some point, though it's technically "working" now...

Fix formatting of GRPC client address

---

internal/invites/service_test.go

I've seen a bunch of flakes in `./internal/invites` tests after I moved the templates to be read from the filesystem in an `initOnce`.  Move the fetch and parse of these files to `TestMain`, which runs before the tests, to hopefully trigger the initialization before other tests are running around affecting things.
Ran `go test -count 2 ./...` and checked that these tests passed (there are a few other that aren't multi-count safe that I will try to fix in the future).

Move email file parsing (and env setting) to TestMain to reduce flakes

---

internal/util/testqueue/passthroughqueue.go

Ref: https://github.com/mindersec/minder/actions/runs/14067172052/job/39392502845
The unit tests failed due to a detected data race:
```
==================
WARNING: DATA RACE
Write at 0x00c0008b5b30 by goroutine 44:
runtime.closechan()
/opt/hostedtoolcache/go/1.23.7/x64/src/runtime/chan.go:397 +0x0
github.com/mindersec/minder/internal/util/testqueue.(*PassthroughQueue).Close()
/home/runner/work/minder/minder/internal/util/testqueue/passthroughqueue.go:44 +0xa4
github.com/mindersec/minder/internal/providers/github/webhook.(*UnitTestSuite).TestHandleGitHubAppWebHook.func5.deferwrap3()
/home/runner/work/minder/minder/internal/providers/github/webhook/handlers_githubwebhooks_test.go:3266 +0x1f
...
Previous read at 0x00c0008b5b30 by goroutine 459:
runtime.chansend() …
```

Fix detected race in interna/providers/github/webhook by locking channel access

---

.github/workflows/license-check.yml
cmd/cli/app/apply.go
cmd/cli/app/profile/export.go
pkg/api/apply.go
pkg/fileconvert/collect.go
pkg/fileconvert/encodedecode.go
pkg/fileconvert/fileconvert_test.go
pkg/fileconvert/testdata/directory/datasource.yaml
pkg/fileconvert/testdata/directory/other.test.yaml
pkg/fileconvert/testdata/directory/profile.ignored
pkg/fileconvert/testdata/directory/profile.json
pkg/fileconvert/testdata/directory/ruletype.yaml
pkg/fileconvert/testdata/resources.yaml
pkg/profiles/util.go

Adds a command to export a profile along with all dependencies for that profile (ruletypes and datasources).
Adds a command to bulk-import resources from either a file (such as the one from `profile export`), or a directory of files.
This should simplify migrating from one Minder server to another, or applying resources from an IaC repository.
Added unit tests for the file import/export (and found some fun edge cases / bugs).  Also tested import/export cycle with the OpenSSF baseline between Stacklok's public service and a local Minder instance.

Add profile export and top-level apply commands

---

cmd/cli/app/auth/auth_delete.go
cmd/cli/app/auth/auth_login.go
cmd/cli/app/auth/auth_logout.go
cmd/cli/app/auth/offline_token/offline_use.go
cmd/cli/app/root.go
internal/util/cli/credentials.go
internal/util/cli/credentials_test.go
internal/util/cli/rpc_client.go

Currently, the `minder` CLI uses a single credential file for all providers.  When working across providers, this means that you constantly need to re-run `minder auth login`, which is annoying.  Use a different file for each API endpoint.
Fixes #1961
Updated tests and ran manual tests.

Support different credential files for different API hosts

---

cmd/server/kodata/templates/invite-email.txt.tmpl
internal/email/email.go
internal/email/email_test.go
internal/invites/service.go
internal/invites/service_test.go

It turns out that we support delivering the invitation code in a larger URL, but we do not supply the invitation code directly to the template (for example, to use in CLI directions).
I also added the UUID project ID to the context, as that's the only form of project ID that the CLI currently supports.

Update email template context to include invite code and project ID

---

internal/controlplane/handlers_authz.go
internal/controlplane/handlers_authz_test.go
internal/controlplane/handlers_projects.go
internal/controlplane/handlers_reconciliationtasks_test.go
internal/projects/creator.go
internal/projects/creator_test.go
pkg/api/protobuf/go/minder/v1/minder.pb.go
pkg/flags/constants.go
proto/minder/v1/minder.proto

Allow CreateProject (with auth but no permission check) on top-level projects.
Allow DeleteProject (with required project permissions) on top-level projects.
Both changes are behind a new feature flag.
Fixes #3173
Fixes #3174
Added a few unit tests, also doing some manual testing.

Enable CreateProject and DeleteProject on top-level projects

---

internal/controlplane/handlers_authz.go
internal/controlplane/handlers_authz_test.go
pkg/config/server/authz.go

This change allows a set of server admins (Keycloak user IDs listed in the server configuration file) to delete offending resources via the front-door API.  This only supports delete, so server admins need to already know the identity of the offending resource (as the probably have access to the backing database).  Deleting these resources through the API ensures that _other_ cleanup (e.g. webhook deregistration and other updates) is performed when compared with simply deleting rows from the backend.
Added unit testing, some manual testing.

Add support for service admins to delete resources via API

---

internal/engine/eval/rego/http.go

I recently found a case where _somehow_ (the path wasn't clear), the OpenFGA client ended up instantiating an `http.DefaultClient` which had the `publicOnlyDialer` installed.  This resulted in the following error message:
```
{"level":"error","request_id":"dcf83d26-8d31-434a-beda-f407bf42eda4","Resource":{"service":"minder.v1.UserService","method":"GetUser"},"login_sha":"----","telemetry":"true","Attributes":{"http.code":"Unknown","http.content-type":["application/grpc"],"http.duration":"1ms","http.forwarded":["10.0.0.1"],"http.user_agent":["minder-cli"],"exception.message":"rpc error: code = Unknown desc = failed to get user dependencies: unable to read authorization tuples: Post \"http://openfga.openfga.svc:8080/stores/ABCD/read\": remote address is not …
```

Avoid overriding default transport with a limited round-tripper in some cases

---

internal/engine/actions/remediate/pull_request/pull_request.go
internal/engine/actions/remediate/pull_request/pull_request_test.go
internal/engine/actions/remediate/pull_request/types_content.go

Enables the use of `EvalRequestOutput` in pull_request remediations, particularly bodies and file contents.  
This allows using data collected during rule evaluation to craft file contents (for example, detected 
ecosystems in dependabot.yml updates)
Continues the work in #5204
Unit tests and a quick usage test.

Support EvalResultOutput in PR templates

---

internal/engine/actions/remediate/pull_request/pull_request.go
internal/engine/actions/remediate/pull_request/pull_request_test.go

The current `pull_request` action *always* attempts to PR to the `main` branch, whether or not that branch exists.  Instead, we should PR to the same branch being evaluated 
by the git ingest.
Fixes #5629
Updated unit tests, found that they failed due to the wrong branch name.

Use current branch when sending pull requests, rather than hard-coding main

---

internal/db/embedded/testdb.go

Currently, we create a new embedded postgres server for each test which uses it (at least 14 call sites).  Each server needs its own port, and goes through all the postgres initialization steps.
It turns out, we need a separate postgres _database_, but not a separate _server_.  This change re-uses the server (and amortizes server startup), for a substantial reduction in test execution time.
Tested this (with other changes in place) on `./internal/controlplane`, but going to use CI to validate the full pass.

Re-use embedded postgres instance across tests

---

go.mod
go.sum
internal/api/api.go

It looks like the Buf libraries all got moved under a vanity URL, so dependabot / `go get` wasn't finding new versions.  Manually upgraded packages (and changed our explicit dependency) to remove the old path.
Fixes #5619
Unit tests, used `go mod why` to figure out what was continuing to import the old path.

Update to new paths for buf.build/go/protovalidate

---

.mk/helm.mk

Fixes #5727 -- I missed a file change when extracting this for upstream, and "skip if env var is set" kept me from noticing on the final push.
Fixes #5727
I set the `PUBLISH_IMAGES` repository variable to `true` and tested with and without this PR:
Without: https://github.com/evankanderson/minder/actions/runs/16031056912
With: https://github.com/evankanderson/minder/actions/runs/16031155307

Record image refs during build for later use by cosign

---

internal/db/embedded/testdb.go

Fixes an [occaisonal test failure](https://github.com/mindersec/minder/actions/runs/16009211483/job/45162919136?pr=5716):
```
panic: sync: WaitGroup is reused before previous Wait has returned
goroutine 58 [running]:
sync.(*WaitGroup).Wait(0x325ecc0)
/opt/hostedtoolcache/go/1.24.2/x64/src/sync/waitgroup.go:120 +0xe5
github.com/mindersec/minder/internal/db/embedded.ensurePostgres.func2()
/home/runner/work/minder/minder/internal/db/embedded/testdb.go:70 +0x51
created by github.com/mindersec/minder/internal/db/embedded.ensurePostgres in goroutine 50
/home/runner/work/minder/minder/internal/db/embedded/testdb.go:69 +0x9ba
```
Tested ./internal/providers/... with a count of 50

Fix WaitGroup race on embeddedpostgres

---

pkg/flags/flags.go

I noticed a number of recent data race failures in `Test_flaggedDriver_Publish`.  It appears that `SetProviderAndWait` avoids some unlocked asynchronous operations that lead to a race in the Go Feature Flag provider's shutdown.
I ran `go test -cover -race -count 1000 ./internal/events` to reproduce the original issue, and after this change `-count 2000` ran cleanly.

Switch to SetProviderAndWait to avoid data races when switching OpenFeature providers in tests
