mindersec/minder

README.md
This makes it more known that we're running it!
=> Add Minder instance info in README.

docs/docs/getting_started/remediations.md, docs/docs/run_minder_server/run_the_server.md, docs/docs/understand/security.md
- Remove empty "Minder's security model" page
- Update instructions on encryption keys
=> Clean up docs

docs/docs/getting_started/first_profile.md, docs/docs/getting_started/remediations.md
- Fix typos
- Make repository deletion instructions consistent
- Avoid getting "profile already exists" error when enabling remediation
=> Improve getting started documentation

docs/docs/run_minder_server/installing_minder.md
Documentation for installing Minder and its separate components.
=> OSS: Installing Minder docs

docs/docs/ref/rules/artifact_signature.md
Adds reference for this rule_type
=> Add artifact_signature reference

.github/workflows/chart-publish.yml
=> Install cosign in chart-publish.yaml

.github/workflows/test.yml
=> Remove optional parameters from `GoTestTools/gotestfmt-action@v2` action instantiation

internal/engine/eval/trusty/trusty.go, internal/engine/eval/vulncheck/vulncheck.go
This would have manifested as the evaluator returning an Error to the
profile instead of a Failure.
Fixes: #1594
=> Return EvaluatioError, not generic error on finding vulnerable or low-scoring packages

go.mod, go.sum, internal/engine/eval/vulncheck/pkgdb.go, internal/engine/eval/vulncheck/pkgdb_test.go, internal/engine/eval/vulncheck/review.go, internal/engine/eval/vulncheck/review_test.go, internal/engine/eval/vulncheck/vulncheck.go, internal/engine/eval/vulncheck/vulndb.go, internal/engine/eval/vulncheck/vulndb_test.go
Also, if there is not patch available, just add a comment.
Fix #1607
What it looks like in a Go update:
What it looks like in a Python update:
=> Suggest smallest delta in PR vulnerability check

cmd/cli/app/auth/auth_whoami.go
This enables us to print several projects in an easy way in case it would
be enabled for a specific user.
=> Print project list as multiple rows in `whoami` subcommand

internal/engine/rule_types_test.go
This adds more test coverage for both our rules and the Validate construct.
=> Add `Validate` check to our rule type tests

internal/logger/logging_interceptor.go
This allows us to get this info in the logs.
=> Add `X-Forwarded-For` to default logging

deployment/helm/values.yaml
Once this merges, it'll trigger the CI job that will update the documentation.
=> Add documentation for helm values

README.md
The following PR updates the readme file with a screencast of the quickstart command.
Preview:
=> Update README.md with quickstart screencast 

.github/workflows/deploy-doc.yml
Fix #1718
Proposal to only update our docs when we publish a new release
=> Trigger documentation update only on release

README.md
This change adds links to Homebrew and Winget, and a couple more copy changes.
=> Adds a bit more clarity to the getting started guide

cmd/dev/README.md
This adds an explanation and samples.
=> Add README to `mindev` command

cmd/cli/app/auth/auth_login.go, cmd/cli/app/auth/auth_logout.go, cmd/cli/app/root.go, cmd/server/app/serve.go, config/config.yaml.example, deployment/helm_tests/basic.yaml, deployment/helm_tests/basic.yaml-out, deployment/helm_tests/sidecar.yaml, deployment/helm_tests/sidecar.yaml-out, docs/docs/run_minder_server/run_the_server.md, internal/auth/jwtauth.go, internal/config/identity.go, internal/controlplane/handlers_user.go, internal/controlplane/handlers_user_test.go, internal/controlplane/identity_events.go, internal/controlplane/identity_events_test.go, internal/util/helpers.go
=> Simplify identity settings in config.yaml

internal/eea/eea.go
=> Set ProjectID for entities created during FlushAll

README.md, cmd/cli/app/profile/status/profile_status.go, cmd/cli/app/profile/status/profile_status_get.go, cmd/cli/app/profile/status/profile_status_list.go, cmd/cli/app/profile/status/table_render.go, cmd/cli/main.go
=> Make status a sub-command of profile

internal/engine/actions/actions.go
This detects if there was an error when evaluating and skips actions if it was
so.
The idea is that evaluation error is an unknown state, and actions shouldn't
be performed if we don't actually know the current state of the entity we're
evaluating.
Closes: #1805
=> Skip actions on error in the executor

internal/config/db.go
=> Remove GetDBURI and cached connection string

internal/eea/eea.go
This was missed and is easily fetcheable via the originating repository.
=> Add provider to `FlushAll` call in aggregator

internal/engine/actions/remediate/pull_request/pull_request_test.go, internal/engine/actions/remediate/pull_request/types_actions_replace_tags.go
This adds the exclude list and takes it into use in frizbee.
This also changes the PR unit tests to use local references, so when a test
fails, it only indicates the failing test and not all of the suite.
Closes: https://github.com/stacklok/minder/issues/1910
=> Add `excludes` configuration for frizbee

docs/docs/getting_started/first_profile.md, docs/docs/getting_started/quickstart.md, docs/docs/getting_started/remediations.md, docs/docs/how-to/create_profile.md, docs/docs/how-to/manage_profiles.md
=> Update docs for profile status command

cmd/cli/app/quickstart/quickstart.go, cmd/cli/app/repo/repo_register.go
Details:
1. Bumps timeout to 30s
2. Fixes showing all registered repos instead of the ones registered within the command's execution.
Found these after talking with @Mustafallica and @ethomson
=> Quickstart updates - bump timeout and show all registered repos

cmd/cli/app/artifact/artifact_get.go
Adds a tabular output with the most important information to artifact
get and makes it the default.
Example output:
```
+--------------------------------------+-----------+--------------+----------+------------+------------+----------------------+
|                  ID                  |   TYPE    |    OWNER     |   NAME   | REPOSITORY | VISIBILITY |    CREATION DATE     |
+--------------------------------------+-----------+--------------+----------+------------+------------+----------------------+
| 16adcff2-2c17-42d3-a235-07bbeb64c5c4 | CONTAINER | jakubtestorg | testrepo | testrepo   | public     | 2023-12-14T10:27:16Z |
+--------------------------------------+-----------+--------------+----------+------------+------------+----------------------+ …
```
=> Add table output to artifact get, make it the default

cmd/cli/app/profile/get.go, cmd/cli/app/profile/list.go, cmd/cli/app/profile/table_render.go, internal/util/cli/table/simple/simple.go
The `get` now shows a table with the identifiers and settings, and a second table
would show the list of rules enabled for that profile.
I also changed the output of the list, which now shows multiple tables with the identifiers and settings.
Sample:
```bash
$ minder profile get -i 2ae05a6c-57de-4751-bd04-d5125b8cbf92
No config file present, using default values.
+----------------------------------------------------+----------------------------------------------------+
|            PROFILE SUMMARY                         |                                                    |
+----------------------------------------------------+----------------------------------------------------+
| ID                                                 | 2ae05a6c-57de-4751-bd04-d5125b8cbf92               | …
```
=> Change the profile get/list output format

cmd/cli/app/artifact/artifact_get.go, cmd/cli/app/artifact/artifact_list.go, cmd/cli/app/auth/common.go, cmd/cli/app/profile/table_render.go, cmd/cli/app/repo/repo_list.go, cmd/cli/app/repo/repo_register.go, cmd/cli/app/ruletype/common.go, internal/util/cli/table/layouts/constants.go, internal/util/cli/table/simple/simple.go, internal/util/cli/table/table.go
This makes it easier to verify and better ensures we use the right type.
=> Replace table layout strings with type

cmd/cli/app/artifact/artifact_get.go, cmd/cli/app/artifact/artifact_list.go, cmd/cli/app/auth/common.go, cmd/cli/app/profile/table_render.go, cmd/cli/app/repo/repo_list.go, cmd/cli/app/repo/repo_register.go, cmd/cli/app/ruletype/common.go, cmd/cli/app/ruletype/ruletype_get.go, cmd/cli/app/ruletype/ruletype_list.go, internal/util/cli/table/simple/simple.go, internal/util/cli/table/table.go
Why? It looks fancier, that's all
=> Use variadic parameters for the table interface

cmd/cli/app/auth/auth_delete.go
This is useful for scripting and testing. The flag is not ergonomical on
purpose.
=> Add a flag to delete an account non-interactively

internal/controlplane/handlers_githubwebhooks_test.go
The webhook tests start an http server and spawn it in the background. This leads
to sporadic test failures, as the caller code might sometimes run before the
server is up.
This adds a retry with backoff in those tests, so if this happens, the caller will
simply retry.
If the retry fails, this will actually be a real issue with the code.
=> Make webhook tests more resilient

docs/docs/run_minder_server/run_the_server.md
This PR addresses the following documentation aspects:
- The docs don't mention updating the webhook configuration for running the minder server (AFAIK). 
- There was confusion about whether a single OAuth app or two of them are required. Configuring the repository provider for Minder should be present on the same page.
- The tutorial on the particular page mentions using `docker compose` for both Keycloak and `Postgres`; the same for `Minder` was added.
=> Add instructions for updating webhook configuration for minder server

internal/controlplane/handlers_profile.go, internal/engine/context.go, proto/minder/v1/minder.proto
=> Use project ID in context and as CLI flag

docs/docs/ref/proto.md, pkg/api/openapi/minder/v1/minder.swagger.json, pkg/api/protobuf/go/minder/v1/minder.pb.go
I thought these were also part of the GitHub action that generates docs, but they're not.
Ref #2051
=> Update generated docs

internal/engine/eval/vulncheck/vulncheck.go
Fixes https://github.com/stacklok/minder/issues/1438
=> Refactor vulncheck's Eval() to address high cyclomatic complexity

internal/auth/jwtauth.go, internal/controlplane/handlers_authz.go, internal/controlplane/handlers_token.go, internal/controlplane/server.go
Also remove unused superadmin role lookup.
Fix #2049
=> Split token validation and authorization middleware

internal/logger/logging_interceptor.go, internal/logger/telemetry_store.go, internal/logger/telemetry_store_test.go
Related-To: #1879
I documented a business record / telemetry store interface in [the design document](https://docs.google.com/document/d/132l2YCasne_p-ILyXG923v0qeLnELVW0qP1Gflza4Dw/edit#heading=h.tfrp6ktgz14f), but I don't seem to have created a separate issue for defining this interface.
=> Add TelemetryStore interface

docs/docs/ref/proto.md, pkg/api/protobuf/go/minder/v1/minder.pb.go, proto/minder/v1/minder.proto
=> Remove unused protos for web exchange

internal/config/server/logging.go, internal/controlplane/server.go, internal/logger/logger_setup.go, internal/logger/logging_interceptor.go
Followup from https://github.com/stacklok/minder/pull/2059#discussion_r1444409522
=> Add the ability to enable/disable payload logging (default disabled)

internal/events/eventer.go, internal/events/eventer_test.go
I noticed that our latency buckets for event processing time only went up to around 10s due to the otel default bucket sizes.  On increasing the bucket sizes, I decided to add some tests for the metrics, because I want them to actually work.  :grin:
I am sad about adding the `time.Sleep(2ms)`, but I couldn't find a more elegant way to get `--count=200` to pass consistently -- without the sleep, it was around a 1-2% flake rate with missing telemetry.
=> Increase size of latency buckets, add tests for exported Eventer metrics.

internal/config/utils.go
From https://github.com/stacklok/minder/pull/2075#discussion_r1443978919
=> minor: Add comment for handling missing config file and directories

internal/util/cli/table/simple/simple.go
Fix column name since we use IDs for projects.
=> Update column name for the rule type list table

internal/controlplane/handlers_githubwebhooks.go, internal/controlplane/handlers_repositories.go, internal/providers/github/github_rest.go, internal/providers/github/mock/github.go, pkg/providers/v1/providers.go
=> Repository deletion should remove the associated webhook

cmd/server/app/serve.go, internal/engine/executor.go, internal/logger/telemetry_store.go, internal/logger/telemetry_store_watermill.go, internal/logger/telemetry_store_watermill_test.go
This is a simple initial implementation of the middleware for logging
telemetry store data.
closes: #1879
=> Initial implementation of telemetry store watermill middleware

cmd/cli/app/profile/create.go
This adds a couple of simple boolean flags to the midner CLI that allows
a caller to enable alerts and remediations explicitly when doing
`minder profile create`.
Note that this was only added to the `create` sub-command, as it's
imperative and not declarative as is the `apply` sub-command.
=> Add overrides for enabling alerts and remediations when creating profiles

authz/minder.fga
=> Add project relationships to FGA model

cmd/server/app/migrate_up.go, internal/authz/authz.go
This keeps the authz interactions in the same package, thus keeping the
logic more contained.
=> Move OpenFGA interactions to authz package

internal/engine/eval/rego/lib.go, internal/engine/eval/rego/lib_test.go
This makes it easy for us to write policies that take `yaml` or `yml`
extensions into account without much hassle.
=> rego: Add new function to list files using a glob pattern

internal/auth/jwtauth.go, internal/controlplane/handlers_authz.go, internal/controlplane/handlers_oauth_test.go, internal/controlplane/handlers_user_test.go
=> Remove superadmin role

internal/engine/eval/rego/lib.go, internal/engine/eval/rego/lib_test.go
This new function walks a filesystem's directory and lists all the
files. This is handy for using it alongside other cunctions such as
`file.http_type` or `file.read`.
=> Add new rego function called `file.walk`

config/server-config.yaml.example, deployment/helm_tests/basic.yaml-out, deployment/helm_tests/sidecar.yaml-out
It now points to the right port which is the one used in docker-compose.
=> Update authz configuration example

cmd/cli/app/project/role/role_grant_list.go, internal/authz/authz.go, internal/authz/interface.go, internal/authz/mock/noop_authz.go, internal/authz/mock/simple_authz.go, internal/controlplane/handlers_authz.go
This adds both the API and the CLI for this functionality.
Closes https://github.com/stacklok/minder/issues/1852
=> Add ability to list role assignments in a project

deployment/helm/templates/ingress.yaml, deployment/helm_tests/basic.yaml-out, deployment/helm_tests/sidecar.yaml-out
=> Add `PermissionsService` to ingress configuration

docs/docs/how-to/add_users_to_project.md, docs/docs/run_minder_server/run_the_server.md
Ref https://github.com/stacklok/epics/issues/11
=> Add documentation for built-in roles

deployment/helm/templates/ingress.yaml, deployment/helm_tests/basic.yaml-out, deployment/helm_tests/sidecar.yaml-out
We had forgotten to clean this up.
=> Cleanup unused GRPC paths from ingress

internal/util/statuses.go, internal/util/statuses_test.go
We were missing test coverage for this.
=> Add test coverage for "nice status" middleware/interceptor

docs/docs/getting_started/first_profile.md
This PR fixes two minor invocation errors in the documentation.
=> Fix CLI invocations in first_profile.md

pkg/api/openapi/minder/v1/minder.swagger.json, pkg/api/protobuf/go/minder/v1/minder.pb.gw.go
I assume we forgot to run/commit `make gen` once 5e20d869 got merged.
=> Run "make gen" for main

internal/eea/eea_test.go
This adds basic tests for the happy path of `FlushAll`
=> Add test coverage for `internal/eea` `FlushAll`

docs/docs/how-to/artifact_signatures.md, docs/docs/ref/rules/artifact_signature.md
=> Update artifact provenance documentation

cmd/cli/app/auth/auth_delete.go, internal/auth/jwtauth.go
I was getting ready to work in this code, and I noticed a bunch of code which seemed to do a lot more work than needed (and needlessly combined CLI and backend context).
=> Clean up some JWT code

.github/pull_request_template.md, .github/workflows/pr-check.yml
Provide a brief overview of the changes and the issue being addressed. 
List dependencies required by this change, if any.
Fixes https://github.com/stacklok/minder/issues/2392
This PR adds a standard "PR template" to be used by contributors, used in this same PR. It also adds a GH action workflow to check if the "Change Type" section is being utilised.
Mark the type of change your PR introduces:
Outline how the changes were tested, including steps to reproduce and any relevant configurations. 
Attach screenshots if helpful.
The GH Action is being tested in this PR by not selecting anything in the "Change Type" section.
=> Standard PR template for Minder and a workflow check

.github/pull_request_template.md
Existing categories do not capture PRs which do not change behaviour but introduce improvements to the codebase.
=> add new type of PR for refactoring

.github/workflows/pr-check.yml
Fixes the PR check workflow to take into account the refactoring change type
=> Fix the PR check workflow to take into account the refactoring change type

Makefile
Fixes commands similar to `make authz-tests`. Commands within loops in a Makefile don't cause make to exit.
This can be tried by changing values in `simple.tests.yaml`. The logs indicate failure, but the command exits with an exit code of `0`. With these changes, the exit code is non-zero.
=> Updated Makefile to handle command failure within loops

internal/verifier/sigstore/container/container.go
This PR moves the signer identity verification to happen during evaluation. 
It was motivated by the recent sigstore-go version bump that broke one of the use cases we have (signing a container through cosign w/ OIDC issuer (i.e. google).
For historical reasons until now we were trying to extract the signer identity from the bundle/simplesigning layer and pass it to sigstore-go along with the bundle for verification. The version bump made us realise this is not really useful.
Instead we switched to verifying the bundle for consistency and inclusion in the transparency log, but without checking the identity. The identity verification happens on the evaluation step where we use the verification result we got from sigstore-go and compare it against the expected profile parameters from the …
=> Verify the signer identity upon evaluation

internal/engine/eval/trusty/actions.go
Hyperlink to trusty page for lower scored packages
Fixes https://github.com/stacklok/minder/issues/2412
Now it looks like that -
=> Hyperlink to trusty page for lower scored packages

internal/controlplane/handlers_authz.go, internal/controlplane/handlers_authz_test.go
By reporting the project ID the user is operating on, they may realize they have selected the wrong project and be able to fix the problem themselves.
N/A
=> Log and report operating project details when return permission denied error

internal/controlplane/handlers_profile.go, internal/engine/entities/entities.go
Noticed a high error rate with internal error:
```
rpc error: code = InvalidArgument desc = invalid entity type ENTITY_UNSPECIFIED, please use one of artifact,build_environment,repository
```
The user only saw:
```
Details: InvalidArgument indicates client specified an invalid argument.
```
No
=> Expose more errors as user-visible so users can adjust their queries in a useful way.

internal/util/cli/cli.go
The following PR checks if the gRPC error code is Unauthenticated and if so prints a helpful message to login again.
`It seems you are logged out. Please run "minder auth login" first.`
Tested this locally.
=> Print a helpful message in case of unauthenticated grpc code

internal/util/helpers.go
Errors were ignored, this parses them and returns them to the user.
=> Catch errors in refresh token fetching

docker-compose.yaml
=> Bump OpenFGA in docker-compose to v1.5.0

docker-compose.yaml
The Minder server depends on openfga for authorization.
=> Include 'openfga' in the 'depends_on' section of the 'minder' server container

internal/engine/ingester/git/git.go, internal/engine/ingester/git/git_test.go
This allows for the git ingester to use the default branch for a particular repo
in case nothing was provided. This is a reasonable default, which is great! However,
it may have been that a default branch was not gathered, so we also provide a global default
in case that's not available.
=> git ingester: Allow using default branch

cmd/dev/app/rule_type/lint.go
This starts verifying that ruletype names also match the name in the file. This a best practice we've identified that should be checked for.
=> `minder ruletype lint`: Also verify that rule type name matches file name

.mk/develop.mk
=> add lint-fix command to makefile

cmd/dev/app/rule_type/rttst.go
The explicit viper binding for environment variables was missing.
=> Ensure viper binds to env vars in mindev

go.mod, go.sum
=> Remove replace statement from go.mod

internal/logger/logger_setup.go, internal/logger/logging_interceptor.go, internal/util/helpers.go
The log-level conversion method would be used by reminder too, so moving this to utils.
=> Refactor: Move logging level method to utils

.gitignore
Update gitignore to ignore local sigstore artifacts.
=> Update gitignore to ignore local sigstore artifacts

cmd/server/app/serve.go, internal/controlplane/handlers_githubwebhooks.go, internal/controlplane/handlers_user_test.go, internal/controlplane/metrics/metrics.go, internal/controlplane/metrics/noop.go, internal/controlplane/server.go, internal/controlplane/server_test.go
This abstracts the server metrics with an interface in order to
make this configurable and easier to plug in.
=> Wrap controlplane metrics with interface

docs/docs/ref/cli/minder_completion_bash.md, docs/docs/ref/cli/minder_completion_zsh.md
=> Revert "Auto-generated cli documentation update - 2024-03-06 06:04:57"

internal/controlplane/handlers_user.go, internal/projects/create.go, internal/projects/create_test.go
This moves the default project creation code to the projects package.
It adds tests too and cleans it up a little.
=> Move default project creation and add tests

cmd/cli/app/project/project_list.go
=> Implement `project list` CLI subcommand

internal/engine/actions/alert/alert.go, internal/engine/actions/alert/security_advisory/security_advisory.go
If explicit severity is not given in the GHSA configuration, this uses
the overall rule type's severity.
=> Hook severity into GHSA generation

internal/engine/actions/remediate/pull_request/pull_request.go, internal/providers/providers.go
Remove unused Git client in pull request remediator
=> Remove unused Git client in pull request remediator

.github/workflows/test-deploy-doc.yml
This changes the name of the docs pages test deployment CI. It very ambiguous.
This also removes the `branch` trigger in favor of triggering based on the path given.
=> Change name and triggers for documentation test deployment CI

cmd/server/app/migrate_up.go
This is no longer needed as the tree migration is done and is running in production.
=> Remove project tree migration code

.github/workflows/compose-migrate.yml, .mk/develop.mk, Makefile, config/server-config.yaml.example, docs/docs/developer_guide/get-hacking.md, docs/docs/getting_started/login.md, docs/docs/run_minder_server/run_the_server.md
The `docker compose` (with a space) is a newer project to migrate compose to Go with the rest of the docker project. See https://stackoverflow.com/q/66514436/15412365 for more details.
=> Move from `docker-compose` to `docker compose`

internal/authz/authz_test.go
this actually waits for the in-process OpenFGA server to report health
before running the tests.
=> Wait for OpenFGA to be healthy in tests

docs/docs/ref/cli/minder_completion_bash.md, docs/docs/ref/cli/minder_completion_zsh.md
=> Fix docs build

cmd/cli/app/provider/provider.go, cmd/cli/app/provider/provider_get.go, docs/docs/ref/proto.md, internal/controlplane/handlers_providers.go, pkg/api/openapi/minder/v1/minder.swagger.json, pkg/api/protobuf/go/minder/v1/minder.pb.go, pkg/api/protobuf/go/minder/v1/minder.pb.gw.go, pkg/api/protobuf/go/minder/v1/minder_grpc.pb.go, proto/minder/v1/minder.proto
This implements the API and the CLI to get the information
of a specific provider.
It looks as follows:
```
$ ./bin/minder provider get -n github
+------------+--------------------------------------+
|    KEY     |                VALUE                 |
+------------+--------------------------------------+
| Name       | github                               |
+------------+--------------------------------------+
| Project    | 38625919-ebaa-4dbb-8ad6-784db6b4ad55 |
+------------+--------------------------------------+
| Version    | v1                                   |
+------------+--------------------------------------+
| Implements | github, git, rest, repo-lister       | …
```
=> Implement `provider get` API and CLI

database/mock/store.go, database/query/profiles.sql, internal/controlplane/handlers_profile.go, internal/db/profiles.sql.go, internal/db/profiles_test.go, internal/db/querier.go
This more strictly enforces the project boundaries in the projects API.
=> Enforce project boundaries in profile API

internal/engine/executor.go
This reverts commit a996b53ba90b10d326c04c324faa20550f07a33a as this wasn't the reason for the race condition issue we are seeing in the smoke tests.
=> Revert "Disable ingestcache for artifacts (#2603)"

cmd/server/app/migrate_up.go
The initial migration introduced the wrong auth flows. This uses the right ones and
sets them up as part of the migration.
Sorry!
=> This makes sure that the github providers have the expected auth flows set up

internal/controlplane/handlers_githubwebhooks.go, internal/eea/eea.go, internal/events/eventer.go
=> Add extra fields to our logging so it's easier to track where issues happen

deployment/helm/templates/ingress.yaml
This was missing, so we weren't serving requests to the projects API at all.
=> Add project service definition to minder ingress

internal/controlplane/handlers_ruletype.go, internal/ruletypes/service.go, internal/ruletypes/service_test.go
Refactor the code to only pass the project ID, not the whole context
=> Use project ID from entity context in rule creation

docker-compose.yaml
We've been seeing random issues with offline tokens and keycloak. Since the
new release does mention several improvements around offline tokens in release
notes, it's worth a try.
N/A
=> Upgrade keycloak to 24.0

docs/docs/ref/cli/minder_completion_bash.md, docs/docs/ref/cli/minder_completion_zsh.md
Our auto generated docs are not correctly formatted. The root issue is #2626, but this will make our build pass in the meantime.
=> Fix docs formatting to make build pass

internal/providers/github/github_rest.go, internal/providers/github/mock/github.go, pkg/providers/v1/providers.go
Remove unused function ListAllPackages
=> Remove unused ListAllPackages on GitHub provider

cmd/cli/app/repo/repo_register.go
1) Remove redundant continue
2) Explicitly check that response has a valid structure. This avoids
segfaulting on malformed responses.
=> Small tweaks to repo registration in the CLI

internal/controlplane/handlers_repositories_test.go, internal/engine/actions/remediate/pull_request/pull_request.go, internal/engine/actions/remediate/pull_request/pull_request_test.go, internal/providers/github/github_rest.go, internal/providers/github/mock/github.go, pkg/providers/v1/providers.go
We've seen temporary issues with minder not being able to create PRs. The current error messages don't really tell us what's going on.
These two patches would add debug messages that say for my test repos:
```
{"level":"debug","repo":"id:\"9c08e499-1c6e-4274-8509-ec92be5c5d45\" owner:\"jakubtestorg\" name:\"bad-python\" repo_id:706108924 hook_url:\"https://api.github.com/repos/jakubtestorg/bad-python/hooks/466546185\" deploy_url:\"https://api.github.com/repos/jakubtestorg/bad-python/deployments\" clone_url:\"https://github.com/jakubtestorg/bad-python.git\" created_at:
{seconds:1710427679 nanos:274883000} updated_at:{seconds:1710427679 nanos:274883000} default_branch:\"main\"","Timestamp":1710427840206368000,"message":"user info: github.User{Login:\"jhrozek\", ID:715522, …
```
=> TEMPORARY: Dump tokeninfo

internal/controlplane/handlers_githubwebhooks_test.go, internal/controlplane/handlers_repositories_test.go, internal/engine/executor_test.go, internal/providers/providers.go
When a provider doesn't have an associated token, use an empty credential.
=> Allow using empty credential if no token

internal/profiles/service.go
I inadvertently set the project ID of the profile to be the provider's project ID, not the project ID specified in the API request.
=> use correct project ID when creating profile

docker-compose.yaml, identity/config/stacklok.yaml
Let's downgrade Keycloak back to 23.0 since that's what we're using in staging and production.
This PR also adds the same realm configuration we're using in higher environments.
=> Update Keycloak to match staging and prod

internal/controlplane/handlers_profile.go
The following PR populates the Alert field for each rule evaluation status result as it was missing so far. It also generates a valid URL for the potential security advisory that was opened.
=> Add alert info to RuleEvaluationStatuses

database/migrations/000029_bundle_subscription.down.sql, database/migrations/000029_bundle_subscription.up.sql, internal/db/models.go, internal/db/projects.sql.go, internal/db/rule_types.sql.go
Relates to #2543
Define the subscriptions and bundles table. Add a foreign key reference to subscriptions in both the profiles and rule type tables.
=> Define DB schema for bundles and subscriptions

database/migrations/000030_subscription_profile_fk.down.sql, database/migrations/000030_subscription_profile_fk.up.sql, internal/db/models.go, internal/db/profiles.sql.go, internal/db/projects.sql.go
Mixed up profiles and projects again :(
=> Put subscription foreign key on correct table

internal/providers/providers.go
Just adds some debug information for the credentials instatiation
Pair-Programmed-With: Juan Antonio Osorio <ozz@stacklok.com>
N/A
=> Add debug information for credentials instantiation

cmd/cli/app/provider/provider_enroll.go
=> Add command line flag to skip browser spawning in provider enroll command

internal/controlplane/handlers_evalstatus.go
This reduces the extra number of project ID parsing by using the
entity context which has already been populated, parsed and validated.
=> `ListEvaluationResults`: Retrieve project ID from entity context

internal/providers/github/common.go
The GitHub provider was calling the wrong delegate function.
=> Use correct delegate for GitHub email

go.mod, go.sum, internal/events/eventer.go
It seems we were accidentally using v2 and not v3. v3 introduces
several fixes that might come in handy!
Fortunately, we're using the defaults, so the "breaking changes" don't
affect us.
=> Use watermill-sql v3 not v2

internal/controlplane/handlers_profile.go
Fixes the error messages in the logs where there's no alert but we still try to parse its URL.
=> Don't parse the alert metadata if there's no alert opened

database/migrations/000032_github_app_installations.down.sql, database/migrations/000032_github_app_installations.up.sql, internal/db/models.go
@evankanderson I broke out the table creation from https://github.com/stacklok/minder/pull/2681 because I'm about to add some code that needs to read from the table.
Ref #2520
=> Add GitHub App installations table

internal/controlplane/handlers_projects.go, internal/controlplane/identity_events.go, internal/projects/delete.go, internal/projects/delete_test.go
In order to better debug the recent race conditions we've seen in user/project deletion
this ads more logs.
=> Add more logging to user/project deletion

internal/engine/eval/homoglyphs/application/homoglyphs_service.go, internal/engine/eval/homoglyphs/application/invisible_characters_eval.go, internal/engine/eval/homoglyphs/application/mixed_scripts_eval.go
This fixes the issue where the homoglyphs profile was not updated based on violations found.
=> fix: homoglyphs status profile

internal/controlplane/identity_events.go
=> Add log message for transaction commit when deleting account

pkg/mindpak/sources/source.go, pkg/mindpak/sources/source_test.go, pkg/mindpak/types.go
As more parts of the code deal with bundles, this will make it more convenient to pass around the information needed to identify a bundle.
=> Add bundle ID structure

internal/controlplane/handlers_user.go
In case when user info is gotten while a project was deleted, we should just skip
the deleted project
Related #2751
=> Skip deleted projects while getting user

internal/controlplane/handlers_projects.go, internal/controlplane/handlers_user.go, internal/projects/create.go
This indicates to the user if the project they're trying to provision already exists; which may
prompt them to contact their minder administrators.
=> Return a user-visible error if the project already exists

internal/controlplane/handlers_profile_test.go, internal/controlplane/handlers_reconciliationtasks_test.go, internal/events/stubs/eventer.go
This moves the `StubEventer` into a dedicated package so it's re-usable and
cleaner.
=> Move stub eventer outside of tests and into dedicated package

database/migrations/000036_profile_label.down.sql, database/migrations/000036_profile_label.up.sql, database/query/profiles.sql, internal/controlplane/handlers_profile.go, internal/db/models.go, internal/db/profiles.sql.go, internal/marketplaces/namespaces/validation.go, internal/profiles/service.go
Extends the `profiles` table with an additional column that stores profile
labels. This was one way I was considering, the other was to normalize the tables
and have a separate profile_labels table and then a "join table" linking profiles with
labels.
The labels column is not indexed. After having experimented with a GIN index, it was apparent that the cost/benefit ratio is not there. Also, we found out that we don't index the `entity_profiles.profile_id` column which was actually more costly than scanning the individual rows for labels.
I decided to go with a simple additional column for now because while the indexing
would have been easier with a separate table, the application logic for creating
and updating profiles would be much involved as we'd have to store the labels and
the link …
=> Store labels for profiles in the database

internal/controlplane/server.go, internal/controlplane/server_test.go
Some fields on the server were left over from previous logic and unused.
=> Remove unused server fields

database/query/rule_types.sql, internal/controlplane/handlers_ruletype.go, internal/db/rule_types.sql.go, internal/engine/executor.go, internal/engine/executor_test.go, internal/profiles/service.go, internal/profiles/validator.go, internal/profiles/validator_test.go, internal/ruletypes/service.go
This removes the requirement for passing in the provider when working with rule types.
This allows us flexibility for working with multiple providers.
=> Remove provider requirement when fetching rule type

internal/controlplane/handlers_oauth_test.go, internal/controlplane/handlers_repositories_test.go
This removes the manually-maintained `StubGitHub` in favor us using
the auto-generated one.
=> Remove `StubGitHub` in favor of our existing mock

cmd/server/app/migrate_up.go
By now we've already deployed this and this temporary migration is ready
to be removed.
=> Remove github auth flows from migration

cmd/cli/app/auth/common.go
=> Fix logic for skipping browser on login

config/server-config.yaml.example, internal/config/server/config.go, internal/config/server/default_profiles.go, internal/controlplane/handlers_user.go, internal/controlplane/handlers_user_test.go, internal/controlplane/server.go, internal/marketplaces/namespaces/validation.go, internal/projects/create.go, internal/projects/create_test.go
Fixes #2542
Bundle and profile to install are defined in the service config.
=> Create healthcheck as part of project creation

internal/controlplane/common.go
This was feedback in https://github.com/stacklok/minder/pull/2802
=> Simplify error return in `getProviderFromRequestOrDefault`

deployment/helm/README.md, deployment/helm/templates/deployment.yaml, deployment/helm/values.yaml
Ref #2520
Read the secrets that are needed for the GitHub App providers.
Ref #2520
=> Read GitHub App secrets from config

deployment/helm/templates/deployment.yaml
It was not a valid secret reference. This fixes that.
=> Fix secret declaration in github app secret

internal/controlplane/common.go
This was feedback in https://github.com/stacklok/minder/pull/2802
=> Simplify `getNameFilterParam` in provider common functions

internal/config/common.go, internal/events/eventer.go
Add additional logs to find out why minder server is crashing.
=> Add additional info logs

internal/config/common.go
We've seen that Ping() might be blocking which defeats the purpose of
the loop. Let's use a dedicated timeout instead to properly time out the
ping.
local testing
=> Use conn.PingContext() instead of Ping() to avoid trying to connect with context.Background()

cmd/cli/app/repo/repo_register.go
This ensures the repo context is retained throughout the registration process.
=> Ensure repo context is retained in registration

cmd/cli/app/repo/repo_register.go
Instead, let's continue
if you typo a provider, the client would have crashed
=> Don't dereference result on error from RegisterRepository

internal/config/server/config.go, internal/config/server/config_test.go, internal/config/server/events.go
See https://github.com/stacklok/minder/pull/2822, which was an emergency revert to unblock Minder rollouts.  I'm going to work on a cleaner approach.
Fixes #2835
Added go tests; validated that the code pre-#2822 would fail the test, and the code pre-#2633 and post this PR both passed the test.
=> Add tests and remove empty-struct defaults that were previous ignored.

cmd/cli/app/profile/table_render.go, database/migrations/000041_remediate_metadata.down.sql, database/migrations/000041_remediate_metadata.up.sql, database/query/profile_status.sql, internal/db/models.go, internal/db/profile_status.sql.go, internal/db/profiles_test.go, internal/engine/actions/actions.go, internal/engine/actions/alert/security_advisory/security_advisory.go, internal/engine/actions/remediate/pull_request/pull_request.go, internal/engine/actions/remediate/pull_request/pull_request_test.go, internal/engine/errors/errors.go, internal/engine/eval_status.go, internal/engine/executor.go, internal/engine/executor_test.go, internal/engine/rule_type_engine.go, internal/providers/github/common.go, internal/providers/github/mock/github.go, pkg/providers/v1/providers.go
Re-applies the troublesome PR but also updates the migration to happen in a single transaction.
=> Re-applies the pending status change and uses a transaction for 000041 migration

internal/engine/eval/homoglyphs/application/homoglyphs_service.go, internal/engine/eval/trusty/trusty.go, internal/engine/eval/vulncheck/vulncheck.go, internal/engine/ingester/diff/diff.go, internal/engine/ingester/rest/rest.go
Fixes a bunch of flagged "problems" in VSCode -- tautological conditions, copying protos with the "please don't copy me" lock, etc.
`go test`; I verified that the logic change had coverage, but used my eyeballs and VSCode search for the proto change, as 2/3rds of the eval rules didn't have coverage.
=> Fix flagged problems in internal/engine

docs/package.json, docs/yarn.lock
The covers dependabot PRs #2874, #2875 and #2876, and ensures all versions are updated simultaneously.
=> Bump docusaurus from 3.1.1 to 3.2.0

internal/engine/executor.go
* **Disables ingest caching for Artifact entities.** 
The reasoning is artifacts are a bit different than the other entities. During the ingest step we actually check if there's provenance information for this artifact version (i.e. `stacklok/minder:latest`) and if the signature is not yet at the time of this evaluation, we ingest a result that says there's no signature found. 
The issue comes when the 2nd event comes in (the one about the actual signature) before the ingest expire time, we start to evaluate it but use the ingested cache from the 1st one which says - for this version, there's no provenance information available.
* **Adds a wait period for evaluating artifact entity events**
This is an after-effect from the 1st one. Now that we don't cache anything this …
=> Disable ingest caching for artifact entities and add a wait period

cmd/cli/app/artifact/artifact.go, cmd/cli/app/repo/repo.go, cmd/server/app/webhook_update.go, database/query/repositories.sql, internal/controlplane/common.go, internal/controlplane/handlers_artifacts.go, internal/controlplane/handlers_oauth.go, internal/controlplane/handlers_profile.go, internal/controlplane/handlers_repositories.go, internal/controlplane/handlers_repositories_test.go, internal/db/repositories.sql.go, internal/db/repositories_test.go, internal/providers/github/common.go, internal/reconcilers/run_profile.go, internal/repositories/github/mock/service.go, internal/repositories/github/service.go, internal/repositories/github/service_test.go
Ref #2522
This makes passing `--provider` optional. If no provider is specified then the command will apply for all providers in the project.
Ref #2522
=> Make provider an optional filter

docs/docs/ref/cli/minder_completion_bash.md, docs/docs/ref/cli/minder_completion_zsh.md
Fix the documentation formatting that the CI job keeps changing.
=> Fix documentation format

deployment/helm/README.md, deployment/helm/templates/deployment.yaml, deployment/helm/values.yaml
=> helm: Allow for configuring the termination grace period for the main deployment

deployment/helm/README.md, deployment/helm/templates/deployment.yaml, deployment/helm/values.yaml
We're currently using the Kubernetes' defaults, this allows us to configure
the strategy in a way that fits us best.
=> helm: Allow for configuring the Minder Deployment strategy

database/migrations/000045_gh_app_install_int.down.sql, database/migrations/000045_gh_app_install_int.up.sql, database/mock/store.go, internal/db/models.go, internal/db/provider_github_app_installations.sql.go, internal/db/querier.go, internal/providers/credentials/github_installation_token_credential.go, internal/providers/credentials/github_installation_token_credential_test.go, internal/providers/service.go, internal/providers/service_test.go
This came up in PR #2870, but doesn't need to be implemented as part
of that PR.
=> Migrate GH App installations to int64 from string

internal/controlplane/handlers_oauth_test.go, internal/controlplane/handlers_reconciliationtasks.go, internal/controlplane/handlers_reconciliationtasks_test.go, internal/controlplane/handlers_user_test.go, internal/controlplane/server.go, internal/controlplane/server_test.go, internal/engine/context.go, internal/engine/executor.go, internal/engine/executor_test.go, internal/service/service.go
Any time the engine needs a provider, go through ProviderStore. This will simplify future refactoring
=> Refactor engine code to use ProviderStore

cmd/cli/app/project/project_delete.go
=> Fixes a typo in the CLI - s/profile/project

internal/controlplane/handlers_repositories.go, internal/controlplane/handlers_repositories_test.go
Now that we have multiple providers, it's possible one will fail. That should not stop the execution if the other providers succeed. 
This updates the list remote repositories function to error only if all providers error. If one errors, then it logs the error and moves on to the next one.
=> Skip erroring providers when listing repos

cmd/dev/app/rule_type/rttst.go
Adjust to using github-app provider
Adjust to the recent remediation changes.
Example usage:
```
$ AUTH_TOKEN=topsecret REGO_ENABLE_PRINT=true go run cmd/dev/main.go ruletype test --profile /Users/jakub/devel/playground/codeql-go-py.yaml \
--rule-type /Users/jakub/devel/minder-rules-and-profiles/rule-types/github/codeql_enabled.yaml \
--entity /Users/jakub/devel/playground/repository.yaml \
--remediate-status=pending
--remediate-metadata=/Users/jakub/devel/playground/metadata_pr.json
```
see above
=> Fix mindev ruletype test

internal/controlplane/handlers_profile_test.go, pkg/api/protobuf/go/minder/v1/validators.go
Fixes #2944
In future, we may want more fine grained errors specifying the exact problem. This will require replacing the regex with some kind of parsing logic, so that is left as future work.
=> Change validation error message to describe max length

internal/db/repositories_test.go
CI tests were failing because of repo ID collisions.
=> Fix flaky DB list repos test

database/query/profile_status.sql, internal/db/profile_status.sql.go
=> Remove duplicate clause in profile status query

docs/docs/integrations/overview.md
Merely fills in the template. The detailed docs will go in their respective sections.
=> Fill in the integrations overview page

internal/controlplane/handlers_oauth.go, internal/controlplane/handlers_oauth_test.go
=> Validate query parameters in GitHub App callback

internal/controlplane/handlers_ruletype.go
Not a 500
```
curl -XGET  -H "Authorization: Bearer $MINDER_BEARER_TOKEN" 'http://localhost:8080/api/v1/rule_type/name/foo?context.project=c3db07ea-09e1-4109-855d-673a22dc953e&context.provider=github'
```
=> Return a nicer error message when a ruletype can't be found

docs/docs/integrations/oss_integrations.md
=> Add OSS integration documentation

docs/docs/understand/profiles.md, docs/docs/understand/providers.md
Update profile with examples of newer rules.
I originally changed the providers doc, but that is taking place in #3015 
=> Change sample profile to use newer rule types

docs/docs/integrations/providers.md, docs/docs/understand/providers.md
Moves around the providers docs
=> Modify docs on providers

database/migrations/000050_artifact_projects.up.sql
=> Artifact index for repos was not meant to be unique

internal/controlplane/handlers_providers.go
We shouldn't block the entire provider deletion operation if deleting a repository fails.
=> Proceed with provider delete if repo delete fails

docs/docs/about/contributing.md, docs/docs/about/roadmap.md
=> Add contributing to Minder docs section

docs/docs/how-to/custom-rules.md
=> Add docs content for writing custom rule types

internal/providers/github/common.go, internal/providers/github/mock/common.go, internal/providers/service.go, internal/providers/service_test.go
=> Avoid deleting GH App installation if already deleted

internal/engine/ingester/git/git.go, internal/providers/git/git.go, pkg/providers/v1/errors.go
This ensures that the policy engine skips a repository if it's empty.
This is done instead of returning an error which only confuses the user.
=> git ingester: Handle empty repository by skipping it

internal/providers/github/common.go, internal/reconcilers/repository.go
If a github App provider is enrolled but no fallback token configured through `GitHubAppConfig.FallbackClient` then the github config structure's `packageListingClient` will be `nil`. While this only affects the initial reconcile of the artifacts on repo registration and not retrieving the artifacts through webhook notifications, minder shouldn't crash.
The patch also checks the result for null because on error the result might be null but the err handler was dereferencing result unconditionally.
enroll with a github app without the fallback client
=> Don't crash if there's no package list client

deployment/helm/templates/deployment.yaml, internal/config/server/github_app.go, internal/providers/github/common.go, internal/providers/service.go
In our deployment we need to read the fallback token and webhook secret from files.
Fixes #3039
Fixes #3038
=> Allow reading secrets from file for GH App config

cmd/cli/app/provider/provider_enroll.go
Used the wrong method on the GRPC enum
Fixes https://github.com/stacklok/minder/issues/3043
=> Fix enrollment issue

cmd/cli/app/provider/provider.go
=> Hide deprecated flag from help

docs/docs/run_minder_server/config_oauth.md
This adds the docs for setting up a GitHub App. This is only for the OSS version of Minder, it is excluded from the downstream docs already.
=> Add docs for setting up GitHub App

docs/docs/integrations/_category_.yml, docs/docs/integrations/community_integrations.md, docs/docs/integrations/overview.md, docs/docs/integrations/providers.md, docs/docs/integrations/trusty.md, docs/docs/user_management/_category_.yml
Some documentation is not displaying properly because of missing titles.
=> Fix documentation sidebar titles

cmd/cli/app/repo/repo_register.go, cmd/cli/app/repo/repo_register_test.go, internal/util/cli/cli.go
This skips the step of listing the remote repos if there is already a
name given. At this point, the user already knows what repo they want to
register and these are merely extra calls to the provider that use the
rate limit.
=> skip remote repo listing if name(s) are given

internal/controlplane/handlers_githubwebhooks.go
=> Revert "Log webhook token type"

cmd/cli/app/repo/repo_register.go
This removes the invalid logic in the repo register subcommand which accidentally thought all repos were already registered in minder.
=> Fix invalid condition in repo register

internal/providers/github/app/app.go
Switch github request logging to Debug()
=> Log requests using Debug()

docs/docs/getting_started/_category_.yml, docs/docs/how-to/_category_.yml, docs/docs/integrations/_category_.yml, docs/docs/integrations/overview.md, docs/docs/ref/_category_.yml, docs/docs/understand/_category_.yml, docs/docs/user_management/_category_.yml
=> Reorder documentation headers

internal/controlplane/handlers_oauth.go
This returns a more user friendly error message when getting the
aforementioned error when setting up a provider.
=> Handle `bad_verification_code` error when doing OAuth2 flow

internal/controlplane/identity_events.go, internal/projects/delete.go, internal/projects/delete_test.go
Cleans up the definition of which projects are unmanaged, to avoid a particular bug that hit @ethomson
Added unit tests.  Did _not_ attempt a manual test, because I'm a bit pressed for time.
=> Delete (only) root projects if they have no admins (rather than any users)

docs/docs/how-to/writing-rules-in-rego.md
=> Add tutorial about writing rule types using rego

docs/docs/how-to/mindev.md
=> Add tutorial on using mindev

docs/docs/about/roadmap.md
Update the Minder roadmap — removing items that we've shipped, rearranging priorities for the things that are in-progress and next.
=> Update Minder roadmap

docs/docs/ref/managed_profiles.md
This belongs only in the downstream docs.
=> Remove managed profiles for OSS docs

README.md
=> Remove GitHub discussions from README

internal/controlplane/handlers_repositories.go
We passed the wrong ID.
`minder repo delete`
this was caught by smoke tests, so we'll have test coverage once this is merged
=> Fix repo deletion

docker/minder/Dockerfile, docker/reminder/Dockerfile, go.mod
=> Bump go base images to go 1.22.2

cmd/server/app/serve.go, cmd/server/app/webhook_update.go, internal/config/server/webhook.go, internal/controlplane/handlers_githubwebhooks.go, internal/controlplane/handlers_githubwebhooks_test.go, internal/repositories/github/fixtures/client.go, internal/repositories/github/webhooks/manager.go, internal/repositories/github/webhooks/manager_test.go
Complements reading the previous webhook secret from a file by allowing
to read the current one.
Fixes: #3160
make test, use the option
=> Read the webhook secret from a file

.trivyignore
The fix has long been merged and we may remove the ignore from here. I
had just forgotten to do so.
=> Remove last CVE from `.trivyignore`

cmd/dev/app/testserver/testserver.go, cmd/server/app/serve.go, internal/controlplane/handlers_githubwebhooks_test.go, internal/controlplane/handlers_oauth_test.go, internal/controlplane/handlers_providers_test.go, internal/controlplane/handlers_token.go, internal/controlplane/handlers_user.go, internal/controlplane/handlers_user_test.go, internal/controlplane/server.go, internal/controlplane/server_test.go, internal/reconcilers/reconcilers.go, internal/service/service.go
With some of the changes I've made, I have started to run into issues with the way we currently wire up the server, event handler and reconcilers:
1. The way in which structs are shared across events, server and reconcilers is a bit hacky, and will get more hacky when I start sharing more structs.
2. The functional options pattern is starting to cause complexity now that we need to wire up dependencies which depend on some of the structs passed by the options.
This moves most of the application wireup outside of `server.go` and into `service.go`. The optional parameters for the server are removed entirely, and are now passed in as explicit arguments. Various tests have been cleaned up to instantiate the Server directly with appropriate stubs for different dependencies. …
=> Refactor application wireup

internal/reconcilers/reconcilers.go, internal/reconcilers/repository.go, internal/service/service.go
Part of the ongoing decoupling of Provider-specific details from various parts of Minder.
=> Use ProviderManager in reconciler

internal/engine/ingester/artifact/artifact.go, internal/engine/ingester/artifact/artifact_test.go
This commit modifies the signer identity function in the artifact code to handle URIs evenly regardless of where they came from.
We trim the ref and return the path only to allow minder to create rules based on it regardless of the repository.
Fixes for the smoke tests
Epxande the function test to capture the full range of cases
=> Artifact: Unify signer identity URIs

docs/package.json, docs/yarn.lock
The covers dependabot PRs #3244, #3245, #3246 and #3247, and ensures all versions are updated simultaneously.
=> Bump docusaurus from 3.2.1 to 3.3.2

internal/verifier/sigstore/container/container.go
This will not be the case for other OCI providers, so let's start
checking for that now.
=> Surface bundle fetch error if gh client is not present

internal/engine/ingester/artifact/artifact.go, internal/engine/ingester/artifact/artifact_test.go
This PR modifies the `signerIdentityFromCertificate` function to ignore the signer from the cert extensions and instead use the identity from the certificate SAN as identity as [specified by sigstore](https://docs.sigstore.dev/certificate_authority/certificate-issuing-overview/#4--constructing-a-certificate).
Also, we now ensure that the parsing we do to the actions URLs used as identities is only done when a certificate was issued from an actions token. All other URIs found are returned verbatim.
/cc @jhrozek 
Updated the unit test with correct samples (correcting the wrong test cases from #3238)
=> Parse correctly github uris, dont use cert ext uri

deployment/helm/templates/deployment.yaml
This, without a feature flag file causes minder to crash.
Relates-to: #3259
Co-Authored-By: Michelangelo Mori <mmori@stacklok.com>
=> Workaround: Remove `MINDER_FLAGS_GO_FEATURE_FILE_PATH` env variable from helm deployment

.goreleaser.yaml
Goreleaser needs oapi-codegen installed to run go generate. This change adds an additional before-hook to address that.
=> Fix goreleaser dependencies.

CONTRIBUTING.md
=> small typo fix to CONTRIBUTING.md

docker-compose.yaml
There was an upgrade we hadn't applied
=> Upgrade to postgres 16.2 in docker-compose file

internal/engine/eval/vulncheck/report.go
Fixes table formatting in case of more than 1 row entry.
Related: https://github.com/stacklok/minder/issues/3368
=> Fix table formatting for found vulnerabilities

.goreleaser.yaml
Fixes the following warning - 
```
• DEPRECATED: brews.folder should not be used anymore, check https://goreleaser.com/deprecations#brewsfolder for more info
```
=> Update .goreleaser.yaml to fix a deprecation warning

internal/controlplane/handlers_providers.go, internal/controlplane/handlers_providers_test.go
Adds a Server.CreateProvider() handler that implements the already
existing grpc method. Adds tests.
Fixes: #3376
=> Add a CreateProvider rpc handler

cmd/cli/app/provider/provider_enroll.go
Config is already a global flag
manual
=> Rename the enroll flag from config to provider-config

internal/engine/eval/jq/fuzz_test.go
Adds a fuzz test for the JQ evaluator.
=> Add fuzz test for JQ eval

internal/controlplane/fuzz_test.go
Adds a fuzzer for the GitHub event parsers.
=> Add fuzzer for github event parsers

internal/crypto/fuzz_test.go
Adds a fuzzer that encrypts and decrypts a string.
=> add fuzz test for crypto package

internal/authz/fuzz_test.go
Adds a fuzzer for the authz APIs.
=> add fuzz test for authz package

internal/auth/fuzz_test.go
Adds a fuzz test for `ParseAndValidate`.
=> add fuzz test for auth package

docs/docs/ref/proto.md, pkg/api/protobuf/go/minder/v1/minder.pb.go
There appears to be some changes missing from main.
=> Rerun make gen

deployment/helm/templates/rotate_provider_tokens.yaml, deployment/helm/templates/session_expiration_purge_job.yaml, deployment/helm/values.yaml
This adds jobs so we can purge sessions and rotate provider secrets in
an automated fashion.
Related-To: #3315
=> Add cron jobs to helm chart to purge and rotate secrets

deployment/helm/templates/rotate_provider_tokens.yaml, deployment/helm/templates/session_expiration_purge_job.yaml
This was needed explicitly... for some reason :/
=> Add db host CLI argument to newly included jobs

deployment/helm/templates/session_expiration_purge_job.yaml
We don't want to give these jobs database schema change privileges. So
let's just use the minder config there instead.
=> User `minder-config` for secret cleanup/rotation jobs

deployment/helm/templates/rotate_provider_tokens.yaml
=> Use `minder-config` for rotation job

deployment/helm/templates/rotate_provider_tokens.yaml
=> Actually mount key directory in rotation job

internal/providers/github/manager/manager.go
We're seeing issues in staging that are hard to debug because we don't log the error
make build
=> Log error when unable to fetch credentials

docs/package.json, docs/yarn.lock
The covers dependabot PRs #3492, #3491, #3490 and #3489, and ensures all versions are updated simultaneously.
=> Bump docusaurus from 3.3.2 to 3.4.0

.clusterfuzzlite/Dockerfile, .clusterfuzzlite/build.sh, .clusterfuzzlite/project.yaml, .github/workflows/cifuzz.yml, internal/crypto/fuzz_test.go
Adds a [ClusterfuzzLite](https://google.github.io/clusterfuzzlite/) workflow that runs Minders fuzzers for 100 seconds when pull requests to main are made. CFLite builds the fuzzers in a container and then runs them.
=> Add ClusterfuzzLite

internal/engine/ingester/diff/parse.go
This was spotted during a code review, but the code was unfortunately
merged before.
unit tests
=> Simplify slice checks in go parser

.github/workflows/releaser.yml, .goreleaser.yaml
Update goreleaser to v2
Did `goreleaser check `
=> Update goreleaser to v2

internal/engine/executor.go
This got moved during refactoring and it needs to be set before the actions take place.
=> Set evaluation errpr immediately after evaluation

docker/minder/Dockerfile, docker/reminder/Dockerfile, go.mod, tools/go.mod
Update go version in go.mod and dockerfiles.
=> Bump go to v1.22.4

database/mock/store.go, database/query/invitations.sql, internal/db/invitations.sql.go, internal/db/querier.go
The following PR updates the necessary queries related to supporting user invitations.
One of the few splits from https://github.com/stacklok/minder/pull/3649
=> Add db queries related to the user_invites table

database/migrations/000070_evaluation_history_most_recent.down.sql, database/migrations/000070_evaluation_history_most_recent.up.sql, internal/db/models.go
This will make it easier to sort the rows by date/time.
Relates to: #3556
=> Store most recent evaluation time in dedicated column

.mk/identity.mk
The following PR updates make password-login to add an email and attributes
=> Update make password-login to add an email and attributes

internal/invite/invite.go
The following PR adds a function for generating user invites.
It uses randomly generated 48 bytes which are then base64 encoded.
I wasn't sure if we should encrypt this but if you think it's necessary we can update it (best to happen in a follow up so we don't block other efforts)
=> Add function for generating user invites

docs/docs/getting_started/register_repos.md, docs/docs/integrations/provider_integrations/github.md, docs/docs/understand/providers.md
Summarizes the current state in minder OSS documentation
Related: #3458
build and read the docs
=> Add docs for provider auto-registration

internal/invite/invite.go
Use URL safe encoding instead of standard one (including `/` )
=> Use URLEncoding instead of Std for base64

internal/invite/invite.go
The following PR adds helper functions for checking/setting invite expiration. Also sets the const scope to local as they are not really meant to be used in other way.
Split from #3689 
=> Add helper functions for checking/setting invite expiration

internal/controlplane/handlers_authz.go
The following PR allows a user to remove their own role from a project. That is unless they are the last admin (ref. https://github.com/stacklok/minder/pull/3715)
=> Allow a user to remove their own role from a project

internal/email/email.go
The following PR updates the terms and privacy URLs in the invite email.
=> Update the terms and privacy URLs in the invite email

internal/email/email.go, internal/email/template.go
Tweak the padding and background color for the email template.
Manual email send
=> Invite email: color and padding changes

internal/controlplane/handlers_user_test.go
This adds unit tests for the `ListInvitations` and `ResolveInvitation` methods.
Fix #3669
=> Add unit tests for ListInvitations and ResolveInvitation

docker/minder/Dockerfile, docker/reminder/Dockerfile, go.mod, tools/go.mod
Release notes: https://go.dev/doc/devel/release#go1.22.minor
=> Bump minder to go 1.22.5

internal/controlplane/handlers_authz.go
This makes the error message more instructive when a user belongs to multiple projects and they haven't specified which project they want to run the command for.
=> Update error message when no project is specified

internal/authz/model/minder.fga
The following PR updates the `entity_reconcile` resource to require the `admin` role
Fixes https://github.com/stacklok/minder/issues/3794
=> Update openfga entity_reconcile to require the admin role

database/migrations/000073_evaluation_statuses_timestamps_with_timezone.down.sql, database/migrations/000073_evaluation_statuses_timestamps_with_timezone.up.sql
There's no such thing as no timezone.
Manual tests.
=> Timestamps for evaluation statuses have time zone.

sqlc.yaml
This makes it easier to reuse examples from the documentation.
=> Use Version 2 config for sqlc.yaml

internal/engine/metrics.go
The code was counting them against the eval status counter
=> Fix remediation/alert counter

cmd/cli/app/history/history_list.go
Option `--rule-name` was meant to be used as filter on rule names, but we decided not to implement it for now as its usefulness is still under discussion.
The option was unused.
=> Removed option from `minder history list`.

internal/engine/actions/alert/security_advisory/security_advisory.go
Since we have generally received negative feedback about these alerts, do not default to On.
=> Default security advisory alerts to Off

internal/controlplane/handlers_profile_test.go
Was meant to be part of #3951 but forgot to commit it :(
=> Remove even more unused code

internal/controlplane/handlers_evalstatus.go
=> Enable history log rpc.

database/migrations/000076_evaluation_entity_type.down.sql, database/migrations/000076_evaluation_entity_type.up.sql, database/query/eval_history.sql, internal/db/eval_history.sql.go, internal/db/models.go, internal/history/service.go
This simplifies some queries which I am working on in another PR.
A subsequent PR will backfill the column for existing data, and make the column non-nullable.
=> Add entity_type column to evaluation_rule_entities

internal/controlplane/handlers_evalstatus.go, internal/history/service.go
Previously they were supressed, making debugging more difficult
=> Log errors from history service

internal/engine/selectors/selectors.go, internal/engine/selectors/selectors_test.go, internal/proto/internal.pb.go, internal/proto/internal.proto
This is more or less for completeness' sake. Both Ozz when reviewing the original code and Giuseppe when implementing the FE side of things were surprised that the selector API didn't handle PRs.
Fixes: #3988
mostly unit tests tbh
=> Add PullRequest as available entity for selectors

internal/reconcilers/repository.go, internal/repositories/github/service.go
I've seen a number of errors relating to repo lookups in the logs. Adding some details to provide more context.
=> Add more context around repo lookup failures

identity/config/stacklok.yaml
Update the local keycloak docker image to have the same configuration as the deployed Keycloak in staging.
This makes local testing and verification more reliable.
=> Update local Keycloak image to match deployed config

internal/controlplane/handlers_repositories.go
We seem to have an issue with listing repos in the Oauth smoke test flow. This should provide us with more context about what is going on.
=> Log errors when listing repositories

pkg/api/protobuf/go/minder/v1/minder.pb.gw.go, tools/go.mod, tools/go.sum
Applies #4010 with the applied changes to the output files.
Fixes #4010
The other output passed tests, and this only changes comments.
=> Re-apply #4010

internal/providers/github/selector_entity.go, internal/providers/selectors/interface.go, internal/providers/selectors/mock/interface.go, internal/providers/selectors/selector_entity.go, internal/providers/selectors/selector_entity_test.go
Add a converter that converts from a pull request entity to a selector entity.
This also fixed the smoke tests.
Fixes #4027
=> Add converter for PR selector

database/migrations/000080_drop_entity_profile_rules.down.sql, database/migrations/000080_drop_entity_profile_rules.up.sql, internal/db/models.go, pkg/api/protobuf/go/minder/v1/minder.pb.gw.go
This table is no longer used, drop it.
=> Drop `entity_profile_rules` table

cmd/cli/app/profile/get.go
The following PR fixes the `minder profile get` json/yaml output to include the full response.
Fixes https://github.com/stacklok/minder/issues/4034
=> Fix the profile get json/yaml output to include .profile

deployment/helm/README.md, deployment/helm/templates/deployment.yaml, deployment/helm/values.yaml
This allows us to set up affinity/anti-affinity rules for Minder via the helm chart
=> Add affinity configuration to helm chart

go.mod, go.sum, internal/email/awsses/awsses.go
=> Use AWS SDK v2 in SES code

deployment/helm/templates/rotate_provider_tokens.yaml, deployment/helm/templates/session_expiration_purge_job.yaml
This makes it easier for us to find the logs (or filter for them) in our
infrastructure.
=> Add k8s labels to session expiration purge and rotate provider token jobs

internal/authz/interface.go
The following PR aligns role descriptions with the docs
Fixes #4061 
=> Align role descriptions with the docs

internal/email/email.go, internal/email/template.go
The following PR updates the email template for invitations
Fixes #4063 
=> Update the email template for invitations

docker-compose.yaml, identity/config/stacklok.yaml
Update the version of the local Keycloak docker image to match what's in staging and production.
=> Use Keycloak v25 image for local development

database/query/eval_history.sql, internal/db/eval_history.sql.go, internal/engine/eval_status.go, internal/engine/executor_test.go, internal/engine/ingester/artifact/artifact.go, internal/engine/ingester/builtin/builtin.go, internal/engine/ingester/diff/diff.go, internal/engine/ingester/git/git.go, internal/engine/ingester/git/git_test.go, internal/engine/ingester/rest/rest.go, internal/engine/ingester/rest/rest_test.go, internal/engine/interfaces/interface.go, internal/entities/checkpoints/checkpoints.go, internal/entities/checkpoints/checkpoints_test.go, internal/history/mock/service.go, internal/history/service.go, internal/history/service_test.go
Reverts stacklok/minder#4059 because it broke staging (potential nil reference)
=> Revert "Persist checkpoints in evaluation history db"

docs/docs/user_management/adding_users.md, docs/docs/user_management/user_roles.md
Swapped order of roles in user management docs
Fixes #4073
=> Swapped order of roles in user management docs

internal/db/eval_history_test.go
Adds back `checkpoint` column to history log tests fixtures.
Integration tests.
=> Add missing column to history log tests' fixtures.

.github/workflows/generation.yml
Replace deprecated actions.
Fix #4099
=> Use non-deprecated buf-action in CI

.github/workflows/generation.yml
The new action was running the push and archive commands by default. This disables them.
Ref #4099
=> Disable additional buf commands in CI

internal/engine/executor_test.go
Use real repository selector in executor tests instead of mock.
Fixes #4017
=> Use non-mock selectors in executor test

internal/repositories/github/service.go, internal/repositories/github/service_test.go
=> Delete repos from the central entities table

internal/engine/eval/vulncheck/report.go
=> Update no vulnerabilities message in PR review rule

internal/authz/interface.go, internal/email/email.go, internal/email/template.go
The following PR fixes the role verb wording in the template for the invite email.
Fixes #4153 
=> Fix the role verb wording in the template for the invite email

.goreleaser.yaml
We were only writing the signature but not the certificate, which is
needed for verification.
=> Set a certificate output for goreleaser's signature step

internal/controlplane/handlers_githubwebhooks.go, internal/controlplane/handlers_githubwebhooks_test.go
Repository deletion events coming from repository webhooks (not app webhooks) were encoded in the wrong way, making downstream deletion handler fail on validation.
This change fixes the logic by encoding a different payload in case of deletion. Further changes will be necessary to encapsulate entity-specific messages in a more general envelope in order to handle deletions of other entities as well without introducing additional infrastructure (i.e. watermill topics).
Unit tests and manual tests.
=> Fix webhook event on repository deletion.

internal/controlplane/handlers_evalstatus.go
Previously, an if statement contained multiple clauses, one of which was missing a `!`. This led to an error being returned when nothing was wrong. This in turn led to empty evaluation statuses in `ListEvaluationResults`.
The problem which the error check was detecting was largely cosmetic, so I have decided to remove the if statement. I also changed the original error handling logic slightly - the code previously would insert empty evaluation responses into the response if an error was encountered. Change the logic to avoid creating these empty statuses. …
=> Fix issue with missing evaluation results

.github/workflows/codeql.yml
CodeQL was having a hard time building minder, this helps it out by
specifying the manual build configuration and running `make build`
=> CodeQL: Specify manual build

docker-compose.yaml
This ensures we get patch upgrades quickly when running out compose.
=> Use 25.0 keycloak tag instead of patch-specific one

database/query/entity_execution_lock.sql, internal/db/entity_execution_lock.sql.go, internal/db/entity_execution_lock.sql_test.go, internal/eea/eea.go
This reverts commit 345b8e8ffa2a60055e19f70d27c8fa15b349cff7.
=> Revert "EEA: Rely solely on entity instances table (#4287)"

internal/controlplane/register_handlers.go, internal/controlplane/server.go
Register the new RuleType service server.
Manually tested on local environment.
=> Register RuleType GRPC server.

internal/events/nats/natschannel_test.go
Let's just skip the test until we fix it properly.
Related: #4312
N/A
=> Skip the flaky NATS test until it's fixed

internal/entities/properties/service/service.go
We started seeing too many requests to upstream. Increasing the timeout
might alleviate that as long as we're requesting the same properties.
N/A
=> Bump the properties timeout

internal/engine/eval/trusty/trusty.go
=> Trusty: Print dependency name and version if fetching their data fails

internal/controlplane/handlers_githubwebhooks.go, internal/controlplane/handlers_githubwebhooks_test.go
Handle `synchronize` events on github PRs.
Manual and unit tests.
=> Handle `synchronize` events on github PRs.

database/query/eval_history.sql, internal/db/eval_history.sql.go, internal/db/eval_history_test.go
Fix `GetEvaluationHistory` from clause.
Manual and integration tests.
=> Fix `GetEvaluationHistory` from clause.

internal/eea/eea.go
This changes the logic to check that an entity exists as part of a transaction
before trying to lock it in the EEA. This way we'd avoid race conditions of trying
to lock an entity that gets deleted at the same time.
=> EEA: Only lock if entity instance exists in a transaction

docs/docs/how-to/profile_selectors.md
Since we can now use properties in selectors, let's document the
available properties.
N/A
=> Extend selectors documentation with properties

database/query/entities.sql, internal/controlplane/handlers_entities.go, internal/controlplane/handlers_entities_test.go, internal/controlplane/handlers_repositories.go, internal/controlplane/handlers_repositories_test.go, internal/db/entities.sql.go, internal/providers/manager/manager.go, internal/providers/manager/manager_test.go, internal/providers/manager/mock/manager.go, internal/repositories/mock/fixtures/service.go, internal/repositories/mock/service.go, internal/repositories/service.go
This is part of generalizing entity registration, as other providers
will need to work with this mechanism. As part of the migration, this
moved the logic to use our new entity model.
Related-To: https://github.com/stacklok/minder/issues/4331
Closes: https://github.com/stacklok/minder/issues/4420
=> Use central entity tables to list remote repos

docs/docs/about/changelog.md
Update Minder's roadmap for September 2024
n/a
=> Update changelog for September 2024

internal/controlplane/handlers_githubwebhooks.go, internal/engine/entities/entity_event.go
Commit 300d857 removed the only function that was using it.
Tests ran locally.
=> Remove `WithActionEvent` since no longer needed.

internal/entities/properties/service/helpers.go
The condition was wrong... This makes it so that data is marked as valid
if the time-range is fine or if we can tolerate it.
=> Fix tolerating stale data in properties service

internal/profiles/service.go
=> Fix linting error

docs/docs/understand/alerts.md, docs/docs/understand/remediations.md, docs/docs/understand/rule_evaluation.md
Include information about the way minder evaluates rules, the possible statuses, and how users can view them.
=> Add rule evaluations document

cmd/dev/app/rule_type/rttst.go, internal/controlplane/server.go, internal/providers/gitlab/gitlab.go, internal/providers/gitlab/manager/manager.go, internal/providers/gitlab/manager/webhook.go, internal/providers/gitlab/properties.go, internal/providers/gitlab/registration.go, internal/service/service.go
This implements the webhook creation and deletion for gitlab.
=> Implement repo register/deregister for gitlab

internal/service/service.go
=> Only set up optional provider managers if feature flags are enabled

internal/providers/gitlab/gitlab_rest.go, internal/providers/gitlab/gitlab_rest_test.go, internal/providers/gitlab/registration.go, internal/providers/gitlab/repo_lister.go
=> Add tests and small refactor for gitlab REST interfaces

internal/providers/github/manager/manager.go, internal/providers/gitlab/manager/auth.go
A recent change ended up initializing them. This ensure that we deal
with these initialized values.
=> Account for nil values in OAuth configuration

internal/engine/ingester/diff/diff.go, internal/providers/github/properties/pull_request.go
This should not matter as int == int64 on 64bit architectures IIRC but
let's silence the code scanning alerts.
make build
=> Check PR number value before casting from int64 to int

MAINTAINERS.md
@Vyom-Yadav has contributed a number of changes and features to Minder, and is an expert in some areas of the code already.  He's agreed to be our first outside-Stacklok maintainer; I've already committed a PR to grant him `push` ("write") permissions on the repo.
https://github.com/stacklok/minder/commits/main/?author=Vyom-Yadav
TODO: we need a different form for these governance-type PRs.  :grin:
=> Add Vyom-Yadav as a maintainer

internal/providers/gitlab/registration_test.go
=> Add unit tests for gitlab entity registration

internal/engine/eval/vulncheck/vulncheck.go
Templated used to produce details for `vulncheck` engine was expecting a list of string under `"packages"` key.
Manual tests.
=> Fix arguments passed to `vulncheck` template.

internal/engine/eval/trusty/actions.go
`/report` was prepended to the path, this reflects that.
=> Use new path for trusty package URLs

.github/workflows/security.yml
In order to cache the vuln db image and not get rate limited as much,
this joins the security scanns to one workflow.
=> Use one workflow for trivy

internal/entities/properties/service/service.go
=> Replace `repository` for `entity` in properties service

internal/entities/properties/service/service.go
It doesn't always update, let's just keep it simple to indicate that
fetching happened.
=> Slight modification in properties fetch log

internal/controlplane/identity_events.go
Follow-on to #4615
Fixes #4614
I didn't, sorry!
=> Adjust deadline on admin identity events as well as user events

cmd/dev/app/rule_type/rttst.go
This allows us to have a more general protobuf construction, thus making
other providers work well with mindev.
=> `mindev`: Use provider to construct entity protobufs

docs/docs/about/changelog.md, docs/docs/about/roadmap.md
Update the changelog and the roadmap based on recent ships. 🚢 
Local testing & review
=> Update changelog and roadmap

internal/engine/eval/templates/templates.go, internal/engine/eval/templates/trustyTemplate.tmpl, internal/engine/eval/trusty/trusty.go, internal/engine/eval/trusty/trusty_test.go
Add an evaluation details template for the Trusty ruletype.
This will be displayed on the UI to give the user a better understanding of why the rule failed.
Fixes https://github.com/stacklok/minder-stories/issues/38
=> Add eval details template for Trusty rule

internal/providers/gitlab/manager/webhook_handlers.go
This passes all the necessary info for origination to work for gitlab
PRs. There was an ordering issue in IDs that we were passing and we were
missing the unique internal ID when originating. Now it works.
=> gitlab: Fix PR origination

internal/providers/gitlab/properties.go, internal/providers/gitlab/pull_request_properties.go, internal/providers/gitlab/repository_properties.go
This makes functions easier to find.
=> cleanup/gitlab: Move repo and PR functions to relevant files

internal/providers/gitlab/manager/webhook.go, internal/providers/gitlab/manager/webhook_handlers_merge_requests.go, internal/providers/gitlab/manager/webhook_handlers_repos.go
The intention is to make handlers easier to find.
=> gitlab: Move webhook handler functions to dedicated files

internal/engine/eval/homoglyphs/application/invisible_characters_eval.go, internal/engine/eval/homoglyphs/application/invisible_characters_eval_test.go, internal/engine/eval/homoglyphs/domain/invisible_characters.go, internal/engine/eval/homoglyphs/domain/invisible_characters_test.go, internal/engine/eval/homoglyphs/domain/violation.go, internal/engine/eval/templates/invisibleCharactersTemplate.tmpl, internal/engine/eval/templates/templates.go
Add a template for the evaluation details message of the rule `homoglyphs/invisible_characters`.
Fixes https://github.com/stacklok/minder-stories/issues/40
=> Add eval details template for invisible characters

internal/auth/keycloak/keycloak.go
Before we settled on sending user invitations for new project users, I had the idea that we could automatically create GitHub-linked accounts in Keycloak.  We're not doing that, so remove the supporting code.
Fixes #4683
Unit tests still pass.
=> Remove dead code that was added speculatively

internal/controlplane/handlers_githubwebhooks_test.go
This allows for either message to be parsed first.
Fixes #4710
=> fix flaky `installation_repositories added` test from `TestHandleGitHubAppWebHook`

internal/history/service.go
We were looking up the same entity over and over again in
ListEvaluationHistory. Let's look up each entity just once, then cache
the properties.
This doesn't really increase the memory usage of the handler as we'd be
keeping the entity around anyway. With this change, we just keep a map
of UUID-to-pointer around for faster lookups.
Related: #4690
I used a bunch of debug printfs to check that the first time the entity is looked up in the
cache and then subsequently in the map.
=> Don't look up the same entity multiple times in ListEvaluationHistory

internal/entities/properties/service/helpers.go, internal/entities/properties/service/service.go
They serve very little purpose except local debugging, pollute our logs
and have performance impact.
Related: #4690
just visual, I made sure the log messages are gone
=> Remove most zerolog messages from the properties service

internal/providers/gitlab/manager/webhook_handlers_releases.go
=> Handle gitlab release deletion

.github/workflows/test.yml
This separates the step of downloading dependencies so it doesn't affect
the timeout for a single step.
=> Explicitly do `go mod download` in CI

internal/repositories/mock/service.go, internal/repositories/service.go
Since we finally migrated to the new handlers completely, we can remove
this temporary code.
go vet
=> Remove unused RefreshRepositoryByUpstreamID

internal/engine/eval/jq/jq.go, internal/engine/eval/jq/jq_test.go, internal/engine/eval/templates/jq.tmpl, internal/engine/eval/templates/templates.go
Fixes https://github.com/stacklok/minder-stories/issues/41
=> Add eval details template for JQ

.goreleaser.yaml
This was missing and it tried to push the assets to the stacklok org.
=> Set `mindersec` as "release" owner in goreleaser config

.github/workflows/test.yml, .mk/test.mk
This converges the test and the cover actions into one. Having two is
wasteful and the benefit unclear.
=> Output test coverage from unit tests action

internal/events/nats/natschannel_test.go
Fixes NATS test to pass (in 1000/1000 runs on my Macbook)
Reworked timeouts after some examination to allow the test to run _much_ faster (0.011s vs 25s)
`go test -count 1000 ./internal/events/nats`
=> Re-enable NATS test

internal/auth/keycloak/client/client.gen.go, internal/auth/keycloak/client/client.go, internal/auth/keycloak/client/keycloak-api.yaml
The v24 link we were using is no longer available. This uses v25 which
we've switched to in the project and uses a valid link.
Note that I ran `make gen`, so most changes come from that.
=> Fix auto-generated keycloak client

.github/workflows/chart-publish.yml, .github/workflows/compose-migrate.yml, .github/workflows/image-build.yml
This is breaking our CI.  Example:
https://github.com/mindersec/minder/actions/runs/11508040243/job/32035580726
Ref: https://github.com/ko-build/ko/issues/1433
Checked the upstream, read the comments
=> ko-build/ko broke their latest v0.17.0 release

internal/events/events.go
The following PR removes a duplicated if statement 
=> Remove duplicated if statement in NewEventer

docs/package-lock.json, docs/package.json
This combines PRs #4871, #4872, #4873 and #4874 into a single PR
=> Update docusaurus to 3.6.0

.github/dependabot.yml
The following PR groups docusaurus PRs into a single dependabot update group.
=> Group docusaurus PRs into a single update group

pkg/api/protobuf/go/minder/v1/validators.go
This adds rego module parsing as part of the rule type validation. This
enables us to catch errors faster as opposed to needing to evaluate a
policy to figure out if the rule type was valid.
If we have a rule with invalid rego, we'd get errors as follows:
```
$ mindev ruletype lint -r rule-types/github/no_binaries_in_repo.yaml
error validating rule type from file rule-types/github/no_binaries_in_repo.yaml: invalid rule type
invalid rule type definition: rego definition is invalid: 1 error occurred: minder-ruletype-def.rego:16: rego_parse_error: unexpected eof token
msg := sprintf("Binary artifact found: %s", [current_file])
^
Error: failed linting rule type
Message: Error on execute
Details: failed linting rule type
```
***Outline how the …
=> Validate rego when parsing rule types

cmd/cli/app/ruletype/ruletype_get.go, cmd/cli/app/ruletype/ruletype_list.go
Related-to: https://github.com/mindersec/minder/issues/4623
=> cli: Print rule types as applyable YAML

cmd/cli/app/profile/get.go, cmd/cli/app/profile/list.go
This follows https://github.com/mindersec/minder/pull/4936 and prints
profiles as individual YAML documents.
Closes #4623
=> cli: Print profiles as applyable YAML

internal/engine/eval/jq/jq_test.go, internal/engine/rtengine/cache_test.go, pkg/api/protobuf/go/minder/v1/validators.go, pkg/api/protobuf/go/minder/v1/validators_test.go
Check that JQ query is valid and parsable at the time the ruletype is created or updated.
=> Validate JQ query during ruletype creation/update

pkg/api/protobuf/go/minder/v1/validators_test.go
Rego validation was already added in https://github.com/mindersec/minder/pull/4906. This adds some additional tests.
=> Add tests for rego validation in ruletypes

internal/util/schemaupdate/schemaupdate.go
This code is kind of funky, and having comments makes it a little more
understandable.
=> Add more code docs for the `required` field validation

cmd/cli/app/history/history_list.go
Fixes stacklok/minder-stories#102
Manual testing.
=> Add support for labels to `minder history list`.

internal/controlplane/handlers_ruletype.go
Make the ruletype validation errors visible to the user, so they get guidance on what to fix.
=> Surface ruletype validation errors to user

internal/engine/eval/rego/datasources.go
This was accidentally left behind in another PR.
=> Remove leftover printf

pkg/api/protobuf/go/minder/v1/validators.go, pkg/api/protobuf/go/minder/v1/validators_test.go
Validate the remediate section of ruletypes.
Also add validation for rest type ingestion.
=> Validate ruletype remediation during creation/update

pkg/querier/bundle.go
The following PR adds queries for:
* Upserting a bundle
* Getting a bundle ID
* Creating a bundle subscription for a project
=> Add more queries for managing bundles and subscriptions

cmd/dev/app/rule_type/rttst.go, pkg/api/protobuf/go/minder/v1/validators.go
This allows us to validate that the different pieces of the data source
protobuf object are valid and usable.
=> Implement validation functions for Data Source protobuf object

pkg/api/protobuf/go/minder/v1/validators.go
This is a leftover spotted by @teodor-yanev
=> Remove `GetRest` leftover from datasources API validator.

database/mock/store.go, database/query/datasources.sql, internal/datasources/service/service.go, internal/datasources/service/service_test.go, internal/db/datasources.sql.go, internal/db/querier.go
- **add: datasource update**
- **remove: redundant receiver**
Fixes: https://github.com/mindersec/minder/issues/5046
=> Add Datasources Update

cmd/cli/app/datasource/common.go
This pre-emptively validates data source structures from the client
before we do the actual call to the server. This avoids a round-trip and
gives results a lot faster.
=> cli: Validate data sources before server calls

internal/controlplane/handlers_datasource.go, internal/datasources/service/service.go
The following PR implements the Create handler for data sources
Ref: https://github.com/mindersec/minder/issues/5042
=> Implement the Create handler for data sources

database/mock/store.go, database/query/datasources.sql, internal/db/datasources.sql.go, internal/db/querier.go
Add insert statement for `rule_type_data_sources` table.
Note: I'm not adding a statement for bulk inserts for two reasons, (1) we don't expect rule types to use hundreds of data sources, but a handful, and (2) writing bulk statements for `sqlc` is a huge pain.
Code is 100% autogenerated.
=> Add insert statement for `rule_type_data_sources`.

internal/engine/ingester/deps/deps_test.go
This pr fixed a race in the deps get branch test when running in parallel
Fixes #5075
=> Fix race in deps branch test

internal/util/helpers.go
=> Explicitly check server name in client TLS configuration

internal/controlplane/handlers_ruletype_test.go
=> Add test for listing ruletypes

internal/datasources/service/service.go
This PR fixes a bug where the data source ID was not returned when updating it via the service.
Before: 
```
🦆❯ go run ./cmd/cli/ datasource apply -f datasource.yaml 
+--------------------------------------+----+---------------------------+--------------+
|              PROJECT ID              | ID |           NAME            | DESCRIPTION  |
+--------------------------------------+----+---------------------------+--------------+
| 132f82e7-4a49-443c-a567-b727be190154 |    | dependencies (type: REST) | dependencies |
+--------------------------------------+----+---------------------------+--------------+
```
Now:
```
🦆❯ go run ./cmd/cli/ datasource apply -f …
```
=> Fix missing data source id in update

internal/datasources/rest/handler.go, internal/datasources/service/helpers.go, internal/datasources/service/service.go, internal/datasources/service/service_test.go, pkg/datasources/v1/datasources.go, pkg/datasources/v1/mock/datasources.go
This hooks in the update validation that's enforced by the data sources
interfaces. This means, we validate that if you do an update to a data
source the update is backwards compatible.
We do this by checking that you're not deleting functions via an update
and that any functions you modify pass our schema update validation.
In the future, we could allow folks to delete functions via a `force`
flag in the API.
=> data sources: Validate individual function updates

.github/workflows/pr-check.yml
When reusing this action elsewhere, I noticed that its status would be cleared if additional commits were pushed to the PR branch. Triggering on the synchronize event ensures that it will be checked on subsequent commits.
=> Run PR check action on `synchronize`

internal/deps/scalibr/scalibr.go
I noticed this before vacation, and apparently Ozz ran into it as well.
Manual testing along with reading the stack trace to locate the problem.
=> Exclude go binary scanner from scalibr, as it sometimes panics on python repos

internal/engine/ingester/git/git.go
This is useful for writing simple rules that check out the git repo for
a pull request.
=> Allow `git` ingester to work on Pull Requests as well

cmd/cli/app/datasource/datasource.go
The following PR registers the project flag for the `minder datasource` CLI command
Fixes https://github.com/mindersec/minder/issues/5187
=> Register the project flag for minder datasource

README.md
Renames stacklok to mindersec now that we made the switch.
=> Replace the winget reference from stacklok to mindersec

internal/providers/github/properties/pull_request.go, internal/providers/github/properties/repository.go
These were missing and are needed for relying less on hardcoded keys and
moving towards a property-based system.
=> Output GitHub properties for repos and pull requests

internal/providers/github/clients/app.go
By giving an explicit name, we're actually able to get the app's user ID
as opposed to trying to get the ID of an app instance which results in a
403.
=> Actually attempt to get the GitHub app's user ID

docs/docs/how-to/mindev.md
=> Fix mindev linting command

pkg/profiles/rule_validator_test.go
Our `make test` target wasn't aware of the `.testdata` directories and was treating yaml files within those directories as ruletypes.
=> Skip testdata yaml files

pkg/querier/datasource.go, pkg/querier/querier.go, pkg/querier/ruletype.go
This can be used to update bundles from an external service.
=> Expose data source operations to Querier

MAINTAINERS.md
=> Add myself to the list of maintainers

internal/engine/eval/trusty/actions.go
This was supposed to be part of #5390 but I forgot to add it
=> Rename Trusty to Stacklok Insight

pkg/querier/datasource.go
Add `ListDataSourcesByProject` to querier so it can be called by external services.
=> Expose data source list method to querier

pkg/querier/querier.go
The querier needs to data source service to query the data source tables.
=> Add data source service to querier

docs/docs/how-to/writing-rules-in-rego.md, internal/engine/eval/rego/lib.go, internal/flags/constants.go
Remove feature flag and update documentation.
Fix #5430
=> Release .tar.gz bundler functions

internal/engine/eval/vulncheck/vulncheck.go, internal/flags/constants.go
Remove the feature flag.
Fixes #5434
=> Release new vulncheck error template

.goreleaser.yaml
We updated the PAT used for submitting to `microsoft/winget` repo, but we forgot to update the commit author, which still looks like a Stacklok robot.
I noticed that the previous release had commits that looked like they came from Stacklok, and investigated.
=> Update commit author for winget releases

.github/workflows/lint.yml, .golangci.yml
=> Upgrade to 6.5 golangci-lint, now with schema checking

internal/providers/github/webhook/handlers_githubwebhooks_test.go
I hit this race condidition in another PR (post-submit), and it was fairly easy to track down -- it turns out we were calling `Close()` on the queue before the eventer had shut down; moving it inside the goroutine fixed that error for `go test -race -count 100`.  (A count of 500 led to different "out of addresses" issues.)
```
go test -race -count 100 ./internal/providers/github/webhook
```
=> Fix race in webhooks test

deployment/helm/templates/routes.yaml
Fixes a manifest problem introduced in #5504.
From argocd:
```
ComparisonError: Failed to load target state: failed to generate manifest for source 1 of 1:
rpc error: code = Unknown desc = Manifest generation error (cached):
`helm template . --name-template minder --namespace minder --kube-version 1.30 --values /tmp/b5c1558c-2fc4-41a4-bd3e-6fc1e473b2f1 <api versions removed> --include-crds` failed exit status 1:
Error: YAML parse error on minder/templates/routes.yaml: error unmarshaling JSON: while decoding JSON:
json: cannot unmarshal string into Go value of type releaseutil.SimpleHead Use --debug flag to render out invalid YAML
```
=> Use proper comment syntax in YAML files

pkg/api/protobuf/go/minder/v1/minder.pb.gw.go, tools/go.mod, tools/go.sum
Replaces #5485.  Dependabot doesn't know how to do the `make bootstrap && make gen` dance after upgrading dependencies in tools that change generated output.
Unit tests.
=> Upgrade grpc-gateway in tools

internal/datasources/service/service.go, internal/engine/actions/alert/pull_request_comment/pull_request_comment.go, internal/engine/eval/vulncheck/review.go
make function comment match function name
=> chore: make function comment match function name

internal/controlplane/handlers_projects.go
I added the flag projection logic after the manual testing, and I screwed up the _delete_ logic trying to reduce nesting.  (I tested create after changes, then was in a hurry to hit send.)
I'm manually testing right now.  Unfortunately, we don't have automated test coverage here, and it looks thorny to add it.  :sadface:
=> Fix flag protection logic on project delete

go.mod, tools/go.mod
Update to go 1.24.2, which is being used by OpenFGA (dependency) among others.
Relying on automated testing for this one.
=> Update to go 1.24.2

docs/docs/ref/proto.mdx, internal/controlplane/handlers_ruletype.go, internal/controlplane/handlers_ruletype_test.go, pkg/api/openapi/minder/v1/minder.swagger.json, pkg/api/protobuf/go/minder/v1/minder.pb.go, pkg/ruletypes/service.go, proto/minder/v1/minder.proto
Updates the DeleteRuleTypeRequest to support deleting rule types by name as well as ID.
Also ensures that new RuleType names don't collide with IDs, which makes deleting RuleTypes somewhat harder.
Added unit tests, some manual testing.
=> Allow delete ruletype by name

internal/controlplane/server_test.go, internal/providers/github/webhook/handlers_githubwebhooks_test.go
I noticed a number of test failures that look like:
```
handlers_githubwebhooks_test.go:2710: 
Error Trace:	/home/runner/work/minder/minder/internal/providers/github/webhook/handlers_githubwebhooks_test.go:2710
Error:      	Received unexpected error:
Post "http://127.0.0.1:44457": http: ContentLength=126 with Body length 0
Test:       	TestAll/TestHandleGitHubWebHook/branch_protection_configuration_enabled
Messages:   	failed to make request
```
It turns out this is due to the use of `httpDoWithRetry` with `POST` bodies -- when we retry, the buffer has already been read, so the length of the second post is 0, which is clearly an error.
Ran `go test -count 2000 ./internal/providres/github/webhook/...` without any failures of the above type …
=> Fix body reuse in test retries

internal/db/embedded/testdb.go
I tried to re-use `sync.WaitGroup` code to handle shutdown of the embeddedpostgres database after tests, but it turns out this was a mis-use which would occaisionally panic with
```
panic: sync: WaitGroup is reused before previous Wait has returned
goroutine 29 [running]:
sync.(*WaitGroup).Wait(0x3262140)
/opt/hostedtoolcache/go/1.24.2/x64/src/sync/waitgroup.go:120 +0xe5
github.com/mindersec/minder/internal/db/embedded.ensurePostgres.func2()
/home/runner/work/minder/minder/internal/db/embedded/testdb.go:70 +0x51
created by github.com/mindersec/minder/internal/db/embedded.ensurePostgres in goroutine 37
/home/runner/work/minder/minder/internal/db/embedded/testdb.go:69 +0x9ba
```
For example: https://github.com/mindersec/minder/actions/runs/16115554145/job/45468503100
This is because tests …
=> Fix WaitGroup mis-use in shared postgres DB

cmd/cli/app/auth/auth_login.go, cmd/cli/app/root.go, cmd/cli/app/set_project/set_project.go, cmd/dev/app/root.go, cmd/reminder/app/root.go, cmd/server/app/root.go, go.mod, internal/util/cli/cli.go, internal/util/cli/credentials.go, internal/util/cli/credentials_test.go, internal/util/cli/rpc_client.go, pkg/config/utils.go, pkg/config/utils_test.go
- Auto-log-in if needed, rather than telling the user to run another command
- When starting with no config file found, create an empty config in the lowest-priority location, so future invocations do not print a warning
Manual testing against existing server, and unit tests.
=> Polish default CLI behavior

internal/util/cli/credentials.go
Adds support for fetching a GitHub auth token natively to minder, modelled off https://github.com/custcodian/minder-action/blob/main/action.yml#L40
I intend to cut a CLI release after this and #5745 merge
I've tested the actions code, but testing GetTokenFromGitHub seems trickier, and I haven't done so yet.  (I intended to do it once I have merged this PR and cut a release.)
=> Add GitHub Actions auth token support

cmd/server/app/common.go, internal/providers/github/webhook/fuzz_test.go, internal/util/cli/types/history.go
fix some function names in comment
=> chore: fix some function names in comment

internal/engine/actions/actions.go, internal/engine/errors/errors.go, internal/engine/eval/eval.go, internal/engine/eval/homoglyphs/application/homoglyphs_service.go, internal/engine/eval/homoglyphs/application/invisible_characters_eval.go, internal/engine/eval/homoglyphs/application/mixed_scripts_eval.go, internal/engine/eval/jq/jq.go, internal/engine/eval/jq/jq_test.go, internal/engine/eval/rego/eval.go, internal/engine/eval/rego/http_test.go, internal/engine/eval/rego/lib_test.go, internal/engine/eval/rego/rego_test.go, internal/engine/eval/trusty/trusty.go, internal/engine/eval/vulncheck/vulncheck.go, internal/engine/ingester/deps/deps.go, internal/engine/ingester/git/git.go, internal/engine/ingester/git/git_test.go, internal/engine/options/options.go, internal/engine/rtengine/cache.go, pkg/engine/v1/interfaces/interfaces.go, pkg/engine/v1/rtengine/engine.go
This should simplify other usages of Minder, such as https://github.com/ossf/scorecard/pull/4723
Unit tests, since this was only a code move.
=> Move a number of engine interfaces to pkg/

docs/docs/ref/proto.mdx, pkg/api/openapi/minder/v1/minder.swagger.json, pkg/api/protobuf/go/minder/v1/minder.pb.go, proto/minder/v1/minder.proto
Per the documentation on the [`ignore` field values](https://buf.build/bufbuild/protovalidate/docs/main:buf.validate#buf.validate.Ignore), `IGNORE_IF_ZERO_VALUE` **only applies to fields that do not track presence** (i.e. fields which are not `optional`, `oneof`, or embedded messages).  We don't have very few embedded message constraints (none of which matter here), but we were using `IGNORE_IF_DEFAULT` to allow "empty value" in a number of `optional` or `oneof` fields, which now needs to be specified explicitly.  In particular, this was hitting `Context.project` and `Context.provider` from the CLI, which unconditionally sets these values to the command-line flag value (which might be "").  Example failure:
```
$ minder repo list
Message: Error listing repositories
Details: validation …
```
=> Adjust usage of IGNORE_IF_ZERO with respect to field presence and empty-but-present values

internal/engine/eval/rego/datasources.go
This adds `Nondeterministic: true` to the REGO function [here](https://github.com/mindersec/minder/blob/main/internal/engine/eval/rego/datasources.go#L47-L50)
Fixes #5158 
Unit tests with and without the flag, test failed on a deliberately break of the function as expected
=> Add Nondeterministic flag to the Data Source function
